"""Chapters 4 and 5 of the Dragon: White avoids the open Sicilian."""

from trainer.study_lessons.courses.authoring import decision, demo, step
from trainer.study_lessons.courses.dragon_positions import (
    ALAPIN,
    CLOSED,
    EARLY_QUEEN,
    MORRA,
    MOSCOW,
    SECOND,
    THIRD,
    THIRD_BISHOP,
    THIRD_C3,
    THIRD_C4_KNIGHT,
    THIRD_JUMP,
    THIRD_KNIGHT,
)

SICILIAN = "e4 c5"
THIRD_MOVE = "e4 c5 Nf3 d6"


def closed_trip():
    return [
        demo(
            "second-closed",
            "White develops the queenside knight",
            "White plays Nc3 instead of Nf3.",
            SICILIAN,
            SICILIAN + " Nc3",
            "second-closed-pawn",
        ),
        decision(
            "second-closed-pawn",
            "Same pawn move",
            "Push d6, as in the main line.",
            SICILIAN + " Nc3",
            "d6",
            "Nf3",
            "second-closed-knight",
            "White develops Nf3.",
            "Move d7 to d6.",
        ),
        decision(
            "second-closed-knight",
            "Develop with an attack",
            "Develop the g8-knight to f6, where it attacks e4.",
            SICILIAN + " Nc3 d6 Nf3",
            "Nf6",
            "d4",
            "second-closed-trade",
            "White opens the center with d4.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "second-closed-trade",
            "Trade on d4",
            "Capture on d4 with your c-pawn.",
            SICILIAN + " Nc3 d6 Nf3 Nf6 d4",
            "cxd4",
            "Nxd4",
            "second-closed-dragon",
            "White takes back with the knight.",
            "Move the pawn from c5 to d4.",
        ),
        decision(
            "second-closed-dragon",
            "Play the Dragon move",
            "Push g6.",
            SICILIAN + " Nc3 d6 Nf3 Nf6 d4 cxd4 Nxd4",
            "g6",
            None,
            "second-closed-summary",
            "This is the Dragon position from the first chapter.",
            "Move g7 to g6.",
        ),
        step(
            "explanation",
            "second-closed-summary",
            "A different road to the Dragon",
            "The moves came in a different order, but the position is exactly the Dragon from the first chapter. Use the same plans.",
            CLOSED,
        ),
    ]


def alapin_trip():
    knight = SICILIAN + " c3 Nf6 e5 Nd5"
    return [
        demo(
            "second-c3",
            "White prepares d4 with c3",
            "White plays c3 to support a later d4. The pawn now stands on the c3-square, where White's knight usually develops.",
            SICILIAN,
            SICILIAN + " c3",
            "second-c3-knight",
        ),
        decision(
            "second-c3-knight",
            "Attack the e4-pawn",
            "Develop the g8-knight to f6, where it attacks e4. White's c-pawn has taken the c3-square, so no knight can defend e4 from there.",
            SICILIAN + " c3",
            "Nf6",
            "e5",
            "second-c3-jump",
            "White pushes e5 and attacks your knight.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "second-c3-jump",
            "Jump to the center",
            "Move the knight to d5, in the middle of the board.",
            SICILIAN + " c3 Nf6 e5",
            "Nd5",
            "d4",
            "second-c3-trade",
            "White builds a center with d4.",
            "Move the knight from f6 to d5.",
        ),
        decision(
            "second-c3-trade",
            "Trade on d4",
            "Capture on d4 with your c-pawn.",
            knight + " d4",
            "cxd4",
            "cxd4",
            "second-c3-pawn",
            "White takes back with the c-pawn. Now no white pawn can reach c4 to chase your d5-knight.",
            "Move the pawn from c5 to d4.",
        ),
        decision(
            "second-c3-pawn",
            "Challenge the e5-pawn",
            "Push d6. The pawn attacks e5 and opens your c8-bishop.",
            knight + " d4 cxd4 cxd4",
            "d6",
            "Nf3",
            "second-c3-develop",
            "White defends e5 with Nf3.",
            "Move d7 to d6.",
        ),
        decision(
            "second-c3-develop",
            "Add pressure",
            "Develop the b8-knight to c6. It attacks both d4 and e5.",
            knight + " d4 cxd4 cxd4 d6 Nf3",
            "Nc6",
            None,
            "second-c3-summary",
            "Your pieces press against White's center pawns.",
            "Move the knight from b8 to c6.",
        ),
        step(
            "explanation",
            "second-c3-summary",
            "Pressure on the center",
            "White's pawns on d4 and e5 look strong, but they can become targets. Your d6-pawn and c6-knight attack e5, and the c6-knight also attacks d4.",
            ALAPIN,
        ),
    ]


def early_queen_trip():
    return [
        demo(
            "second-queen",
            "White takes back with the queen",
            "White plays d4 at once and recaptures on d4 with the queen.",
            SICILIAN,
            SICILIAN + " d4 cxd4 Qxd4",
            "second-queen-knight",
        ),
        decision(
            "second-queen-knight",
            "Develop with an attack",
            "Develop the b8-knight to c6, attacking White's queen.",
            SICILIAN + " d4 cxd4 Qxd4",
            "Nc6",
            "Qd1",
            "second-queen-develop",
            "The queen retreats all the way to d1. You have gained a move.",
            "Move the knight from b8 to c6.",
        ),
        decision(
            "second-queen-develop",
            "Attack the e4-pawn",
            "Develop the g8-knight to f6, where it attacks e4.",
            SICILIAN + " d4 cxd4 Qxd4 Nc6 Qd1",
            "Nf6",
            "Nc3",
            "second-queen-fianchetto",
            "White defends e4 with Nc3.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "second-queen-fianchetto",
            "Prepare the fianchetto",
            "Push g6 to prepare Bg7, as in the Dragon.",
            SICILIAN + " d4 cxd4 Qxd4 Nc6 Qd1 Nf6 Nc3",
            "g6",
            None,
            "second-queen-summary",
            "Your bishop will go to g7 next.",
            "Move g7 to g6.",
        ),
        step(
            "explanation",
            "second-queen-summary",
            "A Dragon-style setup",
            "Next, develop the bishop to g7 and castle. Your d-pawn is still on d7, so you keep the choice between d6 and d5 later.",
            EARLY_QUEEN,
        ),
    ]


def morra_trip():
    return [
        demo(
            "second-morra",
            "The Smith-Morra Gambit",
            "After d4 and your cxd4, White plays c3, offering a pawn for quick development. This is the Smith-Morra Gambit.",
            SICILIAN,
            SICILIAN + " d4 cxd4 c3",
            "second-morra-accept",
        ),
        decision(
            "second-morra-accept",
            "Accept the pawn",
            "Capture the c3-pawn with your d4-pawn.",
            SICILIAN + " d4 cxd4 c3",
            "dxc3",
            "Nxc3",
            "second-morra-pawn",
            "White takes back with the knight. You are a pawn ahead, and White is ahead in development.",
            "Move the pawn from d4 to c3.",
        ),
        decision(
            "second-morra-pawn",
            "Control e5",
            "Push d6. It controls e5 and opens the c8-bishop's path.",
            SICILIAN + " d4 cxd4 c3 dxc3 Nxc3",
            "d6",
            "Nf3",
            "second-morra-knight",
            "White develops Nf3.",
            "Move d7 to d6.",
        ),
        decision(
            "second-morra-knight",
            "Develop the knight",
            "Develop the b8-knight to c6.",
            SICILIAN + " d4 cxd4 c3 dxc3 Nxc3 d6 Nf3",
            "Nc6",
            "Bc4",
            "second-morra-block",
            "White's bishop on c4 aims at f7.",
            "Move the knight from b8 to c6.",
        ),
        decision(
            "second-morra-block",
            "Block the bishop",
            "Push e6. The pawn blocks the c4-bishop's path to f7 and opens your f8-bishop.",
            SICILIAN + " d4 cxd4 c3 dxc3 Nxc3 d6 Nf3 Nc6 Bc4",
            "e6",
            "O-O",
            "second-morra-develop",
            "White castles.",
            "Move e7 to e6.",
        ),
        decision(
            "second-morra-develop",
            "Develop the last knight",
            "Develop the g8-knight to f6, where it attacks e4.",
            SICILIAN + " d4 cxd4 c3 dxc3 Nxc3 d6 Nf3 Nc6 Bc4 e6 O-O",
            "Nf6",
            None,
            "second-morra-summary",
            "Your knights are developed and the f8-bishop is free to come out.",
            "Move the knight from g8 to f6.",
        ),
        step(
            "explanation",
            "second-morra-summary",
            "Keep the extra pawn safely",
            "You are a pawn ahead. Next, develop the f8-bishop to e7 and castle. Finish development before trying to win more.",
            MORRA,
        ),
    ]


def second_chapter():
    steps = [
        step(
            "explanation",
            "second-welcome",
            "When White avoids Nf3",
            "Not every opponent plays 2.Nf3 and 3.d4. This chapter covers White's most common other second moves: Bc4, Nc3, c3 and d4. Some lead back to the Dragon; others need their own plan.",
            next_step="second-arrival",
        ),
        demo(
            "second-arrival",
            "White opens with e4",
            "White starts with the king's pawn.",
            "",
            "e4",
            "second-sicilian",
        ),
        decision(
            "second-sicilian",
            "Answer from the side",
            "Play the Sicilian: push your c-pawn two squares.",
            "e4",
            "c5",
            None,
            "second-closed-choice",
            "Now White chooses a second move.",
            "Move c7 to c5.",
        ),
        step(
            "branch",
            "second-closed-choice",
            "If White plays Nc3",
            "This chapter's main line is Bc4. Explore Nc3 first, or continue to the next reply.",
            SICILIAN,
            branch_start="second-closed",
            next_step="second-c3-choice",
        ),
        *closed_trip(),
        step(
            "branch",
            "second-c3-choice",
            "If White plays c3",
            "Explore c3, or continue to the next reply.",
            SICILIAN,
            branch_start="second-c3",
            next_step="second-queen-choice",
        ),
        *alapin_trip(),
        step(
            "branch",
            "second-queen-choice",
            "If White plays d4 and Qxd4",
            "Explore d4 with a queen recapture, or continue to the next reply.",
            SICILIAN,
            branch_start="second-queen",
            next_step="second-morra-choice",
        ),
        *early_queen_trip(),
        step(
            "branch",
            "second-morra-choice",
            "If White plays d4 and c3",
            "Explore the Smith-Morra Gambit, or continue with Bc4.",
            SICILIAN,
            branch_start="second-morra",
            next_step="second-bishop",
        ),
        *morra_trip(),
        demo(
            "second-bishop",
            "White develops the bishop first",
            "White develops the f1-bishop to c4, where it aims at f7.",
            SICILIAN,
            SICILIAN + " Bc4",
            "second-block",
        ),
        decision(
            "second-block",
            "Block the bishop",
            "Push e6. The pawn blocks the c4-bishop's path to f7 and prepares d5.",
            SICILIAN + " Bc4",
            "e6",
            "Nf3",
            "second-knight",
            "White develops Nf3.",
            "Move e7 to e6.",
        ),
        decision(
            "second-knight",
            "Develop the knight",
            "Develop the b8-knight to c6.",
            SICILIAN + " Bc4 e6 Nf3",
            "Nc6",
            "O-O",
            "second-attack",
            "White castles.",
            "Move the knight from b8 to c6.",
        ),
        decision(
            "second-attack",
            "Attack the e4-pawn",
            "Develop the g8-knight to f6, where it attacks e4.",
            SICILIAN + " Bc4 e6 Nf3 Nc6 O-O",
            "Nf6",
            "d3",
            "second-break",
            "White defends e4 with d3.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "second-break",
            "Strike in the center",
            "Push d5. The pawn attacks the c4-bishop and the e4-pawn.",
            SICILIAN + " Bc4 e6 Nf3 Nc6 O-O Nf6 d3",
            "d5",
            "exd5",
            "second-recapture",
            "White takes on d5.",
            "Move d7 to d5.",
        ),
        decision(
            "second-recapture",
            "Take back with the e-pawn",
            "Recapture with the e6-pawn. Your new d5-pawn attacks the c4-bishop again.",
            SICILIAN + " Bc4 e6 Nf3 Nc6 O-O Nf6 d3 d5 exd5",
            "exd5",
            None,
            "second-summary",
            "The bishop must move, and both of your bishops now have open diagonals.",
            "Move the pawn from e6 to d5.",
        ),
        step(
            "explanation",
            "second-summary",
            "A pawn in the center",
            "Your d5-pawn controls the center and chases the bishop. Next, develop the f8-bishop to d6 or e7 and castle.",
            SECOND,
            next_step="second-rehearsal",
        ),
        step(
            "rehearsal",
            "second-rehearsal",
            "Play against Bc4",
            "Play the main line from the first move without prompts.",
            line_id="dragon-second-bishop",
        ),
    ]
    return dict(
        id="dragon-second-moves",
        title="White's second-move alternatives",
        entry_step=steps[0]["id"],
        steps=steps,
    )


def moscow_trip():
    before = THIRD_MOVE + " Bb5+"
    return [
        demo(
            "third-check",
            "The Moscow Variation",
            "White checks with the f1-bishop on b5. This is the Moscow Variation.",
            THIRD_MOVE,
            before,
            "third-check-block",
        ),
        decision(
            "third-check-block",
            "Block with a bishop",
            "Block the check with the c8-bishop on d7.",
            before,
            "Bd7",
            "Bxd7+",
            "third-check-recapture",
            "White exchanges bishops with check.",
            "Move the bishop from c8 to d7.",
        ),
        decision(
            "third-check-recapture",
            "Take back with the knight",
            "Recapture with the b8-knight.",
            before + " Bd7 Bxd7+",
            "Nxd7",
            "O-O",
            "third-check-knight",
            "White castles.",
            "Move the knight from b8 to d7.",
        ),
        decision(
            "third-check-knight",
            "Attack the e4-pawn",
            "Develop the g8-knight to f6, where it attacks e4.",
            before + " Bd7 Bxd7+ Nxd7 O-O",
            "Ngf6",
            "Re1",
            "third-check-fianchetto",
            "White defends e4 with the rook on e1.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "third-check-fianchetto",
            "Prepare the fianchetto",
            "Push g6 to make room for the bishop on g7.",
            before + " Bd7 Bxd7+ Nxd7 O-O Ngf6 Re1",
            "g6",
            "c3",
            "third-check-bishop",
            "White plays c3 to prepare d4.",
            "Move g7 to g6.",
        ),
        decision(
            "third-check-bishop",
            "Fianchetto the bishop",
            "Develop the f8-bishop to g7.",
            before + " Bd7 Bxd7+ Nxd7 O-O Ngf6 Re1 g6 c3",
            "Bg7",
            None,
            "third-check-summary",
            "Your bishop is on the long diagonal and you can castle next.",
            "Move the bishop from f8 to g7.",
        ),
        step(
            "explanation",
            "third-check-summary",
            "Ready for d4",
            "Castle next. White's c3 prepares d4, so expect the center to open soon.",
            MOSCOW,
        ),
    ]


def third_knight_trip():
    return [
        demo(
            "third-nc3",
            "White develops the queenside knight",
            "White plays Nc3 before d4.",
            THIRD_MOVE,
            THIRD_MOVE + " Nc3",
            "third-nc3-knight",
        ),
        decision(
            "third-nc3-knight",
            "Develop with an attack",
            "Develop the g8-knight to f6, where it attacks e4.",
            THIRD_MOVE + " Nc3",
            "Nf6",
            "d4",
            "third-nc3-trade",
            "White opens the center with d4.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "third-nc3-trade",
            "Trade on d4",
            "Capture on d4 with your c-pawn.",
            THIRD_MOVE + " Nc3 Nf6 d4",
            "cxd4",
            "Nxd4",
            "third-nc3-dragon",
            "White takes back with the knight.",
            "Move the pawn from c5 to d4.",
        ),
        decision(
            "third-nc3-dragon",
            "Play the Dragon move",
            "Push g6.",
            THIRD_MOVE + " Nc3 Nf6 d4 cxd4 Nxd4",
            "g6",
            None,
            "third-nc3-summary",
            "This is the Dragon position from the first chapter.",
            "Move g7 to g6.",
        ),
        step(
            "explanation",
            "third-nc3-summary",
            "Back in the Dragon",
            "A different move order has reached the same Dragon position. Use the plans from the earlier chapters.",
            THIRD_KNIGHT,
        ),
    ]


def third_c3_trip():
    before = THIRD_MOVE + " c3"
    return [
        demo(
            "third-c3",
            "White plays c3",
            "White plays c3 to prepare d4. The c3-pawn takes the square where White's knight would defend e4.",
            THIRD_MOVE,
            before,
            "third-c3-knight",
        ),
        decision(
            "third-c3-knight",
            "Attack the e4-pawn",
            "Develop the g8-knight to f6, where it attacks e4.",
            before,
            "Nf6",
            "d4",
            "third-c3-take",
            "White pushes d4 but does not defend the e4-pawn.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "third-c3-take",
            "Take the pawn",
            "Capture the e4-pawn with your knight.",
            before + " Nf6 d4",
            "Nxe4",
            "dxc5",
            "third-c3-recapture",
            "White takes your c5-pawn.",
            "Move the knight from f6 to e4.",
        ),
        decision(
            "third-c3-recapture",
            "Take back on c5",
            "Recapture the c5-pawn with your knight.",
            before + " Nf6 d4 Nxe4 dxc5",
            "Nxc5",
            None,
            "third-c3-summary",
            "You are a pawn ahead.",
            "Move the knight from e4 to c5.",
        ),
        step(
            "explanation",
            "third-c3-summary",
            "A free pawn",
            "White did not defend e4, and you won it. Develop your other pieces next and keep the extra pawn.",
            THIRD_C3,
        ),
    ]


def jump_trip():
    return [
        demo(
            "third-ng5",
            "The knight jumps to g5",
            "White's knight jumps to g5. Together with the c4-bishop it attacks f7, which only your king defends.",
            THIRD_BISHOP,
            THIRD_BISHOP + " Ng5",
            "third-ng5-block",
        ),
        decision(
            "third-ng5-block",
            "Block the bishop",
            "Push e6. The pawn blocks the c4-bishop's path to f7.",
            THIRD_BISHOP + " Ng5",
            "e6",
            "d3",
            "third-ng5-break",
            "White defends e4 with d3.",
            "Move e7 to e6.",
        ),
        decision(
            "third-ng5-break",
            "Strike in the center",
            "Push d5. The pawn attacks the c4-bishop and the e4-pawn.",
            THIRD_BISHOP + " Ng5 e6 d3",
            "d5",
            None,
            "third-ng5-summary",
            "Your pawns take over the center.",
            "Move d6 to d5.",
        ),
        step(
            "explanation",
            "third-ng5-summary",
            "The attack on f7 is over",
            "The e6-pawn blocks the c4-bishop, so the knight on g5 has no help against f7. If White takes on d5 with the e-pawn, recapture with the e6-pawn.",
            THIRD_JUMP,
        ),
    ]


def bishop_knight_trip():
    return [
        demo(
            "third-bc4-nc3",
            "White develops Nc3",
            "White develops the b1-knight to c3, defending e4.",
            THIRD_BISHOP,
            THIRD_BISHOP + " Nc3",
            "third-bc4-nc3-block",
        ),
        decision(
            "third-bc4-nc3-block",
            "Block the bishop",
            "Push e6 to block the c4-bishop's path to f7.",
            THIRD_BISHOP + " Nc3",
            "e6",
            "d4",
            "third-bc4-nc3-trade",
            "White opens the center with d4.",
            "Move e7 to e6.",
        ),
        decision(
            "third-bc4-nc3-trade",
            "Trade on d4",
            "Capture on d4 with your c-pawn.",
            THIRD_BISHOP + " Nc3 e6 d4",
            "cxd4",
            None,
            "third-bc4-nc3-summary",
            "White will take back on d4.",
            "Move the pawn from c5 to d4.",
        ),
        step(
            "explanation",
            "third-bc4-nc3-summary",
            "A solid setup",
            "After White takes back with the knight, develop the f8-bishop to e7 or push a6. Your e6-pawn keeps the c4-bishop away from f7.",
            THIRD_C4_KNIGHT,
        ),
    ]


def third_chapter():
    steps = [
        step(
            "explanation",
            "third-welcome",
            "When White avoids d4",
            "After 1.e4 c5 2.Nf3 d6, the most common third move other than d4 is Bc4. This chapter shows a Dragon-style setup against it, plus Bb5+, Nc3 and c3.",
            next_step="third-arrival",
        ),
        demo(
            "third-arrival",
            "Reach the second move",
            "White opens with e4 and develops Nf3.",
            "",
            "e4 c5 Nf3",
            "third-pawn",
        ),
        decision(
            "third-pawn",
            "Control e5",
            "Push d6, as in the first chapter.",
            "e4 c5 Nf3",
            "d6",
            None,
            "third-check-choice",
            "Now White chooses a third move.",
            "Move d7 to d6.",
        ),
        step(
            "branch",
            "third-check-choice",
            "If White checks on b5",
            "This chapter's main line is Bc4. Explore Bb5+ first, or continue to the next reply.",
            THIRD_MOVE,
            branch_start="third-check",
            next_step="third-nc3-choice",
        ),
        *moscow_trip(),
        step(
            "branch",
            "third-nc3-choice",
            "If White plays Nc3",
            "Explore Nc3, or continue to the next reply.",
            THIRD_MOVE,
            branch_start="third-nc3",
            next_step="third-c3-choice",
        ),
        *third_knight_trip(),
        step(
            "branch",
            "third-c3-choice",
            "If White plays c3",
            "Explore c3, or continue with Bc4.",
            THIRD_MOVE,
            branch_start="third-c3",
            next_step="third-bishop",
        ),
        *third_c3_trip(),
        demo(
            "third-bishop",
            "White develops the bishop",
            "White develops the f1-bishop to c4, where it aims at f7.",
            THIRD_MOVE,
            THIRD_MOVE + " Bc4",
            "third-knight",
        ),
        decision(
            "third-knight",
            "Attack the e4-pawn",
            "Develop the g8-knight to f6, where it attacks e4.",
            THIRD_MOVE + " Bc4",
            "Nf6",
            None,
            "third-ng5-choice",
            "White must deal with the attack on e4.",
            "Move the knight from g8 to f6.",
        ),
        step(
            "branch",
            "third-ng5-choice",
            "If the knight jumps to g5",
            "White most often defends with d3. Explore Ng5 and Nc3 first, or continue with d3.",
            THIRD_BISHOP,
            branch_start="third-ng5",
            next_step="third-bc4-nc3-choice",
        ),
        *jump_trip(),
        step(
            "branch",
            "third-bc4-nc3-choice",
            "If White plays Nc3",
            "Explore Nc3, or continue with d3.",
            THIRD_BISHOP,
            branch_start="third-bc4-nc3",
            next_step="third-defend",
        ),
        *bishop_knight_trip(),
        demo(
            "third-defend",
            "White defends with d3",
            "White defends the e4-pawn with d3.",
            THIRD_BISHOP,
            THIRD_BISHOP + " d3",
            "third-develop",
        ),
        decision(
            "third-develop",
            "Develop the knight",
            "Develop the b8-knight to c6.",
            THIRD_BISHOP + " d3",
            "Nc6",
            "O-O",
            "third-fianchetto",
            "White castles.",
            "Move the knight from b8 to c6.",
        ),
        decision(
            "third-fianchetto",
            "Prepare the fianchetto",
            "Push g6 to make room for the bishop on g7.",
            THIRD_BISHOP + " d3 Nc6 O-O",
            "g6",
            "Bg5",
            "third-bishop-g7",
            "White's bishop attacks your f6-knight from g5.",
            "Move g7 to g6.",
        ),
        decision(
            "third-bishop-g7",
            "Fianchetto and defend",
            "Develop the f8-bishop to g7. It also defends the f6-knight.",
            THIRD_BISHOP + " d3 Nc6 O-O g6 Bg5",
            "Bg7",
            "Nc3",
            "third-castle",
            "White develops Nc3.",
            "Move the bishop from f8 to g7.",
        ),
        decision(
            "third-castle",
            "Castle",
            "Castle kingside.",
            THIRD_BISHOP + " d3 Nc6 O-O g6 Bg5 Bg7 Nc3",
            "O-O",
            None,
            "third-summary",
            "Your king is safe and your pieces stand as in the Dragon.",
            "Move the king from e8 to g8.",
        ),
        step(
            "explanation",
            "third-summary",
            "A Dragon without d4",
            "Your bishop is on g7, your king is castled and both knights are developed. White has kept the d-pawn on d3, so no central pawns have been exchanged. If White's knight jumps to d5, take it with your f6-knight.",
            THIRD,
            next_step="third-rehearsal",
        ),
        step(
            "rehearsal",
            "third-rehearsal",
            "Play against Bc4",
            "Play the main line from the first move without prompts.",
            line_id="dragon-third-bishop",
        ),
    ]
    return dict(
        id="dragon-third-moves",
        title="White's third-move alternatives",
        entry_step=steps[0]["id"],
        steps=steps,
    )
