"""Chapter 3 of the Dragon: White's bishop goes to g5 or gives check on b5."""

from trainer.study_lessons.courses.authoring import decision, demo, step
from trainer.study_lessons.courses.dragon_positions import (
    BG5,
    BG5_ASK,
    BG5_C4,
    BG5_CHECK,
    BG5_F4,
    BG5_F6,
    BG5_H4,
    BG5_LINE,
    CHECK_SIX,
    DRAGON,
)


def check_trip():
    return [
        demo(
            "bg5-check",
            "White gives check",
            "White checks your king with the f1-bishop on b5.",
            DRAGON,
            DRAGON + " Bb5+",
            "bg5-check-block",
        ),
        decision(
            "bg5-check-block",
            "Block with a bishop",
            "Block the check with the c8-bishop on d7.",
            DRAGON + " Bb5+",
            "Bd7",
            "Bxd7+",
            "bg5-check-recapture",
            "White exchanges bishops with check.",
            "Move the bishop from c8 to d7.",
        ),
        decision(
            "bg5-check-recapture",
            "Take back with the queenside knight",
            "Recapture with the b8-knight. Your f6-knight stays where it attacks e4.",
            DRAGON + " Bb5+ Bd7 Bxd7+",
            "Nbxd7",
            "O-O",
            "bg5-check-fianchetto",
            "White castles.",
            "Move the knight from b8 to d7.",
        ),
        decision(
            "bg5-check-fianchetto",
            "Fianchetto the bishop",
            "Develop the f8-bishop to g7.",
            DRAGON + " Bb5+ Bd7 Bxd7+ Nbxd7 O-O",
            "Bg7",
            None,
            "bg5-check-summary",
            "Your bishop is on the long diagonal, and you can castle next.",
            "Move the bishop from f8 to g7.",
        ),
        step(
            "explanation",
            "bg5-check-summary",
            "A trade of light bishops",
            "The light-squared bishops are gone. Castle next; your d7-knight can later jump to c5 or e5.",
            CHECK_SIX,
        ),
    ]


def bishop_c4_trip():
    return [
        demo(
            "bg5-c4",
            "White develops Bc4",
            "White develops the f1-bishop to c4 instead of playing Qd2.",
            BG5,
            BG5 + " Bc4",
            "bg5-c4-castle",
        ),
        decision(
            "bg5-c4-castle",
            "Castle",
            "Castle kingside. Your rook on f8 and your king will both guard f7.",
            BG5 + " Bc4",
            "O-O",
            "O-O",
            "bg5-c4-ask",
            "White castles too.",
            "Move the king from e8 to g8.",
        ),
        decision(
            "bg5-c4-ask",
            "Ask the bishop",
            "Push h6 to attack the g5-bishop.",
            BG5 + " Bc4 O-O O-O",
            "h6",
            "Bh4",
            "bg5-c4-knight",
            "The bishop retreats to h4, where it still looks at your f6-knight.",
            "Move h7 to h6.",
        ),
        decision(
            "bg5-c4-knight",
            "Develop the knight",
            "Develop the b8-knight to c6, where it attacks the d4-knight.",
            BG5 + " Bc4 O-O O-O h6 Bh4",
            "Nc6",
            None,
            "bg5-c4-summary",
            "Only your c8-bishop, queen and a8-rook are left to develop.",
            "Move the knight from b8 to c6.",
        ),
        step(
            "explanation",
            "bg5-c4-summary",
            "Calm development",
            "Your f6-knight is defended by the e7-pawn and the g7-bishop, so the h4-bishop is not winning anything. Your king is castled and both knights are in play.",
            BG5_C4,
        ),
    ]


def check_seven_trip():
    return [
        demo(
            "bg5-b5",
            "A bishop check",
            "White checks with the f1-bishop on b5.",
            BG5,
            BG5 + " Bb5+",
            "bg5-b5-block",
        ),
        decision(
            "bg5-b5-block",
            "Block with a bishop",
            "Block the check with the c8-bishop on d7.",
            BG5 + " Bb5+",
            "Bd7",
            "Bxd7+",
            "bg5-b5-recapture",
            "White exchanges bishops with check.",
            "Move the bishop from c8 to d7.",
        ),
        decision(
            "bg5-b5-recapture",
            "Take back with the queenside knight",
            "Recapture with the b8-knight, as against the bishop check one move earlier.",
            BG5 + " Bb5+ Bd7 Bxd7+",
            "Nbxd7",
            "O-O",
            "bg5-b5-castle",
            "White castles.",
            "Move the knight from b8 to d7.",
        ),
        decision(
            "bg5-b5-castle",
            "Castle",
            "Castle kingside.",
            BG5 + " Bb5+ Bd7 Bxd7+ Nbxd7 O-O",
            "O-O",
            None,
            "bg5-b5-summary",
            "Both kings are castled and your pieces are developed.",
            "Move the king from e8 to g8.",
        ),
        step(
            "explanation",
            "bg5-b5-summary",
            "Same answer to the check",
            "Whenever the bishop checks on b5, block with the c8-bishop and take back with the b8-knight. Your queen and rooks are next to develop.",
            BG5_CHECK,
        ),
    ]


def retreat_trip():
    return [
        demo(
            "bg5-h4",
            "The bishop keeps watching f6",
            "White retreats the bishop to h4, where it still looks at your f6-knight.",
            BG5_ASK,
            BG5_ASK + " Bh4",
            "bg5-h4-knight",
        ),
        decision(
            "bg5-h4-knight",
            "Develop the knight",
            "Develop the b8-knight to c6, where it attacks the d4-knight.",
            BG5_ASK + " Bh4",
            "Nc6",
            None,
            "bg5-h4-summary",
            "Your knight presses on d4.",
            "Move the knight from b8 to c6.",
        ),
        step(
            "explanation",
            "bg5-h4-summary",
            "Develop and castle",
            "Your f6-knight is defended by the e7-pawn and the g7-bishop. Castle soon; your king will be safe behind the g7-bishop.",
            BG5_H4,
        ),
    ]


def trade_trip():
    return [
        demo(
            "bg5-f6",
            "White trades the bishop",
            "White gives up the bishop for your f6-knight.",
            BG5_ASK,
            BG5_ASK + " Bxf6",
            "bg5-f6-recapture",
        ),
        decision(
            "bg5-f6-recapture",
            "Take back with the bishop",
            "Recapture with the g7-bishop. Your pawns stay healthy and you keep both bishops.",
            BG5_ASK + " Bxf6",
            "Bxf6",
            "O-O-O",
            "bg5-f6-knight",
            "White castles queenside.",
            "Move the bishop from g7 to f6.",
        ),
        decision(
            "bg5-f6-knight",
            "Develop the knight",
            "Develop the b8-knight to c6, where it attacks the d4-knight.",
            BG5_ASK + " Bxf6 Bxf6 O-O-O",
            "Nc6",
            None,
            "bg5-f6-summary",
            "Your knight and f6-bishop both attack d4.",
            "Move the knight from b8 to c6.",
        ),
        step(
            "explanation",
            "bg5-f6-summary",
            "Two bishops",
            "You have two bishops and a knight against White's bishop and two knights. Your f6-bishop and c6-knight both attack the d4-knight.",
            BG5_F6,
        ),
    ]


def fork_trip():
    return [
        demo(
            "bg5-f4",
            "The bishop retreats to f4",
            "White moves the bishop to f4. It now stands on the same rank as the d4-knight.",
            BG5_ASK,
            BG5_ASK + " Bf4",
            "bg5-f4-fork",
        ),
        decision(
            "bg5-f4-fork",
            "Fork the knight and bishop",
            "Push e5. The pawn attacks the d4-knight and the f4-bishop at the same time.",
            BG5_ASK + " Bf4",
            "e5",
            None,
            "bg5-f4-summary",
            "Both White pieces are attacked by one pawn.",
            "Move e7 to e5.",
        ),
        step(
            "explanation",
            "bg5-f4-summary",
            "A pawn fork",
            "A pawn that attacks two pieces is called a fork. White cannot move both pieces at once, so you will win one of them.",
            BG5_F4,
        ),
    ]


def chapter():
    steps = [
        step(
            "explanation",
            "bg5-welcome",
            "When the bishop goes to g5",
            "At club level, Bg5 is one of White's most common sixth moves. The bishop attacks your f6-knight. You answer with simple development, and when White's queen comes to d2, a pawn on h6 starts a chain of attacks on White's pieces.",
            next_step="bg5-arrival",
        ),
        demo(
            "bg5-arrival",
            "Reach the Dragon",
            "You reach the Dragon position from the first chapter.",
            "",
            DRAGON,
            "bg5-check-choice",
        ),
        step(
            "branch",
            "bg5-check-choice",
            "If White checks on b5",
            "Explore the bishop check on b5, or continue with Bg5.",
            DRAGON,
            branch_start="bg5-check",
            next_step="bg5-move",
        ),
        *check_trip(),
        demo(
            "bg5-move",
            "The bishop goes to g5",
            "White develops the c1-bishop to g5, where it attacks your f6-knight.",
            DRAGON,
            DRAGON + " Bg5",
            "bg5-fianchetto",
        ),
        decision(
            "bg5-fianchetto",
            "Fianchetto and defend",
            "Develop the f8-bishop to g7. It also defends your f6-knight.",
            DRAGON + " Bg5",
            "Bg7",
            None,
            "bg5-c4-choice",
            "Your f6-knight is now defended twice, by the e7-pawn and the g7-bishop.",
            "Move the bishop from f8 to g7.",
        ),
        step(
            "branch",
            "bg5-c4-choice",
            "If White plays Bc4",
            "White most often plays Qd2, Bc4 or Bb5+. Explore Bc4, or continue to the next reply.",
            BG5,
            branch_start="bg5-c4",
            next_step="bg5-b5-choice",
        ),
        *bishop_c4_trip(),
        step(
            "branch",
            "bg5-b5-choice",
            "If White checks on b5",
            "Explore the bishop check, or continue with Qd2.",
            BG5,
            branch_start="bg5-b5",
            next_step="bg5-queen",
        ),
        *check_seven_trip(),
        demo(
            "bg5-queen",
            "White plays Qd2",
            "White brings the queen to d2, preparing to castle queenside.",
            BG5,
            BG5 + " Qd2",
            "bg5-ask",
        ),
        decision(
            "bg5-ask",
            "Ask the bishop",
            "Push h6 to attack the g5-bishop and make it decide where to go.",
            BG5 + " Qd2",
            "h6",
            None,
            "bg5-h4-choice",
            "The bishop must move or be traded for your knight.",
            "Move h7 to h6.",
        ),
        step(
            "branch",
            "bg5-h4-choice",
            "If the bishop goes to h4",
            "White most often retreats to e3. Explore h4, Bxf6 and f4 first, or continue with Be3.",
            BG5_ASK,
            branch_start="bg5-h4",
            next_step="bg5-f6-choice",
        ),
        *retreat_trip(),
        step(
            "branch",
            "bg5-f6-choice",
            "If White takes on f6",
            "Explore the trade on f6, or continue to the next reply.",
            BG5_ASK,
            branch_start="bg5-f6",
            next_step="bg5-f4-choice",
        ),
        *trade_trip(),
        step(
            "branch",
            "bg5-f4-choice",
            "If the bishop goes to f4",
            "Explore Bf4, or continue with Be3.",
            BG5_ASK,
            branch_start="bg5-f4",
            next_step="bg5-retreat",
        ),
        *fork_trip(),
        demo(
            "bg5-retreat",
            "The bishop retreats to e3",
            "White retreats the bishop to e3. Your h6-pawn now controls g5, so the bishop cannot come back there.",
            BG5_ASK,
            BG5_ASK + " Be3",
            "bg5-jump",
        ),
        decision(
            "bg5-jump",
            "Attack the bishop again",
            "Jump the f6-knight to g4, where it attacks the e3-bishop. White has no pawn on f3 to stop it.",
            BG5_ASK + " Be3",
            "Ng4",
            "Bf4",
            "bg5-fork",
            "The bishop moves to f4. Now it stands on the same rank as the d4-knight.",
            "Move the knight from f6 to g4.",
        ),
        decision(
            "bg5-fork",
            "Fork the knight and bishop",
            "Push e5. The pawn attacks the d4-knight and the f4-bishop at the same time.",
            BG5_ASK + " Be3 Ng4 Bf4",
            "e5",
            "h3",
            "bg5-take",
            "White ignores the fork and attacks your g4-knight with h3.",
            "Move e7 to e5.",
        ),
        decision(
            "bg5-take",
            "Take a knight first",
            "Capture the d4-knight with your e-pawn. The pawn on d4 then attacks White's c3-knight.",
            BG5_ASK + " Be3 Ng4 Bf4 e5 h3",
            "exd4",
            "hxg4",
            "bg5-second",
            "White takes your g4-knight. So far you have traded knights, but your d4-pawn still attacks the c3-knight.",
            "Move the pawn from e5 to d4.",
        ),
        decision(
            "bg5-second",
            "Take the second knight",
            "Capture the c3-knight with your d4-pawn.",
            BG5_ASK + " Be3 Ng4 Bf4 e5 h3 exd4 hxg4",
            "dxc3",
            None,
            "bg5-summary",
            "You have taken both of White's knights and lost only one of yours.",
            "Move the pawn from d4 to c3.",
        ),
        step(
            "explanation",
            "bg5-summary",
            "A piece ahead",
            "White will take your c3-pawn back with the b-pawn or the queen, and you will be a knight ahead for a pawn. Remember the pattern: h6 takes g5 away from the bishop, Ng4 chases it again, and e5 forks the d4-knight and f4-bishop.",
            BG5_LINE,
            next_step="bg5-rehearsal",
        ),
        step(
            "rehearsal",
            "bg5-rehearsal",
            "Play against Bg5",
            "Play the main line from the first move without prompts.",
            line_id="dragon-bg5",
        ),
    ]
    return dict(
        id="dragon-bg5",
        title="When the bishop goes to g5",
        entry_step=steps[0]["id"],
        steps=steps,
    )
