"""Chapter 2 of the Dragon: meet the Yugoslav Attack with an early d5 break."""

from trainer.study_lessons.courses.authoring import decision, demo, step
from trainer.study_lessons.courses.dragon_positions import (
    DRAGON,
    GAMBIT_QUEEN,
    YUGOSLAV,
    YUGOSLAV_BISHOP,
    YUGOSLAV_BREAK,
    YUGOSLAV_C4,
    YUGOSLAV_CASTLED,
    YUGOSLAV_EXCHANGE,
    YUGOSLAV_GAMBIT,
    YUGOSLAV_KNIGHT,
    YUGOSLAV_LATE,
    YUGOSLAV_QUEEN,
    YUGOSLAV_RECAPTURE,
)


def queen_trip():
    before = YUGOSLAV_BISHOP + " Qd2"
    return [
        demo(
            "yugoslav-queen",
            "Qd2 before f3",
            "White plays Qd2 before f3. Without a pawn on f3, nothing controls the g4-square.",
            YUGOSLAV_BISHOP,
            before,
            "yugoslav-queen-jump",
        ),
        decision(
            "yugoslav-queen-jump",
            "Attack the bishop",
            "Jump the f6-knight to g4, where it attacks White's e3-bishop.",
            before,
            "Ng4",
            "Bf4",
            "yugoslav-queen-take",
            "White moves the bishop to f4. Now the d4-knight is defended only by the queen, and your g7-bishop sees it.",
            "Move the knight from f6 to g4.",
        ),
        decision(
            "yugoslav-queen-take",
            "Take the knight",
            "Capture the d4-knight with the g7-bishop.",
            before + " Ng4 Bf4",
            "Bxd4",
            "Qxd4",
            "yugoslav-queen-fork",
            "White takes back with the queen. Now a pawn can attack two pieces at once.",
            "Move the bishop from g7 to d4.",
        ),
        decision(
            "yugoslav-queen-fork",
            "Fork queen and bishop",
            "Push e5. The pawn attacks White's queen on d4 and bishop on f4 at the same time, a fork.",
            before + " Ng4 Bf4 Bxd4 Qxd4",
            "e5",
            "Bxe5",
            "yugoslav-queen-capture",
            "White takes the pawn with the bishop, which now attacks your rook on h8.",
            "Move e7 to e5.",
        ),
        decision(
            "yugoslav-queen-capture",
            "Take the bishop",
            "Capture the e5-bishop with your d-pawn.",
            before + " Ng4 Bf4 Bxd4 Qxd4 e5 Bxe5",
            "dxe5",
            "Qxd8+",
            "yugoslav-queen-king",
            "White trades queens with check.",
            "Move the pawn from d6 to e5.",
        ),
        decision(
            "yugoslav-queen-king",
            "Take the queen",
            "Recapture the queen with your king.",
            before + " Ng4 Bf4 Bxd4 Qxd4 e5 Bxe5 dxe5 Qxd8+",
            "Kxd8",
            None,
            "yugoslav-queen-summary",
            "The queens are gone and you have an extra piece for a pawn.",
            "Move the king from e8 to d8.",
        ),
        step(
            "explanation",
            "yugoslav-queen-summary",
            "Punish an early Qd2",
            "You traded your g7-bishop and e-pawn for White's d4-knight and f4-bishop: a piece for a pawn. If White checks with Qa4+ instead of taking on e5, block with Bd7: the bishop attacks the queen, and you still win material. Earlier, if White's bishop had gone to g5 instead of f4, h6 would chase it; if White had castled queenside, Nxe3 would trade your knight for that bishop.",
            YUGOSLAV_QUEEN,
        ),
    ]


def bishop_c4_trip():
    before = YUGOSLAV_CASTLED + " Bc4"
    return [
        demo(
            "yugoslav-c4",
            "The bishop aims at your king",
            "White develops the f1-bishop to c4, on the diagonal that leads to f7 and your king on g8.",
            YUGOSLAV_CASTLED,
            before,
            "yugoslav-c4-knight",
        ),
        decision(
            "yugoslav-c4-knight",
            "Develop the knight",
            "Develop the b8-knight to c6.",
            before,
            "Nc6",
            "Qd2",
            "yugoslav-c4-trade",
            "White plays Qd2.",
            "Move the knight from b8 to c6.",
        ),
        decision(
            "yugoslav-c4-trade",
            "Trade knights",
            "Take the d4-knight with your c6-knight.",
            before + " Nc6 Qd2",
            "Nxd4",
            "Bxd4",
            "yugoslav-c4-block",
            "White recaptures with the bishop.",
            "Move the knight from c6 to d4.",
        ),
        decision(
            "yugoslav-c4-block",
            "Block the diagonal",
            "Develop the c8-bishop to e6. It blocks the c4-bishop's path toward your king and offers a trade.",
            before + " Nc6 Qd2 Nxd4 Bxd4",
            "Be6",
            "Bxe6",
            "yugoslav-c4-recapture",
            "White exchanges bishops.",
            "Move the bishop from c8 to e6.",
        ),
        decision(
            "yugoslav-c4-recapture",
            "Take back with the f-pawn",
            "Recapture with the f-pawn. The e6-pawn now controls d5 and f5.",
            before + " Nc6 Qd2 Nxd4 Bxd4 Be6 Bxe6",
            "fxe6",
            "O-O-O",
            "yugoslav-c4-queen",
            "White castles queenside.",
            "Move the pawn from f7 to e6.",
        ),
        decision(
            "yugoslav-c4-queen",
            "Bring the queen toward White's king",
            "Move your queen to a5. It attacks the a2-pawn and the c3-knight, near White's king.",
            before + " Nc6 Qd2 Nxd4 Bxd4 Be6 Bxe6 fxe6 O-O-O",
            "Qa5",
            None,
            "yugoslav-c4-summary",
            "Your queen is active and your rooks can use the c- and f-files.",
            "Move the queen from d8 to a5.",
        ),
        step(
            "explanation",
            "yugoslav-c4-summary",
            "Trade the attackers",
            "The bishop aiming at your king is gone. A rook on c8 would use the c-file, which leads to White's king on c1.",
            YUGOSLAV_C4,
        ),
    ]


def exchange_trip():
    before = YUGOSLAV_KNIGHT + " Nxc6"
    return [
        demo(
            "yugoslav-exchange",
            "White trades knights early",
            "White exchanges knights before castling.",
            YUGOSLAV_KNIGHT,
            before,
            "yugoslav-exchange-recapture",
        ),
        decision(
            "yugoslav-exchange-recapture",
            "Take back toward the center",
            "Recapture with the b-pawn. It supports a later d5 and opens the b-file for a rook.",
            before,
            "bxc6",
            "O-O-O",
            "yugoslav-exchange-bishop",
            "White castles queenside.",
            "Move the pawn from b7 to c6.",
        ),
        decision(
            "yugoslav-exchange-bishop",
            "Develop the last bishop",
            "Develop the c8-bishop to e6, where it covers d5 and looks toward a2.",
            before + " bxc6 O-O-O",
            "Be6",
            None,
            "yugoslav-exchange-summary",
            "Your knight and both bishops are developed, and the b-file, open on your side, points at b2, next to White's king on c1.",
            "Move the bishop from c8 to e6.",
        ),
        step(
            "explanation",
            "yugoslav-exchange-summary",
            "Bring a rook to the b-file",
            "Next, put a rook on b8 and consider Qa5. If White plays Bh6, now or earlier instead of castling, trade bishops with Bxh6 and, after Qxh6, play Qb6.",
            YUGOSLAV_EXCHANGE,
        ),
    ]


def gambit_trip():
    exchanged = YUGOSLAV_BREAK + " Nxc6 bxc6 exd5"
    return [
        demo(
            "yugoslav-gambit",
            "White trades knights first",
            "Before taking on d5, White exchanges knights on c6.",
            YUGOSLAV_BREAK,
            YUGOSLAV_BREAK + " Nxc6",
            "yugoslav-gambit-recapture",
        ),
        decision(
            "yugoslav-gambit-recapture",
            "Take back with the b-pawn",
            "Recapture with the b-pawn so that it supports d5.",
            YUGOSLAV_BREAK + " Nxc6",
            "bxc6",
            "exd5",
            "yugoslav-gambit-pawn",
            "White takes your d5-pawn.",
            "Move the pawn from b7 to c6.",
        ),
        decision(
            "yugoslav-gambit-pawn",
            "Take back with the pawn",
            "Recapture on d5 with the c6-pawn.",
            exchanged,
            "cxd5",
            "Nxd5",
            "yugoslav-gambit-knight",
            "White's knight takes your d5-pawn.",
            "Move the pawn from c6 to d5.",
        ),
        decision(
            "yugoslav-gambit-knight",
            "Take the knight",
            "Capture the d5-knight with your f6-knight.",
            exchanged + " cxd5 Nxd5",
            "Nxd5",
            "Qxd5",
            "yugoslav-gambit-offer",
            "White's queen takes your knight. You are a pawn down, and the queen also attacks your rook on a8.",
            "Move the knight from f6 to d5.",
        ),
        decision(
            "yugoslav-gambit-offer",
            "Offer the rook",
            "Move your queen to c7. You leave the a8-rook to be taken; in return your queen and g7-bishop aim at c2 and b2, beside White's king.",
            exchanged + " cxd5 Nxd5 Nxd5 Qxd5",
            "Qc7",
            "Qxa8",
            "yugoslav-gambit-bishop",
            "White takes the rook. Now White's queen is far from its king.",
            "Move the queen from d8 to c7.",
        ),
        decision(
            "yugoslav-gambit-bishop",
            "Attack with the bishop",
            "Develop the c8-bishop to f5. Together with your queen it attacks c2: now Qxc2 would be checkmate.",
            GAMBIT_QUEEN + " Qxa8",
            "Bf5",
            "Qxf8+",
            "yugoslav-gambit-king",
            "Your f8-rook now attacks White's queen too, so White takes the rook with check rather than lose the queen for nothing. White still has to stop Qxc2 mate next move.",
            "Move the bishop from c8 to f5.",
        ),
        decision(
            "yugoslav-gambit-king",
            "Take the queen",
            "Capture the queen with your king.",
            GAMBIT_QUEEN + " Qxa8 Bf5 Qxf8+",
            "Kxf8",
            None,
            "yugoslav-gambit-summary",
            "You have the queen for two rooks and a pawn, and White's king is under attack.",
            "Move the king from g8 to f8.",
        ),
        step(
            "explanation",
            "yugoslav-gambit-summary",
            "Queen and bishops against rooks",
            "Your queen and two bishops all aim at White's king on c1, while White's rooks are not yet working together. Keep attacking c2 and b2 rather than counting material.",
            YUGOSLAV_GAMBIT,
        ),
    ]


def late_trip():
    return [
        demo(
            "yugoslav-late",
            "White takes on c6 a move later",
            "White exchanges knights on c6 instead of taking on d5.",
            YUGOSLAV_RECAPTURE,
            YUGOSLAV_RECAPTURE + " Nxc6",
            "yugoslav-late-recapture",
        ),
        decision(
            "yugoslav-late-recapture",
            "Take back with the b-pawn",
            "Recapture with the b-pawn. Your d5-knight is still defended by your queen.",
            YUGOSLAV_RECAPTURE + " Nxc6",
            "bxc6",
            "Nxd5",
            "yugoslav-late-pawn",
            "White takes your d5-knight.",
            "Move the pawn from b7 to c6.",
        ),
        decision(
            "yugoslav-late-pawn",
            "Take back with the pawn",
            "Recapture on d5 with the c6-pawn.",
            YUGOSLAV_RECAPTURE + " Nxc6 bxc6 Nxd5",
            "cxd5",
            "Qxd5",
            "yugoslav-late-offer",
            "White's queen takes the pawn. This is the same position as when White trades knights on c6 before taking on d5.",
            "Move the pawn from c6 to d5.",
        ),
        decision(
            "yugoslav-late-offer",
            "Offer the rook",
            "Move your queen to c7. You leave the a8-rook to be taken; in return your queen and g7-bishop aim at c2 and b2, beside White's king.",
            YUGOSLAV_RECAPTURE + " Nxc6 bxc6 Nxd5 cxd5 Qxd5",
            "Qc7",
            None,
            "yugoslav-late-summary",
            "If White takes the a8-rook, continue with Bf5.",
            "Move the queen from d8 to c7.",
        ),
        step(
            "explanation",
            "yugoslav-late-summary",
            "Two roads to one position",
            "After Nxd5 cxd5 Qxd5 you reached the same position as when White trades knights on c6 before taking on d5. Earlier, if White had played Bd4 instead of Nxd5, you would trade bishops with Bxd4 and, after Qxd4, bring your queen to b6.",
            YUGOSLAV_LATE,
        ),
    ]


def chapter():
    steps = [
        step(
            "explanation",
            "yugoslav-welcome",
            "The Yugoslav Attack",
            "In master games, White's main plan against the Dragon, and one of its sharpest, is the Yugoslav Attack: White plays Be3, f3 and Qd2, castles queenside and then pushes the kingside pawns at your king. Your answer is simple: castle, develop Nc6, and as soon as White castles queenside, strike in the center with d5, as long as your knight is still on c6. If the knights have already been traded, the side trips show what to do instead.",
            next_step="yugoslav-arrival",
        ),
        demo(
            "yugoslav-arrival",
            "Reach the Yugoslav Attack",
            "You reach the Dragon, and White develops the c1-bishop to e3.",
            "",
            DRAGON + " Be3",
            "yugoslav-fianchetto",
        ),
        decision(
            "yugoslav-fianchetto",
            "Fianchetto the bishop",
            "Develop the f8-bishop to g7.",
            DRAGON + " Be3",
            "Bg7",
            None,
            "yugoslav-queen-choice",
            "Your bishop is on the long diagonal and you are ready to castle.",
            "Move the bishop from f8 to g7.",
        ),
        step(
            "branch",
            "yugoslav-queen-choice",
            "If White plays Qd2 first",
            "White can play f3 or Qd2 here. Explore Qd2 first, or continue with f3.",
            YUGOSLAV_BISHOP,
            branch_start="yugoslav-queen",
            next_step="yugoslav-f3",
        ),
        *queen_trip(),
        demo(
            "yugoslav-f3",
            "White plays f3",
            "f3 supports the e4-pawn and keeps your knight off g4.",
            YUGOSLAV_BISHOP,
            YUGOSLAV_BISHOP + " f3",
            "yugoslav-castle",
        ),
        decision(
            "yugoslav-castle",
            "Castle",
            "Castle kingside.",
            YUGOSLAV_BISHOP + " f3",
            "O-O",
            None,
            "yugoslav-c4-choice",
            "Your king is safe behind the g7-bishop for now.",
            "Move the king from e8 to g8.",
        ),
        step(
            "branch",
            "yugoslav-c4-choice",
            "If the bishop goes to c4",
            "White usually plays Qd2. Explore Bc4, or continue with Qd2.",
            YUGOSLAV_CASTLED,
            branch_start="yugoslav-c4",
            next_step="yugoslav-qd2",
        ),
        *bishop_c4_trip(),
        demo(
            "yugoslav-qd2",
            "White plays Qd2",
            "Qd2 connects the queen with the e3-bishop. Together they can aim at h6 to exchange your g7-bishop, and the queen clears d1 so that White can castle queenside.",
            YUGOSLAV_CASTLED,
            YUGOSLAV_CASTLED + " Qd2",
            "yugoslav-knight",
        ),
        decision(
            "yugoslav-knight",
            "Develop the knight",
            "Develop the b8-knight to c6, where it attacks the d4-knight.",
            YUGOSLAV_CASTLED + " Qd2",
            "Nc6",
            None,
            "yugoslav-exchange-choice",
            "Your knight presses on d4 and prepares a later d5.",
            "Move the knight from b8 to c6.",
        ),
        step(
            "branch",
            "yugoslav-exchange-choice",
            "If White trades knights now",
            "White usually castles queenside. Explore the knight trade first, or continue with castling.",
            YUGOSLAV_KNIGHT,
            branch_start="yugoslav-exchange",
            next_step="yugoslav-long-castle",
        ),
        *exchange_trip(),
        demo(
            "yugoslav-long-castle",
            "White castles queenside",
            "White's king goes to c1. The kings are now on opposite sides, so each side will attack the other's king.",
            YUGOSLAV_KNIGHT,
            YUGOSLAV_KNIGHT + " O-O-O",
            "yugoslav-break",
        ),
        decision(
            "yugoslav-break",
            "Strike in the center",
            "Push d5. It attacks the e4-pawn and opens the center before White's kingside attack arrives.",
            YUGOSLAV_KNIGHT + " O-O-O",
            "d5",
            None,
            "yugoslav-gambit-choice",
            "If White takes on d5, your pieces recapture and come to life.",
            "Move d6 to d5.",
        ),
        step(
            "branch",
            "yugoslav-gambit-choice",
            "If White trades knights first",
            "White most often takes on d5 or trades knights on c6. Explore the knight trade, or continue with exd5.",
            YUGOSLAV_BREAK,
            branch_start="yugoslav-gambit",
            next_step="yugoslav-takes",
        ),
        *gambit_trip(),
        demo(
            "yugoslav-takes",
            "White takes on d5",
            "White captures your d5-pawn with the e-pawn.",
            YUGOSLAV_BREAK,
            YUGOSLAV_BREAK + " exd5",
            "yugoslav-recapture",
        ),
        decision(
            "yugoslav-recapture",
            "Take back with the knight",
            "Recapture on d5 with the f6-knight. Moving the knight also opens the g7-bishop's diagonal.",
            YUGOSLAV_BREAK + " exd5",
            "Nxd5",
            None,
            "yugoslav-late-choice",
            "Your knight attacks the c3-knight and the e3-bishop, and your g7-bishop now sees the d4-knight.",
            "Move the knight from f6 to d5.",
        ),
        step(
            "branch",
            "yugoslav-late-choice",
            "If White trades on c6",
            "White usually exchanges knights on d5. Explore the trade on c6 first, or continue with Nxd5.",
            YUGOSLAV_RECAPTURE,
            branch_start="yugoslav-late",
            next_step="yugoslav-trade",
        ),
        *late_trip(),
        demo(
            "yugoslav-trade",
            "White trades knights on d5",
            "White's c3-knight takes your d5-knight.",
            YUGOSLAV_RECAPTURE,
            YUGOSLAV_RECAPTURE + " Nxd5",
            "yugoslav-queen-back",
        ),
        decision(
            "yugoslav-queen-back",
            "Take back with the queen",
            "Recapture on d5 with your queen. It now attacks the d4-knight a third time, with the c6-knight and g7-bishop.",
            YUGOSLAV_RECAPTURE + " Nxd5",
            "Qxd5",
            "Nxc6",
            "yugoslav-queen-recapture",
            "White exchanges the attacked knight on c6. White's queen on d2 now faces yours along the d-file.",
            "Move the queen from d8 to d5.",
        ),
        decision(
            "yugoslav-queen-recapture",
            "Take back and step off the d-file",
            "Recapture on c6 with your queen. It leaves the d-file, where White's queen and rook were lined up against it.",
            YUGOSLAV_RECAPTURE + " Nxd5 Qxd5 Nxc6",
            "Qxc6",
            "Bh6",
            "yugoslav-develop",
            "White plays Bh6 to exchange your g7-bishop.",
            "Move the queen from d5 to c6.",
        ),
        decision(
            "yugoslav-develop",
            "Finish developing",
            "Develop the c8-bishop to e6. From there it looks along the diagonal toward a2, near White's king.",
            YUGOSLAV_RECAPTURE + " Nxd5 Qxd5 Nxc6 Qxc6 Bh6",
            "Be6",
            None,
            "yugoslav-summary",
            "Your bishops and queen are active; your rooks come next. If White takes on g7, recapture with the king.",
            "Move the bishop from c8 to e6.",
        ),
        step(
            "explanation",
            "yugoslav-summary",
            "Your attack comes first",
            "Material is equal. Your queen on c6 aims down the c-file at c2, beside White's king, and your rooks can join on c8 and d8. White's g- and h-pawns have not moved yet. Striking with d5 the moment White castled queenside is what made this possible.",
            YUGOSLAV,
            next_step="yugoslav-rehearsal",
        ),
        step(
            "rehearsal",
            "yugoslav-rehearsal",
            "Play against the Yugoslav Attack",
            "Play the main line from the first move without prompts.",
            line_id="dragon-yugoslav",
        ),
    ]
    return dict(
        id="dragon-yugoslav",
        title="Meet the Yugoslav Attack",
        entry_step=steps[0]["id"],
        steps=steps,
    )
