"""Chapter 1 of the Dragon: the fianchetto setup against a quiet bishop move."""

from trainer.study_lessons.courses.authoring import decision, demo, step
from trainer.study_lessons.courses.dragon_positions import (
    CENTER,
    CLASSICAL,
    CLASSICAL_KNIGHT,
    DRAGON,
    EARLY_E3,
    OPEN,
    QUEEN_D2,
    QUEEN_RECAPTURE,
    QUIET,
    QUIET_C4,
)


def queen_trip():
    return [
        demo(
            "setup-queen",
            "The queen takes back",
            "White recaptures on d4 with the queen instead of the knight. The queen stands in the middle of the board, where your pieces can attack it.",
            OPEN,
            OPEN + " Qxd4",
            "setup-queen-knight",
        ),
        decision(
            "setup-queen-knight",
            "Develop with an attack",
            "Develop the b8-knight to c6. It attacks White's queen on d4.",
            OPEN + " Qxd4",
            "Nc6",
            "Bb5",
            "setup-queen-pin",
            "White pins your knight with Bb5: if the c6-knight moved, the bishop could take your king.",
            "Move the knight from b8 to c6.",
        ),
        decision(
            "setup-queen-pin",
            "Break the pin",
            "Develop the c8-bishop to d7. It defends the c6-knight and stands between the bishop and your king.",
            OPEN + " Qxd4 Nc6 Bb5",
            "Bd7",
            "Bxc6",
            "setup-queen-recapture",
            "White exchanges the bishop for your knight.",
            "Move the bishop from c8 to d7.",
        ),
        decision(
            "setup-queen-recapture",
            "Take back with the bishop",
            "Recapture on c6 with the d7-bishop. It now aims along the long diagonal at White's e4-pawn.",
            OPEN + " Qxd4 Nc6 Bb5 Bd7 Bxc6",
            "Bxc6",
            "Nc3",
            "setup-queen-develop",
            "White develops Nc3 and defends e4.",
            "Move the bishop from d7 to c6.",
        ),
        decision(
            "setup-queen-develop",
            "Bring out the last knight",
            "Develop the g8-knight to f6. It adds a second attacker on e4.",
            OPEN + " Qxd4 Nc6 Bb5 Bd7 Bxc6 Bxc6 Nc3",
            "Nf6",
            "Bg5",
            "setup-queen-center",
            "White's Bg5 attacks your f6-knight.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "setup-queen-center",
            "Open the f8-bishop",
            "Play e6. The pawn opens a path for the f8-bishop, which can then develop and let you castle.",
            OPEN + " Qxd4 Nc6 Bb5 Bd7 Bxc6 Bxc6 Nc3 Nf6 Bg5",
            "e6",
            None,
            "setup-queen-summary",
            "Your bishops, knight and pawns are working together, and White has given up the light-squared bishop.",
            "Move e7 to e6.",
        ),
        step(
            "explanation",
            "setup-queen-summary",
            "A different structure",
            "This is not a Dragon: your g-pawn stays on g7. Next, develop the f8-bishop to e7 and castle. You still have both bishops, while White has given up the f1-bishop.",
            QUEEN_RECAPTURE,
        ),
    ]


def bishop_c4_trip():
    return [
        demo(
            "setup-c4",
            "White's bishop goes to c4",
            "White develops the f1-bishop to c4, where it points at f7. Your setup does not change.",
            DRAGON,
            DRAGON + " Bc4",
            "setup-c4-fianchetto",
        ),
        decision(
            "setup-c4-fianchetto",
            "Fianchetto the bishop",
            "Develop the f8-bishop to g7.",
            DRAGON + " Bc4",
            "Bg7",
            "O-O",
            "setup-c4-castle",
            "White castles.",
            "Move the bishop from f8 to g7.",
        ),
        decision(
            "setup-c4-castle",
            "Castle",
            "Castle kingside. Your king will sit behind the g7-bishop and the f7, g6 and h7 pawns.",
            DRAGON + " Bc4 Bg7 O-O",
            "O-O",
            None,
            "setup-c4-summary",
            "Both kings are safe. The f7-pawn is now defended by your rook on f8 as well as your king.",
            "Move the king from e8 to g8.",
        ),
        step(
            "explanation",
            "setup-c4-summary",
            "Same setup, different bishop",
            "The c4-bishop looks at f7, but your rook and king defend it. Keep developing: your b8-knight and c8-bishop are still at home.",
            QUIET_C4,
        ),
    ]


def early_e3_trip():
    return [
        demo(
            "setup-e3",
            "White develops the bishop before castling",
            "White develops the c1-bishop to e3 before castling, keeping the choice of which side the king goes.",
            QUIET,
            QUIET + " Be3",
            "setup-e3-castle",
        ),
        decision(
            "setup-e3-castle",
            "Castle",
            "Castle kingside. Your king is safe whatever White chooses.",
            QUIET + " Be3",
            "O-O",
            "Qd2",
            "setup-e3-knight",
            "White plays Qd2, connecting the queen and the e3-bishop and preparing to castle queenside.",
            "Move the king from e8 to g8.",
        ),
        decision(
            "setup-e3-knight",
            "Develop the knight",
            "Develop the b8-knight to c6.",
            QUIET + " Be3 O-O Qd2",
            "Nc6",
            "O-O-O",
            "setup-e3-break",
            "White castles queenside. The kings are now on opposite sides of the board.",
            "Move the knight from b8 to c6.",
        ),
        decision(
            "setup-e3-break",
            "Strike in the center",
            "Push d5. It attacks the e4-pawn and opens lines toward White's king on c1.",
            QUIET + " Be3 O-O Qd2 Nc6 O-O-O",
            "d5",
            None,
            "setup-e3-summary",
            "d5 attacks e4. If White takes it with exd5, take back with the f6-knight.",
            "Move d6 to d5.",
        ),
        step(
            "explanation",
            "setup-e3-summary",
            "Answer the king on c1 in the center",
            "When White's king goes to c1, open the center at once with d5. Once the f6-knight moves, the g7-bishop's long diagonal points at b2, next to White's king. The Yugoslav Attack chapter shows the same d5 break in detail.",
            EARLY_E3,
        ),
    ]


def queen_d2_trip():
    return [
        demo(
            "setup-d2",
            "White brings the queen to d2",
            "White plays Qd2 instead of exchanging knights. The queen connects with the e3-bishop.",
            CLASSICAL_KNIGHT,
            CLASSICAL_KNIGHT + " Qd2",
            "setup-d2-break",
        ),
        decision(
            "setup-d2-break",
            "Strike in the center",
            "Push d5. It attacks the e4-pawn while White's queen is busy on d2.",
            CLASSICAL_KNIGHT + " Qd2",
            "d5",
            None,
            "setup-d2-summary",
            "d5 and your f6-knight both attack e4, and only White's c3-knight defends it.",
            "Move d6 to d5.",
        ),
        step(
            "explanation",
            "setup-d2-summary",
            "The same break",
            "The d5 break is the Dragon's main way to fight for the center. Here it comes with tempo: White must deal with the attack on e4 before continuing.",
            QUEEN_D2,
        ),
    ]


def chapter():
    steps = [
        step(
            "explanation",
            "setup-welcome",
            "The Sicilian Dragon",
            "You play Black. Against e4 you answer c5, the Sicilian Defense. After White opens the center with d4, you trade pawns and put your f8-bishop on g7. That bishop, aiming along the long diagonal from g7 to a1, gives the Dragon its strength. This chapter builds the setup against a quiet White plan.",
            next_step="setup-arrival",
        ),
        demo(
            "setup-arrival",
            "White opens with e4",
            "White starts with the king's pawn.",
            "",
            "e4",
            "setup-sicilian",
        ),
        decision(
            "setup-sicilian",
            "Answer from the side",
            "Push your c-pawn two squares. It controls d4 without facing the e4-pawn directly.",
            "e4",
            "c5",
            "Nf3",
            "setup-support",
            "This is the Sicilian Defense. White develops the g1-knight to f3, preparing d4.",
            "Move c7 to c5.",
        ),
        decision(
            "setup-support",
            "Prepare the knight's square",
            "Push your d-pawn one square. It controls e5 and opens the c8-bishop's path.",
            "e4 c5 Nf3",
            "d6",
            "d4",
            "setup-trade",
            "White pushes d4 to open the center.",
            "Move d7 to d6.",
        ),
        decision(
            "setup-trade",
            "Trade a side pawn for a center pawn",
            "Capture on d4 with your c-pawn. You give up a side pawn for one of White's center pawns.",
            "e4 c5 Nf3 d6 d4",
            "cxd4",
            None,
            "setup-queen-choice",
            "White will take back on d4.",
            "Move the pawn from c5 to d4.",
        ),
        step(
            "branch",
            "setup-queen-choice",
            "If the queen takes back",
            "White usually takes back with the knight. Explore the queen recapture, or continue with the main line.",
            OPEN,
            branch_start="setup-queen",
            next_step="setup-knight-back",
        ),
        *queen_trip(),
        demo(
            "setup-knight-back",
            "The knight takes back",
            "White recaptures with the f3-knight. You have two central pawns, on d6 and e7, against White's one on e4.",
            OPEN,
            OPEN + " Nxd4",
            "setup-knight",
        ),
        decision(
            "setup-knight",
            "Develop with an attack",
            "Develop the g8-knight to f6. It attacks White's e4-pawn.",
            OPEN + " Nxd4",
            "Nf6",
            "Nc3",
            "setup-dragon",
            "White defends e4 with Nc3.",
            "Move the knight from g8 to f6.",
        ),
        decision(
            "setup-dragon",
            "Prepare the fianchetto",
            "Push your g-pawn one square. This makes room for the f8-bishop on g7, a fianchetto.",
            CENTER,
            "g6",
            None,
            "setup-c4-choice",
            "This is the Dragon. The Russian master Fyodor Dus-Chotimirsky named it in 1901, because Black's kingside pawns reminded him of the constellation Draco, the dragon.",
            "Move g7 to g6.",
        ),
        step(
            "branch",
            "setup-c4-choice",
            "If the bishop goes to c4",
            "White has several sixth moves. This chapter follows the quiet Be2; the next chapters cover Be3 with f3 and Bg5. Explore Bc4 first, or continue with Be2.",
            DRAGON,
            branch_start="setup-c4",
            next_step="setup-quiet",
        ),
        *bishop_c4_trip(),
        demo(
            "setup-quiet",
            "A quiet bishop move",
            "White develops the f1-bishop to e2 and prepares to castle. The bishop on e2 does not attack anything yet.",
            DRAGON,
            DRAGON + " Be2",
            "setup-fianchetto",
        ),
        decision(
            "setup-fianchetto",
            "Fianchetto the bishop",
            "Develop the f8-bishop to g7, on the long diagonal. Your f6-knight stands in front of it for now.",
            DRAGON + " Be2",
            "Bg7",
            None,
            "setup-e3-choice",
            "Your bishop is on its best diagonal, and your king is ready to castle.",
            "Move the bishop from f8 to g7.",
        ),
        step(
            "branch",
            "setup-e3-choice",
            "If White plays Be3 first",
            "White can castle or develop the c1-bishop first. Explore Be3, or continue with castling.",
            QUIET,
            branch_start="setup-e3",
            next_step="setup-white-castles",
        ),
        *early_e3_trip(),
        demo(
            "setup-white-castles",
            "White castles",
            "White castles kingside.",
            QUIET,
            QUIET + " O-O",
            "setup-castle",
        ),
        decision(
            "setup-castle",
            "Castle",
            "Castle kingside. Your king tucks in behind the g7-bishop.",
            QUIET + " O-O",
            "O-O",
            "Be3",
            "setup-knight-c6",
            "White develops Be3, which protects the d4-knight.",
            "Move the king from e8 to g8.",
        ),
        decision(
            "setup-knight-c6",
            "Develop the last knight",
            "Develop the b8-knight to c6, where it attacks the d4-knight.",
            QUIET + " O-O O-O Be3",
            "Nc6",
            None,
            "setup-d2-choice",
            "The d4-knight is attacked by your c6-knight and defended twice, by the e3-bishop and the queen on d1.",
            "Move the knight from b8 to c6.",
        ),
        step(
            "branch",
            "setup-d2-choice",
            "If White plays Qd2",
            "White usually exchanges knights or plays Qd2. Explore Qd2, or continue with the exchange.",
            CLASSICAL_KNIGHT,
            branch_start="setup-d2",
            next_step="setup-exchange",
        ),
        *queen_d2_trip(),
        demo(
            "setup-exchange",
            "White exchanges knights",
            "White takes your c6-knight with the d4-knight.",
            CLASSICAL_KNIGHT,
            CLASSICAL_KNIGHT + " Nxc6",
            "setup-recapture",
        ),
        decision(
            "setup-recapture",
            "Take back toward the center",
            "Recapture with the b-pawn. The pawn moves toward the center, where it can support d5, and the b-file opens for your rook.",
            CLASSICAL_KNIGHT + " Nxc6",
            "bxc6",
            "Qd2",
            "setup-break",
            "White plays Qd2. Your c6-pawn now covers d5.",
            "Move the pawn from b7 to c6.",
        ),
        decision(
            "setup-break",
            "Take the center",
            "Push d5. The c6-pawn supports it, and it attacks White's e4-pawn.",
            CLASSICAL_KNIGHT + " Nxc6 bxc6 Qd2",
            "d5",
            None,
            "setup-summary",
            "You have a pawn on d5, supported by the c6-pawn and attacking e4.",
            "Move d6 to d5.",
        ),
        step(
            "explanation",
            "setup-summary",
            "Your Dragon setup",
            "Your king is castled behind the g7-bishop, and your pawns on c6 and d5 claim the center. The b-file is open for a rook on b8, which can press against b2. If White pushes e5 to attack your f6-knight, jump it to g4, where it attacks the e3-bishop; your c8-bishop defends it there.",
            CLASSICAL,
            next_step="setup-rehearsal",
        ),
        step(
            "rehearsal",
            "setup-rehearsal",
            "Play the Dragon setup",
            "Play the main line from the first move without prompts.",
            line_id="dragon-classical",
        ),
    ]
    return dict(id="dragon-setup", title="Build the Dragon", entry_step=steps[0]["id"], steps=steps)
