"""Six basic skills for new players, each tried on short, checked examples."""

import chess

from trainer.study_lessons.content import CourseDefinition
from trainer.study_lessons.courses.authoring import decision, demo, example, practice, step

# Positions without a named source were composed for this course. White moves
# first in every example; docs/FUNDAMENTALS_COURSE_SOURCES.md records the checks.
KNIGHT_ON_D4 = "e4 e5 Nf3 Nc6 Bc4 Bc5 c3 Nf6 d3 d6 O-O O-O h3 Nd4"
OPEN_DIAGONAL = "r1bq1rk1/ppp2ppp/2n2n2/3p4/3P4/BPN2N2/P1P2PPP/R2Q1RK1 w - - 0 1"
TWO_ATTACKERS = "r2q1rk1/ppp1bppp/2n2n2/4p3/8/2NP1N2/PPP2PPP/R1BQR1K1 w - - 0 1"
PINNED_DEFENDER = "r1bqkb1r/pppn1ppp/5n2/1B2p3/4P3/2N2N2/PPP1QPPP/R1B2RK1 w kq - 0 1"
LOOSE_BISHOP = "r2q1rk1/pppnbppp/2np4/4p3/3PP1b1/2NB4/PPPN1PPP/R1BQ1RK1 w - - 0 1"
SCHOLARS_MATE = "e4 e5 Bc4 Nc6 Qh5 Nf6"
EARLY_QUEEN = "e4 d5 exd5 Qxd5"
# After 1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.d3 Nf6 5.Nc3 Ng4.
KNIGHT_ON_G4 = "r1bqk2r/pppp1ppp/2n5/2b1p3/2B1P1n1/2NP1N2/PPP2PPP/R1BQK2R w KQkq - 3 6"
QUEEN_MATE = "7k/8/8/5K2/8/8/8/6Q1 w - - 0 1"
ROOK_MATE = "6k1/8/5K2/8/8/8/8/4R3 w - - 0 1"
PAWN_RACE = "k7/8/8/5K2/1p5P/8/8/8 w - - 0 1"
OPPOSITION = "8/4k3/8/3K4/4P3/8/8/8 w - - 0 1"
PAWN_FINISH = "Ke5 Kd7 Kf6 Kd8 Kf7 Kd7 e5 Kd8 e6 Kc7 e7 Kd7 e8=Q+"


def course():
    value_steps = [
        example(
            "values-intro",
            "Points for each piece",
            "Players count a pawn as 1 point, a knight or a bishop as 3, a rook as 5 and a queen as 9. The king is never captured, so it has no points. Your pieces and pawns, counted this way, are your material. Use these numbers to judge a capture: add up what you take and what you can lose back. Black's knight has jumped to d4. Two of your pieces can take it, but the e5-pawn and the c5-bishop defend it, so whatever takes it will be taken back.",
            chess.STARTING_FEN,
            "values-cheaper",
            san=KNIGHT_ON_D4,
            squares=("d4",),
            arrows=(("c3", "d4"), ("f3", "d4")),
        ),
        decision(
            "values-cheaper",
            "Capture with the cheaper piece",
            "Take the knight on d4 with the cheaper of your two pieces.",
            KNIGHT_ON_D4,
            "cxd4",
            "exd4",
            "values-exchange-intro",
            "cxd4 takes a knight (3) with a pawn (1). Black takes back with ...exd4, and you are two points ahead. Taking with the knight, Nxd4 exd4, would only have traded knights.",
            "Capture on d4 with the c3-pawn.",
        ),
        example(
            "values-exchange-intro",
            "Win the exchange",
            "A rook (5) is worth more than a bishop or a knight (3). Giving a bishop or a knight for a rook is called winning the exchange. Your bishop on a3 looks down an open diagonal at Black's rook on f8.",
            OPEN_DIAGONAL,
            "values-exchange",
            squares=("f8",),
            arrows=(("a3", "f8"),),
        ),
        decision(
            "values-exchange",
            "Take the rook",
            "Capture the rook. Black will take your bishop back, so count who comes out ahead.",
            "",
            "Bxf8",
            "Qxf8",
            "values-summary",
            "Bxf8 takes a rook (5). After ...Qxf8 you have lost a bishop (3), so you are two points ahead: you have won the exchange.",
            "Capture on f8 with the bishop.",
            fen=OPEN_DIAGONAL,
        ),
        step(
            "explanation",
            "values-summary",
            "Count before you capture",
            "Before you capture, add up what you take and what you can lose. When two pieces can make the same capture, use the cheaper one. The points are a guide, not a rule: checkmate is worth more than any amount of material.",
            "Bxf8 Qxf8",
            OPEN_DIAGONAL,
        ),
    ]
    count_steps = [
        example(
            "count-intro",
            "Attackers against defenders",
            "Before you take something, count. Your attackers are the pieces that can capture on that square; the defenders are the pieces that can take back. With more attackers than defenders, you can usually win what stands there. Black's pawn on e5 is attacked by your knight on f3 and your rook on e1, and defended only by the knight on c6.",
            TWO_ATTACKERS,
            "count-first",
            squares=("e5",),
            arrows=(("f3", "e5"), ("e1", "e5")),
        ),
        decision(
            "count-first",
            "Start with the cheaper attacker",
            "Two attackers, one defender. Take the pawn, starting with your cheaper piece.",
            "",
            "Nxe5",
            "Nxe5",
            "count-second",
            "Nxe5 takes the pawn, and Black takes back with ...Nxe5. So far you have given a knight for a pawn, but your rook still attacks e5, and nothing defends it now.",
            "Capture on e5 with the f3-knight.",
            fen=TWO_ATTACKERS,
        ),
        decision(
            "count-second",
            "Finish the trade",
            "Take back on e5.",
            "Nxe5 Nxe5",
            "Rxe5",
            None,
            "count-pin-intro",
            "Rxe5 finishes the trade: you won a pawn and a knight (4) for your knight (3), so you are one point ahead. Starting with Rxe5 would have left you a point behind, because the c6-knight would have taken your rook (5).",
            "Capture on e5 with the rook.",
            fen=TWO_ATTACKERS,
        ),
        example(
            "count-pin-intro",
            "Count only real defenders",
            "Count only the pieces that can legally take back. A piece pinned to its own king may not leave the line between the attacker and the king, and a pinned knight cannot move at all. Black's e5-pawn seems to be defended by the knight on d7, but your bishop on b5 pins that knight to the king on e8.",
            PINNED_DEFENDER,
            "count-pin",
            squares=("e5", "d7"),
            arrows=(("b5", "e8"),),
        ),
        decision(
            "count-pin",
            "Take the pawn",
            "Count the defenders that can really take back, then capture on e5.",
            "",
            "Nxe5",
            "Be7",
            "count-summary",
            "Nxe5 wins a pawn for nothing: the knight on d7 is pinned, so it cannot take back. Black brings out a bishop with ...Be7 and stays a pawn down.",
            "Capture on e5 with the f3-knight.",
            fen=PINNED_DEFENDER,
        ),
        step(
            "explanation",
            "count-summary",
            "Count, then capture",
            "Count the attackers and the defenders that can really take back; a piece pinned to its king often cannot. Then capture with your cheapest attacker first. "
            + practice("Hanging piece"),
            "Nxe5 Be7",
            PINNED_DEFENDER,
        ),
    ]
    habit_steps = [
        example(
            "habit-intro",
            "Three questions",
            "Before every move, look at checks, captures and threats, for both sides. A threat is something a move sets up for next turn, such as capturing a piece or giving checkmate. Here Black's bishop on g4 attacks your queen. Before you simply move the queen away, look at your captures.",
            LOOSE_BISHOP,
            "habit-capture",
            squares=("g4",),
            arrows=(("g4", "d1"),),
        ),
        decision(
            "habit-capture",
            "Look at captures",
            "Find a capture that wins material. Check whether Black can take back.",
            "",
            "Qxg4",
            "Nxd4",
            "habit-check-intro",
            "Qxg4 takes the bishop, and no black piece can take back. Black wins your d4-pawn with ...Nxd4, but you are still a bishop for a pawn ahead. Moving the queen away would have let the bishop escape.",
            "Capture on g4 with the queen.",
            fen=LOOSE_BISHOP,
        ),
        example(
            "habit-check-intro",
            "Checks come first",
            "Checks come first, because your opponent must answer them. Black's last move, ...Nf6, attacks your queen on h5. Before you save the queen, look at every check you can give. Early in the game, the pawn on f7 is defended only by Black's king.",
            chess.STARTING_FEN,
            "habit-check",
            san=SCHOLARS_MATE,
            squares=("f7",),
        ),
        decision(
            "habit-check",
            "Find the check",
            "One of your checks ends the game. Find it before you save the queen.",
            SCHOLARS_MATE,
            "Qxf7#",
            None,
            "habit-summary",
            "Qxf7 is checkmate, a trap called Scholar's mate. Your bishop on c4 defends the queen, so the king cannot take it, and the king has no square to go to. If someone tries this trap against you as Black, answer Qh5 with ...g6 or ...Qe7 instead of ...Nf6. Play ...g6 only when your e5-pawn is defended, as it is here, or Qxe5+ wins your rook on h8. After ...g6, watch for Qf3, which aims at f7 again; ...Nf6 then blocks it.",
            "Capture on f7 with the queen.",
        ),
        step(
            "explanation",
            "habit-summary",
            "Make it a habit",
            "Before every move, ask which checks, captures and threats you have, and what your opponent's last move threatens. Ask even when the move looks obvious. "
            + practice("Mate in 1"),
            SCHOLARS_MATE + " Qxf7#",
        ),
    ]
    opening_steps = [
        example(
            "opening-intro",
            "Three goals in the opening",
            "In the opening, aim for three things: control the center (d4, d5, e4 and e5), develop your knights and bishops (bring them out from their starting squares), and castle your king to safety. Moving one piece again and again, or bringing the queen out early, usually wastes time. Here Black's queen has come out early to d5.",
            chess.STARTING_FEN,
            "opening-tempo",
            san=EARLY_QUEEN,
            squares=("d5",),
        ),
        decision(
            "opening-tempo",
            "Develop with a threat",
            "Bring out a knight so that it attacks Black's queen.",
            EARLY_QUEEN,
            "Nc3",
            "Qa5",
            "opening-center",
            "Nc3 develops a piece and attacks the queen, so Black has to spend a move saving it. This is called gaining a tempo: you develop while Black loses time. The queen goes to a5.",
            "Move the b1-knight to c3.",
        ),
        decision(
            "opening-center",
            "Claim the center",
            "Put a pawn on one of the four center squares.",
            EARLY_QUEEN + " Nc3 Qa5",
            "d4",
            "Nf6",
            "opening-develop",
            "d4 puts a pawn in the center, where it controls c5 and e5, and it opens a diagonal for your c1-bishop. Black develops a knight with ...Nf6.",
            "Move the d-pawn two squares, to d4.",
        ),
        decision(
            "opening-develop",
            "Develop toward the center",
            "Develop your other knight to a square where it controls the center without blocking your bishops.",
            EARLY_QUEEN + " Nc3 Qa5 d4 Nf6",
            "Nf3",
            "Bf5",
            "opening-castle-intro",
            "Nf3 controls d4 and e5 and keeps the way clear for your bishops. Once your f1-bishop moves, you can castle. Black develops too, with ...Bf5.",
            "Move the g1-knight to f3.",
        ),
        example(
            "opening-castle-intro",
            "Castle early",
            "This position comes from the Italian Game: 1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.d3 Nf6 5.Nc3 Ng4. Black's knight and bishop both aim at f2, which only your king defends. Taking there, ...Nxf2, would attack your queen and your rook at once.",
            KNIGHT_ON_G4,
            "opening-castle",
            squares=("f2",),
            arrows=(("g4", "f2"), ("c5", "f2")),
        ),
        decision(
            "opening-castle",
            "Castle",
            "Castle kingside: your king moves two squares toward the rook, and the rook jumps over it to f1.",
            "",
            "O-O",
            "O-O",
            "opening-summary",
            "O-O moves your king to safety and brings the rook to f1, where it defends f2. If Black takes there, Rxf2 Bxf2+ Kxf2 gives Black a rook and a pawn for a knight and a bishop. That is 6 points for 6, but while many pieces are on the board, a knight and a bishop are usually stronger than a rook and a pawn. Black castles too.",
            "Move the king from e1 to g1.",
            fen=KNIGHT_ON_G4,
        ),
        step(
            "explanation",
            "opening-summary",
            "An opening checklist",
            "In the first moves, put pawns in the center, develop your knights and bishops toward it, and castle early. Avoid moving one piece many times and bringing your queen out early. The opening courses next to this one show these ideas in complete openings.",
            "O-O O-O",
            KNIGHT_ON_G4,
        ),
    ]
    mate_steps = [
        example(
            "mate-queen",
            "Queen and king against king",
            "A queen cannot checkmate a lone king without help from its own king. First drive the enemy king to the edge, then bring your king close. Here your queen controls the g-file, so Black's king can only move along the h-file. Watch out for stalemate: if the player to move is not in check but has no legal move, the game is a draw. Qg6 now would be stalemate.",
            QUEEN_MATE,
            "mate-queen-king",
            arrows=(("g1", "g8"),),
        ),
        decision(
            "mate-queen-king",
            "Bring your king closer",
            "Find the king move that forces checkmate next move.",
            "",
            "Kf6",
            "Kh7",
            "mate-queen-mate",
            "Kf6 brings your king next to g7, the square where your queen will give mate. Black's only legal move is ...Kh7.",
            "Move the king from f5 to f6.",
            fen=QUEEN_MATE,
        ),
        decision(
            "mate-queen-mate",
            "Checkmate with the queen",
            "Give checkmate.",
            "Kf6 Kh7",
            "Qg7#",
            None,
            "mate-rook",
            "Qg7 is checkmate. Your king defends the queen, so Black's king cannot take it, and the queen covers every square the king could go to.",
            "Move the queen to g7.",
            fen=QUEEN_MATE,
        ),
        example(
            "mate-rook",
            "Rook and king against king",
            "A rook also needs its king. The usual mate has the enemy king on the edge, your king facing it with one square between them, and your rook checking along the edge. Checking now with Re8+ fails, because Black's king escapes to h7.",
            ROOK_MATE,
            "mate-rook-wait",
        ),
        decision(
            "mate-rook-wait",
            "Take away the corner",
            "Find a rook move that is not a check but forces checkmate next move.",
            "",
            "Rh1",
            "Kf8",
            "mate-rook-mate",
            "Rh1 takes away h7 and h8. Black's only legal move is ...Kf8, straight in front of your king.",
            "Move the rook from e1 to h1.",
            fen=ROOK_MATE,
        ),
        decision(
            "mate-rook-mate",
            "Mate on the edge",
            "The kings face each other with one square between them. Give checkmate.",
            "Rh1 Kf8",
            "Rh8#",
            None,
            "mate-summary",
            "Rh8 is checkmate. The rook checks along the eighth rank, the edge of the board, and your king covers e7, f7 and g7.",
            "Move the rook to h8.",
            fen=ROOK_MATE,
        ),
        step(
            "explanation",
            "mate-summary",
            "Mating a lone king",
            "Drive the enemy king to the edge, bring your own king close, then give mate. Before each move that is not a check, make sure the enemy king still has a legal move, or the game ends in stalemate. With a rook, put your king in front of the enemy king and check along the edge.",
            "Rh1 Kf8 Rh8#",
            ROOK_MATE,
        ),
    ]
    pawn_steps = [
        example(
            "pawn-square",
            "The square of the pawn",
            "In a pawn race, count moves. A pawn promotes when it reaches the last rank, usually becoming a queen. Black's b-pawn needs three moves to promote and your h-pawn needs four, so pushing your pawn now loses. Use the rule of the square instead: draw a square from the pawn to its promotion square, here with corners b4, e4, e1 and b1. If your king can step into that square on this move, it catches the pawn.",
            PAWN_RACE,
            "pawn-square-enter",
            squares=("b4", "e4", "e1", "b1"),
        ),
        decision(
            "pawn-square-enter",
            "Step into the square",
            "Move your king into the square of Black's pawn.",
            "",
            "Ke4",
            "b3",
            "pawn-square-follow",
            "Ke4 steps into the square, so your king will catch the pawn. Black pushes anyway with ...b3, and the square shrinks to b3, d3, d1 and b1.",
            "Move the king from f5 to e4.",
            fen=PAWN_RACE,
        ),
        decision(
            "pawn-square-follow",
            "Step into the smaller square",
            "The pawn moved, so its square shrank. Step into the smaller square.",
            "Ke4 b3",
            "Kd3",
            "b2",
            "pawn-square-stop",
            "Kd3 steps into the smaller square. Black pushes again with ...b2.",
            "Move the king to d3.",
            fen=PAWN_RACE,
        ),
        decision(
            "pawn-square-stop",
            "Guard the promotion square",
            "Put your king next to b1, the square where the pawn promotes.",
            "Ke4 b3 Kd3 b2",
            "Kc2",
            "b1=Q+",
            "pawn-square-capture",
            "Kc2 guards b1. Black promotes with ...b1=Q+, but the new queen lands next to your king.",
            "Move the king to c2.",
            fen=PAWN_RACE,
        ),
        decision(
            "pawn-square-capture",
            "Take the new queen",
            "Black's new queen gives check. Take it.",
            "Ke4 b3 Kd3 b2 Kc2 b1=Q+",
            "Kxb1",
            None,
            "pawn-opposition",
            "Kxb1 takes the new queen, and Black has only a king left. Now the rule of the square works for you: your h-pawn's square runs from d4 to h8, and Black's king on a8 cannot step into it, so your pawn will promote.",
            "Capture on b1 with the king.",
            fen=PAWN_RACE,
        ),
        example(
            "pawn-opposition",
            "Take the opposition",
            "With king and pawn against king, walk your king in front of the pawn first. When the two kings stand on the same file with one square between them, the player who does not have to move has the opposition: the other king must step aside. Take the opposition here, and Black's king has to let yours through.",
            OPPOSITION,
            "pawn-opposition-take",
        ),
        decision(
            "pawn-opposition-take",
            "Face the king",
            "Move your king so that it faces Black's king on the same file, with one square between them.",
            "",
            "Ke5",
            "Kd7",
            "pawn-opposition-pass",
            "Ke5 takes the opposition, so Black has to give way. Any other move, even pushing the pawn, would let Black draw. Black steps aside with ...Kd7.",
            "Move the king from d5 to e5.",
            fen=OPPOSITION,
        ),
        decision(
            "pawn-opposition-pass",
            "Go around",
            "Black's king stepped aside. Move your king forward.",
            "Ke5 Kd7",
            "Kf6",
            "Kd8",
            "pawn-opposition-finish",
            "Kf6 stands next to e5, e6 and e7, the squares your pawn must cross. Black stays close with ...Kd8.",
            "Move the king from e5 to f6.",
            fen=OPPOSITION,
        ),
        demo(
            "pawn-opposition-finish",
            "Walk the pawn home",
            "Watch the finish. From f7 your king guards e6, e7 and e8, so Black's king can never get in front of the pawn, and the pawn promotes with check.",
            "Ke5 Kd7 Kf6 Kd8",
            PAWN_FINISH,
            "pawn-summary",
            fen=OPPOSITION,
        ),
        step(
            "explanation",
            "pawn-summary",
            "Count, then lead with the king",
            "Count how many moves each pawn needs, and use the square to see whether a king can catch it. With king and pawn against king, bring your king in front of the pawn and take the opposition. This often fails with an a-pawn or an h-pawn: if the defending king reaches the corner in front of the pawn, the game is a draw. "
            + practice("Pawn endgame"),
            PAWN_FINISH,
            OPPOSITION,
        ),
    ]
    return CourseDefinition.model_validate(
        dict(
            id="chess-fundamentals",
            revision="2026-10-v1",
            title="Fundamentals · Six basic skills",
            description="Learn six skills every player needs: what the pieces are worth, counting attackers and defenders, looking for checks, captures and threats before every move, opening principles, checkmating a lone king, and king and pawn endings. Each chapter explains one skill, then you try it in two positions. Some examples start from common openings or from Scholar's mate, a well-known trap; the others were composed for this course. Stockfish checked every answer in the first four chapters, and endgame tablebases checked the endings.",
            learner_color="white",
            attributions=[
                dict(
                    text="Original Fieldwork instruction. Positions without a named source were composed for this course.",
                    license="Repository license",
                ),
            ],
            chapters=[
                dict(id=identity, title=title, entry_step=steps[0]["id"], steps=steps)
                for identity, title, steps in (
                    ("piece-values", "What the pieces are worth", value_steps),
                    ("count-attackers", "Count attackers and defenders", count_steps),
                    (
                        "before-you-move",
                        "Before every move: checks, captures, threats",
                        habit_steps,
                    ),
                    ("opening-principles", "Opening principles", opening_steps),
                    ("lone-king-mates", "Checkmate a lone king", mate_steps),
                    ("king-and-pawn", "King and pawn endings", pawn_steps),
                )
            ],
        )
    )
