"""Turn the quiet setup into central play, including Black's active alternative."""

from trainer.study_lessons.courses.authoring import decision, demo, step
from trainer.study_lessons.courses.italian_positions import CENTRAL, KNIGHT_ROUTE

READY = KNIGHT_ROUTE + " Ng3 Be6"
ADVANCE = READY + " d4"
EXCHANGE = ADVANCE + " exd4 Bxe6 fxe6"


def chapter(excerpt, games):
    return [
        step(
            "explanation",
            "central-welcome",
            "Now use the preparation",
            "We return to the position after ...Re8. This time the f1-knight goes to g3 before the c1-bishop develops. Follow what changes when the d-pawn advances, then compare Black's two central replies.",
            KNIGHT_ROUTE,
            next_step="support-before-break",
        ),
        decision(
            "support-before-break",
            "Replace the pawn's defensive job",
            "The pawn on d3 currently defends e4. Improve the f1-knight so e4 keeps another defender when that pawn advances.",
            KNIGHT_ROUTE,
            "Ng3",
            "Be6",
            "play-break",
            "Ng3 supports e4 alongside the e1-rook. Black develops ...Be6, challenging your bishop on b3. The center is ready for a concrete decision.",
            "Move the knight from f1 to g3.",
        ),
        decision(
            "play-break",
            "Challenge the center",
            "Use your prepared pawn advance to challenge e5. Your c-pawn can recapture on the advance square, and e4 remains defended when d3 is vacated.",
            READY,
            "d4",
            None,
            "central-reply-choice",
            "d4 challenges e5 and takes central space, with your queen and knight also supporting d4. Black can capture there or strike back with ...d5. Neither reply ends the calculation.",
            "Advance the d3-pawn to d4.",
        ),
        step(
            "branch",
            "central-reply-choice",
            "Black can challenge your plan",
            "The main line shows ...exd4. Explore ...d5 for Black's more active response: the extra developed pieces make this break very different from the premature example in the previous chapter.",
            ADVANCE,
            branch_start="active-break",
            next_step="black-captures",
        ),
        demo(
            "active-break",
            "Black contests the center immediately",
            "Black does not have to accept your ideal pawn center. Here ...d5 is a sound counterstrike, supported by active pieces.",
            ADVANCE,
            ADVANCE + " d5",
            "answer-active-break",
        ),
        decision(
            "answer-active-break",
            "Resolve one part of the tension",
            "Use the pawn that just advanced to capture e5. Do not confuse this with moving your e-pawn: the two captures create different positions.",
            ADVANCE + " d5",
            "dxe5",
            "Ng4",
            "centralize-under-pressure",
            "dxe5 removes Black's e-pawn. ...Ng4 adds pressure on f2 and joins the c6-knight in attacking your pawn on e5. Keep developing actively rather than trying to hold every pawn.",
            "Capture from d4 to e5.",
        ),
        decision(
            "centralize-under-pressure",
            "Challenge a developed piece",
            "Centralize your f3-knight with an attack on Black's e6-bishop. Black can recover the pawn; your priority is active pieces, not hanging on to a temporary extra pawn.",
            ADVANCE + " d5 dxe5 Ng4",
            "Nd4",
            "Ncxe5",
            "active-break-takeaway",
            "Nd4 attacks the bishop on e6. Black's c6-knight recovers the pawn on e5. Material is level again, with active pieces on both sides.",
            "Move the knight from f3 to d4.",
        ),
        step(
            "explanation",
            "active-break-takeaway",
            "Counterplay changes the lesson",
            "Both sides have seven pawns. Black keeps a pawn on d5 and knights on e5 and g4; the g4-knight attacks f2 and h2. White has central activity, but no lasting pawn advantage. Continue checking those threats instead of treating the quiet setup as a fixed script.",
            ADVANCE + " d5 dxe5 Ng4 Nd4 Ncxe5",
        ),
        demo(
            "black-captures",
            "Black exchanges the e-pawn",
            "In this continuation Black captures on d4. Before recapturing, consider the bishop on e6: it could otherwise reach g4 and pin your knight to your queen.",
            ADVANCE,
            ADVANCE + " exd4",
            "trade-before-recapture",
        ),
        decision(
            "trade-before-recapture",
            "Choose the order of exchanges",
            "Exchange the bishop that can pin your f3-knight before you rebuild the pawn center. Immediate cxd4 is playable too; we choose the cleaner sequence here.",
            ADVANCE + " exd4",
            "Bxe6",
            "fxe6",
            "rebuild-center",
            "Bxe6 removes Black's light-squared bishop and the ...Bg4 option. ...fxe6 makes Black's f-file semi-open and puts a pawn on e6. Black's original e-pawn is on d4, so these are not doubled e-pawns.",
            "Capture the bishop on e6 with your bishop from b3.",
        ),
        decision(
            "rebuild-center",
            "Make the c-pawn's preparation count",
            "Recover the pawn on d4 with the pawn you prepared on c3, keeping two pawns in the center.",
            EXCHANGE,
            "cxd4",
            "Qe7",
            "finish-after-break",
            "cxd4 leaves White pawns on d4 and e4. Black develops the queen to e7. You have central space, but your c1-bishop still needs to join the game.",
            "Capture the pawn on d4 with your c3-pawn.",
        ),
        decision(
            "finish-after-break",
            "Complete the plan, not just the pawn push",
            "Develop your remaining bishop so it also supports the new d4-pawn.",
            EXCHANGE + " cxd4 Qe7",
            "Be3",
            None,
            "central-takeaway",
            "Be3 completes your minor-piece development and supports d4. The central break now connects to a working piece setup, not just a memorized pawn move.",
            "Move the bishop from c1 to e3.",
        ),
        step(
            "explanation",
            "central-takeaway",
            "Space comes with responsibilities",
            "Your d4- and e4-pawns give space, and your pieces support them. Black can still challenge d4 with ...e5 or chase the e3-bishop with ...Ng4. Recheck those ideas before another pawn push. The lesson gives you a plan, not a promise of an attack.",
            CENTRAL,
            next_step="central-game",
        ),
        excerpt(
            "central-game",
            "Compare a much earlier d4",
            "Steinitz–von Bardeleben, Hastings 1895. White opens the center before castling here, unlike our prepared break. Watch ...Bb4+ and Black's own ...d5: opening lines changes what both players can do.",
            "steinitz-bardeleben",
            6,
            18,
            "historical-center-takeaway",
        ),
        dict(
            kind="explanation",
            id="historical-center-takeaway",
            title="Same pawn move, different calculation",
            text="White has castled, but the central exchanges and Black's active pieces created a different game. Our repertoire supported e4 and castled before playing d4. Remember those requirements, then calculate the actual response to d4.",
            position=games["steinitz-bardeleben"].position.after(
                games["steinitz-bardeleben"].moves[:18]
            ),
            next_step="central-recall",
        ),
        step(
            "rehearsal",
            "central-recall",
            "Play the central plan",
            "Start from the knight-route position and carry the break through to development.",
            KNIGHT_ROUTE,
            line_id="central-break",
        ),
    ]
