"""Finish development, with a concrete comparison of bishop exchange structures."""

from trainer.study_lessons.courses.authoring import decision, demo, step
from trainer.study_lessons.courses.italian_positions import (
    DEVELOPED,
    KNIGHT_ROUTE,
    PREPARED,
    QUIET,
)
from trainer.study_lessons.courses.italian_variations import development_variations


def chapter(excerpt, games):
    return [
        step(
            "explanation",
            "development-welcome",
            "Castling is the beginning",
            "We resume after 5...d6. Your queenside knight and bishop still need jobs. Build support for the center, find a safe diagonal for your Italian bishop, and bring the remaining pieces into play.",
            QUIET,
            next_step="prepare-center",
        ),
        decision(
            "prepare-center",
            "Make room for a central advance",
            "Which pawn move can support a later d4 while leaving the queenside knight another route into the game?",
            QUIET,
            "c3",
            "O-O",
            "support-e4",
            "c3 supports d4. The knight will use d2 rather than the square now occupied by your c-pawn.",
            "Move c2 to c3; the knight can later develop to d2.",
        ),
        decision(
            "support-e4",
            "Support the center and clear a route",
            "Improve the rook that castling brought into play. Its new file supports e4 and frees a square your queenside knight can use later.",
            QUIET + " c3 O-O",
            "Re1",
            None,
            "premature-break-choice",
            "Re1 supports e4 and clears f1. Before continuing, compare what happens if Black opens the center too soon.",
            "Move the rook on f1 to e1.",
        ),
        step(
            "branch",
            "premature-break-choice",
            "A central break needs preparation",
            "Our main line continues with ...a6. Explore premature ...d5 here: opening the center can leave the e5-pawn tactically vulnerable. This does not mean every ...d5 is a mistake.",
            QUIET + " c3 O-O Re1",
            branch_start="premature-break",
            next_step="black-retreat-plan",
        ),
        demo(
            "black-retreat-plan",
            "Black prepares a bishop retreat",
            "Black's ...a6 controls b5 and makes a7 available for the bishop. We will keep improving our pieces while respecting Black's options.",
            QUIET + " c3 O-O Re1",
            PREPARED,
            "bishop-retreat",
        ),
        decision(
            "bishop-retreat",
            "Give your bishop a safe route",
            "Keep the bishop on its diagonal toward f7, but arrange an escape to c2 if Black attacks it with a knight from c6.",
            PREPARED,
            "Bb3",
            "Ba7",
            "develop-queen-knight",
            "Bb3 keeps the f7 diagonal and makes Bc2 available against ...Na5. Black's bishop also steps away from a future pawn attack by d4.",
            "Retreat the c4-bishop one square to b3.",
        ),
        decision(
            "develop-queen-knight",
            "Bring the last knight into play",
            "Develop the queenside knight so it reinforces e4 without displacing your c-pawn.",
            PREPARED + " Bb3 Ba7",
            "Nbd2",
            "h6",
            "bishop-threat-choice",
            "Nbd2 adds support to e4. Black's h6 controls g5. Your knight can now travel through the f1-square freed by the rook.",
            "Move the knight from b1 to d2.",
        ),
        step(
            "branch",
            "bishop-threat-choice",
            "If Black attacks your bishop",
            "The main line continues the knight route. Explore a nearby ...Na5 example to see why the retreat to b3 gave you a useful escape square.",
            PREPARED + " Bb3 Ba7 Nbd2 h6",
            branch_start="bishop-threat-arrives",
            next_step="reroute-knight",
        ),
        decision(
            "reroute-knight",
            "Make a route, not a one-move threat",
            "Move the d2-knight toward e3 or g3. This also clears the diagonal of your undeveloped bishop.",
            PREPARED + " Bb3 Ba7 Nbd2 h6",
            "Nf1",
            "Re8",
            "develop-last-bishop",
            "Nf1 clears d2 for the c1-bishop. From f1 the knight can recapture on e3 or later reach g3; Black's rook now supports e5.",
            "Move the knight from d2 to f1.",
        ),
        decision(
            "develop-last-bishop",
            "Use the route you cleared",
            "Develop your last bishop toward the center. With the knight ready behind it, you can meet an exchange without moving a pawn in front of your king.",
            KNIGHT_ROUTE,
            "Be3",
            "Bxe3",
            "recapture-piece",
            "Be3 develops the bishop and offers a trade. Black accepts; now choose how to recapture.",
            "The c1-bishop can reach e3 through the empty d2-square.",
        ),
        decision(
            "recapture-piece",
            "Recapture while improving a piece",
            "Recover the bishop using the knight route you prepared, keeping your f-pawn in place.",
            KNIGHT_ROUTE + " Be3 Bxe3",
            "Nxe3",
            None,
            "development-takeaway",
            "Nxe3 restores material and puts the knight on an active central square. Your pawns remain on e4 and f2; you did not create doubled e-pawns.",
            "Move the knight from f1 to e3.",
        ),
        step(
            "explanation",
            "development-takeaway",
            "Development creates choices",
            "Your minor pieces have left their starting squares, and the e3-knight eyes d5 and f5. Recheck Black's threats before choosing a central break. The next chapter uses the other knight route, to g3, to show d4 in action.",
            DEVELOPED,
            next_step="quiet-game",
        ),
        excerpt(
            "quiet-game",
            "The same exchange, a different structure",
            "Mason–Lasker, Hastings 1895. Mason develops Nc3 and Be3 early, then recaptures with the f-pawn. Compare that structure with the knight recapture you just played; this historical line is not an extra repertoire assignment.",
            "mason-lasker",
            6,
            14,
            "exchange-comparison",
        ),
        dict(
            kind="explanation",
            id="exchange-comparison",
            title="Look at the recapture, not just the trade",
            text="Mason has pawns on e3 and e4 and no pawn on the f-file. That gives a semi-open f-file but changes his central structure. Our Nxe3 kept the pawns intact. Neither recapture is a universal rule: the available pieces and resulting activity decide.",
            position=games["mason-lasker"].position.after(games["mason-lasker"].moves[:14]),
            next_step="development-recall",
        ),
        step(
            "rehearsal",
            "development-recall",
            "Finish development from your setup",
            "Practise the new decisions from the position after 5...d6.",
            QUIET,
            line_id="central-preparation",
        ),
    ] + development_variations()
