"""Six basic tactical patterns, each practised on short, engine-checked examples."""

import chess

from trainer.study_lessons.content import CourseDefinition
from trainer.study_lessons.courses.authoring import decision, demo, example, practice, step

# Positions without a named source were composed for this course. White moves
# first in every example; docs/TACTICS_COURSE_SOURCES.md records the checks.
KNIGHT_FORK = "r1b2rk1/pppn1ppp/2q5/3N4/8/8/PPP2PPP/R1BQ1RK1 w - - 0 1"
PAWN_FORK = "4r1k1/ppp2ppp/3b1n2/8/3PP3/5N2/PPP2PPP/3R2K1 w - - 0 1"
QUEEN_FORK = "r1bqk2r/ppp2ppp/4pn2/8/1b1P4/4PN2/PP2BPPP/R1BQ1RK1 w kq - 0 1"
PINNED_KNIGHT = "4k2r/ppp2ppp/4n3/8/3P4/3B4/PPP2PPP/4R1K1 w - - 0 1"
PINNED_QUEEN = "r1b1kb1r/pp1q1ppp/4p1n1/2p5/4P3/2NB4/PPP1QPPP/R1B2RK1 w kq - 0 1"
CARO_KANN_TRAP = "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7 Qe2 Ngf6"
RANK_SKEWER = "8/2k4r/5p2/6p1/8/3K4/5PPP/R7 w - - 0 1"
DIAGONAL_SKEWER = "8/p6q/1p3p2/5kp1/8/6P1/P4PKP/1R3B2 w - - 0 1"
FILE_SKEWER = "4r3/8/p5p1/1p5p/4k3/2P3KP/1P4P1/R7 w - - 0 1"
PETROV_TRAP = "e4 e5 Nf3 Nf6 Nxe5 Nxe4 Qe2 Nf6"
DISCOVERED_CHECK = "r1b2rk1/pp1n1ppp/2pq4/8/8/3B1N2/PPP1QPPP/R2R2K1 w - - 0 1"
RETI_TARTAKOWER = "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nf6 Qd3 e5 dxe5 Qa5+ Bd2 Qxe5 O-O-O Nxe4"
CAPTURED_GUARD = "r2q1rk1/pp3ppp/2p1pn2/3p2B1/3P4/2PQ4/PP3PPP/RB3RK1 w - - 0 1"
CHASED_GUARD = "r4rk1/pbq2ppp/1p2pn2/2p5/3PP3/2PQ4/PP1N1PPP/RB3RK1 w - - 0 1"
ONLY_DEFENDER = "5rk1/ppp2ppp/2n5/1B2b3/8/1N5P/PPP2PP1/4R1K1 w - - 0 1"
OPEN_BACK_RANK = "6k1/ppr2ppp/8/q7/2Q5/2P5/PP3PPP/4R1K1 w - - 0 1"
GUARDED_BACK_RANK = "4r1k1/pprb1ppp/1n6/8/8/2N5/PPP1RPPP/4RBK1 w - - 0 1"
QUEEN_SACRIFICE = "2r3k1/pp1q1ppp/8/8/8/7P/PPQ2PP1/2R3K1 w - - 0 1"


def course():
    fork_steps = [
        example(
            "fork-knight",
            "One move, two targets",
            "A fork is a move that attacks two enemy pieces at once. Your opponent can usually save only one. Count what you win with the usual piece values: pawn 1, knight or bishop 3, rook 5, queen 9. Here Black's king and queen are both a knight's jump from one empty square.",
            KNIGHT_FORK,
            "fork-knight-check",
            squares=("g8", "c6"),
        ),
        decision(
            "fork-knight-check",
            "Fork with check",
            "Move your knight so that it checks the king and attacks the queen at the same time.",
            "",
            "Ne7+",
            "Kh8",
            "fork-knight-collect",
            "Ne7+ forks the king and queen. A check must be answered first, and ...Kh8 is Black's only legal move. The queen is still attacked.",
            "Move the knight from d5 to e7. From there it attacks g8 and c6.",
            fen=KNIGHT_FORK,
        ),
        decision(
            "fork-knight-collect",
            "Collect the queen",
            "The king has stepped out of check. Take the piece your fork was aiming at.",
            "Ne7+ Kh8",
            "Nxc6",
            "bxc6",
            "fork-pawn",
            "Nxc6 wins the queen. Black takes back with ...bxc6, so you gave a knight (3) for a queen (9). A fork with check is especially strong, because the king must move first.",
            "Capture on c6 with the knight.",
            fen=KNIGHT_FORK,
        ),
        example(
            "fork-pawn",
            "Pawns fork too",
            "Any piece can fork, even a pawn. A pawn attacks the two squares diagonally ahead of it, so it can hit two pieces that stand on the same rank with one square between them. Black is a piece ahead here.",
            PAWN_FORK,
            "fork-pawn-push",
            squares=("d6", "f6"),
        ),
        decision(
            "fork-pawn-push",
            "Fork with a pawn",
            "Push a pawn that attacks Black's bishop and knight together. Make sure the pawn is defended on its new square.",
            "",
            "e5",
            "Nd7",
            "fork-pawn-collect",
            "e5 forks the bishop and the knight. Black cannot simply take the pawn, because your d4-pawn and f3-knight defend it. Black saves the knight with ...Nd7, which also attacks e5, but the bishop is still attacked.",
            "Move the pawn from e4 to e5. Your d4-pawn and f3-knight defend it there.",
            fen=PAWN_FORK,
        ),
        decision(
            "fork-pawn-collect",
            "Win the bishop",
            "The knight escaped. Take the piece that is still attacked.",
            "e5 Nd7",
            "exd6",
            "cxd6",
            "fork-queen",
            "exd6 wins the bishop for your pawn after ...cxd6. Black's extra piece is gone, and you are now a pawn ahead.",
            "Capture on d6 with the e5-pawn.",
            fen=PAWN_FORK,
        ),
        example(
            "fork-queen",
            "The queen forks in every direction",
            "A queen attacks along ranks, files and diagonals, so it can fork pieces that stand far apart. The best targets are the king and loose pieces: pieces with no defender. Black's bishop on b4 has no defender, and the diagonal leading to Black's king on e8 is open.",
            QUEEN_FORK,
            "fork-queen-check",
            squares=("e8", "b4"),
        ),
        decision(
            "fork-queen-check",
            "Check and attack the bishop",
            "Give a queen check that also attacks the loose bishop on b4.",
            "",
            "Qa4+",
            "Bd7",
            "fork-queen-collect",
            "Qa4+ checks along the diagonal and attacks b4 along the rank. No answer to the check also defends the bishop. Black blocks with ...Bd7, which attacks your queen.",
            "Move the queen from d1 to a4.",
            fen=QUEEN_FORK,
        ),
        decision(
            "fork-queen-collect",
            "Take the loose bishop",
            "Your queen is attacked. Move it to safety by capturing the bishop.",
            "Qa4+ Bd7",
            "Qxb4",
            None,
            "fork-summary",
            "Qxb4 wins the bishop for nothing. Before every move, notice which enemy pieces have no defender: they are the easiest targets for a fork.",
            "Capture on b4 with the queen.",
            fen=QUEEN_FORK,
        ),
        step(
            "explanation",
            "fork-summary",
            "Look for forks",
            "When two enemy pieces can be attacked from one square, look for a piece that can reach that square safely. Kings and undefended pieces make the best targets. "
            + practice("Fork"),
            "Qa4+ Bd7 Qxb4",
            QUEEN_FORK,
        ),
    ]
    pin_steps = [
        example(
            "pin-knight",
            "A piece that cannot move",
            "A pin is a line attack on a piece with a more valuable piece behind it. If the piece behind is the king, moving the pinned piece off the line is illegal. Your rook on e1 pins Black's knight on e6 to the king on e8, so the knight has no legal moves.",
            PINNED_KNIGHT,
            "pin-knight-attack",
            squares=("e6",),
            arrows=(("e1", "e8"),),
        ),
        decision(
            "pin-knight-attack",
            "Attack the pinned piece",
            "A pinned piece is a target. Attack the knight with something worth less than it.",
            "",
            "d5",
            "Ke7",
            "pin-knight-collect",
            "d5 attacks the knight, and the pin stops it from running. Black defends it with the king, ...Ke7, but the king now stands right behind the knight, so the pin remains.",
            "Move the pawn from d4 to d5.",
            fen=PINNED_KNIGHT,
        ),
        decision(
            "pin-knight-collect",
            "Take the pinned knight",
            "The knight is defended, but it is still pinned and attacked by a pawn. Take it.",
            "d5 Ke7",
            "dxe6",
            "fxe6",
            "pin-queen",
            "dxe6 wins the knight for a pawn after ...fxe6. A defender does not help a pinned piece that is attacked by something cheaper. When you pin a piece, look for a way to attack it again.",
            "Capture on e6 with the d-pawn.",
            fen=PINNED_KNIGHT,
        ),
        example(
            "pin-queen",
            "Pin the queen",
            "A pin hurts most when the pinned piece is valuable. Black's queen on d7 and king on e8 stand on one diagonal. If your bishop reaches that diagonal, the queen may only move along it.",
            PINNED_QUEEN,
            "pin-queen-bishop",
            squares=("d7", "e8"),
        ),
        decision(
            "pin-queen-bishop",
            "Pin the queen to the king",
            "Put your bishop on the diagonal through d7 and e8, on a square where it is defended.",
            "",
            "Bb5",
            "a6",
            "pin-queen-collect",
            "Bb5 pins the queen. It can only move along the pin, to c6 or b5, and either way you can take it. Black attacks your bishop with ...a6, but the queen is still pinned.",
            "Move the bishop from d3 to b5. Your knight on c3 and queen on e2 defend it there.",
            fen=PINNED_QUEEN,
        ),
        decision(
            "pin-queen-collect",
            "Take the pinned queen",
            "Capture the queen before Black can unpin it.",
            "Bb5 a6",
            "Bxd7+",
            "Bxd7",
            "pin-trap",
            "Bxd7+ wins the queen with check. Black takes back with ...Bxd7, so you traded a bishop (3) for a queen (9).",
            "Capture on d7 with the bishop.",
            fen=PINNED_QUEEN,
        ),
        example(
            "pin-trap",
            "A pinned piece cannot capture",
            "A piece pinned to its king cannot capture off the pin line either. Watch a well-known trap in the Caro-Kann Defense, an opening that begins 1.e4 c6. Follow the e-file: your queen will stand on it, opposite Black's king.",
            chess.STARTING_FEN,
            "pin-trap-opening",
        ),
        demo(
            "pin-trap-opening",
            "The trap is set",
            "Your queen goes to e2, and Black develops with ...Ngf6, attacking your knight on e4. Only that knight and Black's e7-pawn stand between your queen and Black's king.",
            "",
            CARO_KANN_TRAP,
            "pin-trap-mate",
        ),
        decision(
            "pin-trap-mate",
            "Checkmate with a knight",
            "Move the e4-knight with check. Once it leaves, your queen pins the e7-pawn.",
            CARO_KANN_TRAP,
            "Nd6#",
            None,
            "pin-summary",
            "Nd6 is checkmate. The e7-pawn cannot take the knight because it is pinned to the king, and Black's own pieces block every escape square.",
            "Move the knight from e4 to d6.",
        ),
        step(
            "explanation",
            "pin-summary",
            "Use your pins",
            "A pinned piece is stuck, so attack it again, ideally with a pawn. Remember that a piece pinned to the king cannot capture off its line. "
            + practice("Pin"),
            CARO_KANN_TRAP + " Nd6#",
        ),
    ]
    skewer_steps = [
        example(
            "skewer-rank",
            "The pin turned around",
            "A skewer is a line attack on a valuable piece with another piece behind it. When the front piece moves away, you capture the one behind. A check works best, because the king has to move. Black's king on c7 and rook on h7 stand on the same rank with nothing between them.",
            RANK_SKEWER,
            "skewer-rank-check",
            squares=("c7", "h7"),
        ),
        decision(
            "skewer-rank-check",
            "Check along the rank",
            "Give a check along the seventh rank.",
            "",
            "Ra7+",
            "Kd6",
            "skewer-rank-collect",
            "Ra7+ checks the king, with Black's rook behind it on the same rank. The king must leave the rank, and Black plays ...Kd6.",
            "Move the rook from a1 to a7.",
            fen=RANK_SKEWER,
        ),
        decision(
            "skewer-rank-collect",
            "Take the piece behind",
            "The king has moved. Collect the rook it was shielding.",
            "Ra7+ Kd6",
            "Rxh7",
            None,
            "skewer-diagonal",
            "Rxh7 wins the rook, and nothing can take back. You now have a rook and three pawns against two pawns.",
            "Capture on h7 with the rook.",
            fen=RANK_SKEWER,
        ),
        example(
            "skewer-diagonal",
            "Bishops skewer too",
            "Bishops and queens skewer along diagonals. Black has a queen against your rook and bishop, but the king on f5 and the queen on h7 stand on one diagonal, with only g6 between them.",
            DIAGONAL_SKEWER,
            "skewer-diagonal-check",
            squares=("f5", "h7"),
        ),
        decision(
            "skewer-diagonal-check",
            "Check on the diagonal",
            "Check the king along the diagonal that leads to the queen.",
            "",
            "Bd3+",
            "Ke5",
            "skewer-diagonal-collect",
            "Bd3+ checks the king, and the queen stands behind it. The king must step off the diagonal, and Black plays ...Ke5.",
            "Move the bishop from f1 to d3.",
            fen=DIAGONAL_SKEWER,
        ),
        decision(
            "skewer-diagonal-collect",
            "Win the queen",
            "Take the queen that the king left behind.",
            "Bd3+ Ke5",
            "Bxh7",
            None,
            "skewer-file",
            "Bxh7 wins the queen for nothing. A moment ago Black was ahead; now you are a rook and a bishop up.",
            "Capture on h7 with the bishop.",
            fen=DIAGONAL_SKEWER,
        ),
        example(
            "skewer-file",
            "Skewers on a file",
            "Rooks skewer along files as well as ranks. Black's king on e4 and rook on e8 share the e-file, and the squares between them are empty.",
            FILE_SKEWER,
            "skewer-file-check",
            squares=("e4", "e8"),
        ),
        decision(
            "skewer-file-check",
            "Check along the file",
            "Check the king along the e-file.",
            "",
            "Re1+",
            "Kd5",
            "skewer-file-collect",
            "Re1+ checks the king with Black's rook behind it on the e-file. The king steps aside to d5.",
            "Move the rook from a1 to e1.",
            fen=FILE_SKEWER,
        ),
        decision(
            "skewer-file-collect",
            "Take the rook",
            "The king has left the file. Take the rook behind it.",
            "Re1+ Kd5",
            "Rxe8",
            None,
            "skewer-summary",
            "Rxe8 wins the rook. Black had to move the king, and the rook behind it was left undefended.",
            "Capture on e8 with the rook.",
            fen=FILE_SKEWER,
        ),
        step(
            "explanation",
            "skewer-summary",
            "Look behind the king",
            "In a pin, the less valuable piece stands in front. In a skewer, the more valuable piece is in front and must move. Before giving a check, look at what stands behind the king on that line. "
            + practice("Skewer"),
            "Re1+ Kd5 Rxe8",
            FILE_SKEWER,
        ),
    ]
    discovered_steps = [
        example(
            "discovered-intro",
            "Uncover an attack",
            "In a discovered attack, you move one piece out of a line and uncover an attack by the piece behind it. The piece that moves can make a threat of its own, so your opponent faces two at once. If the uncovered attack is a check, it is a discovered check. Watch a trap in the Petrov Defense, which begins 1.e4 e5 2.Nf3 Nf6.",
            chess.STARTING_FEN,
            "discovered-trap-opening",
        ),
        demo(
            "discovered-trap-opening",
            "The Petrov trap",
            "Black copies your capture with ...Nxe4. Your queen attacks that knight from e2, and Black retreats with ...Nf6, leaving only your knight on e5 between your queen and Black's king.",
            "",
            PETROV_TRAP,
            "discovered-trap-check",
        ),
        decision(
            "discovered-trap-check",
            "Discovered check",
            "Move the e5-knight so your queen gives check, and make the knight attack something valuable at the same time.",
            PETROV_TRAP,
            "Nc6+",
            "Qe7",
            "discovered-trap-collect",
            "Nc6+ uncovers check from your queen, and the knight attacks Black's queen. Black must answer the check first and blocks with ...Qe7.",
            "Move the knight from e5 to c6. It attacks Black's queen on d8.",
        ),
        decision(
            "discovered-trap-collect",
            "Take the queen",
            "Black's queen has blocked on e7, still within your knight's reach.",
            PETROV_TRAP + " Nc6+ Qe7",
            "Nxe7",
            "Bxe7",
            "discovered-bishop",
            "Nxe7 wins the queen for your knight after ...Bxe7. Black's mistake was 4...Nf6, which reopened the e-file; 4...Qe7 would have kept it closed.",
            "Capture on e7 with the knight.",
        ),
        example(
            "discovered-bishop",
            "Check with the moving piece",
            "The moving piece can give check itself. Then your opponent must deal with the check, and the uncovered attack lands for free. Your rook on d1 is lined up with Black's queen on d6, but your bishop on d3 is in the way.",
            DISCOVERED_CHECK,
            "discovered-bishop-check",
            squares=("d3",),
            arrows=(("d1", "d6"),),
        ),
        decision(
            "discovered-bishop-check",
            "Move the bishop with check",
            "Move the d3-bishop with check, uncovering your rook's attack on the queen.",
            "",
            "Bxh7+",
            "Kxh7",
            "discovered-bishop-collect",
            "Bxh7+ checks the king and uncovers your rook's attack on the queen. Black has to answer the check, and ...Kxh7 cannot also save the queen.",
            "Capture on h7 with the bishop.",
            fen=DISCOVERED_CHECK,
        ),
        decision(
            "discovered-bishop-collect",
            "Collect the queen",
            "Now take the queen your rook uncovered.",
            "Bxh7+ Kxh7",
            "Rxd6",
            None,
            "double-check",
            "Rxd6 wins the queen. You gave a bishop but won a pawn and the queen.",
            "Capture on d6 with the rook.",
            fen=DISCOVERED_CHECK,
        ),
        example(
            "double-check",
            "Double check",
            "In a double check, the piece that moves gives check while uncovering a second check. No single move can block or capture two checking pieces, so the king must move. This position is from Réti–Tartakower, a casual game played in Vienna in 1910. Black has just taken your knight on e4.",
            chess.STARTING_FEN,
            "double-check-sacrifice",
            san=RETI_TARTAKOWER,
        ),
        demo(
            "double-check-sacrifice",
            "The queen sacrifice",
            "Réti, playing White, gives up the queen with Qd8+, and the king must take it. Now only your bishop on d2 stands between your rook on d1 and the king.",
            RETI_TARTAKOWER,
            RETI_TARTAKOWER + " Qd8+ Kxd8",
            "double-check-move",
        ),
        decision(
            "double-check-move",
            "Give double check",
            "Move the d2-bishop so that it gives check and uncovers your rook's check too.",
            RETI_TARTAKOWER + " Qd8+ Kxd8",
            "Bg5+",
            "Kc7",
            "double-check-mate",
            "Bg5+ is double check: the bishop checks along the diagonal and the rook along the d-file. Only a king move helps. The earliest published score ends here with Black resigning; the lesson plays ...Kc7 to show the finish.",
            "Move the bishop from d2 to g5.",
        ),
        decision(
            "double-check-mate",
            "Finish the game",
            "Find the checkmate.",
            RETI_TARTAKOWER + " Qd8+ Kxd8 Bg5+ Kc7",
            "Bd8#",
            None,
            "discovered-summary",
            "Bd8 is checkmate. Your rook covers the d-file, the bishop covers b6, and Black's own pieces block the other squares. After ...Ke8 instead, Rd8 would also have been mate.",
            "Move the bishop from g5 to d8.",
        ),
        step(
            "explanation",
            "discovered-summary",
            "Look for hidden lines",
            "Look for your queen, rooks and bishops lined up on enemy pieces with one of your own pieces in between. Moving that piece with a threat of its own creates two threats at once. "
            + practice("Discovered attack or Double check"),
            RETI_TARTAKOWER + " Qd8+ Kxd8 Bg5+ Kc7 Bd8#",
        ),
    ]
    defender_steps = [
        example(
            "defender-capture",
            "Take away the guard",
            "Many pieces have a job, such as guarding a square. Remove the guard and the job is left undone. Your queen on d3 and bishop on b1 aim at h7. Black's knight on f6 is the piece that stops Qxh7 from being checkmate.",
            CAPTURED_GUARD,
            "defender-capture-take",
            squares=("f6",),
            arrows=(("b1", "h7"),),
        ),
        decision(
            "defender-capture-take",
            "Capture the guard",
            "Remove the knight that guards h7.",
            "",
            "Bxf6",
            "g6",
            "defender-capture-collect",
            "Bxf6 removes the guard and also attacks Black's queen on d8. If Black takes the bishop, Qxh7 is checkmate, so Black blocks your diagonal with ...g6.",
            "Capture on f6 with the g5-bishop.",
            fen=CAPTURED_GUARD,
        ),
        decision(
            "defender-capture-collect",
            "Take the queen",
            "Your bishop on f6 still attacks the queen.",
            "Bxf6 g6",
            "Bxd8",
            "Raxd8",
            "defender-chase",
            "Bxd8 wins the queen, and Black takes back with a rook. Your bishop captured a knight and a queen before it was lost.",
            "Capture on d8 with the bishop.",
            fen=CAPTURED_GUARD,
        ),
        example(
            "defender-chase",
            "Chase the guard away",
            "You do not always have to capture a guard. Attacking it can be enough, because a guard that moves leaves its job. Black's knight on f6 guards h7 again, and this time your own pawn on e4 blocks your queen's diagonal.",
            CHASED_GUARD,
            "defender-chase-push",
            squares=("e4", "f6"),
        ),
        decision(
            "defender-chase-push",
            "Attack the guard",
            "Push a pawn that attacks the knight and opens your queen's diagonal at the same time.",
            "",
            "e5",
            "Rfe8",
            "defender-chase-collect",
            "e5 attacks the knight. If it moves away, it stops guarding h7. Black frees f8 for the king with ...Rfe8 and gives up the knight instead.",
            "Move the pawn from e4 to e5.",
            fen=CHASED_GUARD,
        ),
        decision(
            "defender-chase-collect",
            "Win the knight",
            "The knight is still attacked.",
            "e5 Rfe8",
            "exf6",
            "gxf6",
            "defender-count",
            "exf6 wins the knight for a pawn after ...gxf6. Black's king is also more exposed: Qxh7+ wins another pawn with check next.",
            "Capture on f6 with the e5-pawn.",
            fen=CHASED_GUARD,
        ),
        example(
            "defender-count",
            "Count attackers and defenders",
            "Count the attackers and defenders of a piece. Your rook on e1 attacks Black's bishop on e5, and only the knight on c6 defends it. Remove that knight and the bishop is undefended.",
            ONLY_DEFENDER,
            "defender-count-take",
            squares=("e5", "c6"),
        ),
        decision(
            "defender-count-take",
            "Remove the only defender",
            "Capture the bishop's only defender.",
            "",
            "Bxc6",
            "bxc6",
            "defender-count-collect",
            "Bxc6 removes the defender. Black takes back with ...bxc6, and the bishop on e5 is left undefended. If Black saves the bishop instead, for example with ...Bf6, you have still won the knight.",
            "Capture on c6 with the bishop.",
            fen=ONLY_DEFENDER,
        ),
        decision(
            "defender-count-collect",
            "Take the bishop",
            "The bishop on e5 has lost its only defender.",
            "Bxc6 bxc6",
            "Rxe5",
            None,
            "defender-summary",
            "Rxe5 wins the bishop. You traded your bishop for the knight, then took Black's bishop for free.",
            "Capture on e5 with the rook.",
            fen=ONLY_DEFENDER,
        ),
        step(
            "explanation",
            "defender-summary",
            "Ask what each piece guards",
            "Before attacking a piece or square, ask what defends it. Capture the defender, or attack it so it has to move, and what it protected becomes a target. "
            + practice("Capturing defender or Deflection"),
            "Bxc6 bxc6 Rxe5",
            ONLY_DEFENDER,
        ),
    ]
    back_rank_steps = [
        example(
            "back-rank-open",
            "Trapped behind its own pawns",
            "A castled king often sits behind three unmoved pawns. They shield the king, but they also block its escape. If a rook or queen checks along the back rank and nothing can capture it or block, it is checkmate. No black piece guards e8 here.",
            OPEN_BACK_RANK,
            "back-rank-open-mate",
            squares=("f7", "g7", "h7"),
        ),
        decision(
            "back-rank-open-mate",
            "Mate on the back rank",
            "Find the checkmate on Black's back rank, the eighth rank.",
            "",
            "Re8#",
            None,
            "back-rank-count",
            "Re8 is checkmate. The rook checks along the eighth rank, the pawns on f7, g7 and h7 hold the king in, and no black piece can take the rook or block on f8.",
            "Move the rook from e1 to e8.",
            fen=OPEN_BACK_RANK,
        ),
        example(
            "back-rank-count",
            "Count the guards",
            "When the back rank is guarded, count. Black's rook on e8 holds the back rank, and the bishop on d7 defends it. Your rooks are doubled: one behind the other on the e-file.",
            GUARDED_BACK_RANK,
            "back-rank-count-trade",
            squares=("e8", "d7"),
        ),
        decision(
            "back-rank-count-trade",
            "Start the exchange",
            "Capture on e8 with check, then count what can take back.",
            "",
            "Rxe8+",
            "Bxe8",
            "back-rank-count-mate",
            "Rxe8+ leaves Black only one legal move, ...Bxe8. Nothing else of Black's guards e8 now.",
            "Capture on e8 with the e2-rook.",
            fen=GUARDED_BACK_RANK,
        ),
        decision(
            "back-rank-count-mate",
            "The last capture",
            "Make the last capture on e8.",
            "Rxe8+ Bxe8",
            "Rxe8#",
            None,
            "back-rank-sacrifice",
            "Rxe8 is checkmate. You had two rooks attacking e8 and Black had only one piece to take back, so your last capture landed with mate.",
            "Capture on e8 with the e1-rook.",
            fen=GUARDED_BACK_RANK,
        ),
        example(
            "back-rank-sacrifice",
            "Break the guard with a sacrifice",
            "Sometimes the guard can only be broken by giving up material. Black's rook on c8 holds the back rank, and Black's queen on d7 defends it. Your queen and rook are doubled on the c-file.",
            QUEEN_SACRIFICE,
            "back-rank-sacrifice-queen",
            squares=("c8", "d7"),
        ),
        decision(
            "back-rank-sacrifice-queen",
            "Give up the queen",
            "Capture the c8-rook with your queen, with check.",
            "",
            "Qxc8+",
            "Qxc8",
            "back-rank-sacrifice-mate",
            "Qxc8+ checks along the eighth rank. Black can block on d8 or e8, or take your queen with ...Qxc8, and every answer is mated next move. Black takes the queen.",
            "Capture on c8 with the queen.",
            fen=QUEEN_SACRIFICE,
        ),
        decision(
            "back-rank-sacrifice-mate",
            "Mate with the rook",
            "Finish on the back rank.",
            "Qxc8+ Qxc8",
            "Rxc8#",
            None,
            "back-rank-summary",
            "Rxc8 is checkmate. Your queen pulled Black's queen away from d7, and the rook behind it finished the job.",
            "Capture on c8 with the rook.",
            fen=QUEEN_SACRIFICE,
        ),
        step(
            "explanation",
            "back-rank-summary",
            "Give your own king air",
            "Look at your own back rank too. Your pawn on h3 gives your king an escape square on h2, so a check along your back rank need not be mate. Chess players call such a square luft, German for air. "
            + practice("Back rank mate"),
            "Qxc8+ Qxc8 Rxc8#",
            QUEEN_SACRIFICE,
        ),
    ]
    return CourseDefinition.model_validate(
        dict(
            id="tactics-foundations",
            revision="2026-10-v1",
            title="Tactics · Six basic patterns",
            description="Learn six basic tactics: forks, pins, skewers, discovered attacks, removing a defender and back-rank checkmate. Each chapter explains one pattern, then you find the winning moves in three positions. Two positions are well-known opening traps and one comes from Réti–Tartakower, Vienna 1910; the others were composed for this course. Stockfish checked every answer.",
            learner_color="white",
            attributions=[
                dict(
                    text="Original Fieldwork instruction. Positions without a named source were composed for this course.",
                    license="Repository license",
                ),
                dict(
                    text="Réti–Tartakower, Vienna 1910: score and first publication as researched by Edward Winter, Chess Notes",
                    url="https://www.chesshistory.com/winter/extra/retitartakower.html",
                ),
            ],
            chapters=[
                dict(id=identity, title=title, entry_step=steps[0]["id"], steps=steps)
                for identity, title, steps in (
                    ("forks", "Forks: attack two pieces at once", fork_steps),
                    ("pins", "Pins: hold a piece in front of a bigger one", pin_steps),
                    ("skewers", "Skewers: attack through the bigger piece", skewer_steps),
                    ("discovered-attacks", "Discovered attacks and double check", discovered_steps),
                    ("remove-the-defender", "Remove the defender", defender_steps),
                    ("back-rank", "Back-rank checkmate", back_rank_steps),
                )
            ],
        )
    )
