"""Chapter 1 of the Vienna Gambit: Black takes the pawn with 3...exf4."""

from trainer.study_lessons.courses.authoring import decision, demo, step
from trainer.study_lessons.courses.vienna_positions import (
    ACCEPTED,
    BLOCK,
    CENTER,
    CHECK,
    FORK,
    HUNT,
    KING_BACK,
    KING_TAKES,
    KNIGHT,
    PIN,
    PUSHED,
    QUEEN,
    RETREAT,
    SACRIFICE,
)


def queen_trip():
    return [
        demo(
            "accepted-queen",
            "The queen blocks the e-file",
            "Black moves the queen to e7 instead of retreating the knight. The queen now attacks your e5-pawn, and your king on e1 stands behind it on the same file.",
            PUSHED,
            PUSHED + " Qe7",
            "accepted-queen-guard",
        ),
        decision(
            "accepted-queen-guard",
            "Guard the e-file",
            "Move your queen to e2. It defends e5 and stands between Black's queen and your king.",
            PUSHED + " Qe7",
            "Qe2",
            "Ng8",
            "accepted-queen-develop",
            "Black's knight retreats to g8.",
            "Move the queen from d1 to e2.",
        ),
        decision(
            "accepted-queen-develop",
            "Support the pawn",
            "Push d4. It supports e5 and opens the c1-bishop's path toward f4.",
            PUSHED + " Qe7 Qe2 Ng8",
            "d4",
            "d6",
            "accepted-queen-jump",
            "Black attacks your e5-pawn with d6.",
            "Move d2 to d4.",
        ),
        decision(
            "accepted-queen-jump",
            "Attack the queen",
            "Jump the c3-knight to d5. It attacks Black's queen on e7 and the c7-pawn.",
            PUSHED + " Qe7 Qe2 Ng8 d4 d6",
            "Nd5",
            "Qd7",
            "accepted-queen-discover",
            "The queen moves to d7. Now the e-file between your queen and Black's king is clear except for your e5-pawn.",
            "Move the knight from c3 to d5.",
        ),
        decision(
            "accepted-queen-discover",
            "Uncover a check",
            "Capture on d6 with the e5-pawn. Moving the pawn opens the e-file, so your queen on e2 gives check.",
            PUSHED + " Qe7 Qe2 Ng8 d4 d6 Nd5 Qd7",
            "exd6+",
            "Kd8",
            "accepted-queen-fork",
            "The king steps to d8. Your d6-pawn can capture again.",
            "Move the pawn from e5 to d6.",
        ),
        decision(
            "accepted-queen-fork",
            "Check again",
            "Capture the c7-pawn with your d6-pawn. It gives check and attacks the b8-knight.",
            PUSHED + " Qe7 Qe2 Ng8 d4 d6 Nd5 Qd7 exd6+ Kd8",
            "dxc7+",
            None,
            "accepted-queen-summary",
            "The pawn checks the king from c7.",
            "Move the pawn from d6 to c7.",
        ),
        step(
            "explanation",
            "accepted-queen-summary",
            "Watch the knight on d5",
            "Black's king cannot take on c7, because your d5-knight guards that square. If Black's queen takes the pawn, your knight takes the queen.",
            QUEEN,
        ),
    ]


def knight_trip():
    before = RETREAT + " Nc6"
    return [
        demo(
            "accepted-knight",
            "Black develops the knight",
            "Black develops the b8-knight to c6, where it attacks your e5-pawn.",
            RETREAT,
            before,
            "accepted-knight-center",
        ),
        decision(
            "accepted-knight-center",
            "Support the pawn",
            "Push d4. It supports e5 and opens a path for the c1-bishop toward f4.",
            before,
            "d4",
            "d6",
            "accepted-knight-pin",
            "Black attacks e5 a second time with d6.",
            "Move d2 to d4.",
        ),
        decision(
            "accepted-knight-pin",
            "Pin the knight",
            "Develop the f1-bishop to b5. It pins the c6-knight to Black's king: if the knight moved, the bishop would give check.",
            before + " d4 d6",
            "Bb5",
            "Bd7",
            "accepted-knight-queen",
            "Black defends the c6-knight with Bd7.",
            "Move the bishop from f1 to b5.",
        ),
        decision(
            "accepted-knight-queen",
            "Bring the queen to the e-file",
            "Move your queen to e2. It defends the b5-bishop and lines up on the e-file toward Black's king.",
            before + " d4 d6 Bb5 Bd7",
            "Qe2",
            "dxe5",
            "accepted-knight-recapture",
            "Black takes your e5-pawn.",
            "Move the queen from d1 to e2.",
        ),
        decision(
            "accepted-knight-recapture",
            "Win back the gambit pawn",
            "Take the f4-pawn with the c1-bishop.",
            before + " d4 d6 Bb5 Bd7 Qe2 dxe5",
            "Bxf4",
            None,
            "accepted-knight-summary",
            "Your bishop is developed and attacks the e5-pawn.",
            "Move the bishop from c1 to f4.",
        ),
        step(
            "explanation",
            "accepted-knight-summary",
            "Pressure on e5",
            "Black is still a pawn ahead, but your d4-pawn, f3-knight, f4-bishop and e2-queen all attack the e5-pawn, and Black's kingside pieces have not moved.",
            KNIGHT,
        ),
    ]


def pin_trip():
    before = CENTER + " Bg4"
    return [
        demo(
            "accepted-pin",
            "Black pins the knight",
            "Black develops the c8-bishop to g4, pinning your f3-knight to the queen on d1.",
            CENTER,
            before,
            "accepted-pin-take",
        ),
        decision(
            "accepted-pin-take",
            "Win back the pawn",
            "Take the f4-pawn with the c1-bishop. It also defends your e5-pawn.",
            before,
            "Bxf4",
            "dxe5",
            "accepted-pin-recapture",
            "Black takes on e5.",
            "Move the bishop from c1 to f4.",
        ),
        decision(
            "accepted-pin-recapture",
            "Take back",
            "Recapture on e5 with the bishop.",
            before + " Bxf4 dxe5",
            "Bxe5",
            "Nc6",
            "accepted-pin-bishop",
            "Black develops Nc6 and attacks your e5-bishop.",
            "Move the bishop from f4 to e5.",
        ),
        decision(
            "accepted-pin-bishop",
            "Pin the knight back",
            "Develop the f1-bishop to b5. It pins the c6-knight to Black's king.",
            before + " Bxf4 dxe5 Bxe5 Nc6",
            "Bb5",
            None,
            "accepted-pin-summary",
            "The c6-knight cannot take your e5-bishop without exposing Black's king to check.",
            "Move the bishop from f1 to b5.",
        ),
        step(
            "explanation",
            "accepted-pin-summary",
            "Material is level",
            "Both sides have won and lost two pawns, so material is level. Your bishops are active and you can castle next.",
            PIN,
        ),
    ]


def block_trip():
    return [
        demo(
            "accepted-block",
            "Black blocks with the bishop",
            "Black blocks the check with the c8-bishop on d7.",
            CHECK,
            CHECK + " Bd7",
            "accepted-block-queen",
        ),
        decision(
            "accepted-block-queen",
            "Attack e5 and guard the bishop",
            "Move your queen to e2. It attacks the e5-pawn and defends your b5-bishop.",
            CHECK + " Bd7",
            "Qe2",
            "Bxb5",
            "accepted-block-recapture",
            "Black exchanges bishops.",
            "Move the queen from d1 to e2.",
        ),
        decision(
            "accepted-block-recapture",
            "Take back with the knight",
            "Recapture on b5 with the c3-knight.",
            CHECK + " Bd7 Qe2 Bxb5",
            "Nxb5",
            None,
            "accepted-block-summary",
            "Your knight on b5 attacks c7.",
            "Move the knight from c3 to b5.",
        ),
        step(
            "explanation",
            "accepted-block-summary",
            "Two targets",
            "Your b5-knight threatens to jump into c7 with check, and your queen attacks the e5-pawn. Black has to deal with both.",
            BLOCK,
        ),
    ]


def king_takes_trip():
    return [
        demo(
            "accepted-king-takes",
            "The king takes at once",
            "Black's king takes your bishop on f7 instead of stepping to e7.",
            SACRIFICE,
            SACRIFICE + " Kxf7",
            "accepted-king-takes-queen",
        ),
        decision(
            "accepted-king-takes-queen",
            "Take the queen",
            "Take Black's queen on d8 with your queen. The d-file is completely open.",
            SACRIFICE + " Kxf7",
            "Qxd8",
            None,
            "accepted-king-takes-summary",
            "You have won Black's queen.",
            "Move the queen from d1 to d8.",
        ),
        step(
            "explanation",
            "accepted-king-takes-summary",
            "The open d-file",
            "Both sides' d-pawns had left the d-file, so your queen on d1 was looking straight at Black's queen on d8. When the king took your bishop, nothing stood in the way.",
            KING_TAKES,
        ),
    ]


def king_back_trip():
    return [
        demo(
            "accepted-king-back",
            "The king goes back",
            "Black's king steps back to e8 instead of f6.",
            HUNT,
            HUNT + " Ke8",
            "accepted-king-back-discover",
        ),
        decision(
            "accepted-king-back-discover",
            "Uncover a check",
            "Take the c6-pawn with your e5-knight. Moving the knight opens the e-file, so your queen gives check, and the knight now attacks Black's queen.",
            HUNT + " Ke8",
            "Nxc6+",
            "Qe7",
            "accepted-king-back-queen",
            "Black blocks the check with the queen on e7.",
            "Move the knight from e5 to c6.",
        ),
        decision(
            "accepted-king-back-queen",
            "Take the queen",
            "Capture Black's queen on e7 with the knight.",
            HUNT + " Ke8 Nxc6+ Qe7",
            "Nxe7",
            None,
            "accepted-king-back-summary",
            "You have won Black's queen.",
            "Move the knight from c6 to e7.",
        ),
        step(
            "explanation",
            "accepted-king-back-summary",
            "A discovered check",
            "When one piece moves out of the way and another piece behind it gives check, it is a discovered check. The moving knight was free to attack the queen.",
            KING_BACK,
        ),
    ]


def chapter():
    steps = [
        step(
            "explanation",
            "accepted-welcome",
            "The Vienna Gambit",
            "You play White. After 1.e4 e5 2.Nc3 Nf6 you push f4, offering a pawn to open lines for your pieces. This is the Vienna Gambit. Most club players take the pawn with exf4, and this chapter shows how to punish that.",
            next_step="accepted-king-pawn",
        ),
        decision(
            "accepted-king-pawn",
            "Open with the king's pawn",
            "Push your e-pawn two squares.",
            "",
            "e4",
            "e5",
            "accepted-development",
            "Black answers in the center with e5.",
            "Move e2 to e4.",
        ),
        decision(
            "accepted-development",
            "Develop the queenside knight",
            "Develop the b1-knight to c3. Unlike Nf3, it leaves your f-pawn free to advance.",
            "e4 e5",
            "Nc3",
            "Nf6",
            "accepted-gambit",
            "Black develops Nf6.",
            "Move the knight from b1 to c3.",
        ),
        decision(
            "accepted-gambit",
            "Offer the f-pawn",
            "Push f4. The pawn attacks e5 and offers itself to open the f-file.",
            "e4 e5 Nc3 Nf6",
            "f4",
            "exf4",
            "accepted-push",
            "Black takes the pawn.",
            "Move f2 to f4.",
        ),
        decision(
            "accepted-push",
            "Chase the knight",
            "Push e5. The pawn attacks Black's f6-knight.",
            ACCEPTED,
            "e5",
            None,
            "accepted-queen-choice",
            "The knight is attacked and must move.",
            "Move the pawn from e4 to e5.",
        ),
        step(
            "branch",
            "accepted-queen-choice",
            "If the queen goes to e7",
            "The knight usually goes back to g8. Explore Qe7 first, or continue with Ng8.",
            PUSHED,
            branch_start="accepted-queen",
            next_step="accepted-retreat",
        ),
        *queen_trip(),
        demo(
            "accepted-retreat",
            "The knight goes home",
            "Black's knight retreats to g8, its starting square.",
            PUSHED,
            PUSHED + " Ng8",
            "accepted-develop",
        ),
        decision(
            "accepted-develop",
            "Develop and cover h4",
            "Develop the g1-knight to f3. It controls h4, where Black's queen could otherwise give check.",
            PUSHED + " Ng8",
            "Nf3",
            None,
            "accepted-knight-choice",
            "Your knight is out, and Black's queen can no longer check on h4.",
            "Move the knight from g1 to f3.",
        ),
        step(
            "branch",
            "accepted-knight-choice",
            "If Black plays Nc6",
            "Black most often attacks e5 with d6. Explore Nc6 first, or continue with d6.",
            RETREAT,
            branch_start="accepted-knight",
            next_step="accepted-challenge",
        ),
        *knight_trip(),
        demo(
            "accepted-challenge",
            "Black attacks e5",
            "Black pushes d6 to attack your e5-pawn.",
            RETREAT,
            RETREAT + " d6",
            "accepted-center",
        ),
        decision(
            "accepted-center",
            "Support the pawn",
            "Push d4. It supports e5 and opens the c1-bishop's path toward f4.",
            RETREAT + " d6",
            "d4",
            None,
            "accepted-pin-choice",
            "Your pawns on d4 and e5 control the center.",
            "Move d2 to d4.",
        ),
        step(
            "branch",
            "accepted-pin-choice",
            "If Black pins with Bg4",
            "Black usually takes on e5. Explore the pin with Bg4 first, or continue with dxe5.",
            CENTER,
            branch_start="accepted-pin",
            next_step="accepted-exchange",
        ),
        *pin_trip(),
        demo(
            "accepted-exchange",
            "Black takes on e5",
            "Black's d-pawn takes your e5-pawn.",
            CENTER,
            CENTER + " dxe5",
            "accepted-check",
        ),
        decision(
            "accepted-check",
            "Check before recapturing",
            "Give check with the f1-bishop on b5. Taking back on e5 with the d-pawn would let Black trade queens with Qxd1+.",
            CENTER + " dxe5",
            "Bb5+",
            None,
            "accepted-block-choice",
            "Black must answer the check.",
            "Move the bishop from f1 to b5.",
        ),
        step(
            "branch",
            "accepted-block-choice",
            "If Black blocks with Bd7",
            "Black usually blocks with c6. Explore Bd7 first, or continue with c6.",
            CHECK,
            branch_start="accepted-block",
            next_step="accepted-pawn-block",
        ),
        *block_trip(),
        demo(
            "accepted-pawn-block",
            "Black blocks with a pawn",
            "Black blocks the check with c6, and the pawn attacks your bishop.",
            CHECK,
            CHECK + " c6",
            "accepted-bishop",
        ),
        decision(
            "accepted-bishop",
            "Aim at f7",
            "Move the bishop to c4, where it aims at f7.",
            CHECK + " c6",
            "Bc4",
            "exd4",
            "accepted-recapture",
            "Black takes your d4-pawn. The pawn on d4 now attacks your c3-knight.",
            "Move the bishop from b5 to c4.",
        ),
        decision(
            "accepted-recapture",
            "Take back the gambit pawn",
            "Take the f4-pawn with the c1-bishop. Let Black take your knight: you are getting your pieces out for an attack.",
            CHECK + " c6 Bc4 exd4",
            "Bxf4",
            "dxc3",
            "accepted-sacrifice",
            "Black takes your c3-knight. Now count the pieces aimed at Black's king.",
            "Move the bishop from c1 to f4.",
        ),
        decision(
            "accepted-sacrifice",
            "Sacrifice on f7",
            "Take the f7-pawn with your bishop, with check.",
            CHECK + " c6 Bc4 exd4 Bxf4 dxc3",
            "Bxf7+",
            None,
            "accepted-king-takes-choice",
            "Black's king must move or take the bishop.",
            "Move the bishop from c4 to f7.",
        ),
        step(
            "branch",
            "accepted-king-takes-choice",
            "If the king takes at once",
            "Black most often steps to e7. Explore Kxf7 first, or continue with Ke7.",
            SACRIFICE,
            branch_start="accepted-king-takes",
            next_step="accepted-step",
        ),
        *king_takes_trip(),
        demo(
            "accepted-step",
            "The king steps aside",
            "Black's king steps to e7.",
            SACRIFICE,
            SACRIFICE + " Ke7",
            "accepted-queen-check",
        ),
        decision(
            "accepted-queen-check",
            "Check on the e-file",
            "Move your queen to e2 with check. The e-file is open all the way to Black's king.",
            SACRIFICE + " Ke7",
            "Qe2+",
            "Kxf7",
            "accepted-knight-check",
            "The king takes your bishop on f7.",
            "Move the queen from d1 to e2.",
        ),
        decision(
            "accepted-knight-check",
            "Check with the knight",
            "Jump the f3-knight to e5 with check.",
            SACRIFICE + " Ke7 Qe2+ Kxf7",
            "Ne5+",
            None,
            "accepted-king-back-choice",
            "The king must move again.",
            "Move the knight from f3 to e5.",
        ),
        step(
            "branch",
            "accepted-king-back-choice",
            "If the king goes back",
            "Black most often plays Kf6. Explore Ke8 first, or continue with Kf6.",
            HUNT,
            branch_start="accepted-king-back",
            next_step="accepted-king-out",
        ),
        *king_back_trip(),
        demo(
            "accepted-king-out",
            "The king walks out",
            "Black's king steps forward to f6.",
            HUNT,
            HUNT + " Kf6",
            "accepted-lure",
        ),
        decision(
            "accepted-lure",
            "Lure the king",
            "Give check with the f4-bishop on g5. If the king takes it, your knight can check again.",
            HUNT + " Kf6",
            "Bg5+",
            "Kxg5",
            "accepted-fork",
            "The king takes your bishop on g5.",
            "Move the bishop from f4 to g5.",
        ),
        decision(
            "accepted-fork",
            "Fork king, queen and rook",
            "Jump the e5-knight to f7 with check. From f7 it also attacks Black's queen on d8 and rook on h8.",
            HUNT + " Kf6 Bg5+ Kxg5",
            "Nf7+",
            None,
            "accepted-summary",
            "The king must move, and then your knight takes the queen or the rook.",
            "Move the knight from e5 to f7.",
        ),
        step(
            "explanation",
            "accepted-summary",
            "Checks first, material later",
            "You gave up a knight and two bishops, but every move was a check, so Black never had time to defend. Now Black's king must move, and your knight wins the queen or the rook. When the opponent's king is exposed, look at checks first.",
            FORK,
            next_step="accepted-rehearsal",
        ),
        step(
            "rehearsal",
            "accepted-rehearsal",
            "Play the accepted gambit",
            "Play the main line from the first move without prompts.",
            line_id="vienna-accepted",
        ),
    ]
    return dict(
        id="vienna-accepted",
        title="The gambit accepted",
        entry_step=steps[0]["id"],
        steps=steps,
    )
