"""Shared SAN histories for the Vienna Gambit course."""

VIENNA = "e4 e5 Nc3"
GAMBIT = VIENNA + " Nf6 f4"
ACCEPTED = GAMBIT + " exf4"
PUSHED = ACCEPTED + " e5"
RETREAT = PUSHED + " Ng8 Nf3"
CENTER = RETREAT + " d6 d4"
CHECK = CENTER + " dxe5 Bb5+"
SACRIFICE = CHECK + " c6 Bc4 exd4 Bxf4 dxc3 Bxf7+"
HUNT = SACRIFICE + " Ke7 Qe2+ Kxf7 Ne5+"
FORK = HUNT + " Kf6 Bg5+ Kxg5 Nf7+"
KING_TAKES = SACRIFICE + " Kxf7 Qxd8"
KING_BACK = HUNT + " Ke8 Nxc6+ Qe7 Nxe7"
BLOCK = CHECK + " Bd7 Qe2 Bxb5 Nxb5"
QUEEN = PUSHED + " Qe7 Qe2 Ng8 d4 d6 Nd5 Qd7 exd6+ Kd8 dxc7+"
KNIGHT = RETREAT + " Nc6 d4 d6 Bb5 Bd7 Qe2 dxe5 Bxf4"
PIN = CENTER + " Bg4 Bxf4 dxe5 Bxe5 Nc6 Bb5"

STRIKE = GAMBIT + " d5 fxe5 Nxe4 Nf3"
TRADE = STRIKE + " Nxc3 bxc3"
STRIKE_CENTER = TRADE + " Bg4 d4"
STRIKE_CASTLED = STRIKE_CENTER + " Nc6 Bd3 Be7 O-O"
STRIKE_LINE = STRIKE_CASTLED + " O-O h3"
STRIKE_PIN = STRIKE + " Bg4 Qe2 Nxc3 dxc3 Nc6 Bf4"
STRIKE_BISHOP = STRIKE + " Bc5 d4 Bb4 Bd2 Nxd2 Qxd2"
STRIKE_KNIGHT = TRADE + " Nc6 d4 Bg4 Bd3 Be7 O-O"

SOLID = GAMBIT + " d6 Nf3"
SOLID_LINE = SOLID + " Nc6 d4 exd4 Nxd4 Nxd4 Qxd4 Be7 Be3 O-O O-O-O"
SOLID_PIN = SOLID + " Bg4 h3 Bxf3 Qxf3 Nc6 Bb5"
SOLID_TAKE = SOLID + " exf4 d4 Bg4 Bxf4"
DEFENDED = GAMBIT + " Nc6 fxe5 Nxe5 d4 Nc6 e5 Ng8 Nf3"

KNIGHTS = VIENNA + " Nc6 Bc4 Nf6 d3"
KNIGHTS_LINE = KNIGHTS + " Bc5 Nf3 d6 O-O Bg4 h3"
KNIGHTS_EARLY = VIENNA + " Nc6 Bc4 Bc5 Nf3 Nf6 O-O O-O d3"
KNIGHTS_PIN = KNIGHTS + " Bb4 Nf3 Bxc3+ bxc3"
BISHOP_FIRST = VIENNA + " Bc5 Nf3 d6 d4 exd4 Nxd4 Nf6 Bg5 h6 Bh4 g5 Bg3"
