"""Chapters 2 to 4 of the Vienna Gambit: 3...d5, Black's other third moves and second moves."""

from trainer.study_lessons.courses.authoring import decision, demo, step
from trainer.study_lessons.courses.vienna_positions import (
    BISHOP_FIRST,
    DEFENDED,
    GAMBIT,
    KNIGHTS,
    KNIGHTS_EARLY,
    KNIGHTS_LINE,
    KNIGHTS_PIN,
    SOLID,
    SOLID_LINE,
    SOLID_PIN,
    SOLID_TAKE,
    STRIKE,
    STRIKE_BISHOP,
    STRIKE_CASTLED,
    STRIKE_CENTER,
    STRIKE_KNIGHT,
    STRIKE_LINE,
    STRIKE_PIN,
    TRADE,
)

VIENNA = "e4 e5 Nc3"


def strike_pin_trip():
    return [
        demo(
            "strike-pin",
            "Black pins the knight first",
            "Black develops the c8-bishop to g4 instead of trading knights. It pins your f3-knight to the queen on d1.",
            STRIKE,
            STRIKE + " Bg4",
            "strike-pin-queen",
        ),
        decision(
            "strike-pin-queen",
            "Attack the knight",
            "Move your queen to e2. It attacks Black's e4-knight, and the f3-knight is no longer pinned to the queen.",
            STRIKE + " Bg4",
            "Qe2",
            "Nxc3",
            "strike-pin-recapture",
            "Black's knight takes your c3-knight.",
            "Move the queen from d1 to e2.",
        ),
        decision(
            "strike-pin-recapture",
            "Take back with the d-pawn",
            "Recapture with the d-pawn. It opens the path for your c1-bishop.",
            STRIKE + " Bg4 Qe2 Nxc3",
            "dxc3",
            "Nc6",
            "strike-pin-guard",
            "Black's Nc6 attacks your e5-pawn.",
            "Move the pawn from d2 to c3.",
        ),
        decision(
            "strike-pin-guard",
            "Defend the pawn",
            "Develop the c1-bishop to f4, where it defends e5.",
            STRIKE + " Bg4 Qe2 Nxc3 dxc3 Nc6",
            "Bf4",
            None,
            "strike-pin-summary",
            "Your e5-pawn is defended by the f3-knight and the f4-bishop.",
            "Move the bishop from c1 to f4.",
        ),
        step(
            "explanation",
            "strike-pin-summary",
            "Castle queenside next",
            "Your queen and c1-bishop have left the back rank, so you can castle queenside next. The e5-pawn gives you space in the center.",
            STRIKE_PIN,
        ),
    ]


def strike_bishop_trip():
    return [
        demo(
            "strike-bishop",
            "Black develops the bishop",
            "Black develops the f8-bishop to c5, aiming at g1.",
            STRIKE,
            STRIKE + " Bc5",
            "strike-bishop-center",
        ),
        decision(
            "strike-bishop-center",
            "Attack the bishop",
            "Push d4. The pawn attacks the c5-bishop and takes the center.",
            STRIKE + " Bc5",
            "d4",
            "Bb4",
            "strike-bishop-block",
            "The bishop moves to b4 and pins your c3-knight to your king.",
            "Move d2 to d4.",
        ),
        decision(
            "strike-bishop-block",
            "Break the pin",
            "Develop the c1-bishop to d2, between the b4-bishop and your king.",
            STRIKE + " Bc5 d4 Bb4",
            "Bd2",
            "Nxd2",
            "strike-bishop-recapture",
            "Black's knight takes your d2-bishop.",
            "Move the bishop from c1 to d2.",
        ),
        decision(
            "strike-bishop-recapture",
            "Take back with the queen",
            "Recapture on d2 with your queen.",
            STRIKE + " Bc5 d4 Bb4 Bd2 Nxd2",
            "Qxd2",
            None,
            "strike-bishop-summary",
            "Your queen defends the c3-knight, so it is no longer pinned.",
            "Move the queen from d1 to d2.",
        ),
        step(
            "explanation",
            "strike-bishop-summary",
            "A big center",
            "Your pawns on d4 and e5 give you space. Your b1-knight, c1-bishop and queen have all left the back rank, so you can castle queenside next.",
            STRIKE_BISHOP,
        ),
    ]


def strike_knight_trip():
    return [
        demo(
            "strike-knight",
            "Black develops the knight first",
            "Black develops the b8-knight to c6 before pinning with the bishop.",
            TRADE,
            TRADE + " Nc6",
            "strike-knight-center",
        ),
        decision(
            "strike-knight-center",
            "Take the center",
            "Push d4. Your pawns on c3, d4 and e5 form a strong center.",
            TRADE + " Nc6",
            "d4",
            "Bg4",
            "strike-knight-bishop",
            "Black pins your f3-knight with Bg4.",
            "Move d2 to d4.",
        ),
        decision(
            "strike-knight-bishop",
            "Develop the bishop",
            "Develop the f1-bishop to d3 so that you can castle.",
            TRADE + " Nc6 d4 Bg4",
            "Bd3",
            "Be7",
            "strike-knight-castle",
            "Black develops Be7.",
            "Move the bishop from f1 to d3.",
        ),
        decision(
            "strike-knight-castle",
            "Castle",
            "Castle kingside. Your rook arrives on the open f-file.",
            TRADE + " Nc6 d4 Bg4 Bd3 Be7",
            "O-O",
            None,
            "strike-knight-summary",
            "Your king is safe and your rook is on f1.",
            "Move the king from e1 to g1.",
        ),
        step(
            "explanation",
            "strike-knight-summary",
            "Same position, different order",
            "If Black castles now, you reach the chapter's main line: play h3 to question the g4-bishop.",
            STRIKE_KNIGHT,
        ),
    ]


def strike_chapter():
    steps = [
        step(
            "explanation",
            "strike-welcome",
            "Black strikes with d5",
            "The classical answer to the Vienna Gambit is d5: instead of taking your f-pawn, Black hits back in the center. You take on e5, develop quickly and build a center with d4.",
            next_step="strike-arrival",
        ),
        demo(
            "strike-arrival",
            "Reach the Vienna Gambit",
            "You offer the f-pawn, and Black answers with d5, attacking your e4-pawn.",
            "",
            GAMBIT + " d5",
            "strike-take",
        ),
        decision(
            "strike-take",
            "Take on e5",
            "Capture the e5-pawn with your f-pawn. Your new pawn on e5 attacks the f6-knight.",
            GAMBIT + " d5",
            "fxe5",
            "Nxe4",
            "strike-develop",
            "Black's knight takes your e4-pawn and stands in the center.",
            "Move the pawn from f4 to e5.",
        ),
        decision(
            "strike-develop",
            "Develop and guard e5",
            "Develop the g1-knight to f3. It defends the e5-pawn.",
            GAMBIT + " d5 fxe5 Nxe4",
            "Nf3",
            None,
            "strike-pin-choice",
            "Black most often trades knights on c3.",
            "Move the knight from g1 to f3.",
        ),
        step(
            "branch",
            "strike-pin-choice",
            "If Black pins with Bg4",
            "Explore Bg4 and Bc5 first, or continue with the knight trade.",
            STRIKE,
            branch_start="strike-pin",
            next_step="strike-bishop-choice",
        ),
        *strike_pin_trip(),
        step(
            "branch",
            "strike-bishop-choice",
            "If Black plays Bc5",
            "Explore Bc5, or continue with the knight trade.",
            STRIKE,
            branch_start="strike-bishop",
            next_step="strike-trade",
        ),
        *strike_bishop_trip(),
        demo(
            "strike-trade",
            "Black trades knights",
            "Black's e4-knight takes your c3-knight.",
            STRIKE,
            STRIKE + " Nxc3",
            "strike-recapture",
        ),
        decision(
            "strike-recapture",
            "Take back toward the center",
            "Recapture with the b-pawn. It moves toward the center and leaves the b-file without a white pawn, ready for a rook.",
            STRIKE + " Nxc3",
            "bxc3",
            None,
            "strike-knight-choice",
            "Black can pin your knight with Bg4 or develop Nc6.",
            "Move the pawn from b2 to c3.",
        ),
        step(
            "branch",
            "strike-knight-choice",
            "If Black plays Nc6",
            "Black most often pins with Bg4. Explore Nc6 first, or continue with Bg4.",
            TRADE,
            branch_start="strike-knight",
            next_step="strike-pinned",
        ),
        *strike_knight_trip(),
        demo(
            "strike-pinned",
            "Black pins the knight",
            "Black's Bg4 pins your f3-knight to the queen on d1.",
            TRADE,
            TRADE + " Bg4",
            "strike-center",
        ),
        decision(
            "strike-center",
            "Build the center",
            "Push d4. Your pawns on c3, d4 and e5 form a strong center.",
            TRADE + " Bg4",
            "d4",
            "Nc6",
            "strike-bishop-out",
            "Black develops Nc6, which attacks d4 and e5.",
            "Move d2 to d4.",
        ),
        decision(
            "strike-bishop-out",
            "Develop the bishop",
            "Develop the f1-bishop to d3 so that you can castle.",
            STRIKE_CENTER + " Nc6",
            "Bd3",
            "Be7",
            "strike-castle",
            "Black develops Be7.",
            "Move the bishop from f1 to d3.",
        ),
        decision(
            "strike-castle",
            "Castle",
            "Castle kingside. Your rook arrives on f1, on a file with no pawn of yours.",
            STRIKE_CENTER + " Nc6 Bd3 Be7",
            "O-O",
            "O-O",
            "strike-question",
            "Black castles too.",
            "Move the king from e1 to g1.",
        ),
        decision(
            "strike-question",
            "Question the bishop",
            "Push h3 to attack the g4-bishop.",
            STRIKE_CASTLED + " O-O",
            "h3",
            None,
            "strike-summary",
            "The bishop must retreat or take your knight.",
            "Move h2 to h3.",
        ),
        step(
            "explanation",
            "strike-summary",
            "Space and open files",
            "Your pawns on c3, d4 and e5 give you space. Your f1-rook has a file with no pawn of yours, and a rook on b1 would use the b-file the same way. Black usually retreats the bishop to h5.",
            STRIKE_LINE,
            next_step="strike-rehearsal",
        ),
        step(
            "rehearsal",
            "strike-rehearsal",
            "Play against d5",
            "Play the main line from the first move without prompts.",
            line_id="vienna-strike",
        ),
    ]
    return dict(
        id="vienna-strike", title="Black strikes with d5", entry_step=steps[0]["id"], steps=steps
    )


def defended_trip():
    return [
        demo(
            "solid-knight",
            "Black defends with the knight",
            "Black defends e5 with the b8-knight on c6.",
            GAMBIT,
            GAMBIT + " Nc6",
            "solid-knight-take",
        ),
        decision(
            "solid-knight-take",
            "Take on e5",
            "Capture the e5-pawn with your f-pawn.",
            GAMBIT + " Nc6",
            "fxe5",
            "Nxe5",
            "solid-knight-chase",
            "Black's knight takes back on e5.",
            "Move the pawn from f4 to e5.",
        ),
        decision(
            "solid-knight-chase",
            "Chase the knight",
            "Push d4. The pawn attacks the e5-knight.",
            GAMBIT + " Nc6 fxe5 Nxe5",
            "d4",
            "Nc6",
            "solid-knight-push",
            "The knight goes back to c6.",
            "Move d2 to d4.",
        ),
        decision(
            "solid-knight-push",
            "Chase the other knight",
            "Push e5. The pawn attacks the f6-knight.",
            GAMBIT + " Nc6 fxe5 Nxe5 d4 Nc6",
            "e5",
            "Ng8",
            "solid-knight-develop",
            "Black's knight goes back to g8.",
            "Move the pawn from e4 to e5.",
        ),
        decision(
            "solid-knight-develop",
            "Develop the knight",
            "Develop the g1-knight to f3.",
            GAMBIT + " Nc6 fxe5 Nxe5 d4 Nc6 e5 Ng8",
            "Nf3",
            None,
            "solid-knight-summary",
            "You have more space and more developed pieces.",
            "Move the knight from g1 to f3.",
        ),
        step(
            "explanation",
            "solid-knight-summary",
            "Space in the center",
            "Your pawns on d4 and e5 push Black's pieces back. Black's g8-knight cannot use f6, so Black will need several moves to develop.",
            DEFENDED,
        ),
    ]


def solid_pin_trip():
    return [
        demo(
            "solid-pin",
            "Black pins the knight",
            "Black's Bg4 pins your f3-knight to the queen on d1.",
            SOLID,
            SOLID + " Bg4",
            "solid-pin-ask",
        ),
        decision(
            "solid-pin-ask",
            "Question the bishop",
            "Push h3 to attack the g4-bishop.",
            SOLID + " Bg4",
            "h3",
            "Bxf3",
            "solid-pin-recapture",
            "Black takes your knight.",
            "Move h2 to h3.",
        ),
        decision(
            "solid-pin-recapture",
            "Take back with the queen",
            "Recapture with your queen, so your kingside pawns stay together.",
            SOLID + " Bg4 h3 Bxf3",
            "Qxf3",
            "Nc6",
            "solid-pin-bishop",
            "Black develops Nc6.",
            "Move the queen from d1 to f3.",
        ),
        decision(
            "solid-pin-bishop",
            "Pin the knight",
            "Develop the f1-bishop to b5. It pins the c6-knight to Black's king.",
            SOLID + " Bg4 h3 Bxf3 Qxf3 Nc6",
            "Bb5",
            None,
            "solid-pin-summary",
            "Black's c6-knight cannot move without exposing the king.",
            "Move the bishop from f1 to b5.",
        ),
        step(
            "explanation",
            "solid-pin-summary",
            "Two bishops",
            "You have both bishops, while Black has given up the c8-bishop. Castle next.",
            SOLID_PIN,
        ),
    ]


def solid_take_trip():
    return [
        demo(
            "solid-take",
            "Black takes the pawn late",
            "Black takes your f4-pawn after all.",
            SOLID,
            SOLID + " exf4",
            "solid-take-center",
        ),
        decision(
            "solid-take-center",
            "Take the center",
            "Push d4. Your pawns stand side by side on d4 and e4, and the c1-bishop's path to f4 opens.",
            SOLID + " exf4",
            "d4",
            "Bg4",
            "solid-take-back",
            "Black pins your f3-knight with Bg4.",
            "Move d2 to d4.",
        ),
        decision(
            "solid-take-back",
            "Win back the pawn",
            "Take the f4-pawn with the c1-bishop.",
            SOLID + " exf4 d4 Bg4",
            "Bxf4",
            None,
            "solid-take-summary",
            "Material is level and your center stands.",
            "Move the bishop from c1 to f4.",
        ),
        step(
            "explanation",
            "solid-take-summary",
            "A big center",
            "Your pawns on d4 and e4 control the center, and your bishop is developed. Develop the f1-bishop and castle next.",
            SOLID_TAKE,
        ),
    ]


def solid_chapter():
    steps = [
        step(
            "explanation",
            "solid-welcome",
            "Black declines the gambit",
            "Not every player takes the pawn or answers d5. Some defend e5 with d6 or Nc6. Then you develop and open the center with d4.",
            next_step="solid-arrival",
        ),
        demo(
            "solid-arrival",
            "Reach the Vienna Gambit",
            "You offer the f-pawn.",
            "",
            GAMBIT,
            "solid-knight-choice",
        ),
        step(
            "branch",
            "solid-knight-choice",
            "If Black plays Nc6",
            "Black most often defends with d6 here. Explore Nc6 first, or continue with d6.",
            GAMBIT,
            branch_start="solid-knight",
            next_step="solid-pawn",
        ),
        *defended_trip(),
        demo(
            "solid-pawn",
            "Black defends with a pawn",
            "Black defends e5 with d6.",
            GAMBIT,
            GAMBIT + " d6",
            "solid-develop",
        ),
        decision(
            "solid-develop",
            "Develop with an attack",
            "Develop the g1-knight to f3. It attacks e5 a second time, together with your f4-pawn.",
            GAMBIT + " d6",
            "Nf3",
            None,
            "solid-pin-choice",
            "Black has to decide how to hold e5.",
            "Move the knight from g1 to f3.",
        ),
        step(
            "branch",
            "solid-pin-choice",
            "If Black pins with Bg4",
            "Black most often develops Nc6. Explore Bg4 and exf4 first, or continue with Nc6.",
            SOLID,
            branch_start="solid-pin",
            next_step="solid-take-choice",
        ),
        *solid_pin_trip(),
        step(
            "branch",
            "solid-take-choice",
            "If Black takes on f4",
            "Explore exf4, or continue with Nc6.",
            SOLID,
            branch_start="solid-take",
            next_step="solid-defend",
        ),
        *solid_take_trip(),
        demo(
            "solid-defend",
            "Black adds a defender",
            "Black develops Nc6, defending e5 again.",
            SOLID,
            SOLID + " Nc6",
            "solid-center",
        ),
        decision(
            "solid-center",
            "Open the center",
            "Push d4, attacking the e5-pawn a third time.",
            SOLID + " Nc6",
            "d4",
            "exd4",
            "solid-recapture",
            "Black takes on d4.",
            "Move d2 to d4.",
        ),
        decision(
            "solid-recapture",
            "Take back with the knight",
            "Recapture on d4 with the f3-knight.",
            SOLID + " Nc6 d4 exd4",
            "Nxd4",
            "Nxd4",
            "solid-queen",
            "Black trades knights on d4.",
            "Move the knight from f3 to d4.",
        ),
        decision(
            "solid-queen",
            "Take back with the queen",
            "Recapture with your queen. The c6-knight that could have chased it is gone.",
            SOLID + " Nc6 d4 exd4 Nxd4 Nxd4",
            "Qxd4",
            "Be7",
            "solid-bishop",
            "Black develops Be7.",
            "Move the queen from d1 to d4.",
        ),
        decision(
            "solid-bishop",
            "Develop and protect the queen",
            "Develop the c1-bishop to e3, where it defends your queen.",
            SOLID + " Nc6 d4 exd4 Nxd4 Nxd4 Qxd4 Be7",
            "Be3",
            "O-O",
            "solid-castle",
            "Black castles kingside.",
            "Move the bishop from c1 to e3.",
        ),
        decision(
            "solid-castle",
            "Castle queenside",
            "Castle queenside. Your rook lands on d1, behind your queen.",
            SOLID + " Nc6 d4 exd4 Nxd4 Nxd4 Qxd4 Be7 Be3 O-O",
            "O-O-O",
            None,
            "solid-summary",
            "Your king is on c1 and Black's on g8.",
            "Move the king from e1 to c1.",
        ),
        step(
            "explanation",
            "solid-summary",
            "Kings on opposite sides",
            "With the kings castled on opposite sides, both players will attack. Your queen stands in the center with the d1-rook behind it, and your pawns on e4 and f4 are ready to advance.",
            SOLID_LINE,
            next_step="solid-rehearsal",
        ),
        step(
            "rehearsal",
            "solid-rehearsal",
            "Play against d6",
            "Play the main line from the first move without prompts.",
            line_id="vienna-solid",
        ),
    ]
    return dict(
        id="vienna-declined",
        title="Black declines the gambit",
        entry_step=steps[0]["id"],
        steps=steps,
    )


def bishop_first_trip():
    before = VIENNA + " Bc5 Nf3 d6 d4 exd4 Nxd4 Nf6"
    return [
        demo(
            "second-bishop",
            "Black develops the bishop first",
            "Black develops the f8-bishop to c5 on move two.",
            VIENNA,
            VIENNA + " Bc5",
            "second-bishop-knight",
        ),
        decision(
            "second-bishop-knight",
            "Develop the knight",
            "Develop the g1-knight to f3. It attacks e5.",
            VIENNA + " Bc5",
            "Nf3",
            "d6",
            "second-bishop-center",
            "Black defends e5 with d6.",
            "Move the knight from g1 to f3.",
        ),
        decision(
            "second-bishop-center",
            "Open the center",
            "Push d4. It attacks e5 and the c5-bishop's diagonal.",
            VIENNA + " Bc5 Nf3 d6",
            "d4",
            "exd4",
            "second-bishop-recapture",
            "Black takes on d4.",
            "Move d2 to d4.",
        ),
        decision(
            "second-bishop-recapture",
            "Take back with the knight",
            "Recapture on d4 with the f3-knight.",
            VIENNA + " Bc5 Nf3 d6 d4 exd4",
            "Nxd4",
            "Nf6",
            "second-bishop-pin",
            "Black develops Nf6.",
            "Move the knight from f3 to d4.",
        ),
        decision(
            "second-bishop-pin",
            "Pin the knight",
            "Develop the c1-bishop to g5. It pins the f6-knight to Black's queen.",
            before,
            "Bg5",
            "h6",
            "second-bishop-keep",
            "Black asks the bishop with h6.",
            "Move the bishop from c1 to g5.",
        ),
        decision(
            "second-bishop-keep",
            "Keep the pin",
            "Retreat the bishop to h4, where it still pins the knight.",
            before + " Bg5 h6",
            "Bh4",
            "g5",
            "second-bishop-retreat",
            "Black pushes g5 to break the pin.",
            "Move the bishop from g5 to h4.",
        ),
        decision(
            "second-bishop-retreat",
            "Retreat the bishop",
            "Retreat the bishop to g3.",
            before + " Bg5 h6 Bh4 g5",
            "Bg3",
            None,
            "second-bishop-summary",
            "Your bishop is safe on g3.",
            "Move the bishop from h4 to g3.",
        ),
        step(
            "explanation",
            "second-bishop-summary",
            "Pawns that cannot go back",
            "Black's h- and g-pawns have moved forward to chase your bishop. Pawns never move backward, so the squares around Black's king will stay weaker.",
            BISHOP_FIRST,
        ),
    ]


def knights_bishop_trip():
    return [
        demo(
            "knights-early",
            "Black develops the bishop",
            "Black develops the f8-bishop to c5 before the g8-knight.",
            VIENNA + " Nc6 Bc4",
            VIENNA + " Nc6 Bc4 Bc5",
            "knights-early-knight",
        ),
        decision(
            "knights-early-knight",
            "Develop the knight",
            "Develop the g1-knight to f3.",
            VIENNA + " Nc6 Bc4 Bc5",
            "Nf3",
            "Nf6",
            "knights-early-castle",
            "Black develops Nf6.",
            "Move the knight from g1 to f3.",
        ),
        decision(
            "knights-early-castle",
            "Castle",
            "Castle kingside.",
            VIENNA + " Nc6 Bc4 Bc5 Nf3 Nf6",
            "O-O",
            "O-O",
            "knights-early-support",
            "Black castles too.",
            "Move the king from e1 to g1.",
        ),
        decision(
            "knights-early-support",
            "Support the pawn",
            "Push d3. It defends e4 and opens your c1-bishop's path.",
            VIENNA + " Nc6 Bc4 Bc5 Nf3 Nf6 O-O O-O",
            "d3",
            None,
            "knights-early-summary",
            "Your pieces are developed and your king is safe.",
            "Move d2 to d3.",
        ),
        step(
            "explanation",
            "knights-early-summary",
            "A quiet setup",
            "Both sides have developed and castled. Your d3-pawn supports e4, and your c1-bishop can now develop.",
            KNIGHTS_EARLY,
        ),
    ]


def knights_pin_trip():
    return [
        demo(
            "knights-pin",
            "Black pins the knight",
            "Black develops the f8-bishop to b4, attacking your c3-knight.",
            KNIGHTS,
            KNIGHTS + " Bb4",
            "knights-pin-develop",
        ),
        decision(
            "knights-pin-develop",
            "Develop the knight",
            "Develop the g1-knight to f3 and prepare to castle.",
            KNIGHTS + " Bb4",
            "Nf3",
            "Bxc3+",
            "knights-pin-recapture",
            "Black takes your knight with check.",
            "Move the knight from g1 to f3.",
        ),
        decision(
            "knights-pin-recapture",
            "Take back",
            "Recapture with the b-pawn.",
            KNIGHTS + " Bb4 Nf3 Bxc3+",
            "bxc3",
            None,
            "knights-pin-summary",
            "You keep both bishops.",
            "Move the pawn from b2 to c3.",
        ),
        step(
            "explanation",
            "knights-pin-summary",
            "Two bishops",
            "Black gave up a bishop for your knight, so you have both bishops. Castle next.",
            KNIGHTS_PIN,
        ),
    ]


def second_chapter():
    steps = [
        step(
            "explanation",
            "knights-welcome",
            "Black's other second moves",
            "The most common reply to 2.Nc3 is not Nf6 but Nc6. Then f4 at once is a weaker gambit, so you develop the f1-bishop to c4 first. This chapter also covers Bc5 on move two.",
            next_step="knights-arrival",
        ),
        demo(
            "knights-arrival",
            "Reach the Vienna",
            "You play e4 and Nc3, and Black answers e5.",
            "",
            VIENNA,
            "knights-bishop-choice",
        ),
        step(
            "branch",
            "knights-bishop-choice",
            "If Black plays Bc5",
            "Black most often plays Nc6. Explore Bc5 first, or continue with Nc6.",
            VIENNA,
            branch_start="second-bishop",
            next_step="knights-reply",
        ),
        *bishop_first_trip(),
        demo(
            "knights-reply",
            "Black develops the knight",
            "Black develops the b8-knight to c6.",
            VIENNA,
            VIENNA + " Nc6",
            "knights-bishop",
        ),
        decision(
            "knights-bishop",
            "Aim at f7",
            "Develop the f1-bishop to c4, where it aims at f7.",
            VIENNA + " Nc6",
            "Bc4",
            None,
            "knights-early-choice",
            "Black most often develops Nf6.",
            "Move the bishop from f1 to c4.",
        ),
        step(
            "branch",
            "knights-early-choice",
            "If Black plays Bc5",
            "Explore Bc5 first, or continue with Nf6.",
            VIENNA + " Nc6 Bc4",
            branch_start="knights-early",
            next_step="knights-knight",
        ),
        *knights_bishop_trip(),
        demo(
            "knights-knight",
            "Black attacks e4",
            "Black develops Nf6, attacking your e4-pawn.",
            VIENNA + " Nc6 Bc4",
            VIENNA + " Nc6 Bc4 Nf6",
            "knights-support",
        ),
        decision(
            "knights-support",
            "Defend the pawn",
            "Push d3. It defends e4 and opens your c1-bishop's path.",
            VIENNA + " Nc6 Bc4 Nf6",
            "d3",
            None,
            "knights-pin-choice",
            "Black most often develops Bc5.",
            "Move d2 to d3.",
        ),
        step(
            "branch",
            "knights-pin-choice",
            "If Black plays Bb4",
            "Explore Bb4 first, or continue with Bc5.",
            KNIGHTS,
            branch_start="knights-pin",
            next_step="knights-c5",
        ),
        *knights_pin_trip(),
        demo(
            "knights-c5",
            "Black develops the bishop",
            "Black develops the f8-bishop to c5.",
            KNIGHTS,
            KNIGHTS + " Bc5",
            "knights-develop",
        ),
        decision(
            "knights-develop",
            "Develop the knight",
            "Develop the g1-knight to f3.",
            KNIGHTS + " Bc5",
            "Nf3",
            "d6",
            "knights-castle",
            "Black supports e5 with d6.",
            "Move the knight from g1 to f3.",
        ),
        decision(
            "knights-castle",
            "Castle",
            "Castle kingside.",
            KNIGHTS + " Bc5 Nf3 d6",
            "O-O",
            "Bg4",
            "knights-question",
            "Black pins your f3-knight to the queen with Bg4.",
            "Move the king from e1 to g1.",
        ),
        decision(
            "knights-question",
            "Question the bishop",
            "Push h3 to attack the g4-bishop.",
            KNIGHTS + " Bc5 Nf3 d6 O-O Bg4",
            "h3",
            None,
            "knights-summary",
            "The bishop must retreat or take your knight.",
            "Move h2 to h3.",
        ),
        step(
            "explanation",
            "knights-summary",
            "Calm development",
            "All your minor pieces are out and your king is castled. Black usually retreats the bishop to h5.",
            KNIGHTS_LINE,
            next_step="knights-rehearsal",
        ),
        step(
            "rehearsal",
            "knights-rehearsal",
            "Play against Nc6",
            "Play the main line from the first move without prompts.",
            line_id="vienna-knights",
        ),
    ]
    return dict(
        id="vienna-second-moves",
        title="Black's other second moves",
        entry_step=steps[0]["id"],
        steps=steps,
    )
