"""chesscom import jobs and archive checkpoints"""

import sqlalchemy as sa
from alembic import op

revision = "1c14f367bbe8"
down_revision = "475ea36d42d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chesscom_imports",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("time_class", sa.String(), nullable=False),
        sa.Column("months", sa.Integer(), nullable=False),
        sa.Column("max_games", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("archives_total", sa.Integer(), nullable=False),
        sa.Column("archives_processed", sa.Integer(), nullable=False),
        sa.Column("games_fetched", sa.Integer(), nullable=False),
        sa.Column("games_imported", sa.Integer(), nullable=False),
        sa.Column("duplicates", sa.Integer(), nullable=False),
        sa.Column("filtered", sa.Integer(), nullable=False),
        sa.Column("rejected", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=False),
        sa.Column("fetch_completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysis_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "chesscom_archives",
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("games_selected", sa.Integer(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["chesscom_imports.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id", "url"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chesscom_archives")
    op.drop_table("chesscom_imports")
    # ### end Alembic commands ###
