"""initial relational schema"""

import sqlalchemy as sa
from alembic import op

revision = "475ea36d42d5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("target_rating", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "engine_analyses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cache_key", sa.String(), nullable=False),
        sa.Column("fen", sa.String(), nullable=False),
        sa.Column("engine_version", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    op.create_table(
        "game_imports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("original_pgn", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("white", sa.String(), nullable=False),
        sa.Column("black", sa.String(), nullable=False),
        sa.Column("learner_color", sa.Boolean(), nullable=False),
        sa.Column("pgn", sa.Text(), nullable=False),
        sa.Column("played_on", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint"),
    )
    op.create_table(
        "repertoires",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.Boolean(), nullable=False),
        sa.Column("pgn", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("import_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("games_total", sa.Integer(), nullable=False),
        sa.Column("games_processed", sa.Integer(), nullable=False),
        sa.Column("positions_triaged", sa.Integer(), nullable=False),
        sa.Column("deep_completed", sa.Integer(), nullable=False),
        sa.Column("mistakes_identified", sa.Integer(), nullable=False),
        sa.Column("classifications_completed", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["game_imports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analysis_jobs_status"), ["status"], unique=False)

    op.create_table(
        "course_units",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("course_id", sa.String(), nullable=False),
        sa.Column("skill_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("provisional", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "decisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("ply", sa.Integer(), nullable=False),
        sa.Column("fen", sa.String(), nullable=False),
        sa.Column("position_key", sa.String(), nullable=False),
        sa.Column("learner_color", sa.Boolean(), nullable=False),
        sa.Column("move_uci", sa.String(), nullable=False),
        sa.Column("move_san", sa.String(), nullable=False),
        sa.Column("before_analysis_id", sa.String(), nullable=False),
        sa.Column("played_analysis_id", sa.String(), nullable=False),
        sa.Column("loss_cp", sa.Integer(), nullable=True),
        sa.Column("mate_lost", sa.Boolean(), nullable=False),
        sa.Column("allows_mate", sa.Boolean(), nullable=False),
        sa.Column("meaningful", sa.Boolean(), nullable=False),
        sa.Column("deep", sa.Boolean(), nullable=False),
        sa.Column("facts", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["before_analysis_id"],
            ["engine_analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["played_analysis_id"],
            ["engine_analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "ply"),
    )
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_decisions_game_id"), ["game_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_decisions_meaningful"), ["meaningful"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_decisions_position_key"), ["position_key"], unique=False
        )

    op.create_table(
        "import_games",
        sa.Column("import_id", sa.String(), nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["game_imports.id"],
        ),
        sa.PrimaryKeyConstraint("import_id", "game_id"),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("identity", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("decision_id", sa.String(), nullable=True),
        sa.Column("repertoire_id", sa.String(), nullable=True),
        sa.Column("fen", sa.String(), nullable=False),
        sa.Column("orientation", sa.String(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repertoire_id"],
            ["repertoires.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity"),
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("unit_id", sa.String(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["course_units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "llm_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("cache_key", sa.String(), nullable=False),
        sa.Column("decision_id", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    op.create_table(
        "exercise_answers",
        sa.Column("exercise_id", sa.String(), nullable=False),
        sa.Column("uci", sa.String(), nullable=False),
        sa.Column("san", sa.String(), nullable=False),
        sa.Column("grade", sa.String(), nullable=False),
        sa.Column("primary", sa.Boolean(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["engine_analyses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("exercise_id", "uci"),
    )
    op.create_table(
        "exercise_tags",
        sa.Column("exercise_id", sa.String(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("exercise_id", "tag"),
    )
    op.create_table(
        "review_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("exercise_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failed", sa.Boolean(), nullable=False),
        sa.Column("revealed", sa.Boolean(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_sessions_exercise_id"), ["exercise_id"], unique=False
        )

    op.create_table(
        "skill_evidence",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("decision_id", sa.String(), nullable=False),
        sa.Column("skill_id", sa.String(), nullable=False),
        sa.Column("llm_run_id", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["llm_run_id"],
            ["llm_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_id", "skill_id"),
    )
    with op.batch_alter_table("skill_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_skill_evidence_decision_id"), ["decision_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_skill_evidence_skill_id"), ["skill_id"], unique=False)

    op.create_table(
        "srs_states",
        sa.Column("exercise_id", sa.String(), nullable=False),
        sa.Column("card", sa.JSON(), nullable=False),
        sa.Column("due", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviews", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("exercise_id"),
    )
    with op.batch_alter_table("srs_states", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_srs_states_due"), ["due"], unique=False)

    op.create_table(
        "exercise_attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("uci", sa.String(), nullable=False),
        sa.Column("grade", sa.String(), nullable=False),
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("exercise_id", sa.String(), nullable=False),
        sa.Column("rating", sa.String(), nullable=False),
        sa.Column("response_ms", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Boolean(), nullable=False),
        sa.Column("revealed", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(), nullable=False),
        sa.Column("scheduler_version", sa.String(), nullable=False),
        sa.Column("scheduler_log", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviews_exercise_id"), ["exercise_id"], unique=False)

    op.create_table(
        "unit_evidence",
        sa.Column("unit_id", sa.String(), nullable=False),
        sa.Column("evidence_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["skill_evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["course_units.id"],
        ),
        sa.PrimaryKeyConstraint("unit_id", "evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unit_evidence")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_exercise_id"))

    op.drop_table("reviews")
    op.drop_table("exercise_attempts")
    with op.batch_alter_table("srs_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_srs_states_due"))

    op.drop_table("srs_states")
    with op.batch_alter_table("skill_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_evidence_skill_id"))
        batch_op.drop_index(batch_op.f("ix_skill_evidence_decision_id"))

    op.drop_table("skill_evidence")
    with op.batch_alter_table("review_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_sessions_exercise_id"))

    op.drop_table("review_sessions")
    op.drop_table("exercise_tags")
    op.drop_table("exercise_answers")
    op.drop_table("llm_runs")
    op.drop_table("lessons")
    op.drop_table("exercises")
    op.drop_table("import_games")
    with op.batch_alter_table("decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_decisions_position_key"))
        batch_op.drop_index(batch_op.f("ix_decisions_meaningful"))
        batch_op.drop_index(batch_op.f("ix_decisions_game_id"))

    op.drop_table("decisions")
    op.drop_table("course_units")
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_status"))

    op.drop_table("analysis_jobs")
    op.drop_table("skills")
    op.drop_table("repertoires")
    op.drop_table("games")
    op.drop_table("game_imports")
    op.drop_table("engine_analyses")
    op.drop_table("courses")
    # ### end Alembic commands ###
