import { test, expect } from '@playwright/test';

test('account signup, engine-free sync, second-device login and private library', async ({page, browser}, info) => {
  const username = `friend-${info.project.name}`;
  await page.goto('/');
  await page.getByRole('button', {name: 'New here? Create an account'}).click();
  await page.getByLabel('Username', {exact: true}).fill(username);
  await page.getByLabel('Password', {exact: true}).fill('test-only-password');
  await page.getByRole('button', {name: 'Create account', exact: true}).click();
  await page.getByRole('link', {name: 'Games', exact: true}).click();
  await page.getByLabel('Remembered Chess.com username').fill(username);
  await page.getByRole('button', {name: 'Save username', exact: true}).click();
  await expect(page.locator('.game-library-item')).toHaveCount(1, {timeout: 30000});
  await expect(page.locator('.game-library-item')).toContainText(username);
  await expect(page.getByText(`Signed in as ${username}`)).toHaveCount(0);
  await expect(page.getByRole('button', {name: 'Sign out', exact: true})).toHaveCount(0);
  expect(await page.locator('.app-header').evaluate(header => header.getBoundingClientRect().top)).toBe(0);
  const gameHref = (await page.locator('.game-library-item').getAttribute('href'))!;
  await page.getByRole('link', {name: 'Settings', exact: true}).click();
  await page.getByRole('button', {name: 'Women', exact: true}).click();
  await page.getByRole('radio', {name: 'Golden braid', exact: true}).click();
  await expect(page.locator('.coach-preference-status')).toContainText('Saved');
  await page.getByLabel('Coach motion', {exact: true}).selectOption('still');
  await expect(page.locator('.coach-preference-status')).toContainText('Saved');
  await page.getByLabel('Piece & interface motion', {exact: true}).selectOption('natural');
  await expect(page.locator('.motion-preference-status')).toContainText('Saved');
  await page.getByRole('link', {name: 'Games', exact: true}).click();
  const jobs = await (await page.request.get('/api/jobs')).json();
  expect(jobs).toHaveLength(1);
  expect(jobs[0].kind).toBe('sync');
  expect(jobs[0].positions_triaged).toBe(0);
  await page.screenshot({path: `test-results/accounts-${info.project.name}.png`, fullPage: true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);

  const second = await browser.newContext({baseURL: 'http://127.0.0.1:8766'});
  try {
    const device = await second.newPage();
    await device.goto(`${gameHref}?ply=3`);
    await device.getByLabel('Username', {exact: true}).fill(username);
    await device.getByLabel('Password', {exact: true}).fill('test-only-password');
    await device.getByRole('button', {name: 'Sign in', exact: true}).click();
    await expect(device).toHaveURL(`${gameHref}?ply=3`);
    await expect(device.getByRole('heading', {name: `${username} vs FixtureOpponent`})).toBeVisible();
    await expect(device.locator('.review-coach .coach-avatar')).toHaveAttribute('data-motion', 'still');
    await expect(device.locator('.review-coach .coach-avatar')).toHaveAttribute('data-coach', 'woman-blonde');
    await expect(device.getByRole('button', {name: /^2\. g4(?:, .+)?$/})).toHaveAttribute('aria-current', 'step');
    await device.getByRole('link', {name: 'Games', exact: true}).click();
    await expect(device.getByLabel('Remembered Chess.com username')).toHaveValue(username);
    await expect(device.locator('.game-library-item')).toHaveCount(1);
    await device.getByRole('link', {name: 'Settings', exact: true}).click();
    await expect(device.getByLabel('Coach motion', {exact: true})).toHaveValue('still');
    await expect(device.getByLabel('Piece & interface motion', {exact: true})).toHaveValue('natural');
    await expect(device.getByRole('button', {name: 'Women', exact: true})).toHaveAttribute('aria-pressed', 'true');
    await expect(device.getByRole('radio', {name: 'Golden braid', exact: true})).toBeChecked();
    await expect(device.getByLabel('Coach motion', {exact: true})).toBeEnabled();
    await expect(device.getByRole('region', {name: 'Account', exact: true})).toContainText(`Signed in as ${username}`);
    await device.getByRole('button', {name: 'Sign out', exact: true}).click();
    await page.reload();
    await page.getByRole('link', {name: 'Settings', exact: true}).click();
    const account = page.getByRole('region', {name: 'Account', exact: true});
    await expect(account).toContainText(`Signed in as ${username}`);
    await expect(account.getByRole('button', {name: 'Sign out all devices', exact: true})).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({path: `test-results/account-settings-${info.project.name}.png`, fullPage: true});
    await device.getByRole('button', {name: 'New here? Create an account'}).click();
    await device.getByLabel('Username', {exact: true}).fill(`${username}-other`);
    await device.getByLabel('Password', {exact: true}).fill('test-only-password');
    await device.getByRole('button', {name: 'Create account', exact: true}).click();
    await device.getByRole('link', {name: 'Settings', exact: true}).click();
    await expect(device.getByLabel('Coach motion', {exact: true})).toBeEnabled();
    await expect(device.getByLabel('Coach motion', {exact: true})).toHaveValue('system');
    await expect(device.getByLabel('Piece & interface motion', {exact: true})).toHaveValue('system');
    await expect(device.getByRole('radio', {name: 'Storyteller', exact: true})).toBeChecked();
    await device.getByRole('link', {name: 'Games', exact: true}).click();
    await expect(device.locator('.game-library-item')).toHaveCount(0);
    await expect(device.getByLabel('Remembered Chess.com username')).toHaveValue('');
    await device.goto(`${gameHref}?ply=3`);
    await expect(device.getByRole('alert')).toContainText('Game not found');
    await expect(device.getByRole('heading', {name: `${username} vs FixtureOpponent`})).toHaveCount(0);
    await device.getByRole('link', {name: 'All games', exact: true}).click();
    await expect(device.locator('.game-library-item')).toHaveCount(0);
  } finally { await second.close(); }
});
