/** Each template says only what its named evidence-backed slots establish. */
export const neutralTemplates: Record<string, readonly string[]> = {
  allowed_mate: ["This allows a forced checkmate. {reply}", "{opponent} now has a forced mate. {reply}"],
  missed_mate: ["{best} kept a forced mate; this move lets that finish go.", "There was a forced finish with {best}. This move loses that mate."],
  tactic_played: ["{move} finds a {motif} in the engine's continuation. {detail}", "The point of {move} is a {motif}. {detail}"],
  tactic_allowed: ["This allows {opponent} a {motif} in the strongest continuation. {detail}", "{opponent} has a {motif} in the continuation. {detail}"],
  tactic_missed: ["{best} had a {motif} that this move misses. {detail}", "The missed idea is a {motif} with {best}. {detail}"],
  sacrifice: ["The sacrifice stays sound even when it is accepted.", "The offer works even if the opponent accepts it."],
  only_move: ["This was the only searched move that kept the position playable.", "This held the position; the searched alternatives were losing."],
  decisive_resource: ["This was the only searched move that kept the decisive advantage."],
  reply_capture: ["{opponent} can answer {reply}, capturing {side}'s {piece}.", "The immediate reply is {reply}, taking {side}'s {piece}."],
  reply_check: ["{opponent}'s strongest reply is {reply}, with check."],
  alternative: ["Stockfish prefers {best} ({evaluation} for the mover)."],
  loss: ["The searched evaluation falls by {loss} pawns after this move.", "This gives up {loss} pawns of evaluation against the best continuation."],
  best: ["This stays close to the engine's best continuation.", "This preserves what the engine's best move offered."],
  good: ["A sound choice that keeps most of the position's value.", "This remains close to the stronger alternatives."],
  uncertain_reason: ["The search favors {best}; the current evidence does not establish a specific mechanism."],
  human_natural_error: ["The human model considers this natural, even though the engine finds it costly."],
  human_rare: ["The human model considers this an unusual choice at the selected skill band."],
  difficult_defense: ["The saving move, {best}, was difficult in the human-model assessment."],
  human_challenging: ["{best} was a challenging find in the human-model assessment."],
  clock_low: ["{side} had {seconds} seconds left before moving."],
  clock_fast: ["{side} used {elapsed} seconds with {seconds} seconds still available."],
  clock_long: ["{side} spent {elapsed} seconds on this move."],
  book: ["This follows {opening}. Book recognition does not mean the move is sound."],
  book_sound: ["This follows {opening}.", "Recognized theory: {opening}."],
  departure: ["This is the first move outside this game's recognized opening line; that alone is not an error."],
  recovery: ["This restores a playable position after the error at {earlier}.{help}", "The position is playable again, after the setback at {earlier}.{help}"],
  punishment: ["This uses the chance the opponent gave {side} at {earlier}."],
  missed_punishment: ["The opponent gave {side} a chance at {earlier}, but this lets it slip."],
  repeated: ["This {motif} issue has now appeared {count} times in the reviewed part of the game."],
  support_restored: ["The {piece} has support again after being left unguarded at {earlier}."],
  erosion: ["This is one of several small concessions since {earlier}; together they worsened the position."],
  conversion: ["{side} kept the searched advantage from {earlier} through the recorded win."],
  history: ["This {motif} issue also appears in {games} other classified games in your saved history."],
  turning: ["This is the largest reviewed concession in the game."],
  development: ["{lead}develops the {piece} from its original square."],
  rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
  passed: ["{lead}leaves {side} with passed pawns on {squares}; no enemy pawn is ahead on those or neighboring files."],
  passer_advance: ["{lead}advances the passed pawn to {square}."],
  isolated: ["{lead}leaves {side} with isolated pawns on {squares}, with no friendly pawn on a neighboring file."],
  support: ["{lead}gives the {piece} on {square} support."],
  unsupported: ["{lead}leaves the {piece} on {square} undefended; that alone does not mean it is lost."],
  flights: ["{lead}opens {squares} as a legal flight square for the king."],
  castle: ["{lead}castles the king to {square} and relocates the rook."],
  bishops: ["This exchange removes {side}'s pair of opposite-colored bishops."],
  doubled: ["{side} now has doubled pawns on files {files}."],
  mate_win: ["Checkmate. You finished the attack; the king has no legal escape."],
  mate_loss: ["Checkmate. Your king has no legal escape. Let's look back for a way to stop the attack."],
  draw: ["The position is drawn. We can look back at the earlier decisions together."],
  cold: ["Tap a piece, then its destination."],
  thinking: ["I'm checking the move and the opponent's strongest reply…"],
  unavailable: ["You can still explore the board. Engine coaching is unavailable for this position."],
  practice_error: ["I couldn't get a result for that move. You can try again."],
  retry: ["Mistake. Try again."],
  recovered: ["You found it this time. {detail}", "That recovers the idea. {detail}"],
  accepted: ["{detail}"],
  explanation: ["{detail}"],
  explanation_summary: ["{detail}"],
  complete: ["Review complete. {detail}"],
  variation: ["In this variation, {detail}"],
  compatibility: ["{detail}"],
};
