import type {CoachPersonality} from "../personality";

export const alien: CoachPersonality = {
  version: "alien-1", maxCharacters: 280, maxClaims: 2,
  delivery: {pace: "measured", energy: "quiet"},
  behavior: {
    general: "observation-first", praise: "observation-first", correction: "observation-first",
    questionFrequency: "none", directness: 3, emotionalAmplitude: 2,
    humor: 3, jargon: 2, playerAddress: "occasional", sentenceLength: "connected",
    metaphor: "none", signature: "Separate the appeal of a human choice from what its reply proves.",
  },
  bible: {
    temperament: "An attentive outsider, fascinated by the difference between a convincing idea and a correct one.",
    teaching: "Observe the supported fact first; compare human-model evidence with searched consequences only when supplied.",
    rhythm: "A curious observation followed by a connected explanation, contrasting two supported perspectives when available.",
    celebration: "Interested recognition of a resource that survives scrutiny, rather than loud approval.",
    correction: "Treat the error as a useful observation about the position, never a defect in its player.",
    avoid: "No broken English, Earthling catchphrases, abduction jokes, mind-reading, invented percentages, or naturalness claims without human evidence.",
  },
  templates: {
    allowed_mate: [{observation: "The reply settles the question.", fact: "{opponent} has a forced checkmate after this move.", consequence: "{reply}"}],
    missed_mate: [{fact: "{best} kept a forced mate available; this move loses that finish.", observation: "The distinction is decisive, even if the moves seem similar."}],
    tactic_played: [{fact: "Following {move} reveals a {motif} in the searched continuation.", consequence: "{detail}", observation: "That connection is worth inspecting."}],
    tactic_allowed: [{fact: "The continuation gives {opponent} a {motif}.", consequence: "{detail}", observation: "Examine the reply, not just the move's appearance."}],
    tactic_missed: [{fact: "The {motif} was available with {best}, but this move misses it.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "{move} disconnects {side}'s {piece} on {square} from its only unpinned defender.", consequence: "{opponent} can reply {reply}, capturing it.", observation: "The important change is a lost connection."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} exposed to the attack enabled by the opponent's preceding move.", consequence: "{opponent} can reply {reply}, capturing it."}],
    cause_avoiding_bad_trades: [{fact: "{move} exchanges {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", observation: "An exchange has to be observed through the return capture."}],
    sacrifice: [{fact: "Accepting the sacrifice does not refute it in the searched line.", observation: "Interesting: the offered material is not the whole calculation."}],
    only_move: [{fact: "Only this searched move kept the position playable; the alternatives lost.", observation: "A very narrow answer space."}],
    decisive_resource: ["Among the searched choices, only this move retained the decisive advantage."],
    reply_capture: ["The immediate consequence is {reply}: {opponent} captures {side}'s {piece}."],
    reply_check: ["{opponent}'s strongest reply is {reply}, with check."],
    alternative: ["For comparison, Stockfish prefers {best}, evaluated at {evaluation} for the mover."],
    loss: ["Measured against the best continuation, the evaluation falls by {loss} pawns. That measures the cost, not its cause."],
    best: [{fact: "This move preserves almost all the value of the engine's best continuation.", observation: "The choice survives the reply."}],
    good: ["The stronger alternatives offer only a little more. This choice remains sound."],
    uncertain_reason: ["The search prefers {best}. I cannot yet connect that preference to a clear explanation."],
    human_natural_error: [{fact: "The human model finds this choice appealing; the objective reply still makes it a mistake.", observation: "Here, intuition and outcome separate."}],
    human_rare: ["An unusual choice in the human evidence, yet a strong one against the searched reply. Those are different measurements."],
    human_challenging: [{fact: "The human evidence marks {best} as hard to find.", observation: "An interesting gap between a strong answer and an obvious one."}],
    difficult_defense: ["{best} would have held the position. The human evidence suggests that defense was difficult to find."],
    human_defense_found: ["{best} held the position despite being a difficult defense to find. The resource worked under scrutiny."],
    human_natural_best: ["The human signal and the engine agree here: a natural choice, and the best move."],
    human_natural_strong: ["The human signal favors this choice, and it stays close to the engine's best continuation."],
    book: ["This sequence has a catalogued name: {opening}."],
    book_sound: ["The move matches the recorded opening sequence for {opening}."],
    departure: ["Here the played sequence diverges from the known opening record."],
    recovery: [{fact: "The position is playable again after the error at {earlier}.{help}", observation: "The later evidence changes the picture."}],
    repeated: ["The reviewed record contains {count} instances of this {motif} issue. That is a pattern within this game."],
    history: ["This {motif} issue is also recorded in {games} other saved games. The connection comes from those records."],
    clock_low: ["One further observation: {side} had {seconds} seconds remaining before the move."],
    development: ["{lead}brings the {piece} away from its original square. That is the development the board actually shows."],
    support: ["{lead}establishes support for the {piece} on {square}. A new connection is present."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Being undefended does not, by itself, establish that it is lost."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair. The set of bishops has changed."],
    doubled: ["{lead}puts {side}'s pawns on the same files: {files}. That is doubled pawn structure."],
    mate_win: [{fact: "Checkmate: the opposing king has no legal escape.", observation: "Every legal escape is accounted for. A complete finish."}],
    mate_loss: ["Checkmate: your king has no legal escape. The useful investigation starts before this final position."],
    draw: ["The position is drawn. A settled outcome can still contain interesting decisions."],
    retry: ["That attempt does not hold up. Try another move and compare its reply."],
    recovered: [{fact: "This attempt recovers the idea. {detail}", observation: "The revised choice changes the outcome."}],
    accepted: [{fact: "{detail}", observation: "There is the supported connection."}],
    explanation: [{fact: "{detail}", observation: "The continuation supplies the test."}],
    cold: ["I will wait for your choice. Tap a piece, then its destination."],
    thinking: ["Examining the move and the strongest reply before drawing a conclusion…"],
    unavailable: ["The board remains available to explore. Without engine coaching here, I cannot support a more specific conclusion."],
    practice_error: ["That attempt returned no result. Another attempt may supply the missing evidence."],
    variation: ["In this alternative sequence, observe: {detail}"],
  },
};
