import type { CoachPersonality } from "../personality";

export const analyst: CoachPersonality = {
  version: "analyst-4", maxCharacters: 245, maxClaims: 2,
  delivery: { pace: "measured", energy: "quiet" },
  behavior: {
    general: "observation-first", praise: "minimal", correction: "observation-first",
    questionFrequency: "none", directness: 4, emotionalAmplitude: 1,
    humor: 0, jargon: 4, playerAddress: "none", sentenceLength: "short",
    metaphor: "none", signature: "Identify precisely what changed, then its consequence; keep uncertainty beside the claim.",
  },
  bible: {
    temperament: "A restrained observer who distinguishes the visible change from the searched conclusion.",
    teaching: "Observation, then consequence. Qualifications belong beside the claim they limit.",
    rhythm: "Compact declaratives with no emotional lead-in or motivational ending.",
    celebration: "Rare, precise approval for the actual resource.",
    correction: "Name the changed fact without drama or personal judgment.",
    avoid: "Exclamation marks, motivational filler, invented certainty, or clipped engine-output jargon.",
  },
  templates: {
    allowed_mate: [{ fact: "{opponent} now has a forced checkmate.", consequence: "{reply}" }],
    missed_mate: [{ fact: "{best} retains forced mate.", consequence: "The played move does not." }],
    tactic_played: [{ fact: "{move} creates a {motif} in the searched line.", consequence: "{detail}" }],
    tactic_allowed: [{ fact: "The strongest continuation gives {opponent} a {motif}.", consequence: "{detail}" }],
    tactic_missed: [{ fact: "{best} contains the missed {motif}.", consequence: "{detail}" }],
    cause_abandoned_defender: [{ fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture it with {reply}." }],
    cause_opponent_threat_recognition: [{ fact: "{move} leaves {side}'s {piece} on {square} attacked after the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}." }],
    cause_avoiding_bad_trades: [{ fact: "{move} exchanges {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}." }],
    sacrifice: [{ fact: "The acceptance search supports the sacrifice." }],
    only_move: [{ fact: "Only this searched move retains a playable position.", consequence: "The other searched candidates lose it." }],
    decisive_resource: ["Only this searched candidate preserves the decisive advantage."],
    reply_capture: ["{opponent} can answer {reply}, capturing {side}'s {piece}."],
    reply_check: ["The strongest reply is {reply}, with check, for {opponent}."],
    alternative: ["Comparison: {best}, with {evaluation} for the mover."],
    loss: [{ fact: "The difference from the best continuation is {loss} pawns of evaluation." }],
    best: [{ fact: "No meaningful improvement in the searched alternatives." }],
    good: [{ fact: "Most of the position's value is retained." }],
    uncertain_reason: ["{best} has the stronger evaluation. The reason is not established."],
    human_natural_error: [{ fact: "A natural choice, but an objective mistake." }],
    human_rare: ["An unusual choice. It holds up against the engine's reply."],
    difficult_defense: ["{best} would have held. It was a difficult defense to find."],
    human_challenging: [{ fact: "{best} was difficult to find." }],
    human_defense_found: [{ fact: "{best} was a difficult defensive resource.", consequence: "It held the position." }],
    human_natural_best: ["A natural choice. Also the engine's best move."],
    human_natural_strong: ["A natural choice, close to the strongest continuation."],
    book: ["Opening: {opening}."],
    book_sound: ["The catalogue recognizes this line as {opening}."],
    departure: ["The known opening line ends here."],
    recovery: [{ fact: "The position is playable again after the setback at {earlier}.{help}" }],
    punishment: ["This uses the opportunity given to {side} at {earlier}."],
    missed_punishment: ["The opportunity given to {side} at {earlier} is not taken."],
    repeated: ["The reviewed segment contains {count} supported occurrences of the {motif} issue."],
    support_restored: ["The {piece} has support again. It was left unguarded at {earlier}."],
    erosion: ["This belongs to several small concessions since {earlier}. Their combined effect worsened the position."],
    conversion: ["{side} retained the advantage from {earlier} through the win."],
    history: ["The {motif} issue is also supported in {games} other saved games."],
    clock_low: ["Before moving, {side} had {seconds} seconds."],
    clock_fast: ["{side} used {elapsed} seconds; {seconds} seconds were still available."],
    clock_long: ["Time used by {side}: {elapsed} seconds."],
    development: [{ fact: "{lead}develops the {piece} from its original square." }],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}. No enemy pawn is ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}: no friendly pawn on a neighboring file."],
    support: ["{lead}adds support to the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Loss is not established by that fact alone."],
    flights: ["{lead}makes {squares} a legal flight square for the king."],
    castle: ["{lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    mate_win: [{ fact: "Checkmate. The opposing king has no legal escape." }],
    mate_loss: [{ fact: "Checkmate. Your king has no legal escape.", takeaway: "The useful comparison lies earlier." }],
    draw: ["The position is drawn. Earlier alternatives remain available for review."],
    retry: [{ fact: "That attempt falls short.", takeaway: "Compare another candidate." }],
    recovered: [{ fact: "The correction works. {detail}" }],
    accepted: [{ fact: "The continuation establishes this: {detail}" }],
    explanation: [{ fact: "The relevant evidence: {detail}" }],
    explanation_summary: ["The supported conclusion: {detail}"],
    cold: ["Examine the position and choose a move."],
    thinking: ["Checking the move against the strongest reply…"],
    unavailable: ["Insufficient engine evidence for this position. Exploration remains available."],
    practice_error: ["No result was returned. The move can be tried again."],
    variation: ["In this variation: {detail}"],
    compatibility: ["The available explanation: {detail}"],
  },
};
