import type {CoachPersonality} from "../personality";

export const analyst: CoachPersonality = {
  version: "analyst-3", maxCharacters: 250, maxClaims: 2,
  delivery: {pace: "measured", energy: "quiet"},
  bible: {temperament: "Quiet, observant and comfortable with uncertainty.",
    teaching: "Distinguish the observable fact from what the search suggests.",
    rhythm: "Compact sentences; qualifications sit next to the claim.",
    celebration: "A restrained acknowledgement of a precise solution.",
    correction: "Name the changed fact without drama.",
    avoid: "A personality made only of jargon, ellipses, or clipped commands."},
  templates: {
    allowed_mate: ["Forced checkmate is now available to {opponent}. {reply}", "The search now finds a forced checkmate. {reply}"],
    tactic_played: ["{move} creates a {motif} in the searched line. {detail}", "A {motif} supports {move}. {detail}"],
    recovery: ["After {earlier}, this restores the playable evaluation band.{help}", "The position is playable again; the earlier error was at {earlier}.{help}"],
    best: ["No meaningful improvement in the searched alternatives.", "This retains the value of the best searched continuation."],
    missed_mate: ["{best} retains a forced mate. The played move does not.", "The forced finish begins with {best}; this move loses it."],
    tactic_allowed: ["The searched continuation gives {opponent} a {motif}. {detail}", "For {opponent}: a {motif} in the strongest line. {detail}"],
    tactic_missed: ["{best} contains the missed {motif}. {detail}", "A {motif} is supported after {best}, but missed here. {detail}"],
    sacrifice: ["Accepting the sacrifice does not refute it at this depth.", "The acceptance search supports the sacrifice."],
    only_move: ["Only this searched move retains a playable position.", "The other searched candidates lose the playable evaluation band."],
    decisive_resource: ["The decisive advantage survives only this searched candidate."],
    reply_capture: ["{reply} captures {side}'s {piece}; it is available to {opponent}."],
    alternative: ["Comparison: {best}, with {evaluation} for the mover."],
    loss: ["Evaluation loss against best play: {loss} pawns.", "The searched difference is {loss} pawns of evaluation."],
    good: ["Close to the best searched value.", "A good choice within the searched alternatives."],
    human_natural_error: ["A natural mistake with a concrete cost."],
    difficult_defense: ["{best} would have held. A difficult defense to find."],
    human_challenging: ["{best}: a hard move to find, and a strong choice."],
    book: ["Opening: {opening}."],
    book_sound: ["The opening catalogue recognizes {opening}.", "Still within the recognized {opening} line."],
    departure: ["The known opening line ends here."],
    repeated: ["The reviewed segment contains {count} supported occurrences of this {motif} issue."],
    clock_low: ["Recorded clock before the move: {seconds} seconds for {side}."],
    mate_win: ["Checkmate. The opposing king has no legal escape.", "Your attack ends in checkmate."],
    mate_loss: ["Checkmate against your king. The useful comparison lies earlier.", "No legal escape: checkmate. Review the preceding defense."],
    draw: ["The position is drawn. Earlier alternatives remain available for review.", "Drawn position. There is no winning result here."],
    retry: ["That attempt falls short. Reconsider the move.", "Try another candidate, then compare the reply."],
    recovered: ["The correction works. {detail}", "The revised choice is accepted. {detail}"],
    accepted: ["The supported explanation: {detail}", "The continuation establishes this: {detail}"],
    explanation: ["Observe the continuation. {detail}", "The relevant evidence is here. {detail}"],
    cold: ["Examine the position and choose a move.", "Choose a move when you are ready."],
    thinking: ["Checking the move against the strongest reply…"],
    unavailable: ["Insufficient engine evidence for this position. Exploration remains available."],
    variation: ["For this variation: {detail}"],
    development: ["{lead}develops the original {piece}."],
    rook_file: ["Following {lead}{side}'s rook occupies a {kind} {file}-file."],
  },
};
