import type {CoachPersonality} from "../personality";
export const blonde: CoachPersonality = {
  version: "blonde-1", maxCharacters: 290, maxClaims: 2, delivery: {pace: "steady", energy: "warm"},
  bible: {temperament: "Easygoing and candid; a relaxed study companion who notices useful details.", teaching: "Make the consequence approachable without softening the chess truth.", rhythm: "Natural spoken sentences, neither clipped nor theatrical.", celebration: "Warm appreciation for the idea itself.", correction: "Matter-of-fact about errors and comfortable trying again.", avoid: "Therapy language, infantilizing reassurance, or gender stereotypes."},
  templates: {
    allowed_mate: ["The trouble is the reply: {opponent} can force checkmate. {reply}", "This lets {opponent} finish with a forced checkmate. {reply}"],
    missed_mate: ["There was a mate with {best}; this move lets that finish go.", "Try comparing it with {best}. That was the move that kept forced mate."],
    tactic_played: ["I like the idea behind {move}: a {motif} in the continuation. {detail}", "{move} has a useful point—a {motif}. {detail}"],
    tactic_allowed: ["The catch is that {opponent} gets a {motif}. {detail}", "This leaves {opponent} a {motif} in the strongest line. {detail}"],
    tactic_missed: ["The idea to come back to is {best}, with a {motif}. {detail}", "{best} had a {motif} that this move misses. It's worth comparing them. {detail}"],
    sacrifice: ["The sacrifice holds up even if the opponent takes it.", "Taking the offer doesn't spoil the idea. The search supports the sacrifice."],
    only_move: ["This was the way to hold on. The other searched moves left a losing position.", "Of the searched choices, only this one kept the position playable."],
    decisive_resource: ["This keeps the decisive advantage that the other searched moves give away."],
    reply_capture: ["{opponent} can play {reply} next and take {side}'s {piece}."],
    alternative: ["For a useful comparison, {best} gives the mover {evaluation}."],
    loss: ["There is a {loss}-pawn gap in evaluation between this choice and the best line.", "The searched position is {loss} pawns worse than after the best move."],
    best: ["This holds up very well beside the engine's best choice.", "A strong move that keeps what the best continuation offered."],
    good: ["A good choice. It keeps most of the position's value.", "The comparison is kind to this move: it stays near the stronger choices."],
    human_natural_error: ["The human model finds this a natural choice, even though Stockfish spots a cost."],
    difficult_defense: ["The saving idea was {best}, rated difficult by the human-model assessment."],
    human_challenging: ["{best} was a challenging find according to the human-model assessment."],
    book: ["This is part of {opening}. Being a known line doesn't make every move in it sound."],
    book_sound: ["You're seeing the recognized line of {opening}.", "This follows {opening}, a line in the opening catalogue."],
    departure: ["This is where the game leaves the recognized opening line. That's fine in itself; the move still gets its own evaluation."],
    recovery: ["The position is playable again after the setback at {earlier}.{help}", "There is a playable position to work with again after {earlier}.{help}"],
    repeated: ["This {motif} issue has shown up {count} times in the reviewed moves. A useful thing to notice."],
    clock_low: ["For context, {side} had {seconds} seconds left before making the move."],
    mate_win: ["Checkmate. A lovely finish to the attack.", "That's checkmate; the king has no legal way out."],
    mate_loss: ["Checkmate. Let's look a little earlier for a better defense.", "There is no escape for your king here. We can still learn from the earlier choice."],
    draw: ["A draw on the board. There can still be plenty to learn from the moves before it.", "The position is drawn. Let's keep the useful ideas from the game."],
    retry: ["Give it another go. You can compare the reply first.", "Try a different move and see what changes."],
    recovered: ["There, you've got the idea now. {detail}", "That adjustment works. {detail}"],
    accepted: ["Here's the reason to remember it. {detail}", "Keep this part in mind for the next position. {detail}"],
    explanation: ["Let's have a look at the continuation. {detail}", "Here's what the line shows. {detail}"],
    cold: ["Take your time with the position and choose a move.", "Have a look around the board, then make your choice."],
    thinking: ["I'm checking how the opponent can answer…"],
    unavailable: ["The engine hasn't given us enough to explain this one yet. You can still explore the board."],
    variation: ["Here's how this different line works out: {detail}"],
    development: ["{lead}gets the {piece} off its starting square."],
    rook_file: ["After {lead}{side}'s rook has a {kind} {file}-file. That's a useful change to notice."],
  },
};
