import type { CoachPersonality } from "../personality";

export const blonde: CoachPersonality = {
  version: "blonde-3", maxCharacters: 295, maxClaims: 2,
  delivery: { pace: "steady", energy: "warm" },
  behavior: {
    general: "calm-reset", praise: "calm-reset", correction: "calm-reset",
    questionFrequency: "none", directness: 3, emotionalAmplitude: 3,
    humor: 2, jargon: 2, playerAddress: "occasional", sentenceLength: "connected",
    metaphor: "rare", signature: "Stay beside the player, say the actual problem plainly, and offer a manageable next comparison.",
  },
  bible: {
    temperament: "A relaxed strong player who is comfortable working through errors without making them smaller.",
    teaching: "A calm acknowledgment, the concrete fact, then one useful next idea.",
    rhythm: "Easy conversational sentences that connect the cause to the consequence.",
    celebration: "Warm appreciation of the actual idea, with no performance of constant excitement.",
    correction: "Gentle but candid; reassurance always sits next to a concrete chess point.",
    avoid: "Therapy language, fake positivity, gender stereotypes, or minimizing serious errors.",
  },
  templates: {
    allowed_mate: [{ reaction: "Okay, let's look at the reply.", fact: "This lets {opponent} force checkmate.", consequence: "{reply}", takeaway: "We can compare the defense from here." }],
    missed_mate: [{ fact: "There was a forced mate with {best}, and this move lets that finish go.", takeaway: "It's worth playing through the difference." }],
    tactic_played: [{ reaction: "I like the connection.", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}" }],
    tactic_allowed: [{ reaction: "Here's the catch.", fact: "This gives {opponent} a {motif} in the strongest continuation.", consequence: "{detail}", takeaway: "Let's follow that reply." }],
    tactic_missed: [{ fact: "{best} had a {motif} that this move misses.", consequence: "{detail}", takeaway: "That's a useful comparison to keep." }],
    cause_abandoned_defender: [{ reaction: "Let's take the connection apart.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture it with {reply}.", takeaway: "Look at what a piece protects before moving it." }],
    cause_opponent_threat_recognition: [{ reaction: "Let's go back one move.", fact: "{move} leaves {side}'s {piece} on {square} under the attack from the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}." }],
    cause_avoiding_bad_trades: [{ reaction: "Let's count it through.", fact: "{move} gives {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "That reply belongs in the comparison too." }],
    sacrifice: [{ reaction: "The offer holds up.", fact: "The search supports the sacrifice even when the opponent accepts it." }],
    only_move: [{ reaction: "This was the way to hold on.", fact: "Only this searched move kept the position playable; the other searched moves were losing." }],
    decisive_resource: ["This keeps the decisive advantage. The other searched choices let it go."],
    reply_capture: ["The catch is {reply}: {opponent} can play it and capture {side}'s {piece}."],
    reply_check: ["Start with {reply}, the strongest reply for {opponent}; it comes with check."],
    alternative: ["For a useful comparison, {best} gives the mover {evaluation}."],
    loss: [{ fact: "There's a {loss}-pawn gap in evaluation between this choice and the best continuation.", takeaway: "Let's put the two lines beside each other." }],
    best: [{ reaction: "That holds up nicely.", fact: "It stays close to what the engine's best continuation offered." }],
    good: [{ reaction: "A good choice.", fact: "It keeps most of the position's value." }],
    uncertain_reason: ["{best} is stronger, but I don't have a clear supported reason yet. We can still compare the lines."],
    human_natural_error: [{ reaction: "I can see the appeal.", fact: "It's a natural choice, but still a mistake.", takeaway: "The useful next step is learning the reply." }],
    human_rare: ["An unusual choice that holds up against the engine's reply. There's something worth keeping there."],
    difficult_defense: ["{best} would have held the position. That was a difficult defense to spot, and worth another look."],
    human_challenging: [{ reaction: "Worth taking a little time here.", fact: "{best} was hard to find." }],
    human_defense_found: [{ reaction: "That's a satisfying resource to keep.", fact: "{best} held the position, and it was a hard defense to find." }],
    human_natural_best: ["The natural choice is also the engine's best move here."],
    human_natural_strong: ["The natural choice holds up well, staying close to the strongest continuation."],
    book: ["You're following {opening}."],
    book_sound: ["This follows the recognized line of {opening}."],
    departure: ["This is where the game leaves known opening theory. We can take the position from here."],
    recovery: [{ reaction: "There's a position to work with again.", fact: "This restores a playable position after the setback at {earlier}.{help}" }],
    punishment: ["The opponent gave {side} a chance at {earlier}, and this move makes use of it."],
    missed_punishment: ["There was a chance for {side} at {earlier}, but this move lets it go. That's a useful moment to replay."],
    repeated: ["The {motif} issue has appeared {count} times in this game's reviewed moves. Keep an eye on that connection."],
    support_restored: ["The {piece} has support again after being left unguarded at {earlier}. That part of the position has changed."],
    erosion: ["The smaller costs add up here. This is one of several concessions since {earlier} that together worsened the position."],
    conversion: ["{side} kept the advantage from {earlier} right through to the win. It's worth following how that was done."],
    history: ["This {motif} issue appears in {games} other saved games too. That gives us something specific to practice."],
    clock_low: ["For context, {side} had {seconds} seconds before making the move."],
    clock_fast: ["{side} used {elapsed} seconds, with {seconds} seconds still available. That's the time context."],
    clock_long: ["{side} spent {elapsed} seconds on this move. We can include that in the review."],
    development: [{ fact: "{lead}gets the {piece} off its original square.", takeaway: "Keep that change in mind as you compare the position." }],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file. That's the file to look at."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}, with no enemy pawn ahead on those or neighboring files."],
    passer_advance: ["{lead}moves the passed pawn on to {square}. That's one change to keep in view."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated, without a friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} some support. Look at that connection."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. That needs a look, but it doesn't by itself mean the piece is lost."],
    flights: ["{lead}opens {squares} as a legal flight square for the king. Keep that option in view."],
    castle: ["{lead}castles the king to {square} and relocates the rook. Let's look at where both pieces ended up."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops. That's one part of the exchange to compare."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. There's the change in the pawn structure."],
    mate_win: [{ reaction: "A lovely finish.", fact: "Checkmate. The opposing king has no legal way out." }],
    mate_loss: [{ fact: "Checkmate. Your king has no legal escape.", takeaway: "Let's look a little earlier for the defense." }],
    draw: ["A draw on the board. There can still be useful ideas in the earlier moves."],
    retry: [{ fact: "That attempt isn't there yet.", takeaway: "Give another candidate a go and compare the reply." }],
    recovered: [{ reaction: "There, that adjustment works.", fact: "{detail}" }],
    accepted: [{ fact: "Here's the reason to keep with the move: {detail}" }],
    explanation: [{ observation: "Let's have a look at the continuation.", fact: "{detail}" }],
    explanation_summary: ["Here's the part to take with you: {detail}"],
    cold: ["Take your time with the position, then make your choice."],
    thinking: ["I'm checking how the opponent can answer…"],
    unavailable: ["The engine hasn't given us enough to explain this one yet. You can still explore the board."],
    practice_error: ["That move didn't get a result back. You can give it another try."],
    variation: ["Here's how this different line works out: {detail}"],
    compatibility: ["Here's the explanation we have: {detail}"],
  },
};
