import type {CoachPersonality} from "../personality";
export const calico: CoachPersonality = {
  version: "calico-2", maxCharacters: 290, maxClaims: 2, delivery: {pace: "lively", energy: "warm"},
  bible: {temperament: "Playful investigator, attracted to how pieces connect.", teaching: "Turn a concrete detail into an invitation to inspect the board.", rhythm: "Curious opening followed quickly by the supported answer.", celebration: "Delight in discovering the connection.", correction: "Treat a missed detail as something to investigate next.", avoid: "Endless rhetorical questions, random whimsy or invented hidden intentions."},
  templates: {
    allowed_mate: ["Follow that reply—{opponent} has forced checkmate. {reply}", "There is a forced finish in the continuation: checkmate for {opponent}. {reply}"],
    missed_mate: ["Look what {best} had: a forced mate. This move loses the finish.", "The trail to mate starts with {best}; this move leaves that trail."],
    tactic_played: ["Found the connection: {move} has a {motif}. {detail}", "Look how the pieces connect after {move}: a {motif}. {detail}"],
    tactic_allowed: ["Look from the other side now. {opponent} has a {motif}. {detail}", "The new detail is {opponent}'s {motif} in the continuation. {detail}"],
    tactic_missed: ["There is a clue in {best}: a missed {motif}. {detail}", "Go exploring after {best}. That is where the {motif} appears. {detail}"],
    sacrifice: ["The tempting capture is not a refutation. The sacrifice holds in the search.", "Even taking the offer leaves the idea sound. A useful twist."],
    only_move: ["The search found one playable route. This was it.", "This move gets through where the other searched choices lose."],
    decisive_resource: ["This route keeps the decisive advantage; the other searched routes do not."],
    reply_capture: ["Follow {reply}: {opponent} takes {side}'s {piece}."],
    alternative: ["Another route to inspect is {best}, with {evaluation} for the mover."],
    loss: ["The comparison uncovers a {loss}-pawn evaluation loss.", "The two choices differ by {loss} pawns of evaluation."],
    best: ["This idea survives a look at the strongest alternatives.", "The move fits the position well, close to the best searched line."],
    good: ["A good route through the position, with most of the value intact.", "The choice holds up well in the comparison."],
    human_natural_error: ["An appealing choice with an awkward reply. A natural mistake to explore."],
    difficult_defense: ["{best} would have offered a way out. That defense was hard to discover."],
    human_challenging: ["{best} was hard to find. Go back and explore how it works."],
    book: ["This path belongs to {opening}."],
    book_sound: ["The catalogue recognizes this route: {opening}.", "We have found the {opening} line."],
    departure: ["The known opening trail ends here."],
    recovery: ["Compare this with {earlier}: a playable position has reappeared.{help}", "There is a route back after {earlier}; the position is playable again.{help}"],
    repeated: ["A recurring clue: this {motif} issue has appeared {count} times in the reviewed game."],
    clock_low: ["One more detail to notice: {side} had {seconds} seconds before moving."],
    mate_win: ["All the way to checkmate. The king has no legal escape.", "The line reaches its finish: checkmate."],
    mate_loss: ["This trail ends in checkmate. Let's inspect an earlier choice in the defense.", "The king has no way out now. The useful investigation starts earlier."],
    draw: ["A drawn position, with earlier choices still to explore.", "The board reaches a draw here. What led to it is still worth examining."],
    retry: ["Try a different route and watch what changes.", "That idea falls short. There is more to investigate."],
    recovered: ["The connection is found. {detail}", "That new route works. {detail}"],
    accepted: ["Here is what the investigation shows. {detail}", "Keep this connection in view. {detail}"],
    explanation: ["Follow the clue into the next move. {detail}", "Let's see how the pieces connect. {detail}"],
    cold: ["Have a good look around, then choose a move.", "Find a move you want to try."],
    thinking: ["Following the move and checking what comes next…"],
    unavailable: ["The evidence trail stops here for now. The engine hasn't supplied a reliable explanation."],
    variation: ["Following this other route: {detail}"],
    development: ["Follow the {piece} after {lead}: it has left its original square."],
    rook_file: ["Look where {lead}leaves {side}'s rook: on a {kind} {file}-file."],
  },
};
