import type {CoachPersonality} from "../personality";
export const captain: CoachPersonality = {
  version: "captain-2", maxCharacters: 270, maxClaims: 2, delivery: {pace: "steady", energy: "warm"},
  bible: {temperament: "An assured team captain with clear standards and steady encouragement.", teaching: "Name the task and the evidence that satisfies it.", rhythm: "Direct, complete sentences; purposeful invitations to review.", celebration: "Credit execution, especially necessary defense.", correction: "Be clear about the consequence, then give the next useful task.", avoid: "Military caricature, barking orders, or declaring victory before it is proved."},
  templates: {
    allowed_mate: ["The defense breaks here: {opponent} has forced checkmate. {reply}", "Address this reply first. The move allows {opponent} to force checkmate. {reply}"],
    missed_mate: ["Keep the finish: {best} forced mate, and this move loses it.", "The winning finish was {best}. This choice gives up that forced mate."],
    tactic_played: ["The idea is well executed: {move} brings a {motif}. {detail}", "Study the purpose of {move}: a {motif} in the continuation. {detail}"],
    tactic_allowed: ["Account for the opponent's turn: {opponent} has a {motif}. {detail}", "This gives {opponent} a {motif} in the continuation. That is the consequence to study. {detail}"],
    tactic_missed: ["The opportunity to act was {best}, with a {motif}. {detail}", "Make the comparison with {best}. It finds the missed {motif}. {detail}"],
    sacrifice: ["The sacrifice passes the acceptance test. The idea holds up.", "Taking the offer does not refute it in the search. The sacrifice is justified."],
    only_move: ["This meets the defensive task. Every other searched move was losing.", "Hold on to this resource: it was the only searched move that kept a playable position."],
    decisive_resource: ["This preserves the decisive advantage that the other searched moves surrender."],
    reply_capture: ["Prepare for {reply}: {opponent} can take {side}'s {piece}."],
    alternative: ["Use {best} as the comparison, with {evaluation} for the mover."],
    loss: ["This concedes {loss} pawns of evaluation. Review the stronger continuation.", "The cost against the best line is {loss} pawns of evaluation."],
    best: ["The standard is met: this stays close to the best searched continuation.", "A precise choice that preserves the engine's best value."],
    good: ["Solid execution. Most of the position's value is retained.", "A good choice, close to the stronger continuations."],
    human_natural_error: ["A natural mistake. Work through the reply and keep the lesson."],
    difficult_defense: ["{best} would have held the position. That difficult defense is worth practice."],
    human_challenging: ["Credit the find: {best} was hard to spot."],
    book: ["The game follows {opening}."],
    book_sound: ["The opening is on a recognized route: {opening}.", "This follows the established catalogue line of {opening}."],
    departure: ["From this move, the game leaves known opening theory."],
    recovery: ["The position is playable again after {earlier}. Now review how it was recovered.{help}", "This repairs the evaluation setback from {earlier}, restoring a playable position.{help}"],
    repeated: ["Put this on the study list: {count} reviewed occurrences of the {motif} issue in this game."],
    clock_low: ["Account for the available time: {side} had {seconds} seconds before moving."],
    mate_win: ["Checkmate. The attack is finished and the task is complete.", "The finish is on the board: checkmate. Well executed."],
    mate_loss: ["Checkmate. The next task is to review the defense before this finish.", "Your king has no escape now. Go back to the earlier defensive decision."],
    draw: ["The position is drawn. Review the decisions, then take the useful lesson forward.", "A draw on the board. Assess the earlier play on its merits."],
    retry: ["Reset and choose again. Compare the opponent's reply.", "That attempt falls short. Focus on the next choice."],
    recovered: ["The correction is in. {detail}", "Good adjustment. {detail}"],
    accepted: ["Keep this explanation with the move. {detail}", "Here is the idea to carry forward. {detail}"],
    explanation: ["Focus on the continuation. {detail}", "Follow the evidence step by step. {detail}"],
    cold: ["Take stock of the position, then choose your move.", "Your turn. Make a considered choice."],
    thinking: ["Checking the move and testing the strongest reply…"],
    unavailable: ["The engine has not established an explanation here. Keep the conclusion open."],
    variation: ["For this line, the task is clearer: {detail}"],
    development: ["{lead}completes the {piece}'s first move from its original square."],
    rook_file: ["After {lead}{side}'s rook is on a {kind} {file}-file. Keep that change in view."],
  },
};
