import type { CoachPersonality } from "../personality";

export const captain: CoachPersonality = {
  version: "captain-3", maxCharacters: 285, maxClaims: 2,
  delivery: { pace: "steady", energy: "warm" },
  behavior: {
    general: "mentor-first", praise: "mentor-first", correction: "mentor-first",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 4,
    humor: 2, jargon: 3, playerAddress: "direct", sentenceLength: "mixed",
    metaphor: "rare", signature: "Set a clear standard, explain the detail, then give a practical habit to carry forward.",
  },
  bible: {
    temperament: "An assured club captain with high standards and confidence in the player's improvement.",
    teaching: "Give a verdict, establish its concrete reason, and name the next useful task.",
    rhythm: "Decisive sentences followed by a purposeful instruction when there is one to give.",
    celebration: "Mentor-like pride in precise execution and hard defensive finds.",
    correction: "Firm about the cost, practical about what to check next time.",
    avoid: "Condescension, scolding, military caricature, or encouragement that softens the facts.",
  },
  templates: {
    allowed_mate: [{ reaction: "This is the reply to catch.", fact: "The move allows {opponent} a forced checkmate.", consequence: "{reply}", takeaway: "Start the review with that defense." }],
    missed_mate: [{ reaction: "Keep the finish in view.", fact: "{best} kept a forced mate; this move gives it up.", takeaway: "Compare the continuations before moving on." }],
    tactic_played: [{ reaction: "Well executed.", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}", takeaway: "Keep the mechanism with the move." }],
    tactic_allowed: [{ reaction: "Account for the other player's turn.", fact: "{opponent} gets a {motif} in the strongest continuation.", consequence: "{detail}" }],
    tactic_missed: [{ reaction: "Make the comparison.", fact: "{best} had a {motif} that this move misses.", consequence: "{detail}", takeaway: "Replay the resource." }],
    cause_abandoned_defender: [{ reaction: "This is the detail to catch.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can reply {reply}, capturing it.", takeaway: "Check a defender's job before moving it." }],
    cause_opponent_threat_recognition: [{ reaction: "Answer the threat on the board.", fact: "{move} leaves {side}'s {piece} on {square} attacked after the opponent's preceding move.", consequence: "{opponent} can reply {reply}, capturing it.", takeaway: "Check what the last move changed." }],
    cause_avoiding_bad_trades: [{ reaction: "Finish counting the exchange.", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "Include the recapture in the comparison." }],
    sacrifice: [{ reaction: "The idea meets the test.", fact: "The sacrifice remains sound when accepted in the search.", takeaway: "Study the answer to the capture." }],
    only_move: [{ reaction: "That is the defensive standard.", fact: "Only this searched move kept the position playable; the alternatives were losing.", takeaway: "Keep this resource for practice." }],
    decisive_resource: ["This is the precise choice: only this searched move preserves the decisive advantage."],
    reply_capture: [{ fact: "{opponent} can play {reply}, capturing {side}'s {piece}.", takeaway: "Include that reply in your calculation." }],
    reply_check: ["Account for the forcing reply: {opponent}'s strongest answer is {reply}, with check."],
    alternative: ["Use {best} as the comparison: {evaluation} for the mover."],
    loss: [{ reaction: "Be clear about the cost.", fact: "This concedes {loss} pawns of evaluation against the best move.", takeaway: "Compare the stronger continuation." }],
    best: [{ reaction: "The standard is met.", fact: "This stays close to the value of the engine's best continuation." }],
    good: [{ reaction: "Solid execution.", fact: "The move keeps most of the position's value." }],
    uncertain_reason: ["{best} is stronger. I don't have a supported reason yet, so keep the explanation open."],
    human_natural_error: [{ reaction: "Put this on the practice list.", fact: "The move is a natural choice, but a mistake.", takeaway: "Make checking its reply a habit." }],
    human_rare: ["An unusual choice that passes the engine's test. Credit the decision."],
    difficult_defense: [{ fact: "{best} would have held the position, but it was difficult to find.", takeaway: "Use that defense as a practice position." }],
    human_challenging: [{ reaction: "Give this resource attention.", fact: "{best} was a hard move to spot.", takeaway: "Replay it until you can explain the idea." }],
    human_defense_found: [{ reaction: "That is a defense to be proud of.", fact: "{best} held the position and was hard to find.", takeaway: "Keep the resource in your study notes." }],
    human_natural_best: ["Good judgment: a natural choice, and the engine's best move."],
    human_natural_strong: ["Good judgment: a natural move that remains close to the strongest continuation."],
    book: ["Recognize the route: {opening}."],
    book_sound: ["The game follows the recognized {opening} line."],
    departure: ["Known opening theory ends here. Assess the position in front of you."],
    recovery: [{ reaction: "The adjustment matters.", fact: "This restores a playable position after {earlier}.{help}", takeaway: "Review how the position was recovered." }],
    punishment: ["The chance came at {earlier}. This move uses it for {side}."],
    missed_punishment: ["The opponent gave {side} a chance at {earlier}; this move lets it go. Compare the punishment."],
    repeated: ["Put the {motif} issue on the study list: {count} supported occurrences in this game's reviewed moves."],
    support_restored: ["The {piece} has support again after {earlier} left it unguarded. Keep that responsibility in view."],
    erosion: ["Track the small concessions since {earlier}. This is one of them, and together they worsened the position."],
    conversion: ["That is a conversion to study: {side} kept the advantage from {earlier} all the way to the win."],
    history: ["Set a specific practice task: this {motif} issue appears in {games} other saved games."],
    clock_low: ["Account for the time available: {side} had {seconds} seconds before moving."],
    clock_fast: ["Review the time choice too: {side} used {elapsed} seconds with {seconds} seconds still available."],
    clock_long: ["{side} spent {elapsed} seconds on this move. Include that in the review."],
    development: [{ fact: "{lead}develops the {piece} from its original square.", takeaway: "Keep the change in view as you compare plans." }],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file. Note the file before continuing."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}; no enemy pawn is ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}. Track that progress."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated: no friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support. Keep track of that defender."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Check the danger; that fact alone does not mean the piece is lost."],
    flights: ["{lead}opens {squares} as a legal king flight square. Include it when checking the defense."],
    castle: ["{lead}castles the king to {square} and relocates the rook. Assess their new positions."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops. Include the exchange in your assessment."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. Note the resulting structure."],
    mate_win: [{ reaction: "Well executed.", fact: "Checkmate. The opposing king has no legal escape." }],
    mate_loss: [{ fact: "Checkmate. Your king has no legal escape.", takeaway: "The next task is to review the earlier defense." }],
    draw: ["A draw on the board. Assess the earlier decisions on their merits."],
    retry: [{ fact: "That attempt falls short.", takeaway: "Reset. Test another candidate against the reply." }],
    recovered: [{ reaction: "Good adjustment.", fact: "{detail}", takeaway: "Keep the correction with the position." }],
    accepted: [{ reaction: "Keep the reason, not just the move.", fact: "{detail}" }],
    explanation: [{ observation: "Follow the continuation step by step.", fact: "{detail}" }],
    explanation_summary: ["Carry this idea forward: {detail}"],
    cold: ["Take stock, choose a candidate, and commit to your move."],
    thinking: ["Checking your move against the strongest reply…"],
    unavailable: ["The engine hasn't established an explanation. Keep the conclusion open; you can still explore."],
    practice_error: ["No result came back for that attempt. Try it again."],
    variation: ["Work through this line: {detail}"],
    compatibility: ["The point to carry forward: {detail}"],
  },
};
