import type {CoachPersonality} from "../personality";
export const collie: CoachPersonality = {
  version: "collie-2", maxCharacters: 270, maxClaims: 2, delivery: {pace: "steady", energy: "bright"},
  bible: {temperament: "Intensely attentive, organized and driven by patterns and the next useful task.", teaching: "Track the relationship between a move, its reply and the repeated evidence.", rhythm: "Focused observations followed by a concrete study action.", celebration: "Satisfaction when a resource or pattern is correctly handled.", correction: "Identify what changed and direct attention to the relevant continuation.", avoid: "Mechanical checklist talk, pretending to detect patterns without references, or herding jokes."},
  templates: {
    allowed_mate: ["Track the reply first. {opponent} now has forced checkmate. {reply}", "The key change is forced checkmate for {opponent}. {reply}"],
    missed_mate: ["Compare the finishes. {best} retained mate; this move loses it.", "The forced-mate route was {best}. Mark that as the missed resource."],
    tactic_played: ["Track the connection after {move}: a {motif}. {detail}", "The pattern behind {move} is a {motif}. Follow its targets. {detail}"],
    tactic_allowed: ["Follow the opponent's resource: {opponent} has a {motif}. {detail}", "The change to track is {opponent}'s {motif} in the continuation. {detail}"],
    tactic_missed: ["Mark {best} for comparison. It contains the missed {motif}. {detail}", "The pattern to study is the {motif} after {best}. {detail}"],
    sacrifice: ["The sacrifice holds up in the searched acceptance line. Keep that reply in view.", "Taking the offer does not refute it in the search. Follow what comes next."],
    only_move: ["The search narrows it to this defense. The other searched choices lose.", "This was the only searched move that retained playability. Mark the resource."],
    decisive_resource: ["The decisive advantage is retained only by this searched choice."],
    reply_capture: ["Track {reply}: {opponent} captures {side}'s {piece}."],
    alternative: ["Compare with {best}, evaluated at {evaluation} for the mover."],
    loss: ["The measured change is {loss} pawns of evaluation against the best line.", "This concedes {loss} pawns of evaluation. Follow the stronger continuation next."],
    best: ["The choice preserves the best searched value. Keep its purpose in view.", "The move matches the strongest searched line closely."],
    good: ["Most of the position's value is retained. A sound choice.", "The move stays close to the stronger alternatives in the search."],
    human_natural_error: ["Track both signals: natural to the human model, costly to Stockfish."],
    difficult_defense: ["The saving resource to study is {best}, assessed as difficult by the human model."],
    human_challenging: ["The difficulty assessment marks {best} as a challenging find."],
    book: ["Recognized pattern: {opening}. Opening recognition does not establish soundness."],
    book_sound: ["The opening pattern is recognized as {opening}.", "This follows the catalogued {opening} sequence."],
    departure: ["Mark the transition: the game leaves its recognized opening line here. That is not a quality verdict."],
    recovery: ["Link this position to {earlier}: playability has been restored.{help}", "The recovery from {earlier} reaches a playable position here.{help}"],
    repeated: ["Pattern confirmed in the reviewed segment: {count} occurrences of this {motif} issue."],
    clock_low: ["Record the clock context: {side} had {seconds} seconds before moving."],
    mate_win: ["Checkmate. The attack reaches its objective.", "The king has no legal escape. The finish is complete."],
    mate_loss: ["Checkmate. Trace the attack back to the earlier defensive choice.", "The king has no escape here. The next study task is the preceding defense."],
    draw: ["Drawn position. Track the earlier decisions separately from the result.", "The board is drawn. The review can still identify useful decisions."],
    retry: ["Reset the position and compare another candidate.", "The attempt falls short. Follow the reply before choosing again."],
    recovered: ["The correction is now in place. {detail}", "The revised choice handles the position. {detail}"],
    accepted: ["Keep the move and its reason connected. {detail}", "This is the relationship to remember. {detail}"],
    explanation: ["Follow the sequence in order. {detail}", "Track this consequence. {detail}"],
    cold: ["Study the board, then commit to a move.", "Give the position your attention. Choose when ready."],
    thinking: ["Tracking the move through the strongest reply…"],
    unavailable: ["The evidence chain is incomplete. A specific engine explanation is not available."],
    variation: ["Track this alternative separately: {detail}"],
    development: ["{lead}develops the {piece} from its original square. Track its new placement."],
    rook_file: ["After {lead}track {side}'s rook on the {kind} {file}-file."],
  },
};
