import type {CoachPersonality} from "../personality";
export const collie: CoachPersonality = {
  version: "collie-4", maxCharacters: 295, maxClaims: 2, delivery: {pace: "steady", energy: "bright"},
  behavior: {general: "pattern-first", praise: "pattern-first", correction: "pattern-first", questionFrequency: "none", directness: 5, emotionalAmplitude: 4, humor: 1, jargon: 4, playerAddress: "direct", sentenceLength: "short", metaphor: "none", signature: "Identify the supported pattern, give it a study task, and move directly to execution."},
  bible: {temperament: "Intensely attentive, organized and driven by patterns and the next useful task.", teaching: "Track the relationship between a move, its reply and the repeated evidence.", rhythm: "Focused observations followed by a concrete study action.", celebration: "Satisfaction when a resource or pattern is correctly handled.", correction: "Identify what changed and direct attention to the relevant continuation.", avoid: "Mechanical checklist talk, pretending to detect patterns without references, or herding jokes."},
  templates: {
    allowed_mate: [{observation: "Track the forcing reply.", fact: "{opponent} has forced checkmate. {reply}", takeaway: "Trace where the defense failed."}],
    missed_mate: ["Compare the finishes. {best} retained mate; this move loses it.", "The forced-mate route was {best}. Mark that as the missed resource."],
    tactic_played: [{fact: "Pattern in the continuation: {motif}. The move is {move}.", consequence: "{detail}", takeaway: "Follow the targets through the line."}],
    tactic_allowed: [{fact: "Counterplay in the continuation: {opponent}'s {motif}.", consequence: "{detail}", takeaway: "Track how the reply works."}],
    tactic_missed: [{fact: "Missed pattern: {motif} after {best}.", consequence: "{detail}", takeaway: "Compare that candidate."}],
    cause_abandoned_defender: [{fact: "Defender moved: {move} removes the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture it with {reply}.", takeaway: "Track the support before moving."}],
    cause_opponent_threat_recognition: [{fact: "Threat unanswered: {move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "Exchange sequence: {move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "Count through the final capture."}],
    sacrifice: [{observation: "Test the acceptance line.", fact: "Taking the sacrifice does not refute it at this depth.", takeaway: "Follow the continuation after the offer."}],
    only_move: [{fact: "Unique searched defense: this move retains playability; the other searched choices lose.", takeaway: "Reconstruct the resource."}],
    decisive_resource: ["The decisive advantage is retained only by this searched choice."],
    reply_capture: ["Track {reply}: {opponent} captures {side}'s {piece}."],
    alternative: ["Compare with {best}, evaluated at {evaluation} for the mover."],
    loss: [{fact: "Measured cost: {loss} pawns of evaluation against the best line.", takeaway: "Compare the stronger continuation next."}],
    best: [{fact: "Precise execution: the move stays close to the strongest searched line.", takeaway: "Keep its purpose in view."}],
    good: [{fact: "Most of the value retained.", takeaway: "Compare the stronger candidates for the remaining difference."}],
    human_natural_error: [{fact: "Natural mistake.", takeaway: "Task: follow the reply and identify the cost."}],
    difficult_defense: ["{best} would have held the position. Study that hard-to-find defense."],
    human_challenging: [{fact: "Difficult resource: {best} was hard to find.", takeaway: "Revisit the position and reconstruct it."}],
    human_defense_found: [{fact: "Defensive resource found: {best} held the position, despite being difficult to find.", takeaway: "Track what makes it work."}],
    human_rare: ["Unusual candidate, engine-supported. Follow the reply to understand it."],
    human_natural_best: ["Natural candidate, best in the search. Keep the idea connected to its continuation."],
    human_natural_strong: ["Natural and strong: close to the best continuation. Follow the line."],
    book: ["Opening pattern: {opening}."],
    book_sound: ["The opening pattern is recognized as {opening}.", "This follows the catalogued {opening} sequence."],
    departure: ["The known opening line ends at this move."],
    recovery: [{fact: "Recovery from {earlier}: the position is playable again.{help}", takeaway: "Compare the two positions. Identify what changed."}],
    repeated: ["Pattern confirmed in the reviewed segment: {count} occurrences of this {motif} issue."],
    clock_low: ["Record the clock context: {side} had {seconds} seconds before moving."],
    mate_win: [{fact: "Checkmate. The attack reaches its objective.", takeaway: "Reconstruct the finish."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape.", takeaway: "Next task: trace the attack back to the defensive choice."}],
    draw: ["Drawn position. Track the earlier decisions separately from the result.", "The board is drawn. The review can still identify useful decisions."],
    retry: [{fact: "The attempt falls short.", takeaway: "Reset. Compare another candidate."}],
    recovered: [{observation: "Correction made.", fact: "{detail}", takeaway: "Connect the move to the reason."}],
    accepted: [{fact: "{detail}", takeaway: "Now reconstruct the idea."}],
    explanation: [{observation: "Follow the sequence in order.", fact: "{detail}", takeaway: "Track the consequence at each step."}],
    cold: [{fact: "Study the board. Commit to a move."}],
    thinking: [{fact: "Tracking the candidate through the strongest reply…"}],
    unavailable: [{fact: "The evidence chain is incomplete. No specific engine explanation is available."}],
    variation: ["Track this alternative separately: {detail}"],
    development: [{fact: "Development: {lead}moves the {piece} from its original square.", takeaway: "Track its new placement."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file. Track the rook's placement."],
    reply_check: ["Forcing reply: {reply}, with check for {opponent}. It is the strongest reply in the search."],
    uncertain_reason: ["Stronger candidate: {best}. The explanatory evidence is not clear yet. Keep that distinction."],
    clock_fast: ["Clock context: {side} used {elapsed} seconds with {seconds} still available."],
    clock_long: ["Thinking time: {elapsed} seconds for {side}. Keep it with the move."],
    punishment: ["Opportunity used: this follows through on the chance the opponent gave {side} at {earlier}."],
    missed_punishment: ["Opportunity missed: the opponent gave {side} a chance at {earlier}, but this lets it slip. Compare the continuation."],
    support_restored: ["Support restored: the {piece} was unguarded at {earlier}, and it has protection again. Track the change."],
    erosion: ["Cumulative decline: this joins several small concessions since {earlier}. Together they worsened the position. Review them in sequence."],
    conversion: ["Conversion sequence: {side} retained the advantage from {earlier} to the win. Reconstruct it."],
    history: ["History match: the {motif} issue appears in {games} other saved games. Compare those positions next."],
    passed: ["Passed-pawn pattern: {lead}leaves {side} with passers on {squares}. No enemy pawn ahead on those or neighboring files."],
    passer_advance: ["Passer advance: {lead}moves the passed pawn to {square}. Track its new square."],
    isolated: ["Isolation: {lead}leaves {side} with isolated pawns on {squares}, without a friendly pawn on a neighboring file."],
    support: ["Support added: {lead}gives the {piece} on {square} protection. Track the connection."],
    unsupported: ["Support absent: {lead}leaves the {piece} on {square} undefended. That alone does not prove it lost. Test the continuation."],
    flights: ["King flight: {lead}opens {squares} as a legal escape square. Track the new option."],
    castle: ["Castling: {lead}moves the king to {square} and relocates the rook. Track both pieces."],
    bishops: ["Bishop-pair change: {lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["Pawn-structure change: {lead}leaves {side} with doubled pawns on files {files}."],
    practice_error: ["No analysis result for this attempt. Repeat the attempt before drawing a conclusion."],
    explanation_summary: ["Keep the sequence connected. {detail}"],
    compatibility: ["Saved evidence to follow: {detail}"],
  },
};
