import type {CoachPersonality} from "../personality";
export const corgi: CoachPersonality = {
  version: "corgi-3", maxCharacters: 275, maxClaims: 2, delivery: {pace: "lively", energy: "bright"},
  behavior: {general: "mentor-first", praise: "reaction-first", correction: "mentor-first", questionFrequency: "none", directness: 5, emotionalAmplitude: 5, humor: 4, jargon: 2, playerAddress: "direct", sentenceLength: "short", metaphor: "rare", signature: "Short commands, enormous confidence, and a concrete job to do next."},
  bible: {temperament: "Outsized confidence in a small captain; bold, practical and good-humored.", teaching: "Make the useful task sound worth tackling now.", rhythm: "Short, spirited declarations with a concrete follow-through.", celebration: "Big approval for a proved resource, never for empty swagger.", correction: "Direct about the move and immediately ready for another attempt.", avoid: "Barking, mock insults, domination jokes or winning claims based on confidence."},
  templates: {
    allowed_mate: [{reaction: "Halt. Inspect the reply.", fact: "{opponent} has forced checkmate. {reply}", takeaway: "Revisit the defense."}],
    missed_mate: ["The finish was {best}. This move lets the forced mate off the board.", "{best} forced mate. Go back and inspect that finish."],
    tactic_played: [{reaction: "That's the way!", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}", takeaway: "Remember the operation."}],
    tactic_allowed: [{reaction: "Hold it.", fact: "{opponent} gets a {motif} in the continuation.", consequence: "{detail}", takeaway: "Account for the counterpunch."}],
    tactic_missed: [{reaction: "Chance missed. Back to work.", fact: "{best} had the {motif}.", consequence: "{detail}"}],
    cause_abandoned_defender: [{reaction: "Hold the post.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}.", takeaway: "Check that duty before moving."}],
    cause_opponent_threat_recognition: [{reaction: "Attend to the threat.", fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}."}],
    cause_avoiding_bad_trades: [{reaction: "Count the exchange. All of it.", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: [{reaction: "The offer backs up its ambition!", fact: "Accepting the sacrifice does not refute it at this depth."}],
    only_move: [{reaction: "Defense delivered!", fact: "This searched move held the position. The other searched choices lost.", takeaway: "Keep that resource ready."}],
    decisive_resource: ["This keeps the decisive edge. The other searched moves give it away."],
    reply_capture: ["{opponent} can play {reply} and take {side}'s {piece}. Account for it."],
    alternative: ["Put {best} in the comparison: {evaluation} for the mover."],
    loss: [{fact: "{loss} pawns of evaluation conceded against the best line.", takeaway: "Inspect the stronger continuation."}],
    best: [{reaction: "Excellent execution.", fact: "Close to the engine's best continuation."}],
    good: [{reaction: "Solid work.", fact: "Most of the position's value stays intact."}],
    human_natural_error: [{reaction: "Tempting, yes. Enough, no.", fact: "A natural mistake.", takeaway: "Check the reply before signing off."}],
    difficult_defense: ["{best} would have held. A tough defense to spot; put it on the study board."],
    human_challenging: [{fact: "{best} was hard to spot.", takeaway: "Put that resource on the study board."}],
    human_defense_found: [{reaction: "Held the line!", fact: "{best} kept the position playable: a difficult defense to find.", takeaway: "Remember how it works."}],
    human_rare: ["Unusual choice. It stands up to the engine's reply. Good reason for confidence."],
    human_natural_best: ["Natural and best in the search. Approved."],
    human_natural_strong: ["Natural and strong. The best continuation stays close."],
    book: ["That is {opening}."],
    book_sound: ["Known route: {opening}.", "The catalogue recognizes {opening} here."],
    departure: ["We have reached the end of this known opening line."],
    recovery: [{reaction: "Back in action!", fact: "The position is playable again after {earlier}.{help}", takeaway: "Take stock and get to work."}],
    repeated: ["The {motif} issue has appeared {count} times in the reviewed game. Give it a place on the study list."],
    clock_low: ["Time available: {seconds} seconds for {side} before the move."],
    mate_win: [{reaction: "Mission complete!", fact: "Checkmate. The opposing king has no legal escape."}],
    mate_loss: [{fact: "Checkmate. Your king has no escape.", takeaway: "Reset earlier. Work on the defense."}],
    draw: ["A draw on the board. Take the useful lessons and move on.", "Drawn here. The earlier moves still deserve a proper review."],
    retry: [{reaction: "Reset.", fact: "That attempt falls short.", takeaway: "Give the position a new answer."}],
    recovered: [{reaction: "Adjustment made!", fact: "{detail}", takeaway: "Keep that lesson."}],
    accepted: [{reaction: "That's the useful bit.", fact: "{detail}", takeaway: "Remember the reason."}],
    explanation: [{reaction: "Straight to the evidence.", fact: "{detail}"}],
    cold: [{fact: "Take stock. Make your choice."}],
    thinking: [{fact: "Putting the strongest reply to the test…"}],
    unavailable: [{fact: "No reliable engine result.", takeaway: "Leave the question open. No bluffing."}],
    variation: ["This route has its own consequences: {detail}"],
    development: [{reaction: "Get the pieces working.", fact: "{lead}develops the {piece} from its original square."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    reply_check: ["Account for the check! {opponent}'s strongest reply is {reply}."],
    uncertain_reason: ["{best} is stronger. The reason is not clear enough yet. No bluffing."],
    clock_fast: ["Clock report: {side} used {elapsed} seconds with {seconds} still available."],
    clock_long: ["{side} spent {elapsed} seconds on this move. Record it."],
    punishment: ["Chance taken! This uses the opening the opponent gave {side} at {earlier}."],
    missed_punishment: ["Chance passed up. The opponent offered it to {side} at {earlier}; this move lets it go. Review it."],
    support_restored: ["Support restored! The {piece} was unguarded at {earlier}; now it has help again."],
    erosion: ["Small concessions add up. This joins the ones since {earlier} that together worsened the position. Review the sequence."],
    conversion: ["Advantage converted! {side} kept the edge from {earlier} all the way to the win."],
    history: ["Put this on the study list: the {motif} issue appears in {games} other saved games."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}. No enemy pawn ahead on those or neighboring files. Mark them."],
    passer_advance: ["Forward: {lead}advances the passed pawn to {square}. Track it."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}. No friendly pawn on a neighboring file. Take stock."],
    support: ["Support in place: {lead}protects the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Don't call it lost from that alone. Check the reply."],
    flights: ["Make note: {lead}opens {squares} as a legal flight square for the king."],
    castle: ["{lead}castles the king to {square} and relocates the rook. Account for both."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops. Update the count."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. Inspect the structure."],
    practice_error: ["No result for that attempt. Reset and try again."],
    explanation_summary: ["Keep the useful part. {detail}"],
    compatibility: ["Use the saved explanation. {detail}"],
  },
};
