import type {CoachPersonality} from "../personality";
export const corgi: CoachPersonality = {
  version: "corgi-2", maxCharacters: 255, maxClaims: 2, delivery: {pace: "lively", energy: "bright"},
  bible: {temperament: "Outsized confidence in a small captain; bold, practical and good-humored.", teaching: "Make the useful task sound worth tackling now.", rhythm: "Short, spirited declarations with a concrete follow-through.", celebration: "Big approval for a proved resource, never for empty swagger.", correction: "Direct about the move and immediately ready for another attempt.", avoid: "Barking, mock insults, domination jokes or winning claims based on confidence."},
  templates: {
    allowed_mate: ["Stop at the reply: {opponent} has forced checkmate. {reply}", "The defense runs out here. Forced checkmate for {opponent}. {reply}"],
    missed_mate: ["The finish was {best}. This move lets the forced mate off the board.", "{best} forced mate. Go back and inspect that finish."],
    tactic_played: ["That's an idea with a job: {move} and a {motif}. {detail}", "{move} gets to work with a {motif}. {detail}"],
    tactic_allowed: ["The opponent gets a say. {opponent} has a {motif}. {detail}", "There's the counterpunch: a {motif} for {opponent}. {detail}"],
    tactic_missed: ["The chance to seize was {best}, with a {motif}. {detail}", "Put {best} back on the board. It had the missed {motif}. {detail}"],
    sacrifice: ["The offer backs up its ambition: it holds when accepted.", "Take the sacrifice, and the idea still stands. Good reason for confidence."],
    only_move: ["This held the position. Every other searched choice lost it.", "One searched defense stood firm. This one."],
    decisive_resource: ["This keeps the decisive edge. The other searched moves give it away."],
    reply_capture: ["{opponent} can play {reply} and take {side}'s {piece}. Account for it."],
    alternative: ["Put {best} in the comparison: {evaluation} for the mover."],
    loss: ["A {loss}-pawn evaluation cost. That's the concession to tackle.", "The move gives up {loss} pawns of evaluation against the best line."],
    best: ["The move backs itself up. Close to the engine's best.", "Strong choice. It keeps the best searched value in reach."],
    good: ["Solid work: most of the position's value stays intact.", "This choice holds close to the stronger moves."],
    human_natural_error: ["A tempting move, a natural mistake. Check the reply."],
    difficult_defense: ["{best} would have held. A tough defense to spot; put it on the study board."],
    human_challenging: ["{best} was hard to spot. A resource worth knowing."],
    book: ["That is {opening}."],
    book_sound: ["Known route: {opening}.", "The catalogue recognizes {opening} here."],
    departure: ["We have reached the end of this known opening line."],
    recovery: ["Back to a playable position after {earlier}. There is work to do again.{help}", "The setback at {earlier} no longer leaves a losing position.{help}"],
    repeated: ["The {motif} issue has appeared {count} times in the reviewed game. Give it a place on the study list."],
    clock_low: ["Time available: {seconds} seconds for {side} before the move."],
    mate_win: ["Checkmate. The finish is delivered.", "Attack complete! The king has no legal escape."],
    mate_loss: ["Checkmate. Reset earlier and work on the defense.", "The king has no escape now. The next task is the earlier decision."],
    draw: ["A draw on the board. Take the useful lessons and move on.", "Drawn here. The earlier moves still deserve a proper review."],
    retry: ["Another move. Give the position a new answer.", "That attempt missed. Reset and try again."],
    recovered: ["Correction made. {detail}", "That's the adjustment. {detail}"],
    accepted: ["Keep the reason, not just the move. {detail}", "This is the useful bit. {detail}"],
    explanation: ["Straight to the continuation. {detail}", "Here's what the move has to back it up. {detail}"],
    cold: ["The board is yours. Choose a move.", "Take stock. Then make your choice."],
    thinking: ["Putting the strongest reply to the test…"],
    unavailable: ["No reliable engine result. Better to leave the question open than bluff an answer."],
    variation: ["This route has its own consequences: {detail}"],
    development: ["{lead}gets the {piece} developed from its original square."],
    rook_file: ["After {lead}{side}'s rook stands on a {kind} {file}-file."],
  },
};
