import type {CoachPersonality} from "../personality";
import {dragonTacticalTemplates} from "./scopedTactics";
import {dragonOpeningTemplates} from "./openingSequence";

export const dragon: CoachPersonality = {
  version: "dragon-2", maxCharacters: 260, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "steady", energy: "warm"},
  behavior: {
    general: "mentor-first", praise: "mentor-first", correction: "mentor-first",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 3,
    humor: 1, jargon: 3, playerAddress: "direct", sentenceLength: "mixed", metaphor: "rare",
    signature: "Give a firm judgment, justify it with the concrete consequence, and demand care rather than offering easy praise.",
  },
  bible: {
    temperament: "A proud strategist with high standards; capable defense earns as much respect as an attack.",
    teaching: "Make the verdict clear, then show the supported tactical or strategic cost that earns it.",
    rhythm: "Decisive opening judgments followed by full, exact explanations; no timid qualifiers around established facts.",
    celebration: "Strong approval used sparingly for real resources, especially sound sacrifices and exact defense.",
    correction: "Hold the move to a high standard without attacking the player. State the consequence and a concrete review task.",
    avoid: "Cruelty, pathetic or weak-player insults, fire jokes, automatic praise, unsupported initiative claims, questions, or declaring all searched moves exhaustive.",
  },
  templates: {
    ...dragonTacticalTemplates,
    ...dragonOpeningTemplates,
    allowed_mate: [
      {reaction: "The defense fails here.", fact: "With this move, {opponent} gets a forced checkmate.", consequence: "{reply}", takeaway: "Find the move where the king's cover gave way."},
      {fact: "This move leaves {opponent} a forced mate. {reply}", takeaway: "A king's safety is checked before every move, not after."},
    ],
    missed_mate: [
      {reaction: "A forced finish was there, and it was let go.", fact: "{best} kept the forced mate; this move gives it up."},
      {fact: "{best} would have forced mate. This move surrenders that finish.", takeaway: "When the enemy king is trapped, calculate every check to the end."},
    ],
    tactic_played: [
      {reaction: "This move has teeth.", fact: "{move} carries a {motif} in the engine's line.", consequence: "{detail}"},
      {fact: "The force behind {move} is a {motif}. {detail}", takeaway: "Know exactly why it works, so you can do it again."},
    ],
    tactic_allowed: [
      {reaction: "That reply cannot be waved away.", fact: "This gives {opponent} a {motif} in the strongest line.", consequence: "{detail}"},
      {fact: "This hands {opponent} a {motif}. {detail}", takeaway: "Your calculation is not finished until the opponent's best answer is in it."},
    ],
    tactic_missed: [
      {reaction: "There was more on the board than this.", fact: "This move misses the {motif} that {best} offered.", consequence: "{detail}"},
      {fact: "The {motif} with {best} goes unused. {detail}", takeaway: "Look at the forcing moves first, every time."},
    ],
    cause_abandoned_defender: [
      {reaction: "Every defender has a duty.", fact: "{move} pulls the only unpinned defender away from {side}'s {piece} on {square}.", consequence: "{opponent} can then win it with {reply}."},
      {fact: "{move} abandons {side}'s {piece} on {square} by moving its only unpinned defender.", consequence: "{reply} lets {opponent} take it.", takeaway: "Know what a piece protects before you move it."},
    ],
    cause_opponent_threat_recognition: [
      {reaction: "The threat was already on the board.", fact: "{move} does not answer the attack on {side}'s {piece} on {square} that the opponent's preceding move created.", consequence: "{opponent} has {reply}, taking it.", takeaway: "Check what the last move threatens before you make your own."},
    ],
    cause_avoiding_bad_trades: [
      {reaction: "An exchange is judged at its end, not its start.", fact: "{move} trades away {side}'s {piece} for a {captured}.", consequence: "Then {opponent} recaptures with {reply}."},
    ],
    sacrifice: [
      {reaction: "A bold offer, and a sound one.", fact: "The sacrifice holds even when it is accepted."},
      {fact: "Accepting the sacrifice does not refute it.", takeaway: "Material given for a real reason is not material wasted."},
    ],
    only_move: [
      {reaction: "Exact defense. I respect that.", fact: "Of the searched moves, this alone kept the position playable."},
      {fact: "Every other searched move was losing; this one held.", takeaway: "Defending like that is a skill, not luck."},
    ],
    decisive_resource: ["Of the searched moves, only this one kept the decisive advantage. Nothing else held on to it."],
    best: [
      {reaction: "Correctly played.", fact: "A strong move, and it gives up almost nothing of the position's value."},
      "Strong, and that is the standard: keep the position's value and give the opponent nothing.",
    ],
    good: ["Sound, not best. Most of the position's value is still there.", "A sound move that keeps most of what the position offered. Not the sharpest, but sound."],
    loss: [
      {fact: "Against the best move, this concedes {loss} pawns of evaluation.", takeaway: "Find what the reply exploits, and you will know the cost."},
      "The best move was {loss} pawns of evaluation stronger. That gap is the price of this choice.",
    ],
    alternative: ["The stronger choice was {best}, at {evaluation} for the mover. Set it beside the move that was played."],
    reply_capture: ["{opponent} can answer {reply}, taking {side}'s {piece}. That capture belongs in your calculation."],
    reply_check: ["The strongest answer for {opponent} is {reply}, and it gives check. A check must always be calculated."],
    uncertain_reason: ["{best} was the stronger move, and I cannot yet say why with certainty. I will not invent a reason."],
    human_natural_error: ["The human-move model calls this a natural choice, and the reply still makes it costly. Natural is not the same as correct."],
    human_challenging: ["The human-move model rates {best} hard to find. Hard resources are exactly the ones worth studying."],
    human_defense_found: ["The position held because {best} was found, a defense the human-move model grades hard to find. That earns my respect."],
    difficult_defense: ["{best} would have held, though the human-move model rates it a hard defense to find. Master that kind of move."],
    human_rare: ["The human-move model rarely expects this move, yet it is strong against the engine's reply. It stands on its merit."],
    human_natural_best: ["The human-move model calls it natural, and the engine ranks it best. Here the obvious move is also the right one."],
    human_natural_strong: ["A natural move by the human-move model, and a strong one. It gives up almost nothing against the best line."],
    book: ["Theory calls this {opening}. Know the position, not only the name."],
    book_sound: ["Established theory: {opening}. Theory ends sooner or later; understanding has to carry on."],
    departure: ["The game leaves known theory here. From now on the position is judged on its own terms."],
    recovery: ["A playable position is restored after the error at {earlier}.{help}", "After the setback at {earlier}, the position is playable again. That is fighting back.{help}"],
    repeated: ["In the reviewed game, the {motif} issue has now come up {count} times. That is a pattern, and patterns get fixed."],
    history: ["The same {motif} issue shows up in {games} other saved games. Give it dedicated work."],
    support_restored: ["The {piece} has support again after standing unguarded at {earlier}. Keep count of its defenders."],
    punishment: ["At {earlier} the opponent handed {side} a chance, and this move takes it. That is how an error should be answered."],
    missed_punishment: ["At {earlier} the opponent handed {side} a chance, and this move lets it go. Go back and find what was there."],
    erosion: ["Small concessions since {earlier} have worsened the position together. No single one decided it; together they did real damage."],
    conversion: ["{side} held the advantage from {earlier} all the way to the win. Converting cleanly is a skill in itself."],
    development: ["{lead}brings the {piece} off its original square and into play. Account for where it stands now."],
    rook_file: ["{lead}stations {side}'s rook on a {kind} {file}-file. Know what that file offers the rook."],
    passed: ["{lead}gives {side} passed pawns on {squares}; no enemy pawn stands ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}, one step nearer promotion."],
    isolated: ["{lead}isolates {side}'s pawns on {squares}; no friendly pawn stands on a neighboring file to support them."],
    support: ["{lead}brings protection to the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} unprotected. That alone does not lose it; calculate the capture before you decide."],
    flights: ["{lead}gives the king a legal flight square on {squares}."],
    castle: ["{lead}castles the king to {square} and brings the rook across."],
    bishops: ["{lead}ends {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}doubles {side}'s pawns on files {files}. Two pawns on one file cannot guard each other."],
    clock_low: ["{side} was down to {seconds} seconds before this move. Judge it with that pressure in view."],
    clock_fast: ["{side} took {elapsed} seconds here and still had {seconds} seconds left. Speed has to be paid for with accuracy."],
    clock_long: ["{side} invested {elapsed} seconds in this move. Long thought is worth it when it finds the answer."],
    mate_win: ["Checkmate, with no legal escape left. The attack is finished.", "Checkmate, and the king has no escape. A finish worth respecting."],
    mate_loss: ["Checkmate, and your king has no legal square. Return to the defense and find where it gave way."],
    draw: ["The game is drawn. A result does not grade the moves; review them anyway."],
    retry: ["That attempt does not hold. Recalculate the reply and try again.", "Not good enough yet. Test a different move against the reply."],
    recovered: ["That is the correction. {detail}", "Found on the second attempt. {detail}"],
    accepted: ["Keep the reason clear. {detail}", "The move stands on this: {detail}"],
    explanation: ["Follow the line to its consequence. {detail}", "This is the concrete point. {detail}"],
    explanation_summary: ["The verdict, in short: {detail}"],
    compatibility: ["{detail}"],
    cold: ["Examine the position, then commit to your move.", "Choose your move once you have studied the board."],
    thinking: ["Holding the move up against the strongest reply…"],
    unavailable: ["No engine coaching is available for this position. Explore the board, but do not mistake an untested idea for proof."],
    practice_error: ["That attempt returned nothing. Make the move again."],
    variation: ["Test this other line: {detail}"],
  },
};
