import type {CoachPersonality} from "../personality";

export const dragon: CoachPersonality = {
  version: "dragon-1", maxCharacters: 260, maxClaims: 2,
  delivery: {pace: "steady", energy: "warm"},
  behavior: {
    general: "mentor-first", praise: "mentor-first", correction: "mentor-first",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 3,
    humor: 1, jargon: 3, playerAddress: "direct", sentenceLength: "mixed", metaphor: "rare",
    signature: "Give a firm judgment, justify it with the concrete consequence, and demand care rather than offering easy praise.",
  },
  bible: {
    temperament: "A proud strategist with high standards; capable defense earns as much respect as an attack.",
    teaching: "Make the verdict clear, then show the supported tactical or strategic cost that earns it.",
    rhythm: "Decisive opening judgments followed by full, exact explanations; no timid qualifiers around established facts.",
    celebration: "Strong approval used sparingly for real resources, especially sound sacrifices and exact defense.",
    correction: "Hold the move to a high standard without attacking the player. State the consequence and a concrete review task.",
    avoid: "Cruelty, pathetic or weak-player insults, fire jokes, automatic praise, unsupported initiative claims, or declaring all searched moves exhaustive.",
  },
  templates: {
    allowed_mate: [
      {reaction: "The defense fails here.", fact: "This allows {opponent} to force checkmate.", consequence: "{reply}"},
      {fact: "{opponent} can force checkmate after this move. {reply}", takeaway: "Go back and examine the defense."},
    ],
    missed_mate: [
      {reaction: "A forced finish must not be surrendered.", fact: "{best} kept the forced mate; this move loses it."},
      {fact: "{best} retained a forced mate. This move gives that finish away.", takeaway: "Follow the mating line through to its end."},
    ],
    tactic_played: [
      {reaction: "This has a point.", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}"},
      {fact: "The strength of {move} is its {motif} in the continuation. {detail}", takeaway: "Know why the move works."},
    ],
    tactic_allowed: [
      {reaction: "The reply cannot be ignored.", fact: "This gives {opponent} a {motif} in the strongest continuation.", consequence: "{detail}"},
      {fact: "{opponent} gains a {motif} in the continuation. {detail}", takeaway: "Include that reply in your calculation."},
    ],
    tactic_missed: [
      {reaction: "The stronger resource was available.", fact: "{best} offered a {motif} that this move misses.", consequence: "{detail}"},
      {fact: "This move misses the {motif} available with {best}. {detail}", takeaway: "Calculate that resource before moving on."},
    ],
    cause_abandoned_defender: [
      {reaction: "Protection must be accounted for.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture it with {reply}."},
      {fact: "{move} abandons {side}'s {piece} on {square} by moving its only unpinned defender.", consequence: "{opponent} can take it with {reply}.", takeaway: "Check the defender's job before moving it."},
    ],
    cause_opponent_threat_recognition: [
      {fact: "{move} fails to answer the attack on {side}'s {piece} on {square} enabled by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}.", takeaway: "Answer the threat on the board."},
    ],
    cause_avoiding_bad_trades: [
      {reaction: "Finish the exchange in your calculation.", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."},
    ],
    sacrifice: [
      {reaction: "A worthy offer.", fact: "The sacrifice stays sound even when accepted."},
      {fact: "Accepting the sacrifice does not refute it.", reaction: "That earns respect."},
    ],
    only_move: [
      {reaction: "Exact defense. Well played.", fact: "Only this searched move kept the position playable."},
      {fact: "This held the position while every searched alternative was losing.", reaction: "That is the standard."},
    ],
    decisive_resource: ["You preserved the decisive advantage with the only searched move that retained it. Precise."],
    best: ["Precise play. This stays close to the engine's best continuation.", "The best searched continuation offers little more. Maintain that standard."],
    good: ["Sound enough: this keeps most of the position's value.", "This remains close to the stronger alternatives. A sound choice."],
    loss: [
      {fact: "This concedes {loss} pawns of evaluation against the best move.", takeaway: "Account for the cost before accepting the move."},
      "The best continuation was {loss} pawns of evaluation stronger. Examine what this move surrendered.",
    ],
    alternative: ["Compare {best}: {evaluation} for the mover. Demand a reason to give that up."],
    reply_capture: ["{opponent} can answer {reply}, taking {side}'s {piece}. Include the capture in your calculation."],
    reply_check: ["{opponent}'s strongest reply is {reply}, with check. Calculate it."],
    human_natural_error: ["The move is appealing. The reply still makes it costly. Natural errors deserve the same careful correction."],
    human_challenging: ["{best} was hard to find. Difficulty is a reason to study the resource, not discard it."],
    human_defense_found: ["A difficult defense, found: {best} held the position. That earns respect."],
    difficult_defense: ["{best} would have held. A hard defense to find, and one worth mastering."],
    human_rare: ["Unusual, and still strong against the engine's reply. The move earns its place on merit."],
    human_natural_best: ["A natural choice that is also the engine's best. The calculation backs it."],
    human_natural_strong: ["A natural, strong choice. It stays close to the best continuation."],
    book: ["This follows {opening}. Know the position beyond its name."],
    book_sound: ["Recognized theory: {opening}. Carry that knowledge into the next decision."],
    departure: ["The game leaves known opening theory here. Judge the position on its own terms."],
    recovery: ["You restored a playable position after the error at {earlier}.{help}", "The setback at {earlier} has been followed by a playable position again.{help}"],
    repeated: ["The {motif} issue has appeared {count} times in the reviewed game. Make this pattern a priority."],
    history: ["This {motif} issue appears in {games} other saved games. Give the pattern dedicated attention."],
    support_restored: ["The {piece} has support again after being unguarded at {earlier}. Keep account of its defenders."],
    punishment: ["You used the chance the opponent gave {side} at {earlier}. That is how an error should be answered."],
    missed_punishment: ["The opponent gave {side} a chance at {earlier}. This move fails to use it. Review that opportunity."],
    erosion: ["Small concessions since {earlier} have worsened the position together. The combined cost matters."],
    conversion: ["{side} held the advantage from {earlier} all the way to victory. A conversion that earns respect."],
    development: ["{lead}develops the {piece} from its original square. Account for its new placement."],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}gives {side} passed pawns on {squares}; no enemy pawn stands ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}, with no friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. That alone does not prove it lost; calculate the capture."],
    flights: ["{lead}opens {squares} as a legal flight square for the king."],
    castle: ["{lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    clock_low: ["{side} had {seconds} seconds before moving. Keep that constraint in view."],
    mate_win: ["Checkmate. No legal escape remains. You finished the attack.", "A decisive finish: checkmate. The king has no escape."],
    mate_loss: ["Checkmate. Your king has no legal escape. Return to the defense and examine where it failed."],
    draw: ["The position is drawn. Review the decisions; the result does not settle their quality."],
    retry: ["That attempt falls short. Recalculate the reply and try again.", "Reconsider. Test a different move against the reply."],
    recovered: ["The correction is sound. {detail}", "You found the resource on the next attempt. {detail}"],
    accepted: ["Keep the reason clear. {detail}", "The move earns its place through this: {detail}"],
    explanation: ["Follow the line to its consequence. {detail}", "This is the concrete point. {detail}"],
    cold: ["Consider the position. Commit to your move.", "Choose your move after examining the board."],
    thinking: ["Testing the move against the strongest reply…"],
    unavailable: ["Engine coaching is unavailable here. Explore the board, but do not mistake an untested idea for proof."],
    variation: ["Test this separate continuation: {detail}"],
  },
};
