import type {CoachPersonality} from "../personality";
export const expert: CoachPersonality = {
  version: "expert-1", maxCharacters: 240, maxClaims: 2, delivery: {pace: "measured", energy: "quiet"},
  bible: {temperament: "Patient endgame specialist; economical, exact and unhurried.", teaching: "Identify what is retained or surrendered before discussing style.", rhythm: "Firm declarative sentences with little ornament.", celebration: "Respect precision and necessary resources.", correction: "Separate an objective loss from the player's worth.", avoid: "Pretending every position is an endgame or dressing simple facts in jargon."},
  templates: {
    allowed_mate: ["The defense fails to forced checkmate. {reply}", "{opponent} now has forced checkmate. {reply}"],
    missed_mate: ["{best} preserves mate. This move gives it up.", "The forced win by mate was retained by {best}, not this move."],
    tactic_played: ["The resource is {move}, with a {motif} in the continuation. {detail}", "{move} works through a {motif}. {detail}"],
    tactic_allowed: ["{opponent} has a {motif} in the searched continuation. {detail}", "The consequence is a {motif} for {opponent}. {detail}"],
    tactic_missed: ["The missed resource: {best}, with a {motif}. {detail}", "{best} was the route to the {motif}. {detail}"],
    sacrifice: ["The sacrifice is sound against acceptance at the searched depth.", "Accepting the offer leaves a sound continuation. The sacrifice is supported."],
    only_move: ["Necessary defense among the searched moves. The alternatives lose.", "This alone retains a playable evaluation among the searched candidates."],
    decisive_resource: ["Only this searched move retains the decisive advantage."],
    reply_capture: ["{opponent} replies {reply}, capturing {side}'s {piece}."],
    alternative: ["Retain {best} for comparison: {evaluation} for the mover."],
    loss: ["The concession is {loss} pawns of evaluation.", "Against the best line, the evaluation loss is {loss} pawns."],
    best: ["Precise. This retains the best searched value.", "No significant concession to the best continuation."],
    good: ["Sound enough to retain most of the position's value.", "A good continuation, close to the best value."],
    human_natural_error: ["The human model favors the choice. That does not remove its objective cost."],
    difficult_defense: ["The necessary resource was {best}, assessed as difficult by the human model."],
    human_challenging: ["A challenging find by the human-model assessment: {best}."],
    book: ["{opening} is recognized theory. Its soundness is a separate question."],
    book_sound: ["Known opening line: {opening}.", "Recognized {opening} theory."],
    departure: ["The recognized opening sequence ends here. Departure alone carries no penalty."],
    recovery: ["Playability is restored after {earlier}.{help}", "The earlier error at {earlier} has been followed by a return to a playable position.{help}"],
    repeated: ["Same {motif} issue: {count} occurrences in the reviewed segment."],
    clock_low: ["Available time before moving: {seconds} seconds for {side}."],
    turning: ["This is the review's largest objective concession."],
    mate_win: ["Checkmate. The finish is complete.", "The opposing king has no legal escape. Checkmate."],
    mate_loss: ["Checkmate. Return to the last meaningful defensive choice.", "Your king has been checkmated. Study the earlier defense."],
    draw: ["Drawn position. Review the decisions that preceded it.", "The result on the board is a draw."],
    retry: ["Reconsider. Compare another candidate.", "The attempt is insufficient. Choose again."],
    recovered: ["Corrected. {detail}", "The second approach works. {detail}"],
    accepted: ["Keep the underlying reason. {detail}", "The explanation matters more than the label. {detail}"],
    explanation: ["Follow the essential continuation. {detail}", "The relevant sequence: {detail}"],
    complete: ["Review complete. Start with the decisive evidence: {detail}"],
    cold: ["Assess the position. Choose a move.", "Take the time you need, then move."],
    thinking: ["Checking the reply and resulting evaluation…"],
    unavailable: ["No sufficient engine result is available. A specific conclusion would be premature."],
    variation: ["Alternative continuation: {detail}"],
    development: ["{lead}develops the {piece} from its starting square."],
    rook_file: ["After {lead}the {file}-file is {kind} for {side}'s rook."],
  },
};
