import type {CoachPersonality} from "../personality";
export const expert: CoachPersonality = {
  version: "expert-3", maxCharacters: 290, maxClaims: 2, delivery: {pace: "measured", energy: "quiet"},
  behavior: {general: "minimal", praise: "minimal", correction: "consequence-first",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 2, humor: 0, jargon: 4,
    playerAddress: "none", sentenceLength: "short", metaphor: "none",
    signature: "State the exact resource and its consequence; stop when the evidence ends."},
  bible: {temperament: "Calm, disciplined technician; economical, exact and unhurried.", teaching: "State the fact, its exact consequence, and the supported resource.", rhythm: "Short declaratives; stop when the evidence ends.", celebration: "Sparse, specific approval for precision.", correction: "Direct and unemotional; describe the move's consequence.", avoid: "Hype, exclamation marks, speculation, padded prose, or treating every position as an endgame."},
  templates: {
    allowed_mate: [{fact: "{opponent} has forced checkmate.", consequence: "{reply}"}],
    missed_mate: ["{best} preserves mate. This move gives it up.", "The forced win by mate was retained by {best}, not this move."],
    tactic_played: [{fact: "{move}: a {motif} in the searched continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "{opponent} has a {motif} in the searched continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "Missed resource: {best}, with a {motif} in the continuation.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "{move} removes the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture {side}'s {piece} with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture {side}'s {piece} with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "{move} exchanges {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: [{fact: "The sacrifice is sound against acceptance at the searched depth."}],
    only_move: [{fact: "Only this searched move retains a playable evaluation."}],
    decisive_resource: ["Only this searched move retains the decisive advantage."],
    reply_capture: ["{opponent} replies {reply}, capturing {side}'s {piece}."],
    alternative: ["Retain {best} for comparison: {evaluation} for the mover."],
    loss: [{fact: "Evaluation loss against the best line: {loss} pawns."}],
    best: [{fact: "Close to the best searched evaluation."}, {fact: "No significant concession against the best continuation."}],
    good: [{fact: "Sound. Most of the position's value is retained."}],
    human_natural_error: [{fact: "Natural-looking, but mistaken. The reply exposes the cost."}],
    difficult_defense: ["{best} would have held. The necessary defense was difficult to find."],
    human_challenging: [{fact: "A difficult resource to find: {best}."}],
    human_defense_found: [{fact: "{best} holds. A difficult defense to find."}],
    book: ["This continues {opening}."],
    book_sound: ["Known opening line: {opening}.", "Recognized {opening} theory."],
    departure: ["The game has left known theory."],
    recovery: [{fact: "Playable again after the error at {earlier}.{help}"}],
    repeated: ["Same {motif} issue: {count} occurrences in the reviewed segment."],
    clock_low: ["Available time before moving: {seconds} seconds for {side}."],
    mate_win: [{fact: "Checkmate. The opposing king has no legal escape."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape.", takeaway: "Return to the earlier defense."}],
    draw: ["Drawn position. Review the decisions that preceded it.", "The result on the board is a draw."],
    retry: [{fact: "Insufficient. Compare another candidate."}],
    recovered: [{fact: "Corrected. {detail}"}],
    accepted: [{fact: "{detail}"}],
    explanation: [{fact: "The continuation: {detail}"}],
    cold: [{fact: "Assess the position. Choose a move."}],
    thinking: [{fact: "Checking the strongest reply and evaluation…"}],
    unavailable: [{fact: "Insufficient engine evidence for an explanation."}],
    variation: ["Alternative continuation: {detail}"],
    development: [{fact: "{lead}develops the {piece} from its starting square."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    reply_check: ["Strongest reply for {opponent}: {reply}, with check."],
    uncertain_reason: ["{best} has a better evaluation. A specific explanation is not established."],
    human_rare: ["Unusual, but supported against the engine's reply."],
    human_natural_best: ["Natural choice. Best in the search."],
    human_natural_strong: ["Natural, strong, and close to the best searched continuation."],
    clock_fast: ["{side}: {elapsed} seconds used, {seconds} seconds still available."],
    clock_long: ["{side} used {elapsed} seconds."],
    punishment: ["{side} uses the opportunity given at {earlier}."],
    missed_punishment: ["The opportunity given to {side} at {earlier} is missed."],
    support_restored: ["The {piece} is defended again after being unguarded at {earlier}."],
    erosion: ["Several small concessions since {earlier} worsened the position. This is one of them."],
    conversion: ["{side} retained the advantage from {earlier} through the win."],
    history: ["This {motif} issue occurs in {games} other saved games."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}: no enemy pawn ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated, with no friendly pawn on a neighboring file."],
    support: ["{lead}adds support to the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. A forced loss does not follow from that fact alone."],
    flights: ["{lead}makes {squares} a legal flight square for the king."],
    castle: ["{lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    practice_error: ["No result returned. Retry the move."],
    explanation_summary: ["Conclusion: {detail}"],
    compatibility: ["Available explanation: {detail}"],
  },
};
