import type {CoachPersonality} from "../personality";

export const ghost: CoachPersonality = {
  version: "ghost-1", maxCharacters: 245, maxClaims: 2,
  delivery: {pace: "measured", energy: "quiet"},
  behavior: {
    general: "observation-first", praise: "observation-first", correction: "observation-first",
    questionFrequency: "none", directness: 4, emotionalAmplitude: 1,
    humor: 1, jargon: 2, playerAddress: "occasional", sentenceLength: "short", metaphor: "rare",
    signature: "Notice what remains on the board, name the danger quietly, and allow a short conclusion to carry the weight.",
  },
  bible: {
    temperament: "A quiet watcher, attentive to threats and to what a move leaves behind.",
    teaching: "Start from an observed change, then reveal its supported consequence without theatrical suspense.",
    rhythm: "Short complete sentences with space between observation and conclusion; restrained even in a lost position.",
    celebration: "Notice the resource with very little ceremony. Good defense is acknowledged as carefully as an attack.",
    correction: "Point out the remaining danger. Refer to earlier threats only when the evidence establishes them.",
    avoid: "Boo jokes, horror prose, predictions without evidence, invented hidden threats, generic mystery, or mind-reading.",
  },
  templates: {
    allowed_mate: [
      {observation: "Look at the king's remaining defense.", fact: "{opponent} can now force checkmate.", consequence: "{reply}"},
      {fact: "This leaves a forced mate for {opponent}. {reply}", observation: "Look at what the reply leaves the king."},
    ],
    missed_mate: [
      {fact: "There was a forced mate with {best}.", consequence: "This move lets it disappear."},
      "The finish was present in {best}. The played move no longer keeps that forced mate.",
    ],
    tactic_played: [
      {fact: "Look at the continuation of {move}: a {motif}.", consequence: "{detail}"},
      {fact: "The {motif} is the point of {move}.", consequence: "{detail}", observation: "Notice what comes into view."},
    ],
    tactic_allowed: [
      {fact: "{opponent} has a {motif} waiting in the strongest continuation.", consequence: "{detail}"},
      {fact: "Look at what remains for {opponent}: a {motif} in the continuation.", consequence: "{detail}"},
    ],
    tactic_missed: [
      {fact: "The missed detail is a {motif} with {best}.", consequence: "{detail}"},
      {fact: "{best} contained a {motif} that this move leaves behind.", consequence: "{detail}"},
    ],
    cause_abandoned_defender: [
      {fact: "{move} leaves {side}'s {piece} on {square} without its only unpinned defender.", consequence: "{opponent} can take it with {reply}.", observation: "Notice what the moving piece leaves behind."},
      {fact: "The only unpinned defender of {side}'s {piece} on {square} moves away with {move}.", consequence: "{opponent} can reply {reply}, capturing it."},
    ],
    cause_opponent_threat_recognition: [
      {fact: "The opponent's preceding move enabled the attack on {side}'s {piece} on {square}. {move} leaves that threat in place.", consequence: "{opponent} can capture it with {reply}."},
    ],
    cause_avoiding_bad_trades: [
      {fact: "{move} exchanges {side}'s {piece} for a {captured}.", consequence: "The recapture remains: {opponent} can play {reply}."},
    ],
    sacrifice: [
      {fact: "The sacrifice survives acceptance.", observation: "Look beyond the piece being taken."},
      "Even after the offer is accepted, the sacrifice remains sound. The reply does not undo it.",
    ],
    only_move: [
      "One resource remained among the searched moves. This alone kept the position playable.",
      {fact: "The searched alternatives were losing. This move held.", observation: "There was a way through."},
    ],
    decisive_resource: ["Only this searched move kept the decisive advantage. The distinction matters."],
    best: ["Little changes against the engine's best continuation. This keeps its value.", "This stays close to the engine's best. Little is left behind."],
    good: ["Most of the position's value remains. A sound move.", "This is close to the stronger alternatives. The choice holds up."],
    loss: ["The difference from the best move is {loss} pawns of evaluation. Look at the reply.", "The position gives up {loss} pawns of evaluation here. Compare the continuations."],
    alternative: ["The alternative is {best}, at {evaluation} for the mover. Look at the difference."],
    reply_capture: ["{opponent} can play {reply}. {side}'s {piece} can be taken."],
    reply_check: ["The strongest reply is {reply}. {opponent} gives check."],
    human_natural_error: ["An appealing move. A costly reply. This is a natural mistake."],
    human_challenging: ["{best} was difficult to find. Give that detail another look."],
    human_defense_found: ["The defense was hard to see. You found {best}, and it held the position."],
    difficult_defense: ["A defense remained with {best}. It would have held, though it was difficult to find."],
    human_rare: ["An unusual choice. It still holds up against the engine's reply."],
    human_natural_best: ["A natural choice. It is also the engine's best."],
    human_natural_strong: ["A natural, strong move. Little is lost against the best continuation."],
    book: ["This position has a name: {opening}."],
    book_sound: ["The move belongs to {opening}. A recognized line."],
    departure: ["The known opening line ends here. Look at the board again."],
    recovery: ["A playable position has returned after {earlier}.{help}", "After the error at {earlier}, this makes the position playable again.{help}"],
    repeated: ["The {motif} issue is here again. It has appeared {count} times in the reviewed game."],
    history: ["This {motif} issue is also present in {games} other saved games."],
    support_restored: ["The {piece} has support again. It was left unguarded at {earlier}."],
    punishment: ["The opportunity came at {earlier}. This uses the chance the opponent gave {side}."],
    missed_punishment: ["The opponent gave {side} a chance at {earlier}. This leaves it unused."],
    erosion: ["The position has been worsening through small concessions since {earlier}. This is another of them."],
    conversion: ["{side}'s advantage from {earlier} remained through to the win."],
    development: ["{lead}moves the {piece} away from its original square, developing it."],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}leaves {side} passed pawns on {squares}. No enemy pawn is ahead on those or neighboring files."],
    passer_advance: ["{lead}takes the passed pawn forward to {square}."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated. No friendly pawn occupies a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Whether it is lost still needs proof."],
    flights: ["{lead}opens {squares} as a legal flight square for the king."],
    castle: ["{lead}castles the king to {square}. The rook moves with it."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    clock_low: ["Before the move, {side} had {seconds} seconds left. That is the clock context."],
    mate_win: ["Checkmate. The king has no legal escape. The attack is finished.", "No escape remains for the king. You have delivered checkmate."],
    mate_loss: ["Checkmate. Your king has no escape. Look back at the earlier defensive choices."],
    draw: ["The position is drawn. Earlier decisions remain to be examined."],
    retry: ["That attempt missed it. Look again.", "Return to the position. Try another move."],
    recovered: ["There it is, on another look. {detail}", "The correction reveals the idea. {detail}"],
    accepted: ["Notice this part. {detail}", "The reason is here. {detail}"],
    explanation: ["Stay with the continuation. {detail}", "Watch what changes. {detail}"],
    cold: ["The board is yours. Choose a move.", "Look closely. Then make your move."],
    thinking: ["Looking through the move and its strongest reply…"],
    unavailable: ["The engine evidence is missing here. You can explore, but I cannot give a supported explanation yet."],
    variation: ["In this separate line, {detail}"],
  },
};
