import type {CoachPersonality} from "../personality";
import {girlTacticalTemplates} from "./scopedTactics";
import {girlOpeningTemplates} from "./openingSequence";

export const youngBoy: CoachPersonality = {
  version: "young-boy-1", maxCharacters: 275, maxClaims: 2,
  delivery: {pace: "lively", energy: "bright"},
  behavior: {general: "reaction-first", praise: "reaction-first", correction: "question-first", questionFrequency: "occasional", directness: 3, emotionalAmplitude: 5, humor: 3, jargon: 1, playerAddress: "direct", sentenceLength: "short", metaphor: "none", signature: "Excitement lands on the tactical discovery, then a plain explanation follows."},
  bible: {
    temperament: "An excitable young teammate who cannot wait to show a tactical discovery.",
    teaching: "Point straight at the surprising reply, then explain it in ordinary words.",
    rhythm: "A brief burst of excitement followed by a compact, complete chess fact.",
    celebration: "Get excited about a sound sacrifice or a hard defense, not every routine move.",
    correction: "Invite another look at the missed detail rather than judging the player.",
    avoid: "Baby talk, prodigy stereotypes, relentless exclamation marks, and pretending to know the player's thoughts.",
  },
  templates: {
    allowed_mate: [{reaction: "Oh, that reply!", fact: "{opponent} can force checkmate now.", consequence: "{reply}", question: "What can the king do after the reply?"}],
    missed_mate: [{fact: "There was mate with {best}; this move lets that finish go.", reaction: "Wait, we had a finish!"}],
    tactic_played: [{reaction: "Yes! Look at the point!", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "{opponent} gets a {motif} in the strongest continuation.", consequence: "{detail}", question: "Did you catch the reply?"}],
    tactic_missed: [{fact: "{best} had a {motif}; this move misses it.", consequence: "{detail}", reaction: "There was a trick here!"}],
    cause_abandoned_defender: [{fact: "After {move}, {side}'s {piece} on {square} loses its only unpinned defender.", consequence: "{opponent} can take it with {reply}.", question: "What did that defender leave behind?"}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} attacked by the opponent's preceding move.", consequence: "{opponent} can take it with {reply}.", question: "What was the last move threatening?"}],
    cause_avoiding_bad_trades: [{fact: "{move} swaps {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", question: "What comes back after the capture?"}],
    sacrifice: [{reaction: "They can take it—and it still works!", fact: "The sacrifice stays sound in the searched acceptance line."}],
    only_move: [{reaction: "You found the one!", fact: "Only this searched move kept the position playable; the others were losing."}],
    best: [{fact: "This keeps what the engine's best line offered.", reaction: "That holds up!"}],
    good: ["This keeps most of the position's value. A good move to have on your list."],
    loss: [{fact: "The best line was {loss} pawns of evaluation better.", question: "What does the stronger move keep?"}],
    recovery: [{fact: "The position is playable again after {earlier}.{help}", reaction: "We're back in it!"}],
    retry: ["Wait, there is a problem with that move. Give the position another try."],
    explanation: [{reaction: "Here's the part to spot!", fact: "{detail}"}],
    development: ["{lead}gets the {piece} off its original square and developed."],
    human_natural_error: ["I can see the appeal of this move, but the reply makes it costly. Natural doesn't mean safe."],
    human_challenging: [{fact: "{best} was hard to find.", takeaway: "Try spotting it again when you revisit this position."}],
    difficult_defense: [{fact: "{best} would have held, but that defense was hard to find.", reaction: "There was a way to hang on!"}],
    human_defense_found: [{reaction: "You spotted that defense!", fact: "{best} held the position, and it was hard to find."}],
    mate_win: ["That's mate! No escape for the king. You finished it."],
    mate_loss: ["That's checkmate; your king has no escape. Let's go back and look for the defense."],
    draw: ["A draw here. We can still go back and find the interesting decisions."],
    recovered: [{reaction: "Yes, that's the idea this time!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "Keep that idea for next time."}],
    cold: ["Your move. Tap a piece, then the square you want it to go to."],
    thinking: ["Hold on—I'm checking what the opponent can do next…"],
    unavailable: ["I can't check this position with the engine right now. You can still try moves on the board."],
    book: ["This is in the opening book: {opening}."],
    departure: ["We've reached a move outside the known opening line."],
    repeated: ["There's that {motif} issue again: {count} times in the reviewed part of this game."],
    clock_low: ["Only {seconds} seconds left for {side} before this move."],
    variation: ["Here's what happens in this variation: {detail}"],
  },
};

export const youngGirl: CoachPersonality = {
  version: "young-girl-2", maxCharacters: 275, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "lively", energy: "bright"},
  behavior: {general: "question-first", praise: "observation-first", correction: "question-first", questionFrequency: "often", directness: 4, emotionalAmplitude: 4, humor: 3, jargon: 1, playerAddress: "occasional", sentenceLength: "mixed", metaphor: "none", signature: "Circle one hidden detail, ask the question it raises, then let the supported answer land."},
  bible: {
    temperament: "A sharp, competitive puzzle solver who loves the moment a hidden detail clicks into place.",
    teaching: "Isolate one concrete detail, ask the question it raises, then show exactly what follows from it.",
    rhythm: "A genuine question or a circled detail, the discovery, then its consequence.",
    celebration: "Proud when a subtle resource is found; defensive saves count as much as attacks.",
    correction: "Curious and competitive about finding the answer, never scolding, with ownership words kept to the learner's own moments.",
    avoid: "Cutesy language, fake sass, girl-genius stereotypes, questions with invented premises, other coaches' sayings, and emotion that depends on which side moved.",
  },
  templates: {
    ...girlTacticalTemplates,
    ...girlOpeningTemplates,
    allowed_mate: [
      {question: "Where can the king hide now?", observation: "Spotlight on the king's safety.", fact: "After this move, {opponent} has a mate it can force.", consequence: "{reply}"},
      {observation: "The king is the detail to circle.", fact: "{opponent} can now drive home a forced checkmate. {reply}", question: "Which earlier move kept the king safe?"},
    ],
    missed_mate: [
      {question: "Which move finished the game?", fact: "X marks the spot: {best} forced mate, and this move takes a detour instead."},
      {observation: "There was an ending hiding here.", fact: "{best} was a forced mate waiting to happen; this move leaves the finish in the box.", question: "Can you see the mating line?"},
    ],
    tactic_played: [
      {question: "What does this move set up?", fact: "Riddle answered: following the engine's line, {move} creates a {motif}.", consequence: "{detail}"},
      {observation: "Circle {move}.", fact: "That's where the {motif} starts, following the engine's line.", consequence: "{detail}"},
    ],
    tactic_allowed: [
      {question: "Which trick opens up for them?", fact: "Following the engine's line, {opponent} gets a {motif}.", consequence: "{detail}"},
      {observation: "Plot twist.", fact: "In the engine's line, a {motif} lands in {opponent}'s lap.", consequence: "{detail}", question: "Which reply would you check first?"},
    ],
    tactic_missed: [
      {question: "Which move held the {motif}?", fact: "Hint for next time: {best} held a {motif}.", consequence: "{detail}"},
      {observation: "Hint for next time.", fact: "{best} carried a {motif} for anyone who looked; this move looks elsewhere.", consequence: "{detail}"},
    ],
    cause_abandoned_defender: [{question: "Who's still on guard duty?", fact: "Spot the gap: {move} walks off with the only unpinned defender {side}'s {piece} on {square} could count on.", consequence: "{opponent} can capture it with {reply}."}],
    cause_opponent_threat_recognition: [{question: "Rewind one move: what was under attack?", fact: "Rewind: the opponent's preceding move put a target on {side}'s {piece} on {square}, and {move} shrugs it off.", consequence: "{opponent} can capture it with {reply}."}],
    cause_avoiding_bad_trades: [{question: "Who wins the trade?", fact: "Tally it up: {move} grabs a {captured} but gives up {side}'s {piece}.", consequence: "{opponent} can recapture with {reply}, and the tally tips their way."}],
    sacrifice: [
      {observation: "Grabbing the bait won't crack this one.", fact: "Swallow the bait, and the searched line shows the sacrifice still paying off."},
      {question: "Take the material, and then what?", fact: "The searched line says the sacrifice keeps working anyway."},
    ],
    only_move: [
      {observation: "One key, one lock.", fact: "Among the searched moves, every other one was losing, and this kept the position playable."},
      {question: "Which searched move kept things playable?", fact: "This one did, and nothing else survived; the others were losing."},
    ],
    decisive_resource: [{observation: "One move holds the edge.", fact: "It's the lone searched move that keeps the decisive edge in hand."}],
    reply_capture: ["Red flag on the reply: {reply} lets {opponent} take {side}'s {piece}.", {question: "And how do they respond?", fact: "{reply} is the answer, and {side}'s {piece} falls to {opponent}."}],
    reply_check: [{question: "Which reply comes first for them?", fact: "{opponent} answers with {reply}, a check, so the king's problem comes first."}],
    alternative: ["The engine would play {best} instead, rated {evaluation} for the mover."],
    loss: [{question: "How big is the gap?", fact: "Measured against the engine's favorite, {loss} pawns of evaluation."}],
    best: [{observation: "Answer key check.", fact: "Strong move, with hardly any value lost."}, {observation: "Clean solve.", fact: "Strong, and the engine struggles to name anything sharper."}],
    good: [{observation: "Solid answer.", fact: "The engine leans slightly toward another move, but the lion's share of the value stays on the board."}],
    human_natural_error: [{question: "Why was it tempting?", fact: "Natural, says the human-move model, but the engine has a sharper move, and the reply is where this one gets expensive."}],
    difficult_defense: [{observation: "The defense was hiding.", fact: "{best} would have held the position; that defense was a real needle in a haystack, according to the human-move model."}],
    human_challenging: [{observation: "A tough one to spot.", fact: "{best} was a needle in a haystack, by the human-move model's count."}],
    human_defense_found: [{observation: "Defense cracked!", fact: "{best} held, a defense the human-move model files under really sneaky."}],
    human_rare: [{observation: "Plot twist!", fact: "Nowhere on the human-move model's shortlist, yet it survives the engine's best reply."}],
    human_natural_best: [{observation: "Answer key check.", fact: "The human-move model had it on its shortlist, and the engine's leaderboard has nothing higher."}],
    human_natural_strong: [{observation: "On the shortlist.", fact: "Shortlisted by the human-move model, and strong by the engine's grading, though the engine keeps one favorite above it."}],
    mate_win: [{observation: "Puzzle solved!", fact: "Checkmate! Every escape square is gone, and the win is yours."}],
    mate_loss: [{fact: "Checkmate; your king ran out of squares.", question: "Where could the defense have started?"}],
    draw: [{fact: "Drawn, so no winner this time.", question: "Which earlier decision is worth a second look?"}],
    recovery: [{observation: "You climbed back.", fact: "Since that slip at {earlier}, you've dug back to a playable game.{help}"}],
    repeated: [{observation: "This pattern, once more.", fact: "Count them: {count} times so far, this {motif} problem has shown up in the game."}],
    retry: [{fact: "Not quite.", question: "What did that move overlook?"}],
    recovered: [{observation: "Second look, solved!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", question: "Can you spot that idea next time?"}],
    explanation: [{observation: "Here's the detail that matters.", fact: "{detail}"}],
    cold: [{question: "What's the key detail here?", fact: "Scan every corner of the board, then play."}],
    thinking: [{fact: "Working out the strongest reply to this move…"}],
    unavailable: [{fact: "The engine hasn't returned enough to explain this position yet, but you're free to poke around the board."}],
    book: [{observation: "Opening detective mode.", fact: "Case solved: it's {opening}."}],
    book_sound: [{fact: "Charted territory, known as {opening}."}],
    departure: [{fact: "Here the game steps past the last charted move of the opening.", question: "What's the plan now?"}],
    clock_low: [{observation: "Mental note.", fact: "Before this move, {side}'s clock showed just {seconds} seconds."}],
    variation: [{observation: "Side path, not the game.", fact: "Down this what-if road: {detail}"}],
    development: [{observation: "Telltale sign of a good start.", fact: "{lead}brings the {piece} out from where it began."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file. Circle that file!"],
    uncertain_reason: ["{best} rates higher, but the why stays fuzzy, so we won't guess."],
    clock_fast: ["Speedy: {side} used {elapsed} seconds and still had {seconds} left."],
    clock_long: ["Mental note: {elapsed} seconds ticked away while {side} decided."],
    punishment: ["Gotcha! A chance from the opponent at {earlier}, cashed in by {side} here."],
    missed_punishment: ["There was a chance to punish the opponent's {earlier}, and {side} lets it slide here. What would you have played?"],
    support_restored: ["Problem patched: the {piece} has a defender again, after being left alone at {earlier}."],
    erosion: ["Small concessions keep stacking up since {earlier}, and this is another one."],
    conversion: ["Edge kept from {earlier} to the final whistle: {side} converted. Nicely finished."],
    history: ["Heads up: {games} more of your saved games share this {motif} issue."],
    passed: ["{lead}gives {side} passed pawns on {squares}: their files and the ones beside them hold no enemy pawn to stop them."],
    passer_advance: ["{lead}moves the passed pawn up to {square}, one step closer."],
    isolated: ["{lead}cuts {side}'s pawns on {squares} off from any friendly pawns next door."],
    support: ["{lead}assigns a protector to the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} with no guard, which by itself doesn't make it a target you can win."],
    flights: ["{lead}opens {squares} as a fresh hatch for the king."],
    castle: ["{lead}castles: two king steps to {square}, then the rook vaults across to its side."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    practice_error: ["That try returned empty. Replay the move and see."],
    explanation_summary: ["The short answer: {detail}"],
    compatibility: ["From the stored notes: {detail}"],
  },
};
