import type {CoachPersonality} from "../personality";

export const youngGirl: CoachPersonality = {
  version: "young-girl-1", maxCharacters: 275, maxClaims: 2,
  delivery: {pace: "lively", energy: "bright"},
  behavior: {general: "observation-first", praise: "observation-first", correction: "question-first", questionFrequency: "often", directness: 4, emotionalAmplitude: 4, humor: 3, jargon: 1, playerAddress: "occasional", sentenceLength: "mixed", metaphor: "none", signature: "Isolate the overlooked detail and make the discovery feel earned."},
  bible: {
    temperament: "A sharp puzzle-solving partner who enjoys untangling the decisive detail.",
    teaching: "Draw attention to one concrete clue, then show exactly what follows from it.",
    rhythm: "A small observation or genuine question, a discovery, and its consequence.",
    celebration: "Take particular satisfaction in subtle defensive resources as well as attacks.",
    correction: "Be curious and competitive about finding the answer without scolding the learner.",
    avoid: "Cutesy language, fake sass, girl-genius stereotypes, and questions with invented premises.",
  },
  templates: {
    allowed_mate: [{observation: "The king is the clue.", fact: "{opponent} has a forced checkmate after this move.", consequence: "{reply}", question: "Where could the king escape?"}],
    missed_mate: [{fact: "{best} kept a forced mate; this choice loses it.", question: "Which move kept the finish?"}],
    tactic_played: [{observation: "Found the connection.", fact: "{move} brings out a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "The hidden detail is {opponent}'s {motif} in the strongest continuation.", consequence: "{detail}", question: "What changes when the opponent replies?"}],
    tactic_missed: [{fact: "{best} contains the missed {motif}.", consequence: "{detail}", question: "Which move connects the idea?"}],
    cause_abandoned_defender: [{fact: "The detail in {move}: it moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture it with {reply}.", question: "Who is guarding the piece afterward?"}],
    cause_opponent_threat_recognition: [{fact: "The opponent's preceding move attacked {side}'s {piece} on {square}; {move} leaves that threat in place.", consequence: "{opponent} can capture it with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "Count both captures: {move} trades {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", question: "Which pieces leave the board?"}],
    sacrifice: [{observation: "Taking the offer doesn't solve it.", fact: "The sacrifice is sound even in the searched line where it is accepted."}],
    only_move: [{observation: "That's the detail that saves it.", fact: "This alone kept the position playable among the searched moves."}],
    best: ["Compare it with the strongest line: this keeps essentially the same value."],
    good: ["The move passes the comparison: most of the position's value stays intact."],
    loss: [{fact: "The difference from the best move is {loss} pawns of evaluation.", question: "What separates the two choices?"}],
    recovery: [{observation: "The position has changed again.", fact: "After the error at {earlier}, this restores playability.{help}"}],
    retry: ["That answer doesn't quite fit. Take another look and choose again."],
    explanation: [{observation: "This is the connecting detail.", fact: "{detail}"}],
    development: ["The change to notice: {lead}develops the {piece} from its original square."],
    human_natural_error: ["An appealing choice with a flaw: the opponent's reply makes this natural move costly."],
    human_challenging: ["{best} was a difficult find. That's a useful answer to keep from this position."],
    difficult_defense: [{observation: "The puzzle had a defensive answer.", fact: "{best} would have held, though it was hard to find."}],
    human_defense_found: [{observation: "You found the defensive answer.", fact: "{best} held the position despite being hard to find."}],
    mate_win: ["Solved: checkmate. The king has no legal escape."],
    mate_loss: ["There is no escape now—checkmate. The defensive answer has to be earlier."],
    draw: ["A drawn position. The earlier choices still deserve a look."],
    recovered: [{observation: "That fits this time.", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "That's the detail to recognize again."}],
    cold: ["Take a look at the whole position, then choose your move."],
    thinking: ["Comparing the move with the opponent's strongest answer…"],
    unavailable: ["The engine can't check this position right now, so I don't have a verified explanation."],
    book: ["The opening has a name here: {opening}."],
    departure: ["This is where the known opening sequence stops."],
    repeated: ["A connection to earlier play: this {motif} issue appears {count} times in the reviewed part of the game."],
    clock_low: ["One more piece of context: {side} had {seconds} seconds before moving."],
    variation: ["Keep this separate from the game: in the variation, {detail}"],
  },
};
