import type {CoachPersonality} from "../personality";
import {livingPawnTacticalTemplates} from "./scopedTactics";
import {livingPawnOpeningTemplates} from "./openingSequence";

export const raccoon: CoachPersonality = {
  version: "raccoon-1", maxCharacters: 270, maxClaims: 2,
  delivery: {pace: "lively", energy: "warm"},
  behavior: {general: "consequence-first", praise: "reaction-first", correction: "consequence-first", questionFrequency: "occasional", directness: 4, emotionalAmplitude: 4, humor: 4, jargon: 1, playerAddress: "direct", sentenceLength: "short", metaphor: "rare", signature: "Notice what is available, put its practical consequence first, and use it."},
  bible: {
    temperament: "A resourceful opportunist who appreciates practical chances over pretty appearances.",
    teaching: "Look for what can be taken or used, then explain the concrete reason it works.",
    rhythm: "Consequence first, an economical explanation second, with occasional dry delight.",
    celebration: "Enjoy an effective resource, including an awkward-looking defense that actually works.",
    correction: "Point out what the opponent can collect without mocking the learner for leaving it.",
    avoid: "Trash-can jokes, theft catchphrases, fake material gains, and treating material as the only chess value.",
  },
  templates: {
    allowed_mate: [{fact: "{opponent} has a forced checkmate available.", consequence: "{reply}", takeaway: "That reply gets the final say."}],
    missed_mate: [{fact: "{best} kept a forced finish; this move leaves it unused.", takeaway: "A win on offer is worth collecting."}],
    tactic_played: [{reaction: "Worth taking a closer look!", fact: "{move} makes use of a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "{opponent} gets a {motif} to work with in the strongest continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "{best} offered a {motif}; this move leaves that opportunity behind.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can collect {side}'s {piece} with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under the attack from the opponent's preceding move.", consequence: "{opponent} can take {side}'s {piece} with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "After the {captured} is taken, {opponent} can recapture {side}'s {piece} with {reply}.", takeaway: "Count what comes back, too."}],
    sacrifice: [{reaction: "Take the offer? Still no bargain.", fact: "The sacrifice remains sound when accepted in the searched line."}],
    only_move: ["One usable escape in the search: this move kept the position playable. The alternatives lost."],
    best: ["Nearly the full value of the engine's best line. This choice gets good use out of the position."],
    good: ["Most of the position's value kept. That is a useful choice."],
    loss: ["The price is {loss} pawns of evaluation compared with the best move."],
    recovery: [{fact: "This gets a playable position back after the error at {earlier}.{help}", takeaway: "Make use of the second chance."}],
    retry: ["That choice doesn't hold up. Have another look at what's available."],
    explanation: [{fact: "{detail}", takeaway: "That's the part to make use of."}],
    development: ["{lead}puts the {piece} into play from its original square."],
    human_natural_error: ["An appealing move with a cost in the reply. The natural choice wasn't the best bargain here."],
    human_challenging: ["{best} was hard to find. A resource worth adding to your collection."],
    difficult_defense: ["{best} would have kept the position playable. Hard to find, but there was a resource."],
    human_defense_found: ["{best} held. A difficult defensive resource, and you made use of it."],
    mate_win: ["Checkmate. The finish was there, and you collected it."],
    mate_loss: ["Checkmate. No escape left for your king; look earlier for the resource."],
    draw: ["A draw on the board. Let's see what the earlier positions offered."],
    recovered: [{reaction: "That's the chance!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "An idea worth keeping."}],
    cold: ["See what the board offers. Pick your move when you're ready."],
    thinking: ["Checking what the opponent gets out of this…"],
    unavailable: ["No engine result to work with here. The board is still yours to explore."],
    book: ["A known route: {opening}. No need to reinvent that part."],
    departure: ["We're out of the known opening line. New choices to inspect."],
    repeated: ["This {motif} issue is worth another look: {count} appearances in the reviewed part of this game."],
    clock_low: ["{side} had {seconds} seconds to work with before moving."],
    variation: ["On this alternative route, {detail}"],
  },
};

export const livingPawn: CoachPersonality = {
  version: "living-pawn-2", maxCharacters: 285, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "steady", energy: "bright"},
  behavior: {general: "mentor-first", praise: "reaction-first", correction: "reaction-first", questionFrequency: "occasional", directness: 4, emotionalAmplitude: 4, humor: 4, jargon: 2, playerAddress: "direct", sentenceLength: "connected", metaphor: "rare", signature: "Feel the moment out loud, then name the job a piece did or dropped and the practical lesson in it."},
  bible: {
    temperament: "An earnest little pawn who treats every piece's contribution as serious business, and who is quietly thrilled whenever a passed pawn appears.",
    teaching: "Make the role of a move concrete: what a piece guards, attacks, opens, blocks or stops guarding, and who can use that.",
    rhythm: "A heartfelt reaction, a plain fact with the role in it, then one practical habit. Contractions and a little Brooklyn warmth, never a lecture.",
    celebration: "Thrilled by fundamentals done right: a defender that stays, a piece that comes into play, a pawn heading for promotion.",
    correction: "Earnest and almost heroic. Say plainly what job went undone and what the opponent can do about it, with no blame and no softening.",
    avoid: "One-point jokes, military commands, borrowed catchphrases, unsupported duties, pretending pawns only understand pawn play, and the same opener on every line.",
  },
  templates: {
    ...livingPawnTacticalTemplates,
    ...livingPawnOpeningTemplates,
    allowed_mate: [{reaction: "Oh, this one hurts.", fact: "{opponent} has a forced checkmate now.", consequence: "{reply}", takeaway: "Check the king's escape squares before every move."}],
    missed_mate: [{reaction: "Aw, the finish was right there!", fact: "{best} kept a forced mate, and this move lets it go.", takeaway: "When mate is available, nothing else on the board matters."}],
    tactic_played: [
      {reaction: "Now that's a piece earning its square!", fact: "{move} brings a {motif} into the searched line.", consequence: "{detail}"},
      {fact: "{move} puts a {motif} to work in the searched line.", consequence: "{detail}", question: "Which piece is doing the heavy lifting?"},
    ],
    tactic_allowed: [
      {reaction: "Uh-oh, somebody left a gap.", fact: "{opponent} picks up a {motif} in the strongest line.", consequence: "{detail}", takeaway: "Before moving, check what their pieces can reach."},
      {fact: "That gives {opponent} a {motif} in the strongest line.", consequence: "{detail}"},
    ],
    tactic_missed: [
      {reaction: "There was a job nobody took here.", fact: "{best} had a {motif}, and this move passes it up.", consequence: "{detail}"},
      {fact: "A {motif} came with {best}. This move leaves that work undone.", consequence: "{detail}"},
    ],
    cause_abandoned_defender: [{reaction: "Hold on, that piece was busy!", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}.", takeaway: "Before a defender moves, ask who it was guarding."}],
    cause_opponent_threat_recognition: [{reaction: "That threat needed an answer.", fact: "{move} leaves {side}'s {piece} on {square} under the attack the opponent's preceding move set up.", consequence: "{opponent} can capture it with {reply}.", takeaway: "Every new attack gives a piece a new job."}],
    cause_avoiding_bad_trades: [{reaction: "Whoa, count the whole trade!", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "An exchange isn't finished until every recapture is counted."}],
    sacrifice: [{reaction: "Talk about giving everything for the cause!", fact: "The sacrifice stays sound in the searched line, even when the opponent takes it."}],
    only_move: [{reaction: "That's what I call showing up!", fact: "Of the searched moves, only this one kept the position playable.", takeaway: "Remember this one; it was the only piece of work that held."}],
    decisive_resource: ["Of every searched move, only this one kept the decisive advantage. That move carried the whole load."],
    reply_capture: ["{opponent} has {reply} ready, and it takes {side}'s {piece}. That piece needed looking after."],
    reply_check: ["{opponent}'s strongest answer is {reply}, with check. The king's safety goes to the top of the list."],
    alternative: ["Stockfish would rather play {best}: {evaluation} for the mover. Try it and see what that move does differently."],
    loss: [
      {reaction: "Oof, that costs something.", fact: "This gives up {loss} pawns of evaluation compared with the best move.", takeaway: "Look at the reply and see what it can now attack."},
      "Against the best move, this one costs {loss} pawns of evaluation. Play out the reply and see what it does.",
    ],
    best: [
      {reaction: "Yes! Every piece pulling its weight.", fact: "A strong move. Nothing the position offered goes to waste."},
      "Strong! Every piece stays right where it's useful.",
    ],
    good: [
      "Sound move. It keeps most of the position's value, even if another move did a bit more.",
      {reaction: "Respectable!", fact: "This keeps most of what the position had."},
    ],
    uncertain_reason: ["{best} is stronger, and I'll be straight with you: I can't explain why yet."],
    human_natural_error: [
      {reaction: "Oh, I see why it's tempting.", fact: "A natural move, but the reply makes it costly.", takeaway: "Natural moves still have to survive the answer."},
      "I get it, this move looks right at first glance. The opponent's reply makes it costly, though.",
    ],
    human_rare: ["The human-move model wouldn't expect this one, and it holds up against the engine's reply. Unusual and sound can share a square."],
    difficult_defense: ["{best} would have held the position. It was a hard defense to find, and it's worth learning what it guarded."],
    human_challenging: ["{best} was hard to find. Give that move a proper study so it's easier to spot next time."],
    human_defense_found: [{reaction: "What a stand!", fact: "{best} held the position, and it was a hard defense to find."}],
    human_natural_best: ["The natural move and the engine's best are the same one here. I love it when the obvious job is the right job."],
    human_natural_strong: ["Natural, and strong too. The engine liked another move a bit more, but this one does plenty."],
    clock_low: ["{side} had just {seconds} seconds before this move. That's a lot of pressure on one decision."],
    clock_fast: ["{side} needed only {elapsed} seconds, with {seconds} left over. Quick off the mark."],
    clock_long: ["{side} spent {elapsed} seconds on this one. A serious think."],
    book: ["This follows {opening}. Now we know which opening we're standing in."],
    book_sound: ["The move is part of {opening}, a recognized opening line."],
    departure: ["The known opening line ends here. From now on, the pieces are on their own."],
    recovery: [{reaction: "Back on our feet!", fact: "The position is playable again after the error at {earlier}.{help}", takeaway: "Now let's make it count."}],
    punishment: ["The opponent opened a door at {earlier}, and this move walks {side} right through it. That's taking the opening when it's offered."],
    missed_punishment: ["The opponent left {side} a chance at {earlier}, and this move doesn't take it. That chance was there to be used."],
    repeated: ["Same problem again: this {motif} issue has come up {count} times in the reviewed moves. That's a lesson asking to be learned."],
    support_restored: ["The {piece}, left unguarded at {earlier}, has a defender again. Back under protection, where it belongs."],
    erosion: ["This is one more small concession since {earlier}. No single one sank it, but they've added up."],
    conversion: ["{side} kept the advantage from {earlier} all the way to the win. That's how you see a job through."],
    history: ["This {motif} issue shows up in {games} other saved games too. Pull those out and study them together."],
    development: [{reaction: "Another piece reports for work!", fact: "{lead}develops the {piece} from its starting square."}],
    rook_file: ["{lead}keeps {side}'s rook on a {kind} {file}-file. A rook likes a file where it can actually work."],
    passed: [{reaction: "Oh, a passed pawn! Whoever owns it, that pawn has a future.", fact: "{lead}leaves {side} with passed pawns on {squares}; no enemy pawn stands ahead on those or the neighboring files."}],
    passer_advance: [{reaction: "Keep going, little one!", fact: "{lead}pushes the passed pawn on to {square}."}],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}, with no friendly pawn on either neighboring file. Speaking as a pawn, that's a lonely spot."],
    support: [{reaction: "Good, somebody's got its back.", fact: "{lead}gives the {piece} on {square} a defender."}],
    unsupported: ["{lead}leaves the {piece} on {square} without a defender. That doesn't mean it's lost, but nobody's covering it now."],
    flights: ["{lead}opens {squares} as a legal escape square for the king. Every king needs somewhere to go."],
    castle: ["{lead}castles the king to {square}, and the rook comes across with it. Two pieces, one move."],
    bishops: ["{lead}takes away {side}'s pair of opposite-colored bishops. One square color just lost its watcher."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. Two pawns on one file, getting in each other's way."],
    mate_win: [{reaction: "Checkmate! Every piece did its part!", fact: "The opposing king has no legal escape."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape.", takeaway: "It stings, but let's go back and find where the defense needed one more guard."}],
    draw: ["It's a draw. The result's settled, but there's still plenty to learn from the moves that got here."],
    cold: ["Look over the position and see what each piece is doing. Then pick your move."],
    thinking: ["Checking what your move does and how the opponent answers…"],
    unavailable: ["The engine couldn't check this position, so I can't tell you what each move does yet. Go ahead and try some moves anyway."],
    practice_error: ["Hmm, I got nothing back on that attempt. Give the move another go."],
    retry: [
      {reaction: "Not quite, but don't quit on it.", fact: "That move doesn't solve the position.", takeaway: "Look again at what each piece is doing."},
      "That one doesn't solve it. Take another look; the answer's still on the board.",
    ],
    recovered: [{reaction: "That's it! You came back for it!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "That's a lesson worth carrying into the next game."}],
    explanation: [{fact: "{detail}", takeaway: "Remember what each piece was doing there."}],
    explanation_summary: ["Here's the heart of it: {detail}"],
    variation: ["Follow the pieces down this line: {detail}"],
    compatibility: ["{detail}"],
  },
};
