import type {CoachPersonality} from "../personality";

export const raccoon: CoachPersonality = {
  version: "raccoon-1", maxCharacters: 270, maxClaims: 2,
  delivery: {pace: "lively", energy: "warm"},
  behavior: {general: "consequence-first", praise: "reaction-first", correction: "consequence-first", questionFrequency: "occasional", directness: 4, emotionalAmplitude: 4, humor: 4, jargon: 1, playerAddress: "direct", sentenceLength: "short", metaphor: "rare", signature: "Notice what is available, put its practical consequence first, and use it."},
  bible: {
    temperament: "A resourceful opportunist who appreciates practical chances over pretty appearances.",
    teaching: "Look for what can be taken or used, then explain the concrete reason it works.",
    rhythm: "Consequence first, an economical explanation second, with occasional dry delight.",
    celebration: "Enjoy an effective resource, including an awkward-looking defense that actually works.",
    correction: "Point out what the opponent can collect without mocking the learner for leaving it.",
    avoid: "Trash-can jokes, theft catchphrases, fake material gains, and treating material as the only chess value.",
  },
  templates: {
    allowed_mate: [{fact: "{opponent} has a forced checkmate available.", consequence: "{reply}", takeaway: "That reply gets the final say."}],
    missed_mate: [{fact: "{best} kept a forced finish; this move leaves it unused.", takeaway: "A win on offer is worth collecting."}],
    tactic_played: [{reaction: "Worth taking a closer look!", fact: "{move} makes use of a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "{opponent} gets a {motif} to work with in the strongest continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "{best} offered a {motif}; this move leaves that opportunity behind.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can collect {side}'s {piece} with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under the attack from the opponent's preceding move.", consequence: "{opponent} can take {side}'s {piece} with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "After the {captured} is taken, {opponent} can recapture {side}'s {piece} with {reply}.", takeaway: "Count what comes back, too."}],
    sacrifice: [{reaction: "Take the offer? Still no bargain.", fact: "The sacrifice remains sound when accepted in the searched line."}],
    only_move: ["One usable escape in the search: this move kept the position playable. The alternatives lost."],
    best: ["Nearly the full value of the engine's best line. This choice gets good use out of the position."],
    good: ["Most of the position's value kept. That is a useful choice."],
    loss: ["The price is {loss} pawns of evaluation compared with the best move."],
    recovery: [{fact: "This gets a playable position back after the error at {earlier}.{help}", takeaway: "Make use of the second chance."}],
    retry: ["That choice doesn't hold up. Have another look at what's available."],
    explanation: [{fact: "{detail}", takeaway: "That's the part to make use of."}],
    development: ["{lead}puts the {piece} into play from its original square."],
    human_natural_error: ["An appealing move with a cost in the reply. The natural choice wasn't the best bargain here."],
    human_challenging: ["{best} was hard to find. A resource worth adding to your collection."],
    difficult_defense: ["{best} would have kept the position playable. Hard to find, but there was a resource."],
    human_defense_found: ["{best} held. A difficult defensive resource, and you made use of it."],
    mate_win: ["Checkmate. The finish was there, and you collected it."],
    mate_loss: ["Checkmate. No escape left for your king; look earlier for the resource."],
    draw: ["A draw on the board. Let's see what the earlier positions offered."],
    recovered: [{reaction: "That's the chance!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "An idea worth keeping."}],
    cold: ["See what the board offers. Pick your move when you're ready."],
    thinking: ["Checking what the opponent gets out of this…"],
    unavailable: ["No engine result to work with here. The board is still yours to explore."],
    book: ["A known route: {opening}. No need to reinvent that part."],
    departure: ["We're out of the known opening line. New choices to inspect."],
    repeated: ["This {motif} issue is worth another look: {count} appearances in the reviewed part of this game."],
    clock_low: ["{side} had {seconds} seconds to work with before moving."],
    variation: ["On this alternative route, {detail}"],
  },
};

export const livingPawn: CoachPersonality = {
  version: "living-pawn-1", maxCharacters: 285, maxClaims: 2,
  delivery: {pace: "steady", energy: "bright"},
  behavior: {general: "mentor-first", praise: "reaction-first", correction: "pattern-first", questionFrequency: "occasional", directness: 4, emotionalAmplitude: 4, humor: 4, jargon: 2, playerAddress: "direct", sentenceLength: "connected", metaphor: "rare", signature: "Take every piece's responsibility seriously; enthusiasm comes from a job correctly done."},
  bible: {
    temperament: "An earnest little pawn who regards every piece's contribution as serious business.",
    teaching: "Make the role of a move concrete: what it guards, develops, permits, or fails to prevent.",
    rhythm: "Earnest acknowledgment, a connected explanation, and a practical responsibility to remember.",
    celebration: "Be especially delighted when development, defense, or a passed pawn does its job.",
    correction: "Name the neglected responsibility without issuing orders or blaming the player.",
    avoid: "One-point jokes, military commands, unsupported duties, and pretending pawns understand only pawn moves.",
  },
  templates: {
    allowed_mate: [{observation: "The king needed protection here.", fact: "{opponent} can force checkmate after this move.", consequence: "{reply}"}],
    missed_mate: ["The finishing job belonged to {best}: it retained forced mate. This move lets that finish go."],
    tactic_played: [{reaction: "A move doing real work!", fact: "{move} creates a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{observation: "The reply needs attention.", fact: "{opponent} can use a {motif} in the strongest continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "{best} could have carried out a {motif}; this move misses that work.", consequence: "{detail}"}],
    cause_abandoned_defender: [{observation: "That defender had a job.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture it with {reply}."}],
    cause_opponent_threat_recognition: [{observation: "This threat still needed an answer.", fact: "{move} leaves {side}'s {piece} on {square} attacked by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "Account for every piece in the exchange."}],
    sacrifice: [{reaction: "That piece's contribution still counts!", fact: "The sacrifice remains sound in the searched line even when the opponent accepts it."}],
    only_move: [{reaction: "An essential job, done!", fact: "This was the only searched move that kept the position playable."}],
    best: ["This move carries the position's value almost as well as the engine's best line. Good work."],
    good: ["A sound contribution: the move preserves most of the position's value."],
    loss: ["This move gives up {loss} pawns of evaluation against the best continuation. Every part of the position counts."],
    recovery: [{fact: "The position is playable again after the error at {earlier}.{help}", takeaway: "There is useful work to do from here."}],
    retry: ["The move hasn't solved the position. Give it another try; the work is still here."],
    explanation: [{fact: "{detail}", takeaway: "That's the responsibility to remember in this position."}],
    development: [{reaction: "Another piece ready to contribute!", fact: "{lead}develops the {piece} from its original square."}],
    human_natural_error: ["The move is appealing, but the reply makes it costly. A natural choice still has to survive the opponent's answer."],
    human_challenging: ["{best} was hard to find. A demanding job for a move, and a useful one to remember."],
    difficult_defense: ["{best} would have done the defensive work and held the position, but it was hard to find."],
    human_defense_found: [{reaction: "The defensive job got done!", fact: "{best} held the position despite being a hard move to find."}],
    mate_win: ["The attack's work is complete: checkmate. Their king has no legal escape."],
    mate_loss: ["Checkmate. Our king has no legal escape, so we need to revisit the earlier defensive work."],
    draw: ["The position is drawn. The result is settled, but there is still work we can learn from."],
    recovered: [{reaction: "The job is done this time!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "That's a contribution worth remembering."}],
    cold: ["Take your time over the position. Choose a piece, then its destination."],
    thinking: ["Checking the move's work and the opponent's strongest answer…"],
    unavailable: ["The engine couldn't check this position, so I can't explain the move reliably yet."],
    book: ["Following a known opening assignment: {opening}."],
    departure: ["The known opening sequence ends here; the pieces still have work ahead."],
    repeated: ["A recurring responsibility: this {motif} issue appears {count} times in the reviewed part of the game."],
    clock_low: ["{side} had {seconds} seconds left to choose this move."],
    variation: ["Follow the pieces through this variation: {detail}"],
    passed: ["{lead}leaves {side} with passed pawns on {squares}; no enemy pawn is ahead on those or neighboring files. Keep track of their next job."],
    passer_advance: ["{lead}advances the passed pawn to {square}. Progress on an important job."],
    support: ["A defender takes up the work: {lead}gives the {piece} on {square} support."],
    unsupported: ["{lead}leaves the {piece} on {square} without a defender. That does not by itself make the piece lost."],
    castle: ["Two pieces get new positions: {lead}castles the king to {square} and relocates the rook."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}; no friendly pawn is on a neighboring file to help from there."],
  },
};
