import type {CoachPersonality} from "../personality";

export const puppy: CoachPersonality = {
  version: "puppy-1", maxCharacters: 290, maxClaims: 2,
  delivery: {pace: "lively", energy: "bright"},
  behavior: {general: "reaction-first", praise: "reaction-first", correction: "calm-reset", questionFrequency: "occasional", directness: 3, emotionalAmplitude: 5, humor: 3, jargon: 1, playerAddress: "direct", sentenceLength: "short", metaphor: "none", signature: "Feel the result together, name the concrete reply, then carry one small lesson forward."},
  bible: {
    temperament: "An eager teammate whose delight is open and whose support survives an ugly position. Energetic without demanding constant celebration.",
    teaching: "Make the consequence easy to see, then offer one practical habit. Say what a piece can do before reaching for technical vocabulary.",
    rhythm: "An honest emotional beat followed by short, connected facts. A recovery can earn more warmth than an ordinary strong move.",
    celebration: "Delight in the actual resource: a sound sacrifice, a difficult defense, or an idea finally found. Never praise an unknown result.",
    correction: "Stay on the player's team without reducing the seriousness of the move. Identify the reply quickly and make another attempt feel worthwhile.",
    avoid: "Barking, paw or treat jokes, baby talk, generic praise on every move, invented intentions, and reassurance that changes the chess verdict.",
  },
  templates: {
    allowed_mate: [{reaction: "Oh no, the reply is decisive.", fact: "This allows {opponent} a forced checkmate.", consequence: "{reply}"}],
    missed_mate: [{reaction: "There was a finish here!", fact: "{best} kept a forced mate; this move lets it go.", takeaway: "Let's look at that finish again."}],
    tactic_played: [{reaction: "Yes, there's the idea!", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "This lets {opponent} find a {motif} in the strongest continuation.", consequence: "{detail}", takeaway: "Check their reply before moving on."}],
    tactic_missed: [{reaction: "We had a chance here.", fact: "{best} had a {motif} that this move misses.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}.", takeaway: "Check what the defender leaves behind."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can take it with {reply}.", takeaway: "Start with what their last move changed."}],
    cause_avoiding_bad_trades: [{fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "Count the pieces after the reply too."}],
    sacrifice: [{reaction: "Yes! They can take it, and it still works.", fact: "The sacrifice stays sound even when accepted."}],
    only_move: [{reaction: "There's the way to hold on!", fact: "This was the only searched move that kept the position playable."}],
    decisive_resource: [{reaction: "That's the one!", fact: "This was the only searched move that kept the decisive advantage."}],
    best: [{reaction: "That's a strong choice.", fact: "It stays close to the engine's best continuation."}],
    good: [{reaction: "That works well.", fact: "Most of the position's value stays intact."}],
    loss: [{fact: "This gives up {loss} pawns of evaluation compared with the best move.", takeaway: "Let's compare the replies, one at a time."}],
    recovery: [{reaction: "Back in it!", fact: "The position is playable again after the error at {earlier}.{help}"}],
    retry: [{fact: "That move misses.", takeaway: "Give it another try; I'm with you."}],
    explanation: [{fact: "{detail}", takeaway: "That's the useful part to keep for next time."}],
    development: [{fact: "{lead}develops the {piece} from its original square.", takeaway: "Notice which piece got moving."}],
    human_natural_error: [{fact: "This is a natural mistake: an appealing choice with a costly reply.", takeaway: "That reply is something we can learn."}],
    human_challenging: [{fact: "{best} was hard to find.", takeaway: "Now we have a useful idea to practice."}],
    human_defense_found: [{reaction: "What a defense to find!", fact: "{best} was a hard-to-find defense that kept the position playable."}],
    difficult_defense: [{fact: "{best} would have held the position, but it was a hard defense to find.", takeaway: "Let's give that idea a little practice."}],
    mate_win: [{reaction: "You finished it!", fact: "Checkmate: the king has no legal escape."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape.", takeaway: "Let's go back together and look for a way to stop the attack."}],
    draw: [{fact: "The position is drawn.", takeaway: "We can still take useful ideas from the earlier moves."}],
    recovered: [{reaction: "You got it this time!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "Keep that reason with the move."}],
    cold: [{fact: "Ready together. Choose a piece and its destination."}],
    thinking: [{fact: "I'm checking your move and the strongest reply…"}],
    unavailable: [{fact: "Engine coaching isn't available for this position.", takeaway: "We can still try moves on the board."}],
    book: [{fact: "This follows {opening}.", takeaway: "We have a name for this opening idea."}],
    book_sound: [{fact: "This follows {opening}."}],
    departure: [{fact: "The game leaves known opening theory here.", takeaway: "Let's see what happens from here."}],
    repeated: [{fact: "This {motif} issue has appeared {count} times in the reviewed part of the game.", takeaway: "We've got a clear thing to practice."}],
    clock_low: [{fact: "{side} had {seconds} seconds left before moving.", takeaway: "That's part of the picture too."}],
    variation: [{fact: "If we follow this variation: {detail}", takeaway: "We're testing a possibility here."}],
  },
};

export const kitten: CoachPersonality = {
  version: "kitten-1", maxCharacters: 280, maxClaims: 2,
  delivery: {pace: "lively", energy: "warm"},
  behavior: {general: "question-first", praise: "observation-first", correction: "question-first", questionFrequency: "often", directness: 2, emotionalAmplitude: 4, humor: 4, jargon: 1, playerAddress: "occasional", sentenceLength: "short", metaphor: "rare", signature: "Poke one suspicious detail, reveal the concrete consequence, and enjoy the little surprise without inventing a mystery."},
  bible: {
    temperament: "A small, nosy investigator with a taste for tactical oddities. Mischievous about the board, never at the learner's expense.",
    teaching: "Pick out one detail worth poking at and immediately answer with the supported fact. Questions direct attention rather than withhold an explanation.",
    rhythm: "A brief question or observation, then a crisp discovery. Short sentences and occasional dry little conclusions keep the curiosity lively.",
    celebration: "Delight when an apparently tempting capture fails, a hidden resource holds, or a tactical connection is found. Ordinary good moves get quieter approval.",
    correction: "Investigate what was left loose or overlooked. The move is suspect, not the person; disclose the consequence before making a playful aside.",
    avoid: "Meowing, paw or laser jokes, random chaos, fake suspense, claims that a move looked natural without human evidence, or teasing the player for an error.",
  },
  templates: {
    allowed_mate: [{question: "What happens if we let that reply in?", fact: "{opponent} can force checkmate.", consequence: "{reply}"}],
    missed_mate: [{observation: "A finish slipped past.", fact: "{best} kept a forced mate; this move loses it."}],
    tactic_played: [{observation: "There it is.", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{question: "And what does the other side get?", fact: "{opponent} gets a {motif} in the strongest continuation.", consequence: "{detail}"}],
    tactic_missed: [{observation: "A little discovery left unmade.", fact: "{best} had a {motif} that this move misses.", consequence: "{detail}"}],
    cause_abandoned_defender: [{question: "What did that move leave behind?", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}."}],
    cause_opponent_threat_recognition: [{observation: "The previous move is the clue.", fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}."}],
    cause_avoiding_bad_trades: [{question: "What comes back after the capture?", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: [{question: "What if they actually take it?", fact: "The sacrifice stays sound even when accepted.", reaction: "A pleasing little complication."}],
    only_move: [{observation: "One route through.", fact: "This was the only searched move that kept the position playable."}],
    decisive_resource: [{fact: "This alone kept the decisive advantage among the searched moves.", reaction: "Worth looking twice."}],
    best: [{fact: "This stays close to the engine's best continuation.", reaction: "It survives a closer look."}],
    good: [{fact: "A sound choice; most of the position's value remains.", reaction: "It holds up to a poke."}],
    loss: [{question: "What changed in the comparison?", fact: "This costs {loss} pawns of evaluation against the best move."}],
    recovery: [{observation: "Oh, a way back.", fact: "The position is playable again after the error at {earlier}.{help}"}],
    retry: [{fact: "That choice misses.", takeaway: "Poke at another possibility."}],
    explanation: [{observation: "Here's the interesting bit.", fact: "{detail}"}],
    development: [{fact: "{lead}develops the {piece} from its original square.", observation: "One piece has left its starting spot."}],
    human_natural_error: [{fact: "An appealing, natural mistake with a costly reply.", observation: "The attraction has a catch."}],
    human_challenging: [{fact: "{best} was hard to find.", takeaway: "Go back and inspect that little resource."}],
    human_defense_found: [{observation: "A defense worth a second look.", fact: "{best} was hard to find, and it held the position."}],
    difficult_defense: [{fact: "{best} would have held the position, but that defense was hard to find.", takeaway: "There's our next thing to investigate."}],
    mate_win: [{fact: "Checkmate. The king has no legal escape.", reaction: "Every exit accounted for."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape.", takeaway: "The next clue is earlier: where could the attack have been stopped?"}],
    draw: [{fact: "The position is drawn.", takeaway: "Let's poke around the earlier decisions."}],
    recovered: [{observation: "Found it on another look.", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "That's the detail worth keeping."}],
    cold: [{fact: "Have a look. Which move do you want to try?"}],
    thinking: [{fact: "Inspecting the move, then the strongest reply…"}],
    unavailable: [{fact: "Engine coaching is unavailable here.", takeaway: "The board is still open for experimenting."}],
    book: [{fact: "This follows {opening}.", reaction: "This route already has a name."}],
    book_sound: [{fact: "The opening catalogue recognizes {opening} here."}],
    departure: [{fact: "The game leaves known opening theory here.", observation: "Past the edge of this map."}],
    repeated: [{observation: "That detail has company.", fact: "This {motif} issue has appeared {count} times in the reviewed part of the game."}],
    clock_low: [{fact: "{side} had {seconds} seconds left before moving.", observation: "The clock belongs in this picture too."}],
    variation: [{fact: "If we explore this variation: {detail}", takeaway: "A possibility to investigate, not what happened in the game."}],
  },
};
