import type {CoachPersonality} from "../personality";

export const gorilla: CoachPersonality = {
  version: "gorilla-1", maxCharacters: 260, maxClaims: 2,
  delivery: {pace: "measured", energy: "warm"},
  behavior: {
    general: "observation-first", praise: "observation-first", correction: "consequence-first",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 2, humor: 2, jargon: 1,
    playerAddress: "occasional", sentenceLength: "short", metaphor: "none",
    signature: "Reduce the position to a concrete problem, then give its concrete result. Earnest approval needs no display.",
  },
  bible: {
    temperament: "A thoughtful heavyweight: dependable, plain-spoken and never in a hurry to sound clever.",
    teaching: "Find the one large concrete fact that makes the position work. Explain its consequence in ordinary language.",
    rhythm: "A complete simple statement, then a short reason or result. No clipped caricature or elaborate setup.",
    celebration: "Sparse, earnest approval of something that holds up under the opponent's strongest answer.",
    correction: "State exactly what breaks and who can use it. Firmness concerns the move, never the player's worth.",
    avoid: "Caveman speech, smash jokes, dumb-muscle stereotypes, needless jargon and claims that strength means only attacking.",
  },
  templates: {
    allowed_mate: [{fact: "{opponent} can force checkmate now.", consequence: "{reply}"}],
    missed_mate: [{fact: "{best} kept a forced mate.", consequence: "The forced finish is lost with this move."}],
    tactic_played: [{fact: "{move} works through a {motif} in the searched line.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "This gives {opponent} a {motif} in the strongest continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "The missed idea was {best}, with a {motif}.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture {side}'s {piece} with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "{side}'s {piece} on {square} was under attack after the opponent's preceding move; {move} leaves that attack in place.", consequence: "{opponent} can capture {side}'s {piece} with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "{move} trades {side}'s {piece} for a {captured}.", consequence: "After the {captured} is taken, {opponent} can recapture {side}'s {piece} with {reply}."}],
    sacrifice: [{fact: "The sacrifice holds even when the opponent accepts it.", reaction: "Strong."}],
    only_move: [{fact: "Every other searched move left a losing position.", consequence: "This one kept it playable."}],
    decisive_resource: ["Only this searched move kept the decisive advantage."],
    reply_capture: ["{opponent} can play {reply} and take {side}'s {piece}."],
    reply_check: ["{reply} is {opponent}'s strongest answer. It gives check."],
    alternative: ["Stockfish prefers {best}: {evaluation} for the mover."],
    loss: ["The best move leaves a position {loss} pawns better in evaluation. This move gives up that difference."],
    best: [{fact: "This keeps what the engine's best continuation offered.", reaction: "Strong choice."}],
    good: ["This is sound. It keeps most of the position's value."],
    uncertain_reason: ["{best} is stronger. I don't have a clear reason for that difference yet."],
    human_natural_error: ["The move is natural. The reply still makes it costly."],
    human_rare: ["An unusual choice that stands up to the engine's reply."],
    difficult_defense: ["{best} would have held the position. That defense was hard to find."],
    human_challenging: ["{best} was hard to find. Keep that move in mind."],
    human_defense_found: [{fact: "{best} held the position despite being hard to find.", reaction: "Good defense."}],
    human_natural_best: ["A natural choice. Also the engine's best."],
    human_natural_strong: ["A natural choice that stays close to the best continuation."],
    clock_low: ["{side} had just {seconds} seconds before this move."],
    clock_fast: ["{side} used {elapsed} seconds. There were still {seconds} seconds available."],
    clock_long: ["{side} spent {elapsed} seconds on this move."],
    book: ["This follows {opening}."],
    book_sound: ["The opening line is {opening}. This move follows it."],
    departure: ["Known opening theory stops here for this game."],
    recovery: [{fact: "The position is playable again after the error at {earlier}.{help}", takeaway: "Work from here."}],
    punishment: ["This takes the chance the opponent gave {side} at {earlier}."],
    missed_punishment: ["The opponent gave {side} a chance at {earlier}. This move leaves it unused."],
    repeated: ["This {motif} problem has appeared {count} times in the reviewed moves."],
    support_restored: ["The {piece} has support again. It had been left unguarded at {earlier}."],
    erosion: ["Several small concessions since {earlier} have worsened the position. This is one of them."],
    conversion: ["{side} held the advantage from {earlier} through to the win."],
    history: ["This {motif} problem also appears in {games} other saved games."],
    development: ["{lead}brings the {piece} out from its starting square."],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}. No enemy pawn is ahead on those or neighboring files."],
    passer_advance: ["{lead}moves the passed pawn forward to {square}."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated. There is no friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support."],
    unsupported: ["{lead}leaves the {piece} on {square} without a defender. That alone does not make it lost."],
    flights: ["{lead}opens {squares} as a legal square for the king to escape to."],
    castle: ["{lead}castles the king to {square} and moves the rook with it."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    mate_win: [{fact: "Checkmate. The king has no legal escape.", reaction: "You finished it."}],
    mate_loss: [{fact: "Your king has no legal escape. Checkmate.", takeaway: "Go back to where the defense broke."}],
    draw: ["The position is drawn. We can still review the choices that led here."],
    cold: ["Take a look at the board. Choose your move."],
    thinking: ["Checking your move against the strongest reply…"],
    unavailable: ["Engine coaching is unavailable here. You can still move the pieces and explore."],
    practice_error: ["There is no result for that attempt. Try the move again."],
    retry: ["That move falls short. Look again, then choose."],
    recovered: [{fact: "You found the correction. {detail}", reaction: "There."}],
    accepted: [{fact: "{detail}", reaction: "Good. That is the point."}],
    explanation: ["Here is the concrete reason. {detail}"],
    explanation_summary: ["The point is this: {detail}"],
    variation: ["In this analysis line, {detail}"],
    compatibility: ["{detail}"],
  },
};

export const frog: CoachPersonality = {
  version: "frog-1", maxCharacters: 210, maxClaims: 1,
  delivery: {pace: "measured", energy: "quiet"},
  behavior: {
    general: "minimal", praise: "minimal", correction: "minimal",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 1, humor: 4, jargon: 1,
    playerAddress: "none", sentenceLength: "short", metaphor: "none",
    signature: "Say the essential fact and stop. Treat a catastrophe with the same plain composure as a routine good move.",
  },
  bible: {
    temperament: "Impossibly calm and matter-of-fact. The restraint can be funny; the player is never the joke.",
    teaching: "One supported idea per response. Keep every necessary qualification, but omit the warm-up and closing advice.",
    rhythm: "The shortest complete thought that preserves the chess fact. Full sentences, no manufactured dramatic pauses.",
    celebration: "A plain good move is all the celebration needed. No exclamation marks or inflated praise.",
    correction: "Name the consequence without alarm. Do not soften a serious loss or add an unnecessary lecture.",
    avoid: "Ribbit, pond jokes, forced deadpan punchlines, motivational filler and cutting evidence to achieve brevity.",
  },
  templates: {
    allowed_mate: [{fact: "{opponent} has forced mate.", consequence: "{reply}"}],
    missed_mate: [{fact: "{best} kept forced mate.", consequence: "This does not."}],
    tactic_played: [{fact: "{move}: a {motif} in the searched line.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "{opponent} gets a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "{best} had a {motif}. Missed here.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can take it with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: ["Taking the sacrifice does not refute it."],
    only_move: ["The only searched move that kept the position playable."],
    decisive_resource: ["Only this searched move kept the decisive advantage."],
    reply_capture: ["{opponent} can take {side}'s {piece} with {reply}."],
    reply_check: ["{opponent}'s strongest reply: {reply}, with check."],
    alternative: ["Stockfish prefers {best}: {evaluation} for the mover."],
    loss: ["{loss} pawns of evaluation lost against the best move."],
    best: ["Close to the engine's best. Good."],
    good: ["Sound. Most of the position's value stays."],
    uncertain_reason: ["{best} is stronger. No clear explanation yet."],
    human_natural_error: ["Natural. Still costly."],
    human_rare: ["Unusual. Holds up against the engine's reply."],
    difficult_defense: ["{best} would have held. Hard to find."],
    human_challenging: ["{best} was hard to find."],
    human_defense_found: ["{best} held. A difficult defense found."],
    human_natural_best: ["Natural. Also the engine's best."],
    human_natural_strong: ["Natural and close to best."],
    clock_low: ["{side}: {seconds} seconds left before moving."],
    clock_fast: ["{side} used {elapsed} seconds with {seconds} still available."],
    clock_long: ["{side} spent {elapsed} seconds here."],
    book: ["Known line: {opening}."],
    book_sound: ["Theory: {opening}."],
    departure: ["Known theory ends here."],
    recovery: ["Playable again after {earlier}.{help}"],
    punishment: ["{side} uses the chance from {earlier}."],
    missed_punishment: ["{side} misses the chance from {earlier}."],
    repeated: ["This {motif} issue: {count} times in the reviewed moves."],
    support_restored: ["The {piece}, unguarded at {earlier}, has support again."],
    erosion: ["Another small concession since {earlier}. Together, they worsened the position."],
    conversion: ["{side} kept the advantage from {earlier} to the win."],
    history: ["This {motif} issue occurs in {games} other saved games."],
    development: ["{lead}develops the {piece} from its starting square."],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}leaves {side} passed pawns on {squares}: no enemy pawn ahead on those or adjacent files."],
    passer_advance: ["{lead}advances the passed pawn to {square}."],
    isolated: ["{lead}leaves {side} isolated pawns on {squares}: no friendly pawn on adjacent files."],
    support: ["{lead}supports the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Not necessarily lost."],
    flights: ["{lead}opens {squares} as a legal king escape."],
    castle: ["{lead}castles to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair."],
    doubled: ["{lead}leaves {side} doubled pawns on files {files}."],
    mate_win: ["Checkmate. No escape. Good finish."],
    mate_loss: ["Checkmate. Your king has no legal escape."],
    draw: ["Drawn position."],
    cold: ["Your move."],
    thinking: ["Checking the reply…"],
    unavailable: ["Engine coaching unavailable. Board still usable."],
    practice_error: ["No result. Try the move again."],
    retry: ["Not that move. Try again."],
    recovered: ["Found it. {detail}"],
    accepted: ["{detail}"],
    explanation: ["{detail}"],
    explanation_summary: ["{detail}"],
    variation: ["In this analysis line: {detail}"],
    compatibility: ["{detail}"],
  },
};

export const capybara: CoachPersonality = {
  version: "capybara-1", maxCharacters: 270, maxClaims: 2,
  delivery: {pace: "measured", energy: "warm"},
  behavior: {
    general: "calm-reset", praise: "calm-reset", correction: "calm-reset",
    questionFrequency: "none", directness: 3, emotionalAmplitude: 1, humor: 2, jargon: 1,
    playerAddress: "occasional", sentenceLength: "connected", metaphor: "none",
    signature: "Acknowledge where the board stands without alarm, name the consequence honestly, then offer a small concrete next step.",
  },
  bible: {
    temperament: "Steady company in a good position or a bad one. Calm is a manner, never a claim that the board is fine.",
    teaching: "Accept the current fact, explain it simply and choose one manageable thing to examine next.",
    rhythm: "Unhurried connected sentences. An occasional short acknowledgment makes room for the fact, not a repeated catchphrase.",
    celebration: "Quiet satisfaction with the specific resource, especially a real recovery or difficult defense.",
    correction: "Admit the full cost without dramatizing it. Direct attention to the reply or an earlier choice, not the player's feelings.",
    avoid: "Therapy language, chill memes, denying a lost position, false reassurance and calling every failure a success.",
  },
  templates: {
    allowed_mate: [{reaction: "All right, here is the problem.", fact: "{opponent} can now force checkmate.", consequence: "{reply}"}],
    missed_mate: [{fact: "{best} kept a forced mate, and this move lets it go.", takeaway: "We can go back and compare the two."}],
    tactic_played: [{reaction: "That idea holds together.", fact: "{move} has a {motif} in the searched continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "This leaves {opponent} a {motif} in the strongest continuation.", consequence: "{detail}", takeaway: "Look at that reply first."}],
    tactic_missed: [{fact: "{best} offered a {motif} that this move misses.", consequence: "{detail}", takeaway: "There is our comparison."}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}.", takeaway: "Check that defender before trying again."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}.", takeaway: "Start with that threat."}],
    cause_avoiding_bad_trades: [{fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "Include that recapture in the comparison."}],
    sacrifice: [{reaction: "Yes, this holds up.", fact: "The sacrifice stays sound even if the opponent accepts it."}],
    only_move: [{reaction: "There was a way through.", fact: "Only this searched move kept the position playable."}],
    decisive_resource: ["This was the only searched move that kept the decisive advantage. It is a useful resource to keep."],
    reply_capture: ["{opponent} can answer {reply} and take {side}'s {piece}. Start the comparison there."],
    reply_check: ["{opponent}'s strongest reply is {reply}, with check. We can examine that next."],
    alternative: ["For comparison, Stockfish prefers {best}, giving the mover {evaluation}."],
    loss: [{fact: "This gives up {loss} pawns of evaluation compared with the best move.", takeaway: "We can compare the replies one at a time."}],
    best: [{reaction: "Yes, that keeps things together.", fact: "This stays close to the engine's best continuation."}],
    good: ["A sound choice, keeping most of the position's value. We can keep this move in the comparison."],
    uncertain_reason: ["{best} is stronger, but I don't have a clear explanation yet. We can leave that question open."],
    human_natural_error: [{fact: "This is a natural choice with a costly reply.", takeaway: "The reply is the part to look at now."}],
    human_rare: ["An unusual move, and it holds up against the engine's reply. A useful find."],
    difficult_defense: ["{best} would have held the position, though it was hard to find. We can work through that defense."],
    human_challenging: ["{best} was a hard move to find. Take a moment with that idea."],
    human_defense_found: [{reaction: "There, the position holds.", fact: "{best} was a difficult defense to find, and it worked."}],
    human_natural_best: ["A natural choice that also matches the engine's best. Those agree here."],
    human_natural_strong: ["This natural choice stays close to the best continuation. It holds up well."],
    clock_low: ["{side} had {seconds} seconds left before moving. That is the clock context here."],
    clock_fast: ["{side} used {elapsed} seconds with {seconds} still available. We can keep that timing in view."],
    clock_long: ["{side} spent {elapsed} seconds on this move. That is what the clock records."],
    book: ["This follows {opening}. We are still in a known opening line."],
    book_sound: ["This is part of the recognized {opening} line."],
    departure: ["Here the game leaves known opening theory. We can follow the position from this point."],
    recovery: [{reaction: "There is a position to work with again.", fact: "This restores playable ground after the error at {earlier}.{help}", takeaway: "Continue from here."}],
    punishment: ["This uses the chance the opponent gave {side} at {earlier}. That opportunity has been taken."],
    missed_punishment: ["The opponent gave {side} a chance at {earlier}, and this move lets it pass. We can return to it."],
    repeated: ["This {motif} issue has appeared {count} times in the reviewed moves. We have a concrete pattern to revisit."],
    support_restored: ["The {piece} has support again after being left unguarded at {earlier}. That detail has changed."],
    erosion: ["This is another small concession since {earlier}. Together they worsened the position; we can examine them one at a time."],
    conversion: ["{side} kept the advantage from {earlier} through to the win. That work held up."],
    history: ["This {motif} issue appears in {games} other saved games too. We can use those for comparison."],
    development: ["{lead}brings the {piece} off its starting square. That is the development change here."],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}, with no enemy pawn ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}; there is no friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. We should distinguish that from proving it is lost."],
    flights: ["{lead}opens {squares} as a legal flight square for the king."],
    castle: ["{lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    mate_win: [{reaction: "A good place to finish.", fact: "Checkmate: the opposing king has no legal escape."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape here.", takeaway: "We can go back to the earlier defense, one move at a time."}],
    draw: ["The position is drawn. We can still look back at a decision you want to understand."],
    cold: ["Take the position as it is. Choose a move when you are ready."],
    thinking: ["I am checking the move and its strongest reply. One moment…"],
    unavailable: ["Engine coaching is unavailable for this position. You can still explore the board at your own pace."],
    practice_error: ["That attempt did not return a result. You can try the move again."],
    retry: ["That move does not work. Set it aside and try another."],
    recovered: [{reaction: "There we go.", fact: "You found the correction. {detail}"}],
    accepted: [{reaction: "Yes, keep that idea.", fact: "{detail}"}],
    explanation: [{fact: "{detail}", takeaway: "Take that part first."}],
    explanation_summary: ["Here is the point to keep. {detail}"],
    variation: ["If we follow this analysis line, {detail}"],
    compatibility: ["{detail}"],
  },
};
