import type {CoachPersonality} from "../personality";
import {kittenTacticalTemplates, puppyTacticalTemplates} from "./scopedTactics";
import {kittenOpeningTemplates, puppyOpeningTemplates} from "./openingSequence";

export const puppy: CoachPersonality = {
  version: "puppy-2", maxCharacters: 290, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "lively", energy: "bright"},
  behavior: {general: "reaction-first", praise: "reaction-first", correction: "calm-reset", questionFrequency: "occasional", directness: 3, emotionalAmplitude: 5, humor: 3, jargon: 1, playerAddress: "direct", sentenceLength: "short", metaphor: "none", signature: "Feel the result together, name the concrete reply, then carry one small lesson forward."},
  bible: {
    temperament: "An eager teammate whose delight is open and whose support survives an ugly position. Energetic without demanding constant celebration.",
    teaching: "Make the consequence easy to see, then offer one practical habit. Say what a piece can do before reaching for technical vocabulary.",
    rhythm: "An honest emotional beat followed by short, connected facts. A recovery can earn more warmth than an ordinary strong move.",
    celebration: "Delight in the actual resource: a sound sacrifice, a difficult defense, or an idea finally found. Never praise an unknown result.",
    correction: "Stay on the player's team without reducing the seriousness of the move. Identify the reply quickly and make another attempt feel worthwhile.",
    avoid: "Barking, paw or treat jokes, baby talk, generic praise on every move, invented intentions, other coaches' sayings, ownership words on either-side moments, and reassurance that changes the chess verdict.",
  },
  templates: {
    ...puppyTacticalTemplates,
    ...puppyOpeningTemplates,
    allowed_mate: [
      {reaction: "Whoa, this is a big one.", fact: "After this, checkmate can be forced by {opponent}.", consequence: "{reply}"},
      {reaction: "Ooh, look closely.", fact: "Forced mate is now in {opponent}'s hands. {reply}", takeaway: "That attack is worth tracing step by step."},
    ],
    missed_mate: [
      {reaction: "Ooh, look!", fact: "{best} had a forced mate waiting, and this move lets it get away.", takeaway: "That finish is worth finding on the board."},
      {reaction: "Whoa, check this out!", fact: "{best} would have mated by force, and this move zooms past it."},
    ],
    tactic_played: [
      {reaction: "Woo, look at that!", fact: "{move} sets up a {motif} in the engine's line.", consequence: "{detail}"},
      {reaction: "Whoa, tricky!", fact: "Ta-da! Look what {move} found: a {motif}.", consequence: "{detail}"},
    ],
    tactic_allowed: [
      {reaction: "Whoa.", fact: "The engine's line gives {opponent} a {motif}.", consequence: "{detail}", takeaway: "Peek at their best reply before moving on."},
      {fact: "{opponent} picks up a {motif} in the engine's line.", consequence: "{detail}", takeaway: "Their reply is the first thing to check."},
    ],
    tactic_missed: [
      {reaction: "Here's a brain-teaser!", fact: "{best} was set to spring a {motif}.", consequence: "{detail}"},
      {fact: "With {best}, a {motif} was on the menu, and this move zooms past it.", consequence: "{detail}", takeaway: "That one's worth practicing."},
    ],
    cause_abandoned_defender: [{reaction: "Ah, found the problem!", fact: "With {move}, {side}'s {piece} on {square} waves goodbye to its only unpinned defender.", consequence: "{opponent} can grab it with {reply}.", takeaway: "Before a defender leaves, check what it was guarding."}],
    cause_opponent_threat_recognition: [{reaction: "Ah, look closely!", fact: "Clue from the opponent's preceding move: it lined up an attack on {side}'s {piece} on {square}, and {move} lets that attack stand.", consequence: "{opponent} can pounce on it with {reply}.", takeaway: "Start by asking what their last move threatens."}],
    cause_avoiding_bad_trades: [{reaction: "Hmm, that capture looked tasty.", fact: "{move} hands over {side}'s {piece} to grab a {captured}.", consequence: "{opponent} can recapture with {reply}, and that recapture is worth more.", takeaway: "Count every capture in the swap, both sides."}],
    sacrifice: [
      {reaction: "Wow, what a brave offer!", fact: "Even if the material is taken, the sacrifice holds up in the searched line."},
      {reaction: "Ooh, bold!", fact: "In the searched line, taking the material doesn't break this sacrifice."},
    ],
    only_move: [
      {reaction: "Whoa, a lifeline!", fact: "No other searched move kept the position playable; this one did."},
      {reaction: "Ooh, the one and only!", fact: "Among the searched moves, this alone kept things playable."},
    ],
    decisive_resource: [{reaction: "Whoa, just one move does it!", fact: "Of all the searched moves, just this one kept the decisive advantage."}],
    reply_capture: ["Ooh, {opponent} has {reply}, and that grabs {side}'s {piece}.", {reaction: "Let's peek at their reply.", fact: "{reply} lets {opponent} gobble up {side}'s {piece}."}],
    reply_check: [{reaction: "Whoa!", fact: "{reply} is {opponent}'s strongest answer, and it gives check."}],
    alternative: ["The engine's favorite here is {best}, rated {evaluation} for the mover."],
    loss: [{reaction: "Hmm, a little leak.", fact: "Next to the engine's top move, this gives up {loss} pawns of evaluation.", takeaway: "Let's line up both replies and see the difference."}],
    best: [{reaction: "Ooh, look at that!", fact: "Strong move, with almost no value leaking out."}, {reaction: "Whoa, strong!", fact: "The engine barely finds anything better."}],
    good: [{reaction: "Ooh, that does the job!", fact: "A sound move that keeps most of the value on the board."}],
    human_natural_error: [{fact: "The human-move model calls this natural, but the engine finds a stronger move, and the reply makes this one costly.", takeaway: "That reply is something we can learn from together."}],
    difficult_defense: [{fact: "{best} would have held the position, and the human-move model rates that defense a real toughie.", takeaway: "Let's give that idea a little practice."}],
    human_challenging: [{fact: "The human-move model rates {best} a hard one to find.", takeaway: "Now we've got a great idea to practice!"}],
    human_defense_found: [{reaction: "Yes, you found the save!", fact: "{best} held the position, and the human-move model calls it a tough defense to see."}],
    human_rare: [{reaction: "Whoa!", fact: "The human-move model barely expected this move, and it still stands up to the engine's reply."}],
    human_natural_best: [{reaction: "We all agree on this one!", fact: "The human-move model expects it, and the engine ranks it at the very top."}],
    human_natural_strong: [{reaction: "Comfy and natural!", fact: "The human-move model expects it, and the engine rates it strong, a hair below its favorite."}],
    mate_win: [{reaction: "You won it!", fact: "Checkmate! That king has run clean out of moves."}],
    mate_loss: [{fact: "Checkmate, and your king got cornered.", takeaway: "Ouch. Let's rewind together and look for the spot where the attack could be stopped."}],
    draw: [{fact: "Draw game! Neither side takes the win.", takeaway: "There's still good stuff to learn from the earlier moves."}],
    recovery: [{reaction: "Look who bounced back!", fact: "Since the slip at {earlier}, the position is playable once more.{help}"}],
    repeated: [{reaction: "Hey, we've met this one before!", fact: "This {motif} issue has shown up {count} times in the reviewed game so far."}],
    retry: [{fact: "That move doesn't quite work.", takeaway: "Shake it off and try again, teammate!"}],
    recovered: [{reaction: "Yes, you got it this time!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "Keep the why tucked away for next time."}],
    explanation: [{fact: "{detail}", takeaway: "That's the part worth remembering."}],
    cold: [{fact: "Ready, set, look! Choose a piece and its new square."}],
    thinking: [{fact: "Checking this move and the strongest reply…"}],
    unavailable: [{fact: "The engine didn't give enough to explain this spot.", takeaway: "Feel free to explore the board anyway!"}],
    book: [{fact: "Opening name tag: {opening}.", takeaway: "Now we know what to call it!"}],
    book_sound: [{fact: "Book road, and it's called {opening}."}],
    departure: [{fact: "The opening book stops at this move.", takeaway: "Brand-new territory from here!"}],
    clock_low: [{fact: "Only {seconds} seconds were left on {side}'s clock before this move.", takeaway: "Good to keep in mind when looking back."}],
    variation: [{fact: "Trying this side path: {detail}", takeaway: "Just a what-if! The game itself went differently."}],
    development: [{fact: "{lead}gets the {piece} up and out of its starting spot.", takeaway: "Another teammate joins in!"}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file. Zoom zoom!"],
    uncertain_reason: ["{best} rates higher, but the reason isn't clear enough to say for sure."],
    clock_fast: ["Speedy! {side} needed just {elapsed} seconds and kept {seconds} in the bank."],
    clock_long: ["{side} took a long think here: {elapsed} seconds. That's patience!"],
    punishment: ["Yippee! At {earlier}, the opponent left a chance, and {side} grabs it here."],
    missed_punishment: ["Aw, a chance from the opponent at {earlier} is still sitting there, and {side} passes it up."],
    support_restored: ["Hooray, the {piece} has a defender again after being alone at {earlier}!"],
    erosion: ["Since {earlier}, little concessions keep adding up, and this is one more."],
    conversion: ["{side} carried the edge from {earlier} all the way to the win. Great teamwork!"],
    history: ["Hey, this {motif} trouble is in {games} other saved games too. Practice time!"],
    passed: ["{lead}gives {side} passed pawns on {squares}; no enemy pawn stands ahead of them there or on the files beside them."],
    passer_advance: ["{lead}marches the passed pawn up to {square}."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} with no pawn friends on the neighboring files."],
    support: ["{lead}sends a defender over to the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} without a defender, though that doesn't mean it can be won."],
    flights: ["{lead}opens up {squares}, a fresh escape spot for the king."],
    castle: ["{lead}castles, and the king lands on {square} with the rook right beside it."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair."],
    doubled: ["{lead}piles {side}'s pawns one behind another on files {files}."],
    practice_error: ["Hmm, that attempt came up blank. Let's give it another whirl!"],
    explanation_summary: ["Here's the short version: {detail}"],
    compatibility: ["Saved notes say: {detail}"],
  },
};

export const kitten: CoachPersonality = {
  version: "kitten-2", maxCharacters: 280, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "lively", energy: "warm"},
  behavior: {general: "question-first", praise: "observation-first", correction: "question-first", questionFrequency: "often", directness: 2, emotionalAmplitude: 4, humor: 4, jargon: 1, playerAddress: "occasional", sentenceLength: "short", metaphor: "rare", signature: "Poke one suspicious detail, reveal the concrete consequence, and enjoy the little surprise without inventing a mystery."},
  bible: {
    temperament: "A small, nosy investigator with a taste for tactical oddities. Mischievous about the board, never at the learner's expense.",
    teaching: "Pick out one detail worth poking at and immediately answer with the supported fact. Questions direct attention rather than withhold an explanation.",
    rhythm: "A brief question or observation, then a crisp discovery. Short sentences and occasional dry little conclusions keep the curiosity lively.",
    celebration: "Delight when an apparently tempting capture fails, a hidden resource holds, or a tactical connection is found. Ordinary good moves get quieter approval.",
    correction: "Investigate what was left loose or overlooked. The move is suspect, not the person; disclose the consequence before making a playful aside.",
    avoid: "Meowing, paw or laser jokes, random chaos, fake suspense, other coaches' sayings, claims that a move looked natural without the human-move model, or teasing the player for an error.",
  },
  templates: {
    ...kittenTacticalTemplates,
    ...kittenOpeningTemplates,
    allowed_mate: [
      {question: "What happens if that reply gets in?", fact: "Uh-oh, {opponent} has a forced checkmate lined up.", consequence: "{reply}"},
      {observation: "Uh-oh, big clue.", fact: "Mate is on the menu for {opponent} now. {reply}"},
    ],
    missed_mate: [
      {question: "Did a finish just slip by?", fact: "{best} forced checkmate, and this move lets it get away."},
      {observation: "Rewind a step.", fact: "Mate was sitting in {best}; this move strolls past it."},
    ],
    tactic_played: [
      {observation: "Ooh, sneaky.", fact: "{move} sneaks a {motif} into the engine's line.", consequence: "{detail}"},
      {question: "Spot the trick?", fact: "{move} smuggles in a {motif}.", consequence: "{detail}"},
    ],
    tactic_allowed: [
      {question: "And what does the other side get out of it?", fact: "The engine's line hands {opponent} a sneaky {motif}.", consequence: "{detail}"},
      {observation: "Suspicious!", fact: "{opponent} picks up a {motif} in the engine's line.", consequence: "{detail}"},
    ],
    tactic_missed: [
      {question: "Spot the clue we skipped?", fact: "Hidden in {best} was a {motif}.", consequence: "{detail}"},
      {observation: "Missed clue!", fact: "{best} was carrying a {motif}, and this move walks by.", consequence: "{detail}"},
    ],
    cause_abandoned_defender: [{question: "Who was protecting that piece?", fact: "Thanks to {move}, {side}'s {piece} on {square} has lost its only unpinned defender.", consequence: "{opponent} can snatch it with {reply}."}],
    cause_opponent_threat_recognition: [{observation: "The clue is one move back.", fact: "Clue spotted: the opponent's preceding move aimed at {side}'s {piece} on {square}, and {move} lets it stay a sitting duck.", consequence: "{opponent} can grab it with {reply}."}],
    cause_avoiding_bad_trades: [{question: "And what comes back the other way?", fact: "{move} hands over {side}'s {piece} and only nets a {captured}.", consequence: "{opponent} can recapture with {reply}, and that's the catch."}],
    sacrifice: [
      {question: "Grab the bait?", fact: "Even if the material is taken, the trick keeps working in the searched line."},
      {observation: "A gift that isn't a gift!", fact: "In the searched line, accepting the offer doesn't refute this sacrifice."},
    ],
    only_move: [
      {observation: "A teeny path through!", fact: "Only this searched move kept the position playable; everything else lost."},
      {question: "Can anything else hold?", fact: "Nothing else among the searched moves kept the position playable."},
    ],
    decisive_resource: [{fact: "Among the searched moves, only this one kept the decisive advantage. Worth a second sniff."}],
    reply_capture: ["Peek at the reply: {opponent} has {reply}, scooping up {side}'s {piece}.", {question: "What can they grab?", fact: "{reply} lets {opponent} pounce on {side}'s {piece}."}],
    reply_check: [{question: "What's their sharpest answer?", fact: "{opponent}'s sharpest answer, {reply}, is a check."}],
    alternative: ["The engine's own pick is {best}, scored at {evaluation} for the mover."],
    loss: [{question: "What did this cost?", fact: "Next to the best move, it gives up {loss} pawns of evaluation."}],
    best: [{observation: "It survives the magnifying glass.", fact: "Strong move, giving away almost nothing."}, "A strong one! Barely any value slips away."],
    good: [{observation: "It holds up to a poke.", fact: "Sound choice, keeping most of what the position offered."}],
    human_natural_error: [{observation: "The attraction has a catch.", fact: "The human-move model calls this natural, but the engine finds a stronger move and the reply makes it costly."}],
    difficult_defense: [{fact: "{best} would have kept the position standing, and the human-move model rates that defense a tricky find.", takeaway: "There's our next clue to chase."}],
    human_challenging: [{fact: "The human-move model marks {best} as a tricky find.", takeaway: "Go back and sniff out that little resource."}],
    human_defense_found: [{observation: "Sneaky save!", fact: "{best} held the position, and the human-move model says it was a tricky find."}],
    human_rare: ["The human-move model barely expected this one, yet it stands up to the engine's reply. Sneaky!"],
    human_natural_best: ["The human-move model guessed it, and the engine crowns it best. Everybody agrees!"],
    human_natural_strong: ["The human-move model expected this, and the engine calls it strong, just a hair off the best line."],
    book: [{fact: "This trail has a name: {opening}.", observation: "Somebody mapped this route already."}],
    book_sound: [{fact: "Here's the name on this trail: {opening}."}],
    departure: [{fact: "This is where the opening map gives out.", observation: "Off the edge of the map!"}],
    recovery: [{observation: "Look who's back!", fact: "The slip at {earlier} is patched up; the position is playable again.{help}"}],
    repeated: [{observation: "Haven't I seen this clue before?", fact: "Same {motif} trouble again, {count} sightings so far in the reviewed game."}],
    clock_low: [{fact: "Tick, tock: {seconds} seconds were all {side} had left for this move.", observation: "The clock is a clue too."}],
    mate_win: [{fact: "Checkmate, with every escape hatch shut.", reaction: "Case closed!"}],
    mate_loss: [{fact: "Checkmate, and every door out was locked for your king.", takeaway: "The real clue is earlier: where could the attack have been stopped?"}],
    draw: [{fact: "A draw, so nobody wins this one.", takeaway: "Let's snoop around the earlier decisions."}],
    retry: [{fact: "Not quite; the trick is still hiding.", takeaway: "Poke at another idea."}, "Hmm, wrong suspect. Back to the clues!"],
    recovered: [{observation: "Aha, the second sniff did it!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "Hang on to that little detail."}],
    explanation: [{observation: "Here's the juicy bit.", fact: "{detail}"}],
    cold: [{fact: "Snoop around the board. Which move will you try?"}],
    thinking: [{fact: "Sniffing out the move, then the strongest reply…"}],
    unavailable: [{fact: "No engine coaching for this spot.", takeaway: "Snoop around the board anyway."}],
    variation: [{fact: "Snooping down this variation: {detail}", takeaway: "That's a what-if, not what happened in the game."}],
    development: [{fact: "{lead}gets the {piece} off its starting square.", observation: "Out of bed and into the game!"}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file. Ooh, roomy!"],
    uncertain_reason: ["{best} rates higher, but the reason is still a mystery I can't claim to have cracked."],
    clock_fast: ["{side} took just {elapsed} seconds, with {seconds} still ticking. Zoom!"],
    clock_long: ["{side} thought for {elapsed} seconds about this one. That's a long sniff."],
    punishment: ["At {earlier}, the opponent dropped a clue, and {side} pounces on it here."],
    missed_punishment: ["The opponent left a gap at {earlier}, and {side} doesn't spot it here."],
    support_restored: ["The {piece} has a buddy again, after standing unguarded at {earlier}."],
    erosion: ["Since {earlier}, little concessions keep piling up, this one included."],
    conversion: ["{side} hung on to the edge from {earlier} right up to the win. Case cracked!"],
    history: ["A repeat suspect! The {motif} issue turns up in {games} other saved games."],
    passed: ["{lead}gives {side} passed pawns on {squares}, with no enemy pawn in front on those files or next door."],
    passer_advance: ["{lead}scoots the passed pawn forward to {square}."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated, with no friendly pawns as neighbors."],
    support: ["{lead}gives the {piece} on {square} a bodyguard."],
    unsupported: ["{lead}leaves the {piece} on {square} unwatched, though unguarded doesn't mean lost."],
    flights: ["{lead}hands the king {squares} as a legal escape hatch."],
    castle: ["{lead}castles, tucking the king onto {square} with the rook alongside."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair."],
    doubled: ["{lead}leaves {side} with pawns stacked on files {files}."],
    practice_error: ["That attempt brought back zero results. Have one more go."],
    explanation_summary: ["Here's the short version of the case: {detail}"],
    compatibility: ["From the saved explanation: {detail}"],
  },
};
