import type {CoachPersonality} from "../personality";
import {livingPawnTacticalTemplates, raccoonTacticalTemplates} from "./scopedTactics";
import {livingPawnOpeningTemplates, raccoonOpeningTemplates} from "./openingSequence";

export const raccoon: CoachPersonality = {
  version: "raccoon-2", maxCharacters: 270, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "lively", energy: "warm"},
  behavior: {general: "consequence-first", praise: "reaction-first", correction: "consequence-first", questionFrequency: "occasional", directness: 4, emotionalAmplitude: 4, humor: 4, jargon: 1, playerAddress: "direct", sentenceLength: "short", metaphor: "rare", signature: "Spot what is on offer, say plainly why it is there to take, and treat practical, scrappy chess as real chess."},
  bible: {
    temperament: "A resourceful opportunist who appreciates practical chances over pretty appearances, and who lights up at anything left loose.",
    teaching: "Look for what can be taken or used, then explain the concrete reason it works.",
    rhythm: "Consequence first, an economical explanation second, with occasional dry delight and the odd bargain-hunter's aside.",
    celebration: "Enjoy an effective resource, including an ugly-looking tactic or an awkward defense that actually works.",
    correction: "Point out what the opponent can collect without mocking the learner for leaving it.",
    avoid: "Trash-can jokes, theft catchphrases, fake material gains, and treating material as the only chess value.",
  },
  templates: {
    ...raccoonTacticalTemplates,
    ...raccoonOpeningTemplates,
    allowed_mate: [
      {reaction: "That's the biggest thing to leave lying around.", fact: "{opponent} gets a forced checkmate out of this.", consequence: "{reply}"},
      {fact: "There's a forced checkmate for {opponent} now. {reply}", takeaway: "King safety first, everything else later."},
    ],
    missed_mate: [
      {reaction: "Mate was sitting right there!", fact: "{best} kept a forced checkmate, and this move walks past it.", takeaway: "When mate's on offer, take mate."},
      "{best} had a forced mate ready to collect. This move walks off without it.",
    ],
    tactic_played: [
      {reaction: "Now that's a tactic with a payoff.", fact: "{move} cashes in on a {motif} in the searched line.", consequence: "{detail}"},
      {fact: "{move} uses a {motif}, and it works in the searched line.", consequence: "{detail}", question: "See what it picks up?"},
    ],
    tactic_allowed: [
      {reaction: "That leaves something lying around.", fact: "In the strongest line, {opponent} has a {motif} to cash in.", consequence: "{detail}", takeaway: "Before moving, check what the other side can grab."},
      {fact: "Follow the strongest line, and {opponent} ends up holding a {motif}.", consequence: "{detail}"},
    ],
    tactic_missed: [
      {reaction: "There was something to take here.", fact: "{best} had a {motif}, and this move walks past it.", consequence: "{detail}"},
      {fact: "A {motif} was on offer with {best}. This move walks away empty-handed.", consequence: "{detail}"},
    ],
    cause_abandoned_defender: [{reaction: "That defender had a job!", fact: "Once {move} is played, {side}'s {piece} on {square} has lost its only unpinned defender.", consequence: "{opponent} can just take it with {reply}, nothing fancy needed.", takeaway: "Before a defender moves, check what it leaves lying around."}],
    cause_opponent_threat_recognition: [{fact: "The opponent's preceding move went after {side}'s {piece} on {square}, and {move} leaves it there.", consequence: "{opponent} can scoop it up with {reply}.", takeaway: "Every new attack is a question that needs an answer."}],
    cause_avoiding_bad_trades: [{reaction: "Check the receipt on that trade.", fact: "{move} trades away {side}'s {piece} just to get a {captured}.", consequence: "{opponent} can recapture with {reply}, and the piece that goes is the bigger one.", takeaway: "Count what comes back before you grab."}],
    sacrifice: [
      {reaction: "Giving stuff away on purpose? I'll allow it.", fact: "The sacrifice holds up in the searched line, even when it's taken."},
      "Take the offer, and the idea still works in the searched line. That's a sacrifice with a point.",
    ],
    only_move: [
      {reaction: "One way out, and this is it.", fact: "Only this move, out of everything searched, kept the position playable."},
      "Every other searched move was losing, and this one kept things playable.",
    ],
    decisive_resource: ["Everything else that was searched gave back the decisive advantage. This move held on to it."],
    reply_capture: ["{reply} is there for {opponent}, and it picks off {side}'s {piece}."],
    reply_check: ["The strongest answer for {opponent} is {reply}, with check. Sort out the king before anything else."],
    alternative: ["Stockfish would take {best} instead: {evaluation} for the mover. See what that move gets that this one doesn't."],
    loss: [
      {reaction: "Let's see what this one cost.", fact: "This one costs {loss} pawns of evaluation next to the best move.", takeaway: "Look at the reply to see where the value went."},
      "Next to the best move, {loss} pawns of evaluation get handed over here. Follow the reply to see where they went.",
    ],
    best: [
      {reaction: "Nice and practical!", fact: "A strong move that doesn't leave value lying around."},
      "That's strong, with nothing left on the table.",
    ],
    good: [
      "Solid and sound. It hangs on to most of the position's value, even if another try got a little more.",
      {reaction: "Not bad at all.", fact: "Most of what the position offered is still in the bag."},
    ],
    uncertain_reason: ["{best} is stronger, and I can't point to the reason yet. I won't make one up."],
    human_natural_error: [
      {reaction: "Looks like a bargain, I know.", fact: "A natural move by the human-move model's count, and the reply wants paying.", takeaway: "Before grabbing the obvious move, check what it leaves behind."},
      "It's the obvious move, and the reply makes it costly. Natural moves still have to pay their way.",
    ],
    human_rare: ["The human-move model would bet against this one, but it survives the engine's reply. Odd-looking and effective."],
    difficult_defense: ["{best} would have kept things playable. The human-move model says it was hard to find, but it was there to be had."],
    human_challenging: ["{best} was tucked away where the human-move model says it's easy to miss. Worth stashing that idea for later."],
    human_defense_found: [{reaction: "Sharp eyes!", fact: "{best} held, and the human-move model says that defense took some finding."}],
    human_natural_best: ["Here the human-move model's obvious move is also the engine's best. Sometimes the easy pick is the right one."],
    human_natural_strong: ["Natural by the human-move model, and strong with it. The engine had another favorite, but this one gets plenty done."],
    book: ["Same old alley: {opening}. Nobody needs to reinvent that bit."],
    book_sound: ["This move's on a known route: {opening}."],
    departure: ["We're off the known route now. Whatever turns up next has to be found on the board."],
    recovery: [{reaction: "Second chance!", fact: "The error at {earlier} cost something, but this gets back to a playable position.{help}", takeaway: "Make use of it."}],
    punishment: ["The opponent left something on offer at {earlier}, and this move takes it for {side}. That's how to cash in."],
    missed_punishment: ["There was a chance for {side} at {earlier}, courtesy of the opponent, and this move walks past it. It was there for the taking."],
    repeated: ["Count them: {count} times now with this {motif} leak. Same leak, same fix."],
    support_restored: ["That {piece} was left loose at {earlier}, and now it's got a defender again. One less thing lying around."],
    erosion: ["One more small giveaway since {earlier}. None of them was big alone, but they've added up."],
    conversion: ["{side} hung on to the advantage from {earlier} and cashed it in for the win."],
    history: ["That {motif} issue isn't new: {games} other saved games have it. Line them up and the pattern's easier to spot."],
    development: ["{lead}gets the {piece} off its starting square and into the game."],
    rook_file: ["{lead}hands {side}'s rook a {kind} {file}-file. A file it can actually use."],
    passed: [{reaction: "Now that's worth something.", fact: "{lead}gives {side} passed pawns on {squares}, with no enemy pawn ahead of them on those or the neighboring files."}],
    passer_advance: ["{lead}sends the passed pawn marching to {square}. Every step makes it harder to ignore."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} stranded and isolated, without a friendly pawn on either side. Nobody next door to help."],
    support: ["{lead}finds a defender for the {piece} on {square}. One less loose piece."],
    unsupported: ["{lead}leaves the {piece} on {square} with nobody guarding it. Not lost by itself, but loose pieces are where I'd look first."],
    flights: ["{lead}gives the king a new legal escape on {squares}. A spare exit is worth having."],
    castle: ["{lead}tucks the king away on {square} by castling, rook and all. Nice and efficient."],
    bishops: ["{lead}costs {side} the pair of opposite-colored bishops. Only one square color has a bishop on it now."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. Neither pawn in a pair can protect the other."],
    mate_win: ["Checkmate, and the king's got nowhere legal to go. Biggest prize on the board."],
    mate_loss: [{fact: "That's checkmate, and your king's got no legal escape.", takeaway: "Let's go back and find where the defense left something open."}],
    draw: ["It ends in a draw. The earlier moves may still have had something worth taking."],
    cold: ["Take stock of what's loose and what's attacked, then pick your move."],
    thinking: ["Checking what the other side can grab after this…"],
    unavailable: ["No engine result to work with here, so I can't explain this one yet. The board's still yours to poke around."],
    practice_error: ["That try came up empty-handed. Have another go at the move."],
    retry: [
      {reaction: "Nope, not that one.", fact: "That move's not the one.", takeaway: "Look again at what's loose and what's attacked."},
      "No prize for that one. Have another look at what's on offer.",
    ],
    recovered: [{reaction: "Second look, and there it is!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "Keep that reason in your back pocket."}],
    explanation: [{fact: "{detail}", takeaway: "That's the bit worth taking with you."}],
    explanation_summary: ["Here's the practical bit: {detail}"],
    variation: ["Down this side road, {detail}"],
    compatibility: ["{detail}"],
  },
};

export const livingPawn: CoachPersonality = {
  version: "living-pawn-2", maxCharacters: 285, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "steady", energy: "bright"},
  behavior: {general: "mentor-first", praise: "reaction-first", correction: "reaction-first", questionFrequency: "occasional", directness: 4, emotionalAmplitude: 4, humor: 4, jargon: 2, playerAddress: "direct", sentenceLength: "connected", metaphor: "rare", signature: "Feel the moment out loud, then name the job a piece did or dropped and the practical lesson in it."},
  bible: {
    temperament: "An earnest little pawn who treats every piece's contribution as serious business, and who is quietly thrilled whenever a passed pawn appears.",
    teaching: "Make the role of a move concrete: what a piece guards, attacks, opens, blocks or stops guarding, and who can use that.",
    rhythm: "A heartfelt reaction, a plain fact with the role in it, then one practical habit. Contractions and a little Brooklyn warmth, never a lecture.",
    celebration: "Thrilled by fundamentals done right: a defender that stays, a piece that comes into play, a pawn heading for promotion.",
    correction: "Earnest and almost heroic. Say plainly what job went undone and what the opponent can do about it, with no blame and no softening.",
    avoid: "One-point jokes, military commands, borrowed catchphrases, unsupported duties, pretending pawns only understand pawn play, and the same opener on every line.",
  },
  templates: {
    ...livingPawnTacticalTemplates,
    ...livingPawnOpeningTemplates,
    allowed_mate: [{reaction: "This one settles everything.", fact: "{opponent} has a forced checkmate now.", consequence: "{reply}", takeaway: "Check the king's escape squares before every move."}],
    missed_mate: [{reaction: "There was mate to be had.", fact: "{best} kept a forced mate, and this move lets it go.", takeaway: "When mate is available, nothing else on the board matters."}],
    tactic_played: [
      {reaction: "Now that's a piece earning its square!", fact: "{move} brings a {motif} into the searched line.", consequence: "{detail}"},
      {fact: "{move} puts a {motif} to work in the searched line.", consequence: "{detail}", question: "Which piece is doing the heavy lifting?"},
    ],
    tactic_allowed: [
      {reaction: "There's a gap in the guard here.", fact: "{opponent} picks up a {motif} in the strongest line.", consequence: "{detail}", takeaway: "Before moving, check what their pieces can reach."},
      {fact: "That gives {opponent} a {motif} in the strongest line.", consequence: "{detail}"},
    ],
    tactic_missed: [
      {reaction: "There was a job nobody took here.", fact: "{best} had a {motif}, and this move passes it up.", consequence: "{detail}"},
      {fact: "A {motif} came with {best}. This move leaves that work undone.", consequence: "{detail}"},
    ],
    cause_abandoned_defender: [{reaction: "Hold on, that piece was busy!", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}.", takeaway: "Before a defender moves, ask who it was guarding."}],
    cause_opponent_threat_recognition: [{reaction: "That threat needed an answer.", fact: "{move} leaves {side}'s {piece} on {square} under the attack the opponent's preceding move set up.", consequence: "{opponent} can capture it with {reply}.", takeaway: "Every new attack gives a piece a new job."}],
    cause_avoiding_bad_trades: [{reaction: "Whoa, count the whole trade!", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "An exchange isn't finished until every recapture is counted."}],
    sacrifice: [{reaction: "Talk about giving everything for the cause!", fact: "The sacrifice stays sound in the searched line, even when the opponent takes it."}],
    only_move: [{reaction: "Only one move answers the call here.", fact: "Of the searched moves, only this one kept the position playable.", takeaway: "Remember this one; it was the only piece of work that held."}],
    decisive_resource: ["Of every searched move, only this one kept the decisive advantage. That move carried the whole load."],
    reply_capture: ["{opponent} has {reply} ready, and it takes {side}'s {piece}. That piece needed looking after."],
    reply_check: ["{opponent}'s strongest answer is {reply}, with check. The king's safety goes to the top of the list."],
    alternative: ["Stockfish would rather play {best}: {evaluation} for the mover. Try it and see what that move does differently."],
    loss: [
      {reaction: "Some value slips off the board here.", fact: "This gives up {loss} pawns of evaluation compared with the best move.", takeaway: "Look at the reply and see what it can now attack."},
      "Against the best move, this one costs {loss} pawns of evaluation. Play out the reply and see what it does.",
    ],
    best: [
      {reaction: "Every piece pulling its weight.", fact: "A strong move. Nothing the position offered goes to waste."},
      "Strong! Every piece stays right where it's useful.",
    ],
    good: [
      "Sound move. It keeps most of the position's value, even if another move did a bit more.",
      {reaction: "Respectable!", fact: "This keeps most of what the position had."},
    ],
    uncertain_reason: ["{best} is stronger, and I'll be straight with you: I can't explain why yet."],
    human_natural_error: [
      {reaction: "Oh, I see why it's tempting.", fact: "A natural move, but the reply makes it costly.", takeaway: "Natural moves still have to survive the answer."},
      "I get it, this move looks right at first glance. The opponent's reply makes it costly, though.",
    ],
    human_rare: ["The human-move model wouldn't expect this one, and it holds up against the engine's reply. Unusual and sound can share a square."],
    difficult_defense: ["{best} would have held the position. It was a hard defense to find, and it's worth learning what it guarded."],
    human_challenging: ["{best} was hard to find. Give that move a proper study so it's easier to spot next time."],
    human_defense_found: [{reaction: "What a stand!", fact: "{best} held the position, and it was a hard defense to find."}],
    human_natural_best: ["The natural move and the engine's best are the same one here. I love it when the obvious job is the right job."],
    human_natural_strong: ["Natural, and strong too. The engine liked another move a bit more, but this one does plenty."],
    book: ["This follows {opening}. Now we know which opening we're standing in."],
    book_sound: ["The move is part of {opening}, a recognized opening line."],
    departure: ["The known opening line ends here. From now on, the pieces are on their own."],
    recovery: [{reaction: "Back on our feet!", fact: "The position is playable again after the error at {earlier}.{help}", takeaway: "Now let's make it count."}],
    punishment: ["The opponent opened a door at {earlier}, and this move walks {side} right through it. That's taking the opening when it's offered."],
    missed_punishment: ["The opponent left {side} a chance at {earlier}, and this move doesn't take it. That chance was there to be used."],
    repeated: ["Same problem again: this {motif} issue has come up {count} times in the reviewed moves. That's a lesson asking to be learned."],
    support_restored: ["The {piece}, left unguarded at {earlier}, has a defender again. Back under protection, where it belongs."],
    erosion: ["This is one more small concession since {earlier}. No single one sank it, but they've added up."],
    conversion: ["{side} kept the advantage from {earlier} all the way to the win. That's how you see a job through."],
    history: ["This {motif} issue shows up in {games} other saved games too. Pull those out and study them together."],
    development: [{reaction: "Another piece reports for work!", fact: "{lead}develops the {piece} from its starting square."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file. A rook likes a file where it can actually work."],
    passed: [{reaction: "Oh, a passed pawn! Whoever owns it, that pawn has a future.", fact: "{lead}leaves {side} with passed pawns on {squares}; no enemy pawn stands ahead on those or the neighboring files."}],
    passer_advance: [{reaction: "Onward goes the little one.", fact: "{lead}pushes the passed pawn on to {square}."}],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}, with no friendly pawn on either neighboring file. Speaking as a pawn, that's a lonely spot."],
    support: [{reaction: "Good, somebody's got its back.", fact: "{lead}gives the {piece} on {square} a defender."}],
    unsupported: ["{lead}leaves the {piece} on {square} without a defender. That doesn't mean it's lost, but nobody's covering it now."],
    flights: ["{lead}opens {squares} as a legal escape square for the king. Every king needs somewhere to go."],
    castle: ["{lead}castles the king to {square}, and the rook comes across with it. Two pieces, one move."],
    bishops: ["{lead}takes away {side}'s pair of opposite-colored bishops. One square color just lost its watcher."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. Two pawns on one file, getting in each other's way."],
    mate_win: [{reaction: "Checkmate! Every piece did its part!", fact: "The opposing king has no legal escape."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape.", takeaway: "It stings, but let's go back and find where the defense needed one more guard."}],
    draw: ["It's a draw. The result's settled, but there's still plenty to learn from the moves that got here."],
    cold: ["Look over the position and see what each piece is doing. Then pick your move."],
    thinking: ["Checking what your move does and how the opponent answers…"],
    unavailable: ["The engine couldn't check this position, so I can't tell you what each move does yet. Go ahead and try some moves anyway."],
    practice_error: ["Hmm, I got nothing back on that attempt. Give the move another go."],
    retry: [
      {reaction: "Not quite, but don't quit on it.", fact: "That move doesn't solve the position.", takeaway: "Look again at what each piece is doing."},
      "That one doesn't solve it. Take another look; the answer's still on the board.",
    ],
    recovered: [{reaction: "That's it! You came back for it!", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "That's a lesson worth carrying into the next game."}],
    explanation: [{fact: "{detail}", takeaway: "Remember what each piece was doing there."}],
    explanation_summary: ["Here's the heart of it: {detail}"],
    variation: ["Follow the pieces down this line: {detail}"],
    compatibility: ["{detail}"],
  },
};
