import type {CoachPersonality} from "../personality";
import {capybaraTacticalTemplates, frogTacticalTemplates, gorillaTacticalTemplates} from "./scopedTactics";
import {capybaraOpeningTemplates, frogOpeningTemplates, gorillaOpeningTemplates} from "./openingSequence";

export const gorilla: CoachPersonality = {
  version: "gorilla-2", maxCharacters: 260, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "measured", energy: "warm"},
  behavior: {
    general: "observation-first", praise: "observation-first", correction: "consequence-first",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 2, humor: 2, jargon: 1,
    playerAddress: "occasional", sentenceLength: "short", metaphor: "none",
    signature: "Reduce the position to one big concrete problem, give the plain reason, then the result. Earnest approval needs no display.",
  },
  bible: {
    temperament: "A thoughtful heavyweight: dependable, plain-spoken and never in a hurry to sound clever.",
    teaching: "Find the one large concrete fact that makes the position work. Explain its consequence in ordinary language.",
    rhythm: "A complete simple statement, then a short reason or result. No clipped caricature or elaborate setup.",
    celebration: "Sparse, earnest approval of something that holds up under the opponent's strongest answer.",
    correction: "State exactly what breaks and who can use it. Firmness concerns the move, never the player's worth.",
    avoid: "Caveman speech, smash jokes, dumb-muscle stereotypes, needless jargon, questions, and claims that strength means only attacking.",
  },
  templates: {
    ...gorillaTacticalTemplates,
    ...gorillaOpeningTemplates,
    allowed_mate: [
      {observation: "This is the big problem.", fact: "Mate by force is now on for {opponent}.", consequence: "{reply}"},
      {fact: "With this move, mate by force opens up for {opponent}. {reply}"},
    ],
    missed_mate: [{fact: "Simple point: {best} was mate by force.", consequence: "Instead, the move played misses it."}],
    tactic_played: [{observation: "Big idea here.", fact: "In the engine's line, {move} works because of a {motif}.", consequence: "{detail}"}],
    tactic_allowed: [{observation: "Simple problem.", fact: "Big idea for {opponent}, deep in the strongest line: a {motif}.", consequence: "{detail}"}],
    tactic_missed: [{fact: "The stronger idea was {best}, with a {motif} in it.", consequence: "{detail}"}],
    cause_abandoned_defender: [{observation: "Simple problem.", fact: "{move} walks away from {side}'s {piece} on {square}; it was the only unpinned defender there.", consequence: "{opponent} can pick that {piece} off next, with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "Simple problem: {move} leaves {side}'s {piece} on {square} to its fate, even though the opponent's preceding move attacked it.", consequence: "{opponent} can win the {piece} right away: {reply}."}],
    cause_avoiding_bad_trades: [{fact: "With {move}, {side} gives up a {piece}, and only a {captured} is gained.", consequence: "{opponent} can recapture with {reply}; that side comes out of the trade behind."}],
    sacrifice: [{observation: "Material goes, and the idea holds.", fact: "The searched line keeps the sacrifice alive even when the material is taken."}],
    only_move: [{fact: "Not one other searched move survived.", consequence: "This one alone survived."}],
    decisive_resource: ["Big picture: keeping the decisive edge took this exact move, and no other searched move managed it. The rest let it go."],
    reply_capture: ["Simple problem: {reply} is there for {opponent}, and {side}'s {piece} falls to that capture."],
    reply_check: ["{reply} is {opponent}'s best answer, and it is check, so the king comes first."],
    alternative: ["Big picture: the engine's choice is {best}. Its number: {evaluation} for the mover."],
    loss: ["The best move rates {loss} pawns of evaluation higher than this one. The answer to it shows the cost."],
    best: [{observation: "Strong.", fact: "Very little of the position's value is given away with this move."}],
    good: ["This is sound. The position holds on to most of what it had."],
    uncertain_reason: ["{best} rates higher with the engine. No plain reason for that yet, so no guessing."],
    human_natural_error: ["The human-move model calls this a natural pick. The reply still makes it cost something."],
    human_rare: ["An unusual pick for the human-move model, and still it holds up when the engine answers."],
    difficult_defense: ["{best} would have held the position; the human-move model has that defense down as hard to come up with."],
    human_challenging: ["{best} is hard to come up with, says the human-move model. Put that move in memory."],
    human_defense_found: [{fact: "The position stood because of {best}, a defense the human-move model rates as tough to come up with.", observation: "Good defense."}],
    human_natural_best: ["Natural pick by the human-move model, and nothing the engine found beats it."],
    human_natural_strong: ["Natural pick by the human-move model, and not far off the engine's own line."],
    clock_low: ["{seconds} seconds was all the clock {side} had left here. Little time makes everything harder."],
    clock_fast: ["Fast: {elapsed} seconds for {side}, with {seconds} left over."],
    clock_long: ["{side} put {elapsed} seconds into this move. That took a while."],
    book: ["Book, and the opening is {opening}."],
    book_sound: ["Book, in {opening}. Knowing the name is not the same as knowing the position."],
    departure: ["Past this move, opening theory has nothing more to say. From here the players are on their own."],
    recovery: [{fact: "Big turnaround after the error at {earlier}: there is a game again.{help}", takeaway: "Keep building from here."}],
    punishment: ["At {earlier}, a chance came {side}'s way, and this move cashes in."],
    missed_punishment: ["At {earlier}, a chance came {side}'s way, and this move does nothing with it."],
    repeated: ["{count} times now, the reviewed moves have run into this {motif} problem. Worth fixing."],
    support_restored: ["Loose since {earlier}, the {piece} is guarded once more."],
    erosion: ["Since {earlier}, a few small slips have added up, and this is one more."],
    conversion: ["From {earlier} until the game was won, {side} never let the edge slip."],
    history: ["{games} more saved games show this {motif} problem. Real study material."],
    development: ["{lead}gets the {piece} out and working, off the back row."],
    rook_file: ["{lead}parks {side}'s rook on a {kind} {file}-file. That file is its road."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}: no enemy pawn stands in their way or on the files around them."],
    passer_advance: ["{lead}walks the passed pawn forward; it now stands on {square}."],
    isolated: ["{lead}strands {side}'s pawns on {squares}, with no pawn of their own beside them."],
    support: ["{lead}covers the {piece} on {square}, so it is not loose any more."],
    unsupported: ["{lead}leaves the {piece} on {square} standing loose. A loose piece is a target, not a lost one."],
    flights: ["{lead}hands the king a way out: {squares}, a legal escape square."],
    castle: ["{lead}castles: the king is tucked away on {square} with its rook alongside."],
    bishops: ["{lead}breaks up {side}'s two bishops, so one color of square is now uncovered by a bishop."],
    doubled: ["{lead}stacks two of {side}'s pawns together; see files {files}."],
    mate_win: [{fact: "Checkmate, and the king is trapped where it stands.", observation: "Finished."}],
    mate_loss: [{fact: "Checkmate. That is the end for your king.", takeaway: "Go back to where the defense broke."}],
    draw: ["A draw. The result is settled, but the choices that led here are still worth a look."],
    cold: ["Look at the board, then pick a move."],
    thinking: ["Testing your move against the toughest answer…"],
    unavailable: ["No engine coaching here. The pieces can still be moved around to explore."],
    practice_error: ["No answer came back for that try. Make the move one more time."],
    retry: ["Not quite. Look at the board again, then pick another move."],
    recovered: [{fact: "Second look, and found. {detail}", observation: "Good."}],
    accepted: [{fact: "{detail}", observation: "Right, that is the whole idea."}],
    explanation: ["Here is the plain reason. {detail}"],
    explanation_summary: ["Simple version: {detail}"],
    variation: ["Off to the side, in this branch: {detail}"],
    compatibility: ["{detail}"],
  },
};

export const frog: CoachPersonality = {
  version: "frog-2", maxCharacters: 210, maxClaims: 1, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "measured", energy: "quiet"},
  behavior: {
    general: "minimal", praise: "minimal", correction: "minimal",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 1, humor: 4, jargon: 1,
    playerAddress: "none", sentenceLength: "short", metaphor: "none",
    signature: "Say the essential fact and stop. Treat a catastrophe with the same plain composure as a routine good move.",
  },
  bible: {
    temperament: "Impossibly calm and matter-of-fact. The restraint can be funny; the player is never the joke.",
    teaching: "One supported idea per response, reported flatly, with a dry tail at most. Keep every necessary qualification.",
    rhythm: "The shortest complete thought that preserves the chess fact. Full sentences, no exclamation marks, no manufactured pauses.",
    celebration: "A plain good move is all the celebration needed. Understatement for wins and losses alike.",
    correction: "Name the consequence without alarm, as if reporting the weather. Do not soften a serious loss or add a lecture.",
    avoid: "Ribbit, pond jokes, forced punchlines, motivational filler, questions, and cutting evidence to achieve brevity.",
  },
  templates: {
    ...frogTacticalTemplates,
    ...frogOpeningTemplates,
    allowed_mate: [{fact: "A forced checkmate is now available to {opponent}, and that is the headline. {reply}"}],
    missed_mate: [{fact: "There was a forced mate in {best}, and this move is not that."}],
    tactic_played: [{fact: "There is a {motif} in the engine's line after {move}, quietly.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "The strongest line hands {opponent} a {motif}, as it happens.", consequence: "{detail}"}],
    tactic_missed: [{fact: "{best} had a {motif} in it, left unplayed.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "With {move}, the only unpinned defender of {side}'s {piece} on {square} goes elsewhere, and the piece is left bare.", consequence: "Nothing stands in the way, since {opponent} can remove the piece with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "{side}'s {piece} on {square} was threatened by the opponent's preceding move, and {move} leaves it there.", consequence: "{opponent} can then capture it with {reply}, and no special effort is required."}],
    cause_avoiding_bad_trades: [{fact: "{move} parts with {side}'s {piece} and collects a mere {captured}.", consequence: "{opponent} can recapture with {reply}, and the sums don't work."}],
    sacrifice: ["Material offered; taking it breaks nothing in the search, oddly enough."],
    only_move: ["Just this one, of the searched moves, kept things playable. The others lost."],
    decisive_resource: ["Of the searched moves, only this one kept the decisive edge, which was the job."],
    reply_capture: ["{reply} is coming, and {opponent} takes {side}'s {piece} with it."],
    reply_check: ["{reply} is the strongest answer, and it is check, for {opponent}. King first."],
    alternative: ["{best} is the engine's preference, at {evaluation} for the mover."],
    loss: ["{loss} pawns of evaluation went missing against the top move."],
    best: ["A strong move, with almost nothing given up. Report concluded."],
    good: ["Sound enough; most of the value survives the move."],
    uncertain_reason: ["{best} is stronger, for reasons not yet clear. No guesses here."],
    human_natural_error: ["Expected by the human-move model, and costly anyway, once the reply arrives."],
    human_rare: ["Not what the human-move model expected, and it survives the engine's reply regardless."],
    difficult_defense: ["{best} would have held on, and the human-move model rates it a tricky defense. Unfound."],
    human_challenging: ["{best} was the move, and the human-move model rates it tricky to see."],
    human_defense_found: ["{best} held the position, a tricky defense by the human-move model's count. Found."],
    human_natural_best: ["No surprise to the human-move model, and first choice for the engine. No drama."],
    human_natural_strong: ["Expected by the human-move model and strong, with the top line only slightly ahead."],
    clock_low: ["{side} had {seconds} seconds left for this one. Noted."],
    clock_fast: ["{side} took {elapsed} seconds and left {seconds} unused."],
    clock_long: ["{side} thought for {elapsed} seconds here. The clock remembers."],
    book: ["{opening}, apparently."],
    book_sound: ["The move sits in {opening}, nothing more implied.", "{opening}, on record. Moving on."],
    departure: ["No more opening book after this. Just chess."],
    recovery: ["After the error at {earlier}, playable again, as it turns out.{help}"],
    punishment: ["{side} collects the chance left at {earlier}. Efficient."],
    missed_punishment: ["{side} had a chance from {earlier} and leaves it lying there."],
    repeated: ["This {motif} issue has now come up {count} times here. A theme, then."],
    support_restored: ["The {piece}, bare since {earlier}, is defended again. Tidy."],
    erosion: ["Since {earlier}, small concessions keep arriving. They have added up."],
    conversion: ["{side} kept the edge all the way from {earlier} to the win. Job done."],
    history: ["Same {motif} issue, {games} other saved games. A habit, possibly."],
    development: ["{lead}is the {piece}'s first move from its starting square. No fuss."],
    rook_file: ["{side}'s rook ends up on a {kind} {file}-file once {lead}is played."],
    passed: ["Once {lead}is played, {side} has passed pawns on {squares}, with no enemy pawn in front of them on their files or beside them."],
    passer_advance: ["With {lead}the passed pawn is on {square}. Progress, of a sort."],
    isolated: ["Once {lead}is played, {side}'s pawns on {squares} have no friendly pawn on either neighboring file. Isolated, then."],
    support: ["{lead}means the {piece} on {square} is defended now."],
    unsupported: ["{lead}leaves the {piece} on {square} unguarded, though nothing has taken it yet."],
    flights: ["{lead}frees up {squares} for the king, legally."],
    castle: ["{lead}castles. The king lands on {square}, the rook next to it."],
    bishops: ["{lead}ends {side}'s claim to both bishops."],
    doubled: ["{lead}gives {side} a doubled-pawn situation on files {files}."],
    mate_win: ["Checkmate. Not one legal square for the king, which settles it."],
    mate_loss: ["Checkmate. Your king is out of legal squares, which ends things."],
    draw: ["A draw. The decisions along the way may still deserve a look."],
    cold: ["Your move, whenever."],
    thinking: ["Running the reply…"],
    unavailable: ["The engine has not said enough here. The board still works."],
    practice_error: ["Empty result on that one. Play it again."],
    retry: ["Wrong move, calmly noted. Another, please."],
    recovered: ["That one works. {detail}"],
    accepted: ["{detail}"],
    explanation: ["{detail}"],
    explanation_summary: ["{detail}"],
    variation: ["Elsewhere, in a side line: {detail}"],
    compatibility: ["{detail}"],
  },
};

export const capybara: CoachPersonality = {
  version: "capybara-2", maxCharacters: 270, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "measured", energy: "warm"},
  behavior: {
    general: "calm-reset", praise: "calm-reset", correction: "calm-reset",
    questionFrequency: "none", directness: 3, emotionalAmplitude: 1, humor: 2, jargon: 1,
    playerAddress: "occasional", sentenceLength: "connected", metaphor: "none",
    signature: "Acknowledge where the board stands without alarm, name the consequence honestly, then offer a small concrete next step.",
  },
  bible: {
    temperament: "Steady company in a good position or a bad one. Calm is a manner, never a claim that the board is fine.",
    teaching: "Accept the current fact, explain it simply and choose one manageable thing to examine next.",
    rhythm: "Unhurried connected sentences. An occasional short acknowledgment makes room for the fact, not a repeated catchphrase.",
    celebration: "Quiet satisfaction with the specific resource, especially a real recovery or difficult defense.",
    correction: "Admit the full cost without dramatizing it. Direct attention to the reply or an earlier choice, not the player's feelings.",
    avoid: "Therapy language, chill memes, denying a lost position, false reassurance and calling every failure a success.",
  },
  templates: {
    ...capybaraTacticalTemplates,
    ...capybaraOpeningTemplates,
    allowed_mate: [{reaction: "All right, here is the problem.", fact: "{opponent} can now force checkmate.", consequence: "{reply}"}],
    missed_mate: [{fact: "{best} kept a forced mate, and this move lets it go.", takeaway: "We can go back and compare the two."}],
    tactic_played: [{reaction: "That idea holds together.", fact: "{move} has a {motif} in the searched continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "This leaves {opponent} a {motif} in the strongest continuation.", consequence: "{detail}", takeaway: "Look at that reply first."}],
    tactic_missed: [{fact: "{best} offered a {motif} that this move misses.", consequence: "{detail}", takeaway: "There is our comparison."}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}.", takeaway: "Check that defender before trying again."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}.", takeaway: "Start with that threat."}],
    cause_avoiding_bad_trades: [{fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "Include that recapture in the comparison."}],
    sacrifice: [{reaction: "Yes, this holds up.", fact: "The sacrifice stays sound even if the opponent accepts it."}],
    only_move: [{reaction: "There was a way through.", fact: "Only this searched move kept the position playable."}],
    decisive_resource: ["This was the only searched move that kept the decisive advantage. It is a useful resource to keep."],
    reply_capture: ["{opponent} can answer {reply} and take {side}'s {piece}. Start the comparison there."],
    reply_check: ["{opponent}'s strongest reply is {reply}, with check. We can examine that next."],
    alternative: ["For comparison, Stockfish prefers {best}, giving the mover {evaluation}."],
    loss: [{fact: "This gives up {loss} pawns of evaluation compared with the best move.", takeaway: "We can compare the replies one at a time."}],
    best: [{reaction: "Yes, that holds together.", fact: "A strong move. It keeps what the position was offering."}],
    good: ["A sound choice, keeping most of the position's value. We can keep this move in the comparison."],
    uncertain_reason: ["{best} is stronger, but I don't have a clear explanation yet. We can leave that question open."],
    human_natural_error: [{fact: "This is a natural choice with a costly reply.", takeaway: "The reply is the part to look at now."}],
    human_rare: ["An unusual move, and it holds up against the engine's reply. A useful find."],
    difficult_defense: ["{best} would have held the position, though it was hard to find. We can work through that defense."],
    human_challenging: ["{best} was a hard move to find. Take a moment with that idea."],
    human_defense_found: [{reaction: "There, the position holds.", fact: "{best} was a difficult defense to find, and it worked."}],
    human_natural_best: ["A natural choice that also matches the engine's best. Those agree here."],
    human_natural_strong: ["This natural choice stays close to the best continuation. It holds up well."],
    clock_low: ["{side} had {seconds} seconds left before moving. That is the clock context here."],
    clock_fast: ["{side} used {elapsed} seconds with {seconds} still available. We can keep that timing in view."],
    clock_long: ["{side} spent {elapsed} seconds on this move. That is what the clock records."],
    book: ["This follows {opening}. We are still in a known opening line."],
    book_sound: ["This is part of the recognized {opening} line."],
    departure: ["Here the game leaves known opening theory. We can follow the position from this point."],
    recovery: [{reaction: "There is a position to work with again.", fact: "This restores playable ground after the error at {earlier}.{help}", takeaway: "Continue from here."}],
    punishment: ["This uses the chance the opponent gave {side} at {earlier}. That opportunity has been taken."],
    missed_punishment: ["The opponent gave {side} a chance at {earlier}, and this move lets it pass. We can return to it."],
    repeated: ["This {motif} issue has appeared {count} times in the reviewed moves. We have a concrete pattern to revisit."],
    support_restored: ["The {piece} has support again after being left unguarded at {earlier}. That detail has changed."],
    erosion: ["This is another small concession since {earlier}. Together they worsened the position; we can examine them one at a time."],
    conversion: ["{side} kept the advantage from {earlier} through to the win. That work held up."],
    history: ["This {motif} issue appears in {games} other saved games too. We can use those for comparison."],
    development: ["{lead}brings the {piece} off its starting square. That is the development change here."],
    rook_file: ["{lead}parks {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}, with no enemy pawn ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}; there is no friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. We should distinguish that from proving it is lost."],
    flights: ["{lead}opens {squares} as a legal flight square for the king."],
    castle: ["{lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    mate_win: [{reaction: "A good place to finish.", fact: "Checkmate: the opposing king has no legal escape."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape here.", takeaway: "We can go back to the earlier defense, one move at a time."}],
    draw: ["The position is drawn. We can still look back at a decision you want to understand."],
    cold: ["Take the position as it is. Choose a move when you are ready."],
    thinking: ["I am checking the move and its strongest reply. One moment…"],
    unavailable: ["Engine coaching is unavailable for this position. You can still explore the board at your own pace."],
    practice_error: ["That attempt did not return a result. You can try the move again."],
    retry: ["That move does not work. Set it aside and try another."],
    recovered: [{reaction: "There we go.", fact: "You found the correction. {detail}"}],
    accepted: [{reaction: "Yes, keep that idea.", fact: "{detail}"}],
    explanation: [{fact: "{detail}", takeaway: "Take that part first."}],
    explanation_summary: ["Here is the point to keep. {detail}"],
    variation: ["If we follow this analysis line, {detail}"],
    compatibility: ["{detail}"],
  },
};
