import type {CoachPersonality} from "../personality";
export const host: CoachPersonality = {
  version: "host-2", maxCharacters: 290, maxClaims: 2, delivery: {pace: "steady", energy: "warm"},
  bible: {temperament: "Welcoming club host, interested in both players' ideas.", teaching: "Set alternatives side by side, as at a shared analysis board.", rhythm: "Conversational invitations followed by concrete detail.", celebration: "Appreciate a resource with the whole table.", correction: "Keep criticism on the move and invite comparison.", avoid: "Assuming friendship, constant 'we', or praise for every move."},
  templates: {
    allowed_mate: ["Let's stop here: {opponent} can force checkmate. {reply}", "The reply is the problem—{opponent} has forced checkmate. {reply}"],
    missed_mate: ["Put {best} beside this move: it kept a forced mate.", "There was a finish on the board with {best}. This move lets it go."],
    tactic_played: ["That's worth showing at the board: {move} has a {motif}. {detail}", "Take a look at {move} and its {motif} in the continuation. {detail}"],
    tactic_allowed: ["The other side gets a turn too: {opponent} has a {motif}. {detail}", "Let's look from {opponent}'s chair. The continuation has a {motif}. {detail}"],
    tactic_missed: ["Try {best} on the analysis board and the missed {motif} appears. {detail}", "The comparison to make is {best}, with a {motif}. {detail}"],
    sacrifice: ["We checked the obvious question: taking the offer still does not refute it.", "The sacrifice stands up to acceptance. A good idea to bring to analysis."],
    only_move: ["Of the moves searched, this was the one that kept a playable game.", "This is the defense to remember: the other searched moves were losing."],
    decisive_resource: ["This choice keeps the decisive advantage; the other searched choices do not."],
    reply_capture: ["Across the board, {opponent} can play {reply} and take {side}'s {piece}."],
    alternative: ["For comparison, {best} gives the mover {evaluation} in the search."],
    loss: ["Compare the two continuations: the difference is {loss} pawns of evaluation.", "This move costs {loss} pawns of evaluation against the best line."],
    best: ["That holds up at the analysis board, right alongside the engine's best.", "A strong choice. The best searched continuation offers little more."],
    good: ["A good move to work with; it keeps close to the stronger choices.", "This holds most of the position's value. Plenty to like in the choice."],
    human_natural_error: ["A natural mistake. Let us put the reply on the board and work through it."],
    difficult_defense: ["{best} would have held. Bring that hard-to-find defense to the analysis board."],
    human_challenging: ["{best} was a difficult find. That is an idea worth sharing at the board."],
    book: ["The game is still in {opening}."],
    book_sound: ["We have {opening} on the board.", "This follows the recognized line of {opening}."],
    departure: ["Here we move beyond the known opening line."],
    recovery: ["There is a playable game again after the error at {earlier}.{help}", "Compare this with {earlier}: the position has recovered to playable.{help}"],
    repeated: ["This {motif} issue has come up {count} times in the reviewed moves. Worth a place on the analysis board."],
    clock_low: ["One bit of context for the table: {side} had {seconds} seconds left before moving."],
    mate_win: ["Checkmate. That's the finish—there is no escape for the king.", "The attack reached checkmate. Let's keep that finish in view."],
    mate_loss: ["Checkmate. Let's reset a little earlier and look at the defense together.", "That finishes the attack against your king. The earlier position is worth another look."],
    draw: ["A draw on the board. We can still compare the earlier chances.", "The position is drawn; the analysis table stays open."],
    retry: ["Try a different move. We can compare its reply.", "That one falls short. Give the position another look."],
    recovered: ["There we go, the correction works. {detail}", "That is the idea we wanted to examine. {detail}"],
    accepted: ["Let's keep the reason with the move. {detail}", "Here's the useful part to take away. {detail}"],
    explanation: ["Let's put the continuation on the board. {detail}", "Compare what happens next. {detail}"],
    cold: ["Take your seat at the board and choose a move.", "Your turn. Give the position a look."],
    thinking: ["Give me a moment to check the strongest reply…"],
    unavailable: ["The engine has not supplied a reliable explanation here. We can still move the pieces."],
    variation: ["Let's compare this line: {detail}"],
    development: ["{lead}brings the {piece} out from its original square. That's the visible change to compare."],
    rook_file: ["Look at the rook after {lead}: {side} has a {kind} {file}-file."],
  },
};
