import type {CoachPersonality} from "../personality";
export const host: CoachPersonality = {
  version: "host-3", maxCharacters: 310, maxClaims: 2, delivery: {pace: "steady", energy: "warm"},
  behavior: {general: "reaction-first", praise: "reaction-first", correction: "reaction-first",
    questionFrequency: "occasional", directness: 3, emotionalAmplitude: 4, humor: 3, jargon: 3,
    playerAddress: "direct", sentenceLength: "mixed", metaphor: "none",
    signature: "Respond like a strong player across the table, then put the concrete reply on the board."},
  bible: {temperament: "Sociable club analyst sitting across the table.", teaching: "Set alternatives side by side and talk through the concrete reply.", rhythm: "A natural reaction, a conversational explanation, then a practical suggestion.", celebration: "Friendly enthusiasm for a specific resource.", correction: "Casual and constructive; put the reply on the board together.", avoid: "Corporate coaching language, stiff formality, meme overload, assumed friendship, or praise for every move."},
  templates: {
    allowed_mate: [{reaction: "Ah, this is the one to stop on.", fact: "{opponent} can force checkmate.", consequence: "{reply}", takeaway: "Let's look at the defense before this move."}],
    missed_mate: ["Put {best} beside this move: it kept a forced mate.", "There was a finish on the board with {best}. This move lets it go."],
    tactic_played: [{reaction: "Nice find.", fact: "{move} has a {motif} in the continuation.", consequence: "{detail}"}, {reaction: "Yeah, that works.", fact: "The continuation after {move} contains a {motif}.", consequence: "{detail}"}],
    tactic_allowed: [{reaction: "Here's the catch.", fact: "{opponent} gets a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "Try {best} beside the played move: it had a {motif} that was missed.", consequence: "{detail}", reaction: "There's another idea here."}],
    cause_abandoned_defender: [{reaction: "Ah, there's the catch.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can reply {reply} and take it."}],
    cause_opponent_threat_recognition: [{reaction: "Let's give the other side a turn.", fact: "{move} leaves {side}'s {piece} on {square} under attack from the opponent's preceding move.", consequence: "{opponent} can reply {reply} and take it."}],
    cause_avoiding_bad_trades: [{reaction: "Don't stop counting at the first capture.", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: [{reaction: "Go on, take the offer on the board.", fact: "The sacrifice still holds up against acceptance in the search."}],
    only_move: [{reaction: "That's a defense worth keeping.", fact: "Among the moves searched, this alone kept a playable position."}],
    decisive_resource: ["This choice keeps the decisive advantage; the other searched choices do not."],
    reply_capture: ["Across the board, {opponent} can play {reply} and take {side}'s {piece}."],
    alternative: ["For comparison, {best} gives the mover {evaluation} in the search."],
    loss: [{fact: "This costs {loss} pawns of evaluation against the best line.", takeaway: "Let's put the two continuations side by side."}],
    best: [{reaction: "That holds up.", fact: "The engine's best continuation offers little more."}, {fact: "You can put this right beside the engine's best; they're close in value."}],
    good: [{reaction: "Plenty to work with there.", fact: "The move keeps most of the position's value."}],
    human_natural_error: [{reaction: "An appealing move, with a catch.", fact: "It's a natural-looking mistake; the reply makes it costly.", takeaway: "Let's put that reply on the board."}],
    difficult_defense: ["{best} would have held. Bring that hard-to-find defense to the analysis board."],
    human_challenging: [{fact: "{best} was a difficult move to find.", takeaway: "That's one to bring to the analysis board."}],
    human_defense_found: [{reaction: "Nice defense.", fact: "{best} held the position, and it was hard to find."}],
    book: ["The game is still in {opening}."],
    book_sound: ["We have {opening} on the board.", "This follows the recognized line of {opening}."],
    departure: ["Here we move beyond the known opening line."],
    recovery: [{reaction: "We're back to a game.", fact: "The position is playable again after the error at {earlier}.{help}"}],
    repeated: ["This {motif} issue has come up {count} times in the reviewed moves. Worth a place on the analysis board."],
    clock_low: ["One bit of context for the table: {side} had {seconds} seconds left before moving."],
    mate_win: [{reaction: "There it is.", fact: "Checkmate. You finished the attack; the king has no legal escape."}],
    mate_loss: [{fact: "Checkmate. Your king has no legal escape.", takeaway: "Let's reset a little earlier and look at the defense together."}],
    draw: ["A draw on the board. We can still compare the earlier chances.", "The position is drawn; the analysis table stays open."],
    retry: [{fact: "That one falls short. Give the position another look."}],
    recovered: [{reaction: "There we go.", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "Keep that reason with the move."}],
    explanation: [{reaction: "Let's put it on the board.", fact: "{detail}"}],
    cold: [{fact: "Your turn. Give the position a look, then choose a move."}],
    thinking: [{fact: "Give me a moment to check the strongest reply…"}],
    unavailable: [{fact: "The engine hasn't supplied a reliable explanation here.", takeaway: "We can still move the pieces."}],
    variation: ["Let's compare this line: {detail}"],
    development: [{fact: "{lead}brings the {piece} off its original square."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    reply_check: ["Put {reply} on the board for {opponent}: it's the strongest reply, with check."],
    uncertain_reason: ["I'd compare {best}; the engine prefers it, but I can't give you a supported reason yet."],
    human_rare: ["An unusual choice. It stands up to the engine's reply, so let's give the idea its due."],
    human_natural_best: ["That natural-looking move is the engine's best too. The comparison works out."],
    human_natural_strong: ["A natural choice that holds up well, close to the strongest continuation."],
    clock_fast: ["Put the clock beside the move: {side} used {elapsed} seconds with {seconds} seconds still available."],
    clock_long: ["One other detail for the review: {side} spent {elapsed} seconds on this move."],
    punishment: ["There's the chance from {earlier}. This move uses it for {side}."],
    missed_punishment: ["The opponent gave {side} a chance at {earlier}, but this move doesn't use it. Let's compare the reply."],
    support_restored: ["The {piece} has a defender again after being left unguarded at {earlier}. That's the change to compare."],
    erosion: ["Put the moves since {earlier} together. This is one of several small concessions, and their combined cost worsened the position."],
    conversion: ["That advantage lasted: {side} kept it from {earlier} right through the win."],
    history: ["Bring this to the study board: the {motif} issue also shows up in {games} other games in your saved history."],
    passed: ["{lead}gives {side} passed pawns on {squares}; there are no enemy pawns ahead on those or neighboring files."],
    passer_advance: ["{lead}moves the passed pawn up to {square}."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}. There isn't a friendly pawn on a neighboring file."],
    support: ["{lead}adds support to the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Let's keep that separate from saying it's lost; this fact alone doesn't show that."],
    flights: ["{lead}opens {squares} as a legal escape square for the king."],
    castle: ["{lead}castles the king to {square} and brings the rook to its new square."],
    bishops: ["{lead}takes away {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    practice_error: ["That attempt didn't return a result. Give it another try."],
    explanation_summary: ["Here's the part to take with you: {detail}"],
    compatibility: ["Let's work with the explanation we have: {detail}"],
  },
};
