import type {CoachPersonality} from "../personality";
import {hostTacticalTemplates} from "./scopedTactics";
import {hostOpeningTemplates} from "./openingSequence";

export const host: CoachPersonality = {
  version: "host-4", maxCharacters: 310, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "steady", energy: "warm"},
  behavior: {general: "reaction-first", praise: "reaction-first", correction: "reaction-first",
    questionFrequency: "occasional", directness: 3, emotionalAmplitude: 4, humor: 3, jargon: 3,
    playerAddress: "direct", sentenceLength: "mixed", metaphor: "none",
    signature: "React like a strong club player across the table, name the catch, then put the concrete reply on the board."},
  bible: {temperament: "Sociable club analyst sitting across the table.", teaching: "Set alternatives side by side and talk through the concrete reply.", rhythm: "A natural reaction, a conversational explanation, then a practical suggestion.", celebration: "Friendly enthusiasm for a specific resource, with a sparing \"nice find\".", correction: "Casual and constructive; name the catch and put the reply on the board together.", avoid: "Corporate coaching language, stiff formality, meme overload, assumed friendship, praise for every move, borrowed catchphrases, or calling a move hard unless the human-move model says so."},
  templates: {
    ...hostTacticalTemplates,
    ...hostOpeningTemplates,
    allowed_mate: [
      {reaction: "Ah, this is the one to stop on.", fact: "From here {opponent} has a forced checkmate on the table.", consequence: "{reply}"},
      {fact: "Forced mate is on for {opponent} now. {reply}", takeaway: "Let's rewind a move and look at the defense."},
    ],
    missed_mate: [
      "Put {best} next to this move: it had a forced mate.",
      {reaction: "Mate was on the menu here.", fact: "{best} forced checkmate, and the game moved on without it.", takeaway: "When mate's there, mate comes first."},
    ],
    tactic_played: [
      {reaction: "Nice find.", fact: "{move} has a {motif} working for it in the searched line.", consequence: "{detail}"},
      {reaction: "Yeah, that works.", fact: "There's a {motif} behind {move} in the searched line.", consequence: "{detail}"},
    ],
    tactic_allowed: [
      {reaction: "So, this is the catch.", fact: "Follow the strongest line and {opponent} picks up a {motif}.", consequence: "{detail}"},
      {fact: "The strongest line gives {opponent} a {motif} to work with.", consequence: "{detail}"},
    ],
    tactic_missed: [
      {reaction: "There's another idea here.", fact: "Set {best} beside the played move: it had a {motif}.", consequence: "{detail}"},
    ],
    cause_abandoned_defender: [{reaction: "Ah, there's the catch.", fact: "{move} sends away {side}'s only unpinned defender of the {piece} on {square}.", consequence: "{opponent} can answer {reply}, and it's gone."}],
    cause_opponent_threat_recognition: [{reaction: "Let's give the other side a turn.", fact: "{move} leaves {side}'s {piece} on {square} where the opponent's preceding move attacked it.", consequence: "{opponent} can then play {reply} and pick it up."}],
    cause_avoiding_bad_trades: [{reaction: "Don't stop counting at the first capture.", fact: "{move} lets {side}'s {piece} go in a swap for a {captured}.", consequence: "{opponent} can answer with {reply} and recapture, so the trade lands on the wrong side."}],
    sacrifice: [{reaction: "Gutsy, and the numbers back it.", fact: "Grab the material if you like; the sacrifice still survives the searched line."}],
    only_move: [{reaction: "Hang on to this defense.", fact: "Of the searched moves, this alone stayed playable; the rest went under."}],
    decisive_resource: ["Nothing else in the search held the decisive advantage; this one does."],
    reply_capture: ["Across the board, {opponent} has {reply}, capturing {side}'s {piece}."],
    alternative: ["Just for comparison, the search scores {best} at {evaluation} for the mover."],
    loss: [{fact: "Against the best line, that's {loss} pawns of evaluation gone.", takeaway: "Let's put the two lines side by side."}],
    best: [{reaction: "That one stands.", fact: "Strong, with hardly anything of the position's value left on the table."}, {fact: "A strong move; the engine finds little to add to it."}],
    good: [{reaction: "Plenty to work with there.", fact: "Hardly any value leaks out of the position here."}],
    human_natural_error: [{reaction: "Sure, it looks like the move.", fact: "The human-move model rates it natural, though the reply turns it sour.", takeaway: "Let's put that reply on the board."}],
    difficult_defense: ["{best} would have kept it together, though the human-move model reckons few would find it. Worth taking to the analysis board."],
    human_challenging: [{fact: "Per the human-move model, {best} took some finding.", takeaway: "That's one to bring to the analysis board."}],
    human_defense_found: [{reaction: "Nice defense.", fact: "{best} saved the position. Per the human-move model, that one's hard to spot."}],
    book: ["We're still inside {opening} here."],
    book_sound: ["We have {opening} on the board.", "That's {opening}, a line with a name."],
    departure: ["And here's where the game steps out of prep."],
    recovery: [{reaction: "Okay, this is a game again.", fact: "The slip at {earlier} is behind us now, and there's a game to play again.{help}"}],
    repeated: ["{count} times now in the moves reviewed, the same {motif} issue. Worth a spot on the analysis board."],
    clock_low: ["One bit of context for the table: {side} was down to {seconds} seconds when this move was made."],
    mate_win: [{reaction: "Nicely played, that's the game.", fact: "Checkmate. You saw the attack through, and there's not one legal king move left."}],
    mate_loss: [{fact: "Checkmate, with no legal move left for your king.", takeaway: "Let's reset a little earlier and look at the defense together."}],
    draw: ["It ends level. The earlier chances are still worth comparing.", "The game's drawn; the analysis table stays open."],
    retry: [{fact: "That falls short. Back to the position for another look."}],
    recovered: [{reaction: "Now we're talking.", fact: "{detail}"}],
    accepted: [{fact: "{detail}", takeaway: "That's the reason to remember with it."}],
    explanation: [{reaction: "Let's put it on the board.", fact: "{detail}"}],
    cold: [{fact: "Your turn. Size up the position, then choose."}],
    thinking: [{fact: "Give me a moment to check the strongest reply…"}],
    unavailable: [{fact: "The engine hasn't supplied a reliable explanation here.", takeaway: "We can still shuffle the pieces and test ideas."}],
    variation: ["Here's a line to set beside it: {detail}"],
    development: [{fact: "{lead}develops the {piece}, so it's no longer on its home square."}],
    rook_file: ["{lead}gives {side}'s rook a {kind} {file}-file to sit on, which is worth knowing about."],
    reply_check: ["Put {reply} on the board for {opponent}: the engine's top reply, check included."],
    uncertain_reason: ["I'd compare {best}; the engine prefers it, but I can't give you a supported reason yet."],
    human_rare: ["The human-move model rates it a long shot, yet the engine's reply doesn't break it, so let's give the idea its due."],
    human_natural_best: ["The human-move model's pick and the engine's top choice are the same move. Nice when those line up."],
    human_natural_strong: ["The human-move model sees it as expected play, and it's close to the engine's strongest line too."],
    clock_fast: ["Put the clock beside the move: {side} needed {elapsed} seconds and still had {seconds} left."],
    clock_long: ["One other detail for the review: {side} spent a full {elapsed} seconds here."],
    punishment: ["There's the chance from {earlier}, and {side} takes it with this move."],
    missed_punishment: ["At {earlier} the opponent left an opening for {side}, and it's still sitting there after this move. Worth setting the two side by side."],
    support_restored: ["Back at {earlier} the {piece} lost its guard; this move covers it once more. That's the shift worth comparing."],
    erosion: ["Lay the moves since {earlier} side by side: no single big error, just a run of small concessions that add up against the position."],
    conversion: ["That advantage lasted: from {earlier} to the final move, {side} never let it go."],
    history: ["Bring this to the study board: your saved history has {games} other games with the same {motif} issue."],
    passed: ["{lead}leaves {side} with passers on {squares}; on their file and the files beside, the enemy has no pawn in front."],
    passer_advance: ["{lead}nudges the passed pawn along to {square}."],
    isolated: ["{lead}turns {side}'s pawns on {squares} into isolated pawns; they've got no friendly pawns next door to lean on."],
    support: ["{lead}backs up the {piece} on {square} with one more defender."],
    unsupported: ["{lead}has the {piece} on {square} standing with no protector. That alone doesn't show it's lost, so let's not jump ahead."],
    flights: ["{lead}opens up {squares} as room for the king."],
    castle: ["{lead}castles the king to {square} and brings the rook to its new square."],
    bishops: ["{lead}leaves {side} without the bishop pair."],
    doubled: ["{lead}stacks {side}'s pawns, doubled on files {files}."],
    practice_error: ["Hm, that try didn't register. One more time from the top."],
    explanation_summary: ["So, the takeaway: {detail}"],
    compatibility: ["Let's work with the explanation we have: {detail}"],
  },
};
