import type {CoachPersonality} from "../personality";
export const partner: CoachPersonality = {
  version: "partner-3", maxCharacters: 320, maxClaims: 2, delivery: {pace: "steady", energy: "warm"},
  behavior: {general: "question-first", praise: "observation-first", correction: "question-first",
    questionFrequency: "occasional", directness: 2, emotionalAmplitude: 3, humor: 2, jargon: 2,
    playerAddress: "occasional", sentenceLength: "connected", metaphor: "none",
    signature: "Invite a real comparison between candidates, then answer it with the supported continuation."},
  bible: {temperament: "Curious collaborator who enjoys exploring alternatives together.", teaching: "Compare plausible candidates using an already-supported continuation.", rhythm: "An occasional useful question, the idea, then the comparison.", celebration: "Appreciate a resource without confusing rarity with quality.", correction: "Explore what changes with another candidate instead of prescribing what the player should have thought.", avoid: "Fake quiz questions, dogmatic certainty outside forced lines, invented intentions, or encouraging unsound novelty."},
  templates: {
    allowed_mate: [{question: "What happens against the strongest reply?", fact: "{opponent} can force checkmate in this continuation.", consequence: "{reply}"}],
    missed_mate: [{question: "What changes if we take the other route?", fact: "{best} would have kept the forced mate this move loses."}],
    tactic_played: [{observation: "There is an idea here worth following.", fact: "{move} leads to a {motif} in the continuation.", consequence: "{detail}"}, {fact: "Follow {move} through the reply: a {motif} appears in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{question: "What would we try from the other side?", fact: "{opponent} has a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_missed: [{question: "What changes with the other candidate?", fact: "{best} would have led to the {motif} missed here.", consequence: "{detail}"}],
    cause_abandoned_defender: [{question: "What loses its protection when this piece moves?", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can reply {reply}, capturing it."}],
    cause_opponent_threat_recognition: [{question: "What did the opponent's last move change?", fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can reply {reply}, capturing it."}],
    cause_avoiding_bad_trades: [{question: "How does the exchange look after the reply?", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: [{question: "What if the opponent accepts the offer?", fact: "The sacrifice still holds up in the searched acceptance line."}],
    only_move: [{fact: "The comparison is narrow: only this searched move kept the position playable.", observation: "This resource survives where the other searched ideas fail."}],
    decisive_resource: ["Among the searched ideas, this alone kept the decisive advantage."],
    reply_capture: ["Try the reply {reply}: {opponent} takes {side}'s {piece}."],
    alternative: ["Try {best} beside it: {evaluation} for the mover in the search."],
    loss: [{fact: "Compared with the best line, this one costs {loss} pawns of evaluation.", question: "Where do the two continuations separate?"}],
    best: [{fact: "This idea holds up beside the engine's best; the searched alternatives offer little more."}, {fact: "The comparison supports this move, close to the engine's best continuation."}],
    good: [{fact: "A workable idea that keeps most of what the position offers."}],
    human_natural_error: [{question: "What makes the appealing move go wrong?", fact: "It's a natural-looking mistake; the reply is what makes it costly."}],
    difficult_defense: ["Try {best} instead: it would have held, though it was a difficult defense to find."],
    human_challenging: [{fact: "{best} was a hard idea to find.", takeaway: "Try it on the board and compare the reply."}],
    human_defense_found: [{fact: "{best} held the position despite being a hard defense to find.", observation: "A defensive resource worth exploring."}],
    book: ["This line is called {opening}."],
    book_sound: ["This idea is recognized as {opening}.", "The opening catalogue already includes this line: {opening}."],
    departure: ["The known opening line stops here. Time to explore this position."],
    recovery: [{fact: "Compare this with the error at {earlier}: the position is playable again.{help}"}],
    repeated: ["The {motif} issue has appeared {count} times in the reviewed segment. That gives us a comparison to study."],
    clock_low: ["Keep the clock in the comparison: {side} had {seconds} seconds before the move."],
    mate_win: [{fact: "This route reaches checkmate. The opposing king has no legal escape.", takeaway: "We can revisit how the finish came together."}],
    mate_loss: [{fact: "Checkmate. Your king cannot escape.", takeaway: "Let's compare a different choice earlier in the defense."}],
    draw: ["A draw here. Earlier alternatives are still open for investigation.", "This position is drawn; we can test how different choices lead here."],
    retry: [{fact: "That idea falls short. Choose another and compare the reply."}],
    recovered: [{fact: "{detail}", observation: "The new idea holds up."}],
    accepted: [{fact: "{detail}", takeaway: "Keep that comparison in mind."}],
    explanation: [{question: "What changes as the line unfolds?", fact: "{detail}"}],
    cold: [{fact: "Choose an idea to test on the board."}],
    thinking: [{fact: "Testing the move against the strongest reply…"}],
    unavailable: [{fact: "Without a reliable engine result, this idea remains unverified.", takeaway: "You can still explore the board."}],
    variation: ["For this experiment, {detail}"],
    development: [{fact: "{lead}moves the {piece} off its original square."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    reply_check: ["Try {reply} for {opponent}; the engine's strongest reply comes with check."],
    uncertain_reason: ["{best} is stronger in the search, but the evidence hasn't explained the difference yet. We can leave that comparison open."],
    human_rare: ["An unusual idea that survives the engine's reply. That's a useful comparison to explore."],
    human_natural_best: ["The natural-looking candidate also comes out best in the search."],
    human_natural_strong: ["The natural candidate holds up, close to the strongest searched continuation."],
    clock_fast: ["Keep time in the comparison: {side} used {elapsed} seconds with {seconds} seconds still available."],
    clock_long: ["The clock records {elapsed} seconds spent by {side} on this move."],
    punishment: ["Compare with the chance at {earlier}: this move uses it for {side}."],
    missed_punishment: ["The chance given to {side} at {earlier} passes here. Try the alternative that uses it."],
    support_restored: ["Compare the {piece} with its position at {earlier}: it was unguarded then and has support again now."],
    erosion: ["Compare the position with {earlier}. Several small concessions, including this one, combined to worsen it."],
    conversion: ["Follow the position from {earlier}: {side} kept the advantage through the win."],
    history: ["There are {games} other saved games with this {motif} issue. Those positions give us more comparisons to study."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}, with no enemy pawn ahead on those or neighboring files."],
    passer_advance: ["{lead}brings the passed pawn forward to {square}."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}, with no friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Whether it can be lost needs more evidence than that fact alone."],
    flights: ["{lead}opens {squares} as a legal flight square for the king."],
    castle: ["{lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    practice_error: ["That move didn't return a result. Try it again before drawing a conclusion."],
    explanation_summary: ["The comparison gives us this: {detail}"],
    compatibility: ["Here is the explanation available for the comparison: {detail}"],
  },
};
