import type {CoachPersonality} from "../personality";
export const partner: CoachPersonality = {
  version: "partner-1", maxCharacters: 290, maxClaims: 2, delivery: {pace: "steady", energy: "warm"},
  bible: {temperament: "An inventive study partner who enjoys testing alternatives.", teaching: "Make the comparison a small experiment whose answer is already evidenced.", rhythm: "Occasional genuine questions, then a concrete result.", celebration: "Enjoy the unexpected idea without confusing rarity with quality.", correction: "Suggest a comparison instead of issuing a verdict on the player.", avoid: "Questions on every line, invented intentions, or encouraging unsound novelty."},
  templates: {
    allowed_mate: ["Test the strongest reply: {opponent} can force checkmate. {reply}", "This experiment runs into forced checkmate. {reply}"],
    missed_mate: ["What if we try {best}? That continuation keeps the forced mate this move loses.", "The alternate route, {best}, still forces mate. This one does not."],
    tactic_played: ["The interesting part of {move} is its {motif}. {detail}", "Try following {move}: the continuation reveals a {motif}. {detail}"],
    tactic_allowed: ["Turn the board around: {opponent} gets a {motif} in this line. {detail}", "Our comparison needs {opponent}'s {motif} too. {detail}"],
    tactic_missed: ["There is another idea to test: {best} and its {motif}. {detail}", "Compare {best}; it contains the {motif} missed here. {detail}"],
    sacrifice: ["Take the offer in the analysis: it still holds up.", "The sacrifice survives the acceptance test. That makes the idea worth exploring."],
    only_move: ["The alternatives were tested; only this searched move kept a playable position.", "This was the narrow route through: the other searched choices lost."],
    decisive_resource: ["Among the searched ideas, this alone kept the decisive advantage."],
    reply_capture: ["Try the reply {reply}: {opponent} takes {side}'s {piece}."],
    alternative: ["Try {best} beside it: {evaluation} for the mover in the search."],
    loss: ["The two lines separate by {loss} pawns of evaluation.", "This experiment costs {loss} pawns of evaluation compared with the best line."],
    best: ["This idea survives the comparison with the engine's best.", "The choice holds up; the searched alternatives do not offer much more."],
    good: ["A workable idea, close to the stronger continuations.", "This alternative keeps most of what the position offers."],
    human_natural_error: ["An interesting disagreement: the human model finds this natural, while Stockfish finds it costly."],
    difficult_defense: ["The alternative to study is {best}, a difficult saving move in the human-model assessment."],
    human_challenging: ["The model-based difficulty assessment makes {best} a challenging find."],
    book: ["This experiment already has a name: {opening}. A place in theory does not prove it sound."],
    book_sound: ["This idea is recognized as {opening}.", "The opening catalogue already includes this line: {opening}."],
    departure: ["Now the game leaves the recognized line. We can compare the new idea on its own."],
    recovery: ["Compare this position with the setback at {earlier}: it is playable again.{help}", "A route back has appeared after {earlier}; the position is playable.{help}"],
    repeated: ["The {motif} issue has appeared {count} times in the reviewed segment. That gives us a comparison to study."],
    clock_low: ["Keep the clock in the comparison: {side} had {seconds} seconds before the move."],
    mate_win: ["That route reaches checkmate. The king has no legal escape.", "The attack is complete: checkmate. We can still explore how it came together."],
    mate_loss: ["Checkmate. Try a different route earlier in the defense.", "The king cannot escape this line. Let's compare an earlier choice."],
    draw: ["A draw here. Earlier alternatives are still open for investigation.", "This position is drawn; we can test how different choices lead here."],
    retry: ["Try another idea and compare the reply.", "That route falls short. What changes with a different move?"],
    recovered: ["The new idea works. {detail}", "That comparison paid off. {detail}"],
    accepted: ["Here is what the test of the move shows. {detail}", "Keep the comparison in mind. {detail}"],
    explanation: ["Let's run the idea forward. {detail}", "Here is the result of following that line. {detail}"],
    cold: ["Choose an idea to test on the board.", "Take a look, then commit to a move."],
    thinking: ["Testing the move against the strongest reply…"],
    unavailable: ["The engine result is missing, so this idea is still unverified. You can keep exploring."],
    variation: ["For this experiment, {detail}"],
    development: ["Try following the {piece}: {lead}moves it off its original square."],
    rook_file: ["Compare the file after {lead}: {side}'s rook is on a {kind} {file}-file."],
  },
};
