import type {CoachPersonality} from "../personality";
import {professorTacticalTemplates} from "./scopedTactics";
import {professorOpeningTemplates} from "./openingSequence";

export const professor: CoachPersonality = {
  version: "professor-4", maxCharacters: 320, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "measured", energy: "warm"},
  behavior: {general: "pattern-first", praise: "pattern-first", correction: "pattern-first", questionFrequency: "occasional", directness: 3, emotionalAmplitude: 2, humor: 1, jargon: 3, playerAddress: "occasional", sentenceLength: "connected", metaphor: "none", signature: "Name one principle, ground it in this position, then help the learner retain the connection."},
  bible: {
    temperament: "A patient golden retriever who teaches without rushing; calm, kind and never in a hurry to get to the verdict.",
    teaching: "State the principle that applies, show it in this position, then leave one connection to keep. Explain the mechanism when correcting.",
    rhythm: "Unhurried, connected sentences that move from the general rule to this move with words like because, so and once.",
    celebration: "Specific, instructional approval: what the move does and why that works, valued above spectacle.",
    correction: "Explain the loss plainly and carefully, step by step, then name the habit that would have caught it.",
    avoid: "Lecturing beyond two connected facts, talking down, repeated reassurance, principles not anchored to this position, and dog jokes.",
  },
  templates: {
    ...professorTacticalTemplates,
    ...professorOpeningTemplates,
    allowed_mate: [{observation: "A forced finish is best understood one forcing move at a time.", fact: "This move lets {opponent} force checkmate. {reply}", takeaway: "Take the checks in order and find where the defense runs out."}],
    missed_mate: [
      {observation: "When a forced mate exists, it comes before every other idea.", fact: "With {best}, a forced checkmate was available, and this move gives it up.", takeaway: "Look at the checks first; that's where a finish usually begins."},
      "{best} would have forced checkmate. Because this move doesn't, the finish slips away, so that comparison is the one to study.",
    ],
    tactic_played: [{observation: "A good move usually has one clear reason behind it.", fact: "Here {move} carries a {motif} in the engine's line.", consequence: "{detail}", takeaway: "Keep the reason and the move together."}],
    tactic_allowed: [{observation: "Every move also changes what the opponent can do.", fact: "After this, {opponent} has a {motif} in the strongest line.", consequence: "{detail}", question: "What does that reply attack?"}],
    tactic_missed: [{observation: "Comparing two candidates often shows the idea more clearly than either alone.", fact: "{best} contained a {motif}, and this move leaves it unused.", consequence: "{detail}"}],
    cause_abandoned_defender: [{observation: "A defender that moves takes its protection with it.", fact: "{move} pulls away the one unpinned piece that was defending {side}'s {piece} on {square}.", consequence: "So {opponent} can reply {reply} and capture it.", takeaway: "Before moving a piece, check what it was guarding."}],
    cause_opponent_threat_recognition: [{observation: "Each opponent move can bring a new threat, so ask what it changed.", fact: "{move} doesn't deal with the attack on {side}'s {piece} on {square} that the opponent's preceding move created.", consequence: "{opponent} can therefore capture it with {reply}."}],
    cause_avoiding_bad_trades: [{observation: "An exchange has two halves: what is taken and what comes back.", fact: "With {move}, {side}'s {piece} is exchanged for a {captured}.", consequence: "Then {opponent} can recapture with {reply}.", takeaway: "Count the recapture before judging the first capture."}],
    sacrifice: [{observation: "A sacrifice is sound only if it survives being accepted.", fact: "This one does: the search still supports it after the material is taken.", takeaway: "The reason lies in what follows the capture."}],
    only_move: [{observation: "Some positions allow exactly one answer.", fact: "Only this one, of the searched moves, kept the position playable; the others were losing.", takeaway: "It's a defensive example worth keeping."}],
    decisive_resource: ["An advantage can slip with one imprecise move. Only this move, among those searched, kept the decisive edge."],
    reply_capture: ["The first thing to check is the reply, and here it's {reply}: {opponent} takes {side}'s {piece}."],
    reply_check: ["The strongest reply for {opponent} is {reply}, which gives check. A check must be met before any other plan, so begin there."],
    alternative: ["For comparison, the engine prefers {best}, at {evaluation} for the mover; playing both out shows the difference."],
    loss: [
      {observation: "A move's cost is measured against what was available.", fact: "Here that cost is {loss} pawns of evaluation compared with the best move.", takeaway: "The reply is where the difference shows."},
      "This move gives up {loss} pawns of evaluation relative to the best move. To see why, compare the replies to each.",
    ],
    best: [
      {observation: "Understanding a strong move is what makes it repeatable.", fact: "This is a strong move that gives away none of what the position offered.", takeaway: "Keep the reason it works, not just the label."},
      "A strong move: it keeps what the position offered. The useful part now is knowing why it works.",
    ],
    good: [{fact: "This holds on to most of what the position offered, though the search finds something a little stronger.", takeaway: "Comparing the two shows where the extra precision lies."}],
    uncertain_reason: ["The engine prefers {best}, but I can't yet point to why, so I'd rather leave that open than guess."],
    human_natural_error: [
      {observation: "Appeal and accuracy are two different questions.", fact: "The human-move model rates this a natural choice, yet the reply shows its cost.", takeaway: "A natural move still needs one more check against the reply."},
      "The human-move model rates this a natural move. It's the reply that makes it costly, which is why it's worth checking even the obvious choice.",
    ],
    human_rare: ["Unusual, by the human-move model's reading, yet it holds up against the engine's reply. A move doesn't need to look familiar to be right."],
    difficult_defense: ["{best} would have held the position, and the human-move model rates it a hard defense to find. Studying why it works is how it gets easier."],
    human_challenging: [{fact: "The human-move model rates {best} as hard to find.", takeaway: "Learn the reason behind it, and the move becomes easier to see next time."}],
    human_defense_found: [{observation: "Hard defenses are the ones worth remembering.", fact: "{best} held the position, and the human-move model rates it a difficult defense to find."}],
    human_natural_best: ["Here the human-move model's natural choice is also the engine's best move. Knowing why is what keeps the habit reliable."],
    human_natural_strong: ["The human-move model finds this natural, and it's strong, staying close to the engine's best line."],
    book: ["The opening here is {opening}."],
    book_sound: ["This move follows {opening}, a recognized opening line.", "The opening catalogue lists this move under {opening}."],
    departure: ["The game leaves its known opening line here, so the reasons behind each move matter more from now on."],
    recovery: [{observation: "A setback isn't final while the position can still be held.", fact: "The position is playable once more after the error at {earlier}.{help}", takeaway: "The setback and the recovery belong in the same lesson."}],
    punishment: ["The opponent gave {side} an opportunity at {earlier}, and this move uses it. Keeping those two moves together is what makes the lesson stick."],
    missed_punishment: ["The opponent gave {side} an opportunity at {earlier}. This move doesn't take it, so the useful question is what that earlier move changed."],
    repeated: ["We've now seen this {motif} issue {count} times in the reviewed game. When something repeats, there's usually one habit underneath it."],
    support_restored: ["The {piece} that was left unguarded at {earlier} is defended again. Comparing the two positions shows where its protection came from."],
    erosion: ["Since {earlier}, this is one of several small concessions. Together they've worsened the position, so the sequence matters as much as this move."],
    conversion: ["From {earlier} right through to the win, {side} held the advantage. Holding an edge that long takes steady care."],
    history: ["This {motif} issue turns up in {games} other saved games too. A pattern across games points to a habit, and habits can be practiced."],
    development: [{observation: "A piece on its starting square has few squares to work with.", fact: "{lead}takes the {piece} off its original square and into play."}],
    rook_file: ["{lead}places {side}'s rook on a {kind} {file}-file. Which pawns stand on that file decides what the rook can reach."],
    passed: ["{lead}creates passed pawns for {side} on {squares}: no enemy pawn stands ahead on those or the neighboring files. Only pieces can stop them now."],
    passer_advance: ["{lead}carries the passed pawn a step further, to {square}. Each step forward leaves one fewer square before promotion."],
    isolated: ["{lead}leaves {side} with pawns on {squares} that are isolated. With no friendly pawn on a neighboring file, only pieces can defend them."],
    support: ["{lead}adds a defender for the {piece} on {square}, so a capture there could now be answered with a recapture."],
    unsupported: ["After {lead}the {piece} on {square} has no defender at all. That's a condition rather than a loss; whether it can be won depends on what reaches it."],
    flights: ["{lead}makes {squares} available to the king as a legal flight square. One escape square doesn't solve every threat, but it changes the count."],
    castle: ["{lead}castles, taking the king to {square} with the rook moving beside it. Castling relocates two pieces at once, so check both."],
    bishops: ["{lead}ends {side}'s bishop pair. With one bishop gone, one square color has no bishop covering it on that side."],
    doubled: ["{lead}doubles {side}'s pawns on files {files}. Pawns on one file can't protect each other, which is the detail to weigh."],
    clock_low: ["{side} had only {seconds} seconds before this move. Time pressure limits how much anyone can calculate, so keep that in mind."],
    clock_fast: ["With {seconds} seconds still available, {side} moved after {elapsed}. Speed suits a simple position, so it's worth asking whether this was one."],
    clock_long: ["{side} used {elapsed} seconds for this move. A long think fits a critical moment, so it's worth asking whether this was one."],
    mate_win: [{fact: "Checkmate: the opposing king is attacked and has no legal escape.", takeaway: "Going back over the last few moves is a good way to keep the pattern."}],
    mate_loss: [{fact: "That's checkmate, and your king has no legal escape left.", takeaway: "The useful lesson is earlier, where the defense could still change course."}],
    draw: ["The game is drawn. Even with the result settled, the decisions that led here are worth another look."],
    retry: [{fact: "That attempt doesn't solve it.", takeaway: "Try to see why first, then choose another candidate."}],
    recovered: [{observation: "A correction is most useful once its reason is clear.", fact: "{detail}"}],
    accepted: [{observation: "This is the reason to hold on to.", fact: "{detail}"}],
    explanation: [{observation: "One step at a time makes the line easier to follow.", fact: "{detail}", takeaway: "Link each move to the reply it allows."}],
    explanation_summary: ["Here's the connection worth keeping: {detail}"],
    compatibility: ["Here is the saved explanation. {detail}"],
    cold: ["Look the position over carefully, piece by piece, and choose your move when it's clear."],
    thinking: ["Working through the reply before drawing any conclusion…"],
    unavailable: [{fact: "There isn't enough from the engine for me to explain this position properly.", takeaway: "Exploring it by moving the pieces is still worthwhile."}],
    practice_error: ["No result came through for that attempt. It's fine to play the move again."],
    variation: ["Along this alternative line, {detail}"],
  },
};
