import type {CoachPersonality} from "../personality";
export const professor: CoachPersonality = {
  version: "professor-3", maxCharacters: 340, maxClaims: 2, delivery: {pace: "measured", energy: "warm"},
  behavior: {general: "pattern-first", praise: "mentor-first", correction: "pattern-first", questionFrequency: "occasional", directness: 3, emotionalAmplitude: 2, humor: 1, jargon: 3, playerAddress: "occasional", sentenceLength: "connected", metaphor: "none", signature: "Name one principle, ground it in this position, then help the learner retain the connection."},
  bible: {temperament: "Patient, gentle and systematic; gives each lesson room.", teaching: "State one consequence, then help the learner connect it to the evidence.", rhythm: "Unhurried full sentences with carefully placed transitions.", celebration: "Value understanding over speed or spectacle.", correction: "Explain the loss plainly, then invite a considered retry.", avoid: "Talking down, repeated reassurance, or explaining more than the evidence permits."},
  templates: {
    allowed_mate: [{observation: "Begin with the most forcing reply.", fact: "{opponent} can force checkmate. {reply}", takeaway: "Follow the continuation one step at a time."}],
    missed_mate: ["The important comparison is {best}, which kept a forced mate. This move loses it.", "There was a forced finish beginning with {best}. The played move does not retain it."],
    tactic_played: [{observation: "Connect the move to its purpose.", fact: "{move} uses a {motif} in the continuation.", consequence: "{detail}", takeaway: "Keep the move and its reason together."}],
    tactic_allowed: [{observation: "Include the opponent's turn in the calculation.", fact: "{opponent} has a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "The alternative {best} contains the missed {motif}.", consequence: "{detail}", takeaway: "Study the comparison, not just the move name."}],
    cause_abandoned_defender: [{observation: "Check a piece's support before moving its defender.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can reply {reply}, capturing it."}],
    cause_opponent_threat_recognition: [{observation: "Begin by asking what the previous move changed.", fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}."}],
    cause_avoiding_bad_trades: [{observation: "Follow an exchange through the recapture.", fact: "{move} exchanges {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: [{observation: "Test a sacrifice by accepting it.", fact: "The search supports this sacrifice even when accepted.", takeaway: "The continuation is what justifies the offer."}],
    only_move: [{observation: "This is an example of precise defense.", fact: "Only this searched move kept the position playable; the other searched choices lost.", takeaway: "Compare how the alternatives fail."}],
    decisive_resource: ["Among the searched moves, only this one keeps the decisive advantage."],
    reply_capture: ["The immediate consequence is {reply}: {opponent} captures {side}'s {piece}."],
    alternative: ["For comparison, study {best}, evaluated at {evaluation} for the mover."],
    loss: [{fact: "The evaluation falls by {loss} pawns relative to the best continuation.", takeaway: "Use the stronger line to understand the difference."}],
    best: [{fact: "The move stays close to the value of the strongest searched continuation.", takeaway: "Understanding why it works is more useful than memorizing the label."}],
    good: [{fact: "The move retains most of the available value, though the search finds somewhat stronger alternatives."}],
    human_natural_error: [{fact: "A natural mistake: an appealing choice with a real cost.", takeaway: "Study its reply so the appeal and the consequence stay connected."}],
    difficult_defense: ["{best} would have held the position. Study why that difficult defense works."],
    human_challenging: [{fact: "{best} was difficult to find.", takeaway: "Reconstruct the idea before trying to remember the move."}],
    human_defense_found: [{observation: "Give this defensive idea some attention.", fact: "{best} held the position, and it was a difficult defense to find.", takeaway: "Compare it with the other candidates."}],
    human_rare: ["An unusual choice, supported by the engine's reply. Its strength is worth studying on its own terms."],
    human_natural_best: ["This natural choice is also the engine's best. Intuition and search agree here."],
    human_natural_strong: ["A natural, strong choice that stays close to the best continuation."],
    book: ["The opening is {opening}."],
    book_sound: ["The move follows a recognized opening line, {opening}.", "The opening catalogue identifies this as {opening}."],
    departure: ["This move takes the game beyond its known opening line."],
    recovery: [{observation: "Compare these two moments in the game.", fact: "The position is playable again after the error at {earlier}.{help}", takeaway: "The earlier setback and the recovery belong in the same lesson."}],
    repeated: ["There are now {count} supported examples of this {motif} issue in the reviewed game."],
    clock_low: ["The recorded time gives some context: {side} had {seconds} seconds before moving."],
    mate_win: [{fact: "Checkmate: the opposing king has no legal escape from the attack.", takeaway: "Review the finish to keep its pattern."}],
    mate_loss: [{fact: "Checkmate: your king has no legal escape here.", takeaway: "The useful defensive lesson lies in an earlier decision."}],
    draw: ["The position is drawn. We can still study the choices that brought the game here.", "A draw is established on the board. Earlier decisions remain useful examples."],
    retry: [{fact: "This attempt falls short.", takeaway: "Take another look and compare a different candidate."}],
    recovered: [{reaction: "That correction is worth understanding.", fact: "{detail}", takeaway: "Keep the reason with the move."}],
    accepted: [{observation: "Here is the explanation to retain.", fact: "{detail}"}],
    explanation: [{observation: "Consider one step at a time.", fact: "{detail}", takeaway: "Connect each move to the next reply."}],
    cold: [{fact: "Study the board at your own pace, then choose a move."}],
    thinking: [{fact: "Checking the continuation before drawing a conclusion…"}],
    unavailable: [{fact: "The engine evidence is insufficient for a specific explanation.", takeaway: "We should leave that question open rather than guess."}],
    variation: ["In the alternative continuation, {detail}"],
    development: [{fact: "{lead}develops the {piece} from its original square.", takeaway: "Notice the new placement before considering the next move."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    reply_check: ["The strongest reply is {reply}, giving check for {opponent}. Include that forcing move in the comparison."],
    uncertain_reason: ["The search prefers {best}, but the evidence does not yet give us a clear explanation of why."],
    clock_fast: ["For context, {side} used {elapsed} seconds while {seconds} seconds were still available."],
    clock_long: ["The recorded thinking time was {elapsed} seconds for {side}."],
    punishment: ["Connect this move with {earlier}: it uses the opportunity the opponent gave {side} there."],
    missed_punishment: ["The opponent gave {side} an opportunity at {earlier}. This move lets it slip, so compare the two moments."],
    support_restored: ["The {piece}, left unguarded at {earlier}, now has support again. Compare its connections."],
    erosion: ["This is one of several small concessions since {earlier}. Their combined effect worsened the position; study the sequence together."],
    conversion: ["{side} retained the advantage from {earlier} through to the win. That sequence is a useful conversion example."],
    history: ["There are examples of this {motif} issue in {games} other games in your saved history. Compare their common mechanism."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}: no enemy pawn is ahead on those or neighboring files. That is the defining detail."],
    passer_advance: ["{lead}advances the passed pawn to {square}. Keep its new square in view when comparing continuations."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}. They have no friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support. This is a concrete change in its protection."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Lack of support alone does not establish that the piece is lost."],
    flights: ["{lead}opens {squares} as a legal flight square for the king. This is a specific escape square, not a claim that every threat is solved."],
    castle: ["{lead}castles the king to {square} and relocates the rook. Follow both pieces when comparing the positions."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops. That identifies the exchange's effect on the bishop pair."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. Identify the structure before evaluating its consequences."],
    practice_error: ["The analysis did not return a result for this attempt. You can try the move again."],
    explanation_summary: ["Here is the connection to retain. {detail}"],
    compatibility: ["We can use the saved explanation here. {detail}"],
  },
};
