import type {CoachPersonality} from "../personality";
export const professor: CoachPersonality = {
  version: "professor-1", maxCharacters: 290, maxClaims: 2, delivery: {pace: "measured", energy: "warm"},
  bible: {temperament: "Patient, gentle and systematic; gives each lesson room.", teaching: "State one consequence, then help the learner connect it to the evidence.", rhythm: "Unhurried full sentences with carefully placed transitions.", celebration: "Value understanding over speed or spectacle.", correction: "Explain the loss plainly, then invite a considered retry.", avoid: "Talking down, repeated reassurance, or explaining more than the evidence permits."},
  templates: {
    allowed_mate: ["The first consequence to understand is forced checkmate for {opponent}. {reply}", "After this move, {opponent} can force checkmate. Let us follow the reply. {reply}"],
    missed_mate: ["The important comparison is {best}, which kept a forced mate. This move loses it.", "There was a forced finish beginning with {best}. The played move does not retain it."],
    tactic_played: ["The reason to study {move} is the {motif} in its continuation. {detail}", "We can explain {move} through a {motif}. {detail}"],
    tactic_allowed: ["Consider the opponent's turn carefully. {opponent} has a {motif}. {detail}", "The continuation gives {opponent} a {motif}; that is the consequence here. {detail}"],
    tactic_missed: ["Begin with {best} to understand the missed {motif}. {detail}", "The alternative {best} contains a {motif} this move does not use. {detail}"],
    sacrifice: ["A sacrifice needs to work when accepted. This one passes that search test.", "The search checks the acceptance and still supports the sacrifice."],
    only_move: ["This is an important defensive example: only this searched move kept the position playable.", "The searched alternatives were losing. This move preserved a playable position."],
    decisive_resource: ["Among the searched moves, only this one keeps the decisive advantage."],
    reply_capture: ["The immediate consequence is {reply}: {opponent} captures {side}'s {piece}."],
    alternative: ["For comparison, study {best}, evaluated at {evaluation} for the mover."],
    loss: ["Relative to the best continuation, the evaluation falls by {loss} pawns.", "The search measures a loss of {loss} pawns of evaluation from this choice."],
    best: ["The move preserves the value of the strongest searched continuation.", "This is a precise choice, with little given up to the engine's best."],
    good: ["The move retains most of the value available in the position.", "A good choice, even though the search has somewhat stronger alternatives."],
    human_natural_error: ["The human model finds this move natural. Stockfish still identifies a cost; those are different kinds of evidence."],
    difficult_defense: ["The saving move was {best}. Its human-model assessment indicates a difficult find."],
    human_challenging: ["Finding {best} is rated challenging by the human-model assessment."],
    book: ["This is recognized as {opening}. Recognition describes opening history, not necessarily move quality."],
    book_sound: ["The move follows a recognized opening line, {opening}.", "The opening catalogue identifies this as {opening}."],
    departure: ["Here the game first leaves its recognized opening line. That fact alone does not make the move inaccurate."],
    recovery: ["The position is playable again after the error at {earlier}. Compare the two moments.{help}", "This restores playability following the setback at {earlier}.{help}"],
    repeated: ["There are now {count} supported examples of this {motif} issue in the reviewed game."],
    clock_low: ["The recorded time gives some context: {side} had {seconds} seconds before moving."],
    mate_win: ["Checkmate. The opposing king has no legal escape from the attack.", "The attack is complete. This position is checkmate."],
    mate_loss: ["Checkmate. To understand the defense, we should return to an earlier decision.", "Your king has no legal escape here. The useful lesson lies before this position."],
    draw: ["The position is drawn. We can still study the choices that brought the game here.", "A draw is established on the board. Earlier decisions remain useful examples."],
    retry: ["Take another look and choose a different candidate.", "This attempt falls short. Compare the reply before trying again."],
    recovered: ["The correction shows the idea. {detail}", "That revised choice works. Let us keep the reason with it. {detail}"],
    accepted: ["Here is the explanation to remember. {detail}", "Understanding the continuation is the useful part. {detail}"],
    explanation: ["Consider one step at a time. {detail}", "The saved continuation shows the reason. {detail}"],
    cold: ["Study the position at your own pace, then choose a move.", "Consider the board before making your choice."],
    thinking: ["Checking the continuation before drawing a conclusion…"],
    unavailable: ["The available engine evidence is insufficient for a specific explanation. We should leave that question open."],
    variation: ["In the alternative continuation, {detail}"],
    development: ["{lead}develops the {piece}, moving it from its original square."],
    rook_file: ["Following {lead}{side}'s rook is on a {kind} {file}-file."],
  },
};
