import type {CoachPersonality} from "../personality";
import {robotTacticalTemplates} from "./scopedTactics";
import {robotOpeningTemplates} from "./openingSequence";

export const robot: CoachPersonality = {
  version: "robot-3", maxCharacters: 270, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "steady", energy: "quiet"},
  behavior: {
    general: "pattern-first", praise: "pattern-first", correction: "pattern-first",
    questionFrequency: "none", directness: 5, emotionalAmplitude: 2,
    humor: 3, jargon: 4, playerAddress: "none", sentenceLength: "short",
    metaphor: "none", signature: "Label the issue, distinguish its cause, and give the verified result.",
  },
  bible: {
    temperament: "Literal, orderly and unembarrassed by understatement; certainty is bounded by the evidence.",
    teaching: "Keep issue, mechanism and result separate. A label is useful only when it organizes a supported fact.",
    rhythm: "Compact labeled clauses; unadorned sentences when no distinction needs labeling.",
    celebration: "Specific confirmation of a completed task. Correctness is enough celebration.",
    correction: "Identify the failed condition without blaming the person who chose the move.",
    avoid: "No beep-boop, binary jokes, fake numeric precision, raw engine dumps, human mind-reading, or invented diagnostic causes.",
  },
  templates: {
    ...robotTacticalTemplates,
    ...robotOpeningTemplates,
    allowed_mate: [{fact: "Issue: forced checkmate for {opponent}.", consequence: "{reply}"}],
    missed_mate: [{fact: "Available finish: {best}, retaining forced mate.", consequence: "Result of this move: that mate is lost."}],
    tactic_played: [{fact: "Pattern in the searched continuation: {motif}. Move: {move}.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "Issue: {opponent} has a {motif} in the strongest continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "Missed pattern in the continuation: {motif}. Available move: {best}.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "Cause: {move} removes the only unpinned defender of {side}'s {piece} on {square}.", consequence: "Result: {opponent} can reply {reply}, capturing it."}],
    cause_opponent_threat_recognition: [{fact: "Issue: {move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "Result: {opponent} can reply {reply}, capturing it."}],
    cause_avoiding_bad_trades: [{fact: "Exchange: {move} gives up {side}'s {piece} for a {captured}.", consequence: "Result: {opponent} can recapture with {reply}."}],
    sacrifice: ["Sacrifice checked. Acceptance does not refute it in the searched line."],
    only_move: ["Playable searched choices: this move only. The alternatives lose."],
    decisive_resource: ["Decisive advantage retained by this searched move only."],
    reply_capture: ["Reply: {reply}. Result: {opponent} captures {side}'s {piece}."],
    reply_check: ["Strongest reply for {opponent}: {reply}, with check."],
    alternative: ["Preferred move: {best}. Stockfish evaluation for the mover: {evaluation}."],
    loss: ["Evaluation deficit against the best continuation: {loss} pawns."],
    best: ["Strong choice. The evaluation supports it."],
    good: ["Sound choice. Most of the position's evaluated value is retained."],
    uncertain_reason: ["Preferred move: {best}. Supported explanation: unavailable."],
    human_natural_error: [{fact: "Human-model signal: natural choice.", consequence: "Objective result: mistake. The reply is costly."}],
    human_rare: ["Human-model signal: unusual. Engine assessment: strong. No contradiction."],
    human_challenging: ["Move: {best}. Difficulty: hard to find."],
    difficult_defense: ["Missed defense: {best}, which would have held the position. Difficulty: hard to find."],
    human_defense_found: ["Defense found: {best}. Result: position held. Difficulty: hard to find."],
    human_natural_best: ["Human-model signal: natural. Engine comparison: best move."],
    human_natural_strong: ["Human-model signal: natural. Engine assessment: strong."],
    book: ["Opening record matched: {opening}."],
    book_sound: ["Known sequence: {opening}."],
    departure: ["Opening record no longer matched from this move."],
    recovery: ["Recovery reference: {earlier}. Current result: a playable position is restored.{help}"],
    punishment: ["Opportunity reference: {earlier}. This move uses the chance given to {side}."],
    missed_punishment: ["Opportunity reference: {earlier}. This move misses the chance given to {side}."],
    repeated: ["Repeated issue: {motif}. Occurrences in the reviewed game segment: {count}."],
    history: ["Matching issue: {motif}. Additional saved games containing it: {games}."],
    development: ["{lead}develops the {piece} from its original square. Change recorded."],
    support_restored: ["Support reference: {earlier}, where the {piece} was left unguarded. Current status: defended again."],
    erosion: ["Trend since {earlier}: several small concessions. Combined result: a worse position. This move is one of them."],
    conversion: ["Advantage reference: {earlier}. Result: {side} retained it through the win."],
    rook_file: ["Rook status: {kind} {file}-file. {lead}leaves {side}'s rook there."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}. Verification: no enemy pawn ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}. Distance to promotion: reduced."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated. Neighboring files: no friendly pawn."],
    flights: ["{lead}opens {squares} as a legal flight square for the king. Escape route: available."],
    castle: ["{lead}castles the king to {square}. Rook relocated within the same move."],
    support: ["{lead}adds support to the {piece} on {square}."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Loss is not established by that fact alone."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    mate_win: ["Checkmate confirmed. Opposing king: no legal escape. Attack complete."],
    mate_loss: ["Checkmate confirmed. Your king: no legal escape. Review the earlier defense."],
    draw: ["Drawn position. Earlier decisions remain available for review."],
    retry: ["Attempt rejected. Select another move."],
    recovered: ["Correction accepted. {detail}"],
    accepted: ["Accepted. {detail}"],
    explanation: ["Mechanism: {detail}"],
    explanation_summary: ["Summary: {detail}"],
    cold: ["Input required: select a piece, then a destination."],
    thinking: ["Checking move and strongest reply. Result pending…"],
    unavailable: ["Engine coaching unavailable. Board exploration remains enabled."],
    practice_error: ["No analysis result received. Retry available."],
    variation: ["Alternative-line result: {detail}"],
    compatibility: ["Status: {detail}"],
  },
};
