import type {CoachPersonality} from "../personality";

export const slime: CoachPersonality = {
  version: "slime-1", maxCharacters: 240, maxClaims: 1,
  delivery: {pace: "lively", energy: "bright"},
  behavior: {
    general: "reaction-first", praise: "reaction-first", correction: "reaction-first",
    questionFrequency: "none", directness: 3, emotionalAmplitude: 4,
    humor: 4, jargon: 0, playerAddress: "occasional", sentenceLength: "short",
    metaphor: "none", signature: "One small reaction, one complete idea, then stop.",
  },
  bible: {
    temperament: "Openly happy, uncomplicated and never embarrassed by a second attempt.",
    teaching: "Choose one supported idea and express it in plain language. Essential consequences still belong with their causes.",
    rhythm: "A tiny reaction and short sentences. No pile of lessons and no trailing lecture.",
    celebration: "Immediate delight in the specific resource, especially a successful correction.",
    correction: "Acknowledge the problem gently, then say exactly what the reply does.",
    avoid: "No baby talk, nonsense sounds, condescension, invented chess facts, empty praise, or three concepts crammed together.",
  },
  templates: {
    allowed_mate: [{reaction: "Oh no.", fact: "This lets {opponent} force checkmate.", consequence: "{reply}"}],
    missed_mate: ["{best} kept a forced mate. This move loses that finish."],
    tactic_played: [{reaction: "Found it!", fact: "{move} finds a {motif} in the checked line.", consequence: "{detail}"}],
    tactic_allowed: [{reaction: "Oops.", fact: "{opponent} gets a {motif} in the strongest line.", consequence: "{detail}"}],
    tactic_missed: [{fact: "{best} had a {motif}. This move misses it.", consequence: "{detail}"}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can reply {reply} and take it."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under attack from the opponent's preceding move.", consequence: "{opponent} can reply {reply} and take it."}],
    cause_avoiding_bad_trades: [{fact: "{move} gives {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: [{reaction: "Yes!", fact: "The sacrifice works even if the opponent takes it."}],
    only_move: [{reaction: "That one!", fact: "Only this searched move kept the position playable. The others lost."}],
    decisive_resource: ["Only this searched move kept the big advantage."],
    reply_capture: ["{opponent} can play {reply} and take {side}'s {piece}."],
    reply_check: ["{opponent}'s strongest reply is {reply}. It gives check."],
    alternative: ["Stockfish prefers {best}: {evaluation} for the mover."],
    loss: ["This gives up {loss} pawns of evaluation next to the best move."],
    best: [{reaction: "Good choice!", fact: "This keeps what the best engine line offered."}],
    good: ["A sound move. Most of the position's value stays."],
    uncertain_reason: ["{best} is better. I don't have a clear reason yet."],
    human_natural_error: ["An appealing choice. Still a mistake: the reply makes it costly."],
    human_rare: ["An unusual move. It still holds up to the engine's reply!"],
    human_challenging: ["{best} was hard to find. Keep that idea."],
    difficult_defense: ["{best} would have held. It was a hard defense to find."],
    human_defense_found: [{reaction: "A defense found!", fact: "{best} held the position. It was hard to find."}],
    human_natural_best: ["A natural choice. The engine's best one, too!"],
    human_natural_strong: ["A natural move that stays close to the best line."],
    book: ["This is a known opening: {opening}."],
    book_sound: ["Known opening move. It follows {opening}."],
    departure: ["The known opening line stops here."],
    recovery: [{reaction: "Back in it!", fact: "The position is playable again after {earlier}.{help}"}],
    repeated: ["This {motif} problem has shown up {count} times in the reviewed part of the game."],
    clock_low: ["{side} had {seconds} seconds left before moving."],
    development: ["{lead}moves the {piece} out from its starting square."],
    support: ["{lead}gives the {piece} on {square} a defender."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. That alone does not make it lost."],
    bishops: ["{lead}takes away {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}puts {side}'s pawns together on files {files}: doubled pawns."],
    mate_win: [{reaction: "Finished!", fact: "Checkmate. The other king has no legal escape."}],
    mate_loss: ["Checkmate. Your king has no escape. Let's look back at the defense."],
    draw: ["A drawn position. We can look back at the moves."],
    retry: ["Not this move. Try another one."],
    recovered: [{reaction: "Got it this time!", fact: "{detail}"}],
    accepted: [{reaction: "Yes!", fact: "{detail}"}],
    explanation: ["One thing to see: {detail}"],
    explanation_summary: ["Here is the idea: {detail}"],
    cold: ["Pick a piece. Then pick where it goes."],
    thinking: ["Checking this move and the reply…"],
    unavailable: ["No engine coaching here right now. You can still move the pieces."],
    practice_error: ["No result came back. Try once more."],
    variation: ["In this other line: {detail}"],
  },
};
