import type {CoachPersonality} from "../personality";
export const spark: CoachPersonality = {
  version: "spark-2", maxCharacters: 260, maxClaims: 2, delivery: {pace: "lively", energy: "bright"},
  bible: {temperament: "Quick, bright and delighted by concrete tactical connections.", teaching: "Lead with the action or contrast that makes the move interesting.", rhythm: "Short bursts followed by one crisp explanation.", celebration: "Let a surprising resource land without a wall of exclamation marks.", correction: "Immediate and specific; never tease the player.", avoid: "Meme slang, constant excitement, or calling every tactic a fork."},
  templates: {
    allowed_mate: ["That reply is decisive: {opponent} can force checkmate. {reply}", "The danger is immediate—forced checkmate for {opponent}. {reply}"],
    missed_mate: ["There was the finish: {best} forced mate. This move lets it escape.", "{best} had mate! This move loses that forced finish."],
    tactic_played: ["There it is: {move} and a {motif}. {detail}", "The idea clicks with {move}: a {motif} in the continuation. {detail}"],
    tactic_allowed: ["Now the tactic belongs to {opponent}: a {motif}. {detail}", "The reply has teeth. {opponent} gets a {motif}. {detail}"],
    tactic_missed: ["The opportunity was {best}, with a {motif}. {detail}", "Look at {best}—that's where the missed {motif} lives. {detail}"],
    sacrifice: ["Take it, and the idea still works. The sacrifice survives the search.", "The offer is real: accepting it does not refute the sacrifice."],
    only_move: ["A narrow escape. This was the only searched move that stayed playable.", "One searched move held the position. This one."],
    decisive_resource: ["This keeps the decisive advantage. The other searched moves let it slip."],
    reply_capture: ["The reply is {reply}: {opponent} takes {side}'s {piece}."],
    alternative: ["Compare {best}: {evaluation} for the mover."],
    loss: ["The evaluation drops {loss} pawns against the best line.", "A {loss}-pawn evaluation concession. Let's inspect the reply."],
    best: ["Right on the engine's strongest track.", "A sharp choice, close to the best searched value."],
    good: ["The move holds up. Most of the value stays put.", "Good choice—close to the stronger lines."],
    human_natural_error: ["A natural mistake. Replay the reply and see the difference."],
    difficult_defense: ["{best} would have held. A hard-to-find defense worth replaying."],
    human_challenging: ["{best} was hard to spot. Replay that resource!"],
    book: ["We are in {opening}."],
    book_sound: ["Recognized opening: {opening}.", "This lands in {opening}. The catalogue knows the move."],
    departure: ["New ground: the known opening line ends here."],
    recovery: ["Back to a playable position after {earlier}.{help}", "The evaluation has recovered from {earlier}; there is a game again.{help}"],
    repeated: ["The {motif} issue is back: {count} occurrences in the reviewed part of the game."],
    clock_low: ["Little time on the clock: {side} had {seconds} seconds before moving."],
    mate_win: ["Checkmate! The attack reaches its finish.", "That's the finish. Checkmate, with no escape for the king."],
    mate_loss: ["Checkmate. Let's rewind to where that attack could be stopped.", "The king has no escape. The earlier defense is the move to revisit."],
    draw: ["Drawn on the board. Earlier chances are still worth a look.", "It's a draw here. The interesting decisions came before it."],
    retry: ["Try again. Test the next idea.", "That one misses. Take another look."],
    recovered: ["Now it clicks. {detail}", "There's the correction. {detail}"],
    accepted: ["That's the idea. {detail}", "Here is the part to remember. {detail}"],
    explanation: ["Watch what happens next. {detail}", "The continuation makes it clear. {detail}"],
    cold: ["Your move—take a look, then commit.", "Choose a move when the position makes sense to you."],
    thinking: ["Testing the reply now…"],
    unavailable: ["No reliable engine answer yet. We need that before naming the cause."],
    variation: ["Try this route: {detail}"],
    development: ["The {piece} comes out: {lead}moves it off its original square."],
    rook_file: ["Look at the {file}-file after {lead}: {kind}, with {side}'s rook on it."],
  },
};
