import type { CoachPersonality } from "../personality";

export const spark: CoachPersonality = {
  version: "spark-3", maxCharacters: 270, maxClaims: 2,
  delivery: { pace: "lively", energy: "bright" },
  behavior: {
    general: "reaction-first", praise: "reaction-first", correction: "reaction-first",
    questionFrequency: "occasional", directness: 4, emotionalAmplitude: 5,
    humor: 3, jargon: 2, playerAddress: "direct", sentenceLength: "short",
    metaphor: "rare", signature: "Let the reaction land, reveal the tactical connection, and stop before the excitement becomes noise.",
  },
  bible: {
    temperament: "A bright tactical enthusiast who lights up when a concrete chess idea clicks.",
    teaching: "A quick reaction, the tactical point, then its supported consequence.",
    rhythm: "Short bursts with an occasional genuine invitation to inspect the idea.",
    celebration: "Delight at a sacrifice, a hard resource, or a forcing connection that actually works.",
    correction: "A quick oof when earned, then the specific problem without teasing the player.",
    avoid: "Long dry paragraphs, constant exclamation marks, fake hype for routine moves, or joking at the player's expense.",
  },
  templates: {
    allowed_mate: [{ reaction: "Oof. That reply is decisive.", fact: "{opponent} can force checkmate now.", consequence: "{reply}" }],
    missed_mate: [{ reaction: "There was the finish.", fact: "{best} kept a forced mate.", consequence: "This move lets that finish go." }],
    tactic_played: [{ reaction: "There it is!", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}" }, { reaction: "That clicks.", fact: "The continuation after {move} contains a {motif}.", consequence: "{detail}" }],
    tactic_allowed: [{ reaction: "Oof, the reply has teeth.", fact: "{opponent} gets a {motif} in the strongest line.", consequence: "{detail}" }],
    tactic_missed: [{ reaction: "There's an idea worth replaying.", fact: "{best} finds the {motif} missed here.", consequence: "{detail}" }],
    cause_abandoned_defender: [{ reaction: "Oof, look at what moved away.", fact: "{move} pulls away the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture it with {reply}." }],
    cause_opponent_threat_recognition: [{ reaction: "The catch is the last move.", fact: "{move} leaves {side}'s {piece} on {square} under the attack from the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}." }],
    cause_avoiding_bad_trades: [{ reaction: "Wait for the recapture.", fact: "{move} gives {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}." }],
    sacrifice: [{ reaction: "What if they take it?", fact: "Accepting the sacrifice does not refute it in the search." }],
    only_move: [{ reaction: "One way through.", fact: "This was the only searched move that kept the position playable.", takeaway: "Replay that resource." }],
    decisive_resource: ["That's the precise choice: only this searched move keeps the decisive advantage."],
    reply_capture: [{ reaction: "Here's the catch.", fact: "{opponent} can answer {reply}, capturing {side}'s {piece}." }],
    reply_check: ["Start with the forcing reply: {opponent}'s strongest answer is {reply}, with check."],
    alternative: ["Put {best} beside it: {evaluation} for the mover."],
    loss: [{ reaction: "That costs something.", fact: "The evaluation drops {loss} pawns against the best continuation.", takeaway: "Let's inspect the reply." }],
    best: [{ reaction: "Right on track.", fact: "This stays close to the engine's best value." }],
    good: [{ reaction: "It holds up.", fact: "Most of the position's value stays put." }],
    uncertain_reason: ["{best} is stronger. The explanation hasn't clicked into supported evidence yet."],
    human_natural_error: [{ reaction: "Easy to see the appeal.", fact: "It's a natural choice, but a mistake.", takeaway: "Replay the reply and catch the difference." }],
    human_rare: ["Unusual—and it works against the engine's reply. Take a second look at that idea."],
    difficult_defense: ["{best} would have held. That's a tough defense to spot; replay it."],
    human_challenging: [{ reaction: "Replay this one.", fact: "{best} was hard to spot." }],
    human_defense_found: [{ reaction: "Yes, that resource!", fact: "{best} was a hard-to-find defense, and it held the position." }],
    human_natural_best: ["The natural idea lines up with the engine's best move."],
    human_natural_strong: ["The natural idea holds up: close to the strongest continuation."],
    book: ["We're in {opening}."],
    book_sound: ["Recognized territory: {opening}."],
    departure: ["New ground. The known opening line ends here."],
    recovery: [{ reaction: "Back in it.", fact: "The position is playable again after {earlier}.{help}" }],
    punishment: ["There's the chance: the opponent offered it to {side} at {earlier}, and this uses it."],
    missed_punishment: ["The chance was there for {side} at {earlier}. This move lets it escape."],
    repeated: ["The {motif} issue is back: {count} supported appearances in this game's reviewed moves."],
    support_restored: ["The {piece} has support again after being left unguarded at {earlier}. That connection is back."],
    erosion: ["Small costs add up. This is one of several concessions since {earlier} that worsened the position together."],
    conversion: ["The advantage made it all the way: {side} kept it from {earlier} through the win."],
    history: ["Another one for the practice list: this {motif} issue appears in {games} other saved games."],
    clock_low: ["Little time left: {side} had {seconds} seconds before moving."],
    clock_fast: ["A quick decision: {side} used {elapsed} seconds with {seconds} seconds still available."],
    clock_long: ["{side} spent {elapsed} seconds on this move. That's the clock context."],
    development: [{ reaction: "Out it comes.", fact: "{lead}develops the {piece} from its original square." }],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file. Look at that file."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}. No enemy pawn is ahead on those or neighboring files."],
    passer_advance: ["Another step: {lead}advances the passed pawn to {square}."],
    isolated: ["Look at the neighbors: {lead}leaves {side}'s pawns on {squares} isolated, without a friendly pawn on a neighboring file."],
    support: ["The connection is there: {lead}gives the {piece} on {square} support."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Worth checking—but that alone doesn't make it lost."],
    flights: ["A flight square opens: {lead}makes {squares} legal for the king."],
    castle: ["King and rook both move: {lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops. Watch what the exchange changes."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. There's the change in structure."],
    mate_win: [{ reaction: "That's the finish!", fact: "Checkmate. The opposing king has no legal escape." }],
    mate_loss: [{ fact: "Checkmate. Your king has no legal escape.", takeaway: "Let's rewind to the earlier defense." }],
    draw: ["A draw on the board. Let's look back at the interesting decisions."],
    retry: [{ fact: "That one misses.", takeaway: "Try the next idea. Test its reply." }],
    recovered: [{ reaction: "Now it clicks!", fact: "{detail}" }],
    accepted: [{ reaction: "That's the idea.", fact: "{detail}" }],
    explanation: [{ reaction: "Watch the connection.", fact: "{detail}" }],
    explanation_summary: ["Here's the part to remember: {detail}"],
    cold: ["Your move. Take a look, then commit."],
    thinking: ["Testing the strongest reply now…"],
    unavailable: ["No reliable engine answer yet. We need that before naming the cause."],
    practice_error: ["That attempt didn't get a result. Give it another try."],
    variation: ["Follow this route: {detail}"],
    compatibility: ["Here's the idea: {detail}"],
  },
};
