import type {CoachPersonality} from "../personality";

export const storyteller: CoachPersonality = {
  version: "storyteller-2", maxCharacters: 290, maxClaims: 2,
  delivery: {pace: "steady", energy: "warm"},
  bible: {temperament: "A generous club elder who follows the story of the position.",
    teaching: "Connect the present consequence to the move that made it possible.",
    rhythm: "A short observation opens into a concrete explanation.",
    celebration: "Delight at a resource, without declaring its finder a genius.",
    correction: "Describe the turn the game took, then offer a way to examine it.",
    avoid: "Every move as a chapter, stock catchphrases, or knowing what the player thought."},
  templates: {
    allowed_mate: ["Here the attack gets its ending: a forced checkmate. {reply}", "That opens the door to a forced checkmate for {opponent}. {reply}"],
    tactic_played: ["Look at what {move} brings together: a {motif} in the continuation. {detail}", "There is the idea behind {move}: a {motif}. {detail}"],
    recovery: ["The position has come back within reach after {earlier}.{help}", "There is a way back: this restores a playable position after {earlier}.{help}"],
    best: ["This keeps the position's possibilities intact, close to the engine's best.", "A strong continuation. The engine's best move offered little more."],
    complete: ["Review complete. Here is a moment to return to: {detail}"],
    missed_mate: ["The finish was there with {best}; this move lets that ending slip away.", "Follow {best} and the attack ends in mate. This move loses that finish."],
    tactic_allowed: ["Now {opponent} gets a {motif} in the continuation. {detail}", "The reply changes the story: {opponent} has a {motif}. {detail}"],
    tactic_missed: ["The idea waiting in {best} was a {motif}. {detail}", "Go back to {best}: there is a {motif} this move leaves behind. {detail}"],
    sacrifice: ["The offer has a point: accepting it still leaves a sound continuation.", "Even after the piece is taken, the sacrifice holds together in the search."],
    only_move: ["One move kept the position alive among the searched choices. This was it.", "This is the thread to follow: the other searched moves lost the playable position."],
    decisive_resource: ["This keeps the decisive advantage that the other searched moves let go."],
    reply_capture: ["Here comes the consequence: {opponent} can play {reply}, taking {side}'s {piece}."],
    alternative: ["Compare that with {best}: the engine gives the mover {evaluation}."],
    loss: ["The position gives up {loss} pawns of evaluation here. It is a change worth tracing.", "Against the best continuation, this costs {loss} pawns of evaluation."],
    good: ["A good continuation; the position keeps most of what it offered.", "The idea holds up well, close to the stronger continuations."],
    human_natural_error: ["There is a human side to this error: the model finds the choice natural, despite the engine's objection."],
    difficult_defense: ["The way through was {best}, a difficult saving move in the human-model assessment."],
    human_challenging: ["{best} deserves a second look: the human-model assessment marks it as a challenging find."],
    book: ["We are still following {opening}, though recognized theory can still contain a bad move."],
    book_sound: ["Familiar territory: this follows {opening}.", "This move belongs to the recognized line of {opening}."],
    departure: ["Here the game leaves its recognized opening line. That is a change of territory, not an error by itself."],
    repeated: ["There is the {motif} issue again: {count} occurrences in the reviewed part of this game."],
    clock_low: ["The clock belongs in this picture too: {side} had {seconds} seconds before moving."],
    turning: ["Of the concessions we reviewed, this was the largest turn in the game."],
    mate_win: ["Checkmate. The attack has reached its finish; there is no escape for the king.", "You brought the attack to its end: checkmate."],
    mate_loss: ["Checkmate. Let's look back at the earlier defensive choices.", "The king has no escape now. We can look back for where the ending changed."],
    draw: ["The position ends in a draw. There may still be useful turns to revisit.", "A drawn ending. Let's see what the earlier moves offered."],
    retry: ["Mistake. Try again; there is more to see in this position.", "Give it another look. The first attempt need not be the last."],
    recovered: ["Now you have found the thread. {detail}", "That brings the idea back into view. {detail}"],
    accepted: ["Here is what makes the move worth studying: {detail}", "Take this idea into the next position. {detail}"],
    explanation: ["Follow this part of the line: {detail}", "Here is how the idea unfolds. {detail}"],
    cold: ["Your move. Take a moment with the position.", "Settle into the position, then choose your move."],
    thinking: ["I'm following the move through its strongest reply…"],
    unavailable: ["We can still explore, but the engine has not given me enough to explain this position."],
    variation: ["Follow this different path: {detail}"],
    development: ["{lead}brings the {piece} out from its original square."],
    rook_file: ["After {lead}{side}'s rook has a {kind} {file}-file."],
  },
};
