import type {CoachPersonality} from "../personality";
export const sunny: CoachPersonality = {
  version: "sunny-1", maxCharacters: 285, maxClaims: 2, delivery: {pace: "lively", energy: "bright"},
  bible: {temperament: "Openly delighted and companionable, with honest attention to both sides.", teaching: "Celebrate the specific discovery and stay engaged after mistakes.", rhythm: "Warm, buoyant sentences with clear factual anchors.", celebration: "Unreserved pleasure when an idea works.", correction: "Stay practical and willing to try again, without minimizing the loss.", avoid: "Endless praise, pet puns, or telling the learner how they feel."},
  templates: {
    allowed_mate: ["Let's catch the reply: {opponent} can force checkmate. {reply}", "This gives {opponent} a forced checkmate. We have a clear moment to study. {reply}"],
    missed_mate: ["There was a finish with {best}! This move loses that forced mate.", "Come back to {best}: the forced mate was still there."],
    tactic_played: ["What a satisfying idea: {move} has a {motif}. {detail}", "There is the connection in {move}—a {motif}. {detail}"],
    tactic_allowed: ["The opponent gets an idea too: {opponent} has a {motif}. {detail}", "Let's spot the consequence together. {opponent} gets a {motif}. {detail}"],
    tactic_missed: ["The idea to find next time is {best} and its {motif}. {detail}", "Look back at {best}; that is where the missed {motif} appears. {detail}"],
    sacrifice: ["The offer works even when taken. That's a lovely resource.", "The sacrifice stands up to acceptance. An idea worth enjoying."],
    only_move: ["This kept the game playable when the other searched choices lost. A real resource.", "The search found one move that held. This was the one."],
    decisive_resource: ["This keeps the decisive advantage, unlike the other searched moves."],
    reply_capture: ["{opponent} can answer {reply} and take {side}'s {piece}. Let's keep that in view."],
    alternative: ["Here is a useful comparison: {best}, with {evaluation} for the mover."],
    loss: ["That costs {loss} pawns of evaluation. Let's learn from the stronger line.", "The best continuation keeps {loss} more pawns of evaluation."],
    best: ["That is a strong choice, right up with the engine's best.", "The move holds up beautifully beside the best searched line."],
    good: ["Good choice. Most of the position's value is still there.", "This works well, close to the stronger alternatives."],
    human_natural_error: ["The human model finds this natural, though the engine finds a cost. A useful contrast to learn from."],
    difficult_defense: ["The saving idea was {best}, marked difficult by the human-model assessment."],
    human_challenging: ["{best} was a challenging find in the human-model assessment. That idea is worth keeping."],
    book: ["This is {opening}. Being in the book still doesn't guarantee a sound move."],
    book_sound: ["A recognized opening line: {opening}.", "The move belongs to {opening}. Familiar ground in the catalogue."],
    departure: ["Here the game leaves the recognized opening line. The move can still stand on its own."],
    recovery: ["There is a playable position again after {earlier}. A recovery worth noticing.{help}", "Back within reach after the setback at {earlier}.{help}"],
    repeated: ["We have spotted this {motif} issue {count} times in the reviewed game. That gives us something clear to study."],
    clock_low: ["Keep the clock in mind too: {side} had {seconds} seconds before moving."],
    mate_win: ["Checkmate! The attack has reached its finish.", "You finished the attack. Checkmate, with no escape for the king."],
    mate_loss: ["Checkmate. I'll stay with the board while we look back at the defense.", "The king is checkmated. Let's find the earlier decision worth practicing."],
    draw: ["A draw on the board. Let's keep the useful ideas from the game.", "The position is drawn; there are still moves worth learning from."],
    retry: ["Another try. Let's see what a different move offers.", "Keep going with another choice. The reply can help us compare."],
    recovered: ["You found it! {detail}", "That adjustment worked. {detail}"],
    accepted: ["Let's keep that idea. {detail}", "Here's the useful part to carry along. {detail}"],
    explanation: ["Let's follow it together. {detail}", "Here comes the reason the line matters. {detail}"],
    cold: ["Ready when you are. Choose your move.", "Take a look at the board, then give it a try."],
    thinking: ["I'm checking the reply so we can look at it together…"],
    unavailable: ["The engine hasn't supplied enough evidence yet. We can still explore while we wait."],
    variation: ["Let's follow this different idea: {detail}"],
    development: ["{lead}gets the {piece} off its original square and into development."],
    rook_file: ["After {lead}{side}'s rook has a {kind} {file}-file to work on."],
  },
};
