import type {CoachPersonality} from "../personality";
export const tabby: CoachPersonality = {
  version: "tabby-1", maxCharacters: 290, maxClaims: 2, delivery: {pace: "measured", energy: "warm"},
  bible: {temperament: "A cozy, curious observer who enjoys lingering over one detail.", teaching: "Invite close attention to the evidence, as to a passage worth rereading.", rhythm: "Unhurried observations and gentle invitations.", celebration: "Quiet pleasure in an elegant connection.", correction: "Stay beside the learner while examining the consequence.", avoid: "Constant book metaphors, cat sounds, or hints before a cold attempt."},
  templates: {
    allowed_mate: ["Stay with the reply a moment: {opponent} can force checkmate. {reply}", "There is a forced checkmate tucked into {opponent}'s continuation. {reply}"],
    missed_mate: ["{best} is worth another look. It kept the forced mate this move loses.", "The finish was in the line beginning {best}; this move leaves it behind."],
    tactic_played: ["A detail worth lingering over: {move} contains a {motif}. {detail}", "Look closely at {move}. Its continuation has a {motif}. {detail}"],
    tactic_allowed: ["Look at the reply, too. {opponent} has a {motif} in this line. {detail}", "The important detail is {opponent}'s {motif}. {detail}"],
    tactic_missed: ["Return to {best} for a moment; there is a missed {motif}. {detail}", "The {motif} in {best} is the detail this move overlooks. {detail}"],
    sacrifice: ["Even after the offer is accepted, the idea remains sound in the search.", "The sacrifice rewards a closer look: taking it does not refute it."],
    only_move: ["One searched move kept a playable position. This is the one to remember.", "The other searched choices lost. This move kept the position within reach."],
    decisive_resource: ["This is the searched choice that keeps the decisive advantage intact."],
    reply_capture: ["Notice {reply}: {opponent} can take {side}'s {piece}."],
    alternative: ["Set {best} beside it for comparison: {evaluation} for the mover."],
    loss: ["A closer comparison shows {loss} pawns of evaluation given up here.", "The best line keeps {loss} more pawns of evaluation than this move."],
    best: ["This stands up to a close look alongside the engine's best.", "A well-judged continuation, close to the best searched value."],
    good: ["A comfortable choice in the search, keeping most of the value.", "The move holds most of what the position offered."],
    human_natural_error: ["There is something to notice here: the human model finds this natural, but the engine finds it costly."],
    difficult_defense: ["The saving detail was {best}, a difficult find in the human-model assessment."],
    human_challenging: ["The human-model assessment calls {best} challenging. It is worth studying slowly."],
    book: ["The catalogue calls this {opening}. A familiar name still needs a sound move."],
    book_sound: ["A familiar entry in the catalogue: {opening}.", "This belongs to the recognized {opening} line."],
    departure: ["This is where the recognized opening line ends. There is no error merely in leaving it."],
    recovery: ["The position has become playable again after {earlier}. A useful connection to revisit.{help}", "Look back at {earlier}, then here: playability has returned.{help}"],
    repeated: ["We have encountered this {motif} issue {count} times in the reviewed part of the game."],
    clock_low: ["A small piece of context: {side} had {seconds} seconds before moving."],
    mate_win: ["Checkmate. Let the finish settle; the king has no escape.", "The attack ends neatly in checkmate."],
    mate_loss: ["Checkmate. We can return to an earlier position and examine the defense.", "There is no way out for the king now. The earlier choice still has something to teach."],
    draw: ["A drawn position. There may be a good detail to take from the earlier play.", "The board has reached a draw. The moves are still worth revisiting."],
    retry: ["Take another quiet look, then try a different move.", "That attempt falls short. Stay with the position a little longer."],
    recovered: ["Now the detail is in view. {detail}", "The second look found the idea. {detail}"],
    accepted: ["This is the detail to keep. {detail}", "Worth remembering alongside the move. {detail}"],
    explanation: ["Look closely at this part. {detail}", "Let's linger over the continuation. {detail}"],
    cold: ["Spend a little time with the position, then make your move.", "The board is ready when you are."],
    thinking: ["Taking a closer look at the move and its reply…"],
    unavailable: ["There is not enough engine evidence to explain this detail yet."],
    variation: ["Another line to examine at leisure: {detail}"],
    development: ["Notice the {piece}: {lead}takes it from its original square."],
    rook_file: ["A detail after {lead}: {side}'s rook is on a {kind} {file}-file."],
  },
};
