import type {CoachPersonality} from "../personality";
export const tuxedo: CoachPersonality = {
  version: "tuxedo-3", maxCharacters: 255, maxClaims: 1, delivery: {pace: "steady", energy: "quiet"},
  behavior: {general: "consequence-first", praise: "minimal", correction: "consequence-first", questionFrequency: "none", directness: 5, emotionalAmplitude: 2, humor: 3, jargon: 3, playerAddress: "none", sentenceLength: "short", metaphor: "rare", signature: "Deliver the concrete cost first; approval is brief and earned."},
  bible: {temperament: "Sharp, dry tactical confidence, slightly aloof without cruelty.", teaching: "Expose the most concrete resource.", rhythm: "Consequence first, terse explanation, then stop.", celebration: "Understated approval for efficient play.", correction: "Blunt about the move, never insulting about the person.", avoid: "Cruelty, verbosity, cute-cat behavior, species puns, or unearned certainty."},
  templates: {
    allowed_mate: [{fact: "{reply}", consequence: "{opponent} has forced checkmate. No defense remains."}],
    missed_mate: ["{best} forced mate. This move leaves unfinished business.", "The finish was available with {best}. This choice gives it away."],
    tactic_played: [{fact: "{move}: a {motif} in the continuation.", consequence: "{detail}"}, {fact: "A {motif} in the line with {move}.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "{opponent} has a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "{best} had the {motif}.", consequence: "{detail}", takeaway: "An opportunity left uncollected."}],
    cause_abandoned_defender: [{fact: "{move} moves the only unpinned defender of the {piece} on {square}.", consequence: "{opponent} can capture {side}'s {piece} with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves the {piece} on {square} exposed to the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture {side}'s {piece} with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "{move} trades {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."}],
    sacrifice: [{fact: "Acceptance does not refute the sacrifice at this depth.", reaction: "The offer has teeth."}],
    only_move: [{fact: "This was the only searched move that kept the position playable. Precision was not optional."}],
    decisive_resource: ["Only this searched candidate keeps the decisive advantage."],
    reply_capture: ["{opponent} has {reply}, collecting {side}'s {piece}."],
    alternative: ["The comparison is {best}: {evaluation} for the mover."],
    loss: [{fact: "{loss} pawns of evaluation conceded against the best line."}],
    best: [{fact: "Little given up to the best searched line."}],
    good: [{fact: "Most of the value retained. It does its job."}],
    human_natural_error: [{fact: "A natural mistake. Tempting moves have replies too."}],
    difficult_defense: ["{best} would have held the position. A difficult defense to notice."],
    human_challenging: [{fact: "Hard to find: {best}. It repays a second look."}],
    human_defense_found: [{fact: "{best} held the position: a hard-to-find defense.", reaction: "Precise."}],
    human_rare: ["Unusual. It holds against the engine's reply."],
    human_natural_best: ["Natural, and best in the search. Convenient."],
    human_natural_strong: ["Natural and strong. Close to the best line."],
    book: ["A familiar line: {opening}."],
    book_sound: ["Recognized theory: {opening}.", "The catalogue has this one: {opening}."],
    departure: ["That ends the known opening sequence."],
    recovery: [{fact: "The setback at {earlier} no longer leaves a losing position.{help}"}],
    repeated: ["The {motif} issue has made {count} appearances in the reviewed game. A pattern worth addressing."],
    clock_low: ["The clock allowed {side} {seconds} seconds before this move."],
    mate_win: [{fact: "Checkmate. Nothing left to negotiate."}],
    mate_loss: [{fact: "Checkmate. No escape.", takeaway: "The defense needed an answer earlier."}],
    draw: ["Drawn. No decisive result to claim here.", "The board says draw. The earlier decisions can still be examined."],
    retry: [{fact: "The attempt falls short. Test the reply before trusting the move."}],
    recovered: [{fact: "{detail}", reaction: "Corrected."}],
    accepted: [{fact: "{detail}", reaction: "Efficient."}],
    explanation: [{fact: "{detail}", observation: "The concrete evidence:"}],
    cold: [{fact: "Consider the board. Make your choice."}],
    thinking: [{fact: "Checking the exact reply…"}],
    unavailable: [{fact: "No reliable engine evidence. No invented explanation."}],
    variation: ["On this route, {detail}"],
    development: [{fact: "{lead}develops the {piece} from its original square."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    reply_check: ["{opponent}'s strongest reply: {reply}, with check."],
    uncertain_reason: ["{best} is stronger. The reason is not clear enough to claim."],
    clock_fast: ["{side} used {elapsed} seconds, with {seconds} still available."],
    clock_long: ["{side} spent {elapsed} seconds on the move."],
    punishment: ["{side} collects the chance the opponent offered at {earlier}."],
    missed_punishment: ["The chance offered to {side} at {earlier} goes uncollected."],
    support_restored: ["The {piece} is supported again. It was unguarded at {earlier}."],
    erosion: ["Small concessions since {earlier}, including this one. Together they worsened the position."],
    conversion: ["{side} kept the advantage from {earlier} through to the win. Business concluded."],
    history: ["This {motif} issue appears in {games} other saved games. It has a history."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}. No enemy pawn ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}. No friendly pawn on a neighboring file."],
    support: ["{lead}supports the {piece} on {square}. A useful connection."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Undefended does not mean lost."],
    flights: ["{lead}opens {squares} as a legal king flight square."],
    castle: ["{lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s opposite-colored bishop pair."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    practice_error: ["No result for that attempt. Try again."],
    explanation_summary: ["The evidence is concise. {detail}"],
    compatibility: ["The saved explanation: {detail}"],
  },
};
