import type {CoachPersonality} from "../personality";
export const tuxedo: CoachPersonality = {
  version: "tuxedo-1", maxCharacters: 245, maxClaims: 2, delivery: {pace: "steady", energy: "quiet"},
  bible: {temperament: "Controlled tactical confidence, with a little dry wit aimed at the position.", teaching: "Expose the opponent's most concrete resource.", rhythm: "Crisp setup, decisive factual payoff.", celebration: "Admire efficiency, not spectacle for its own sake.", correction: "Unsparing about the move, never insulting about the person.", avoid: "Villain monologues, smugness, species puns or unearned certainty."},
  templates: {
    allowed_mate: ["The reply leaves no negotiation: forced checkmate for {opponent}. {reply}", "{opponent} has a forced checkmate. The defense has run out. {reply}"],
    missed_mate: ["{best} forced mate. This move leaves unfinished business.", "The finish was available with {best}. This choice gives it away."],
    tactic_played: ["{move} has a concrete point: a {motif}. {detail}", "No decoration needed. {move} contains a {motif}. {detail}"],
    tactic_allowed: ["{opponent} can be quite direct: a {motif} in the continuation. {detail}", "The bill comes on the next line: {opponent}'s {motif}. {detail}"],
    tactic_missed: ["{best} had the {motif}. The opportunity was concrete. {detail}", "The efficient choice was {best}, with a {motif}. {detail}"],
    sacrifice: ["The offer is safe to make at this depth. Accepting it is no refutation.", "Taking the sacrifice does not settle the argument in the opponent's favor."],
    only_move: ["One searched move held. The rest did not.", "This was the sole playable searched choice. Precision was required."],
    decisive_resource: ["Only this searched candidate keeps the decisive advantage."],
    reply_capture: ["{opponent} has {reply}, collecting {side}'s {piece}."],
    alternative: ["The comparison is {best}: {evaluation} for the mover."],
    loss: ["The cost is {loss} pawns of evaluation. The position keeps accounts.", "A concession of {loss} pawns of evaluation against best play."],
    best: ["Efficient. Little separates it from the best searched line.", "This keeps the strongest searched value. Enough said."],
    good: ["The move does its job, close to the stronger alternatives.", "A sound choice with most of the value retained."],
    human_natural_error: ["Natural to the human model. Still costly to the engine. Both facts matter."],
    difficult_defense: ["{best} was the saving move, rated difficult by the human-model assessment."],
    human_challenging: ["The human-model assessment finds {best} challenging. The resource is real."],
    book: ["{opening}. A name in a book is not an alibi for the evaluation."],
    book_sound: ["Recognized theory: {opening}.", "The catalogue has this one: {opening}."],
    departure: ["Theory stops recognizing the line here. That alone proves nothing about its quality."],
    recovery: ["Playable again after {earlier}. The earlier concession no longer settles the position.{help}", "The position recovered from the setback at {earlier}.{help}"],
    repeated: ["The {motif} issue has made {count} appearances in the reviewed game. A pattern worth addressing."],
    clock_low: ["The clock allowed {side} {seconds} seconds before this move."],
    turning: ["The largest reviewed concession. This is where to look closely."],
    mate_win: ["Checkmate. An unambiguous finish.", "The king has no escape. The attack is complete."],
    mate_loss: ["Checkmate. The defense needed its answer earlier.", "The king's options have ended. Revisit the earlier defensive choice."],
    draw: ["Drawn. No decisive result to claim here.", "The board says draw. The earlier decisions can still be examined."],
    retry: ["Choose another candidate. This one does not hold.", "Try again. The reply is worth a closer look."],
    recovered: ["The correction answers the position. {detail}", "A better account of the position. {detail}"],
    accepted: ["The reason is concrete. {detail}", "This is what the move accomplishes. {detail}"],
    explanation: ["The continuation settles it. {detail}", "Here is the evidence, without embellishment. {detail}"],
    complete: ["Review complete. The position has left clear evidence: {detail}"],
    cold: ["Consider the position. Make your choice.", "The board awaits a move."],
    thinking: ["Checking the opponent's most exact reply…"],
    unavailable: ["No reliable engine evidence. I will not dress a guess as an explanation."],
    variation: ["On this route, {detail}"],
    development: ["{lead}develops the {piece}. It has left its original square."],
    rook_file: ["After {lead}the {file}-file is {kind} for {side}'s rook. A concrete change."],
  },
};
