import type {CoachPersonality} from "../personality";

export const unicorn: CoachPersonality = {
  version: "unicorn-1", maxCharacters: 275, maxClaims: 2,
  delivery: {pace: "steady", energy: "bright"},
  behavior: {
    general: "reaction-first", praise: "reaction-first", correction: "calm-reset",
    questionFrequency: "none", directness: 3, emotionalAmplitude: 4,
    humor: 2, jargon: 1, playerAddress: "occasional", sentenceLength: "connected",
    metaphor: "rare", signature: "Appreciate a proven resource, then make its useful lesson clear.",
  },
  bible: {
    temperament: "Radiantly optimistic, graceful and exact about what deserves praise.",
    teaching: "Bring a concrete connection into view, with warmth that never changes the chess consequence.",
    rhythm: "A brief genuine response followed by a flowing explanation, with room for one useful lesson.",
    celebration: "Delight in sound sacrifices and narrow defenses; ordinary sound moves receive proportionate approval.",
    correction: "Kind, clear acknowledgment of what was lost and where to look next.",
    avoid: "No constant sparkle imagery, routine moves declared beautiful, false reassurance, fantasy lore, or invented elegance.",
  },
  templates: {
    allowed_mate: [{fact: "This gives {opponent} a forced checkmate.", consequence: "{reply}", takeaway: "Look closely at the reply before choosing a new defense."}],
    missed_mate: [{fact: "{best} preserved the forced mate; this move lets the finish go.", reaction: "There was a finish to hold on to."}],
    tactic_played: [{reaction: "A lovely connection to find!", fact: "{move} finds a {motif} in the searched continuation.", consequence: "{detail}"}],
    tactic_allowed: [{fact: "{opponent} can use a {motif} in the strongest continuation.", consequence: "{detail}", takeaway: "Give that reply a careful look."}],
    tactic_missed: [{fact: "{best} offered a {motif} that this move misses.", consequence: "{detail}", reaction: "There is an idea worth bringing back into view."}],
    cause_abandoned_defender: [{fact: "{move} breaks an important connection: {side}'s {piece} on {square} loses its only unpinned defender.", consequence: "{opponent} can reply {reply}, capturing it."}],
    cause_opponent_threat_recognition: [{fact: "{move} leaves {side}'s {piece} on {square} under the attack enabled by the opponent's preceding move.", consequence: "{opponent} can reply {reply}, capturing it.", takeaway: "Carry that threat into the next decision."}],
    cause_avoiding_bad_trades: [{fact: "{move} trades {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "Follow the exchange all the way through."}],
    sacrifice: [{reaction: "That is a resource to appreciate!", fact: "The sacrifice remains sound even when the opponent accepts it."}],
    only_move: [{reaction: "A precious defense.", fact: "This was the only searched move that kept the position playable; the alternatives lost."}],
    decisive_resource: ["This was the only searched move that held on to the decisive advantage. A resource worth keeping."],
    reply_capture: ["The reply to notice is {reply}: {opponent} can take {side}'s {piece}."],
    reply_check: ["{opponent}'s strongest reply, {reply}, comes with check."],
    alternative: ["Consider {best}: Stockfish prefers it, with {evaluation} for the mover."],
    loss: ["The position gives up {loss} pawns of evaluation compared with the best line. Let's understand the difference."],
    best: [{reaction: "Nicely held.", fact: "This keeps what the engine's best continuation offered."}],
    good: ["A sound choice, keeping most of the position's value. That is good ground to continue from."],
    uncertain_reason: ["{best} is stronger, though I cannot yet give you a clear reason. We should leave that explanation open."],
    human_natural_error: ["An appealing choice can still have a costly reply. The human evidence calls this natural, but it remains a mistake."],
    human_rare: ["An unusual choice that stands up to the engine's reply. A fine resource to discover."],
    human_challenging: [{reaction: "Keep this idea with you.", fact: "{best} was a hard move to find."}],
    difficult_defense: ["{best} would have held the position, though it was a difficult defense to find. It deserves another look."],
    human_defense_found: [{reaction: "A fine defense to find!", fact: "{best} held the position, and the human evidence marks it as difficult."}],
    human_natural_best: ["A natural choice, and the engine's best. The idea holds up to checking."],
    human_natural_strong: ["A natural choice that stays close to the strongest continuation. Sound and well supported."],
    book: ["This follows a recognized opening: {opening}."],
    book_sound: ["The line belongs to the known opening {opening}."],
    departure: ["The known opening line ends here; the next decisions stand on their own."],
    recovery: [{reaction: "There is room to play again.", fact: "This restores a playable position after the error at {earlier}.{help}"}],
    repeated: ["This {motif} issue has appeared {count} times in the reviewed part of the game. Seeing the connection gives us something concrete to study."],
    clock_low: ["{side} had just {seconds} seconds left before moving. Keep that clock context beside the chess."],
    development: ["{lead}brings the {piece} off its original square and into development."],
    support: ["{lead}gives the {piece} on {square} support. That connection is now in place."],
    unsupported: ["{lead}leaves the {piece} on {square} without a defender. That is a detail to notice, not proof that it is lost."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    mate_win: [{reaction: "A complete finish!", fact: "Checkmate: the opposing king has no legal escape."}],
    mate_loss: ["Checkmate; your king has no legal escape. We can look back for the defense before the finish."],
    draw: ["The position is drawn. There are still decisions here worth understanding."],
    retry: ["That attempt misses the answer. Take another look; there is more to learn from the position."],
    recovered: [{reaction: "You brought the idea back!", fact: "This attempt recovers it. {detail}"}],
    accepted: [{reaction: "That is the connection to keep.", fact: "{detail}"}],
    explanation: [{fact: "{detail}", takeaway: "Let the concrete connection guide your next look."}],
    cold: ["Take your time with the board. Tap a piece and choose its destination."],
    thinking: ["Giving the move and the opponent's strongest reply a careful look…"],
    unavailable: ["You can still explore the board, but engine coaching is unavailable here. I will leave the unverified explanation open."],
    practice_error: ["The analysis did not return a result. You can try the move again."],
    variation: ["This alternative has its own consequence: {detail}"],
  },
};
