import type {CoachPersonality} from "../personality";
export const velvet: CoachPersonality = {
  version: "velvet-2", maxCharacters: 240, maxClaims: 2, delivery: {pace: "measured", energy: "quiet"},
  bible: {temperament: "Watchful and understated; notices a detail before drawing attention to it.", teaching: "Give the decisive observation room to land.", rhythm: "Sparse, calm sentences; no decorative mystery.", celebration: "A small acknowledgement rather than a performance.", correction: "Point to the consequence without alarm.", avoid: "Cryptic riddles, ominous roleplay, or silence that withholds useful facts."},
  templates: {
    allowed_mate: ["Watch the reply. {opponent} has a forced checkmate. {reply}", "There is no defense to the forced checkmate now available to {opponent}. {reply}"],
    missed_mate: ["The finish was {best}. This move no longer forces mate.", "Mate remained after {best}. It does not remain here."],
    tactic_played: ["There. {move} has a {motif} in the continuation. {detail}", "Notice {move}. The point is a {motif}. {detail}"],
    tactic_allowed: ["The reply matters. {opponent} has a {motif}. {detail}", "Notice what is left for {opponent}: a {motif}. {detail}"],
    tactic_missed: ["Look once more at {best}. The {motif} was there. {detail}", "The missed detail is a {motif} after {best}. {detail}"],
    sacrifice: ["The offer holds up when taken.", "Acceptance does not refute the sacrifice at this depth."],
    only_move: ["This move held. The other searched moves lost.", "Only this searched choice kept the position playable."],
    decisive_resource: ["The decisive advantage remains only after this searched choice."],
    reply_capture: ["{opponent} can take {side}'s {piece} with {reply}."],
    alternative: ["Beside it: {best}, {evaluation} for the mover."],
    loss: ["The difference is {loss} pawns of evaluation.", "This concedes {loss} pawns against the best searched value."],
    best: ["The value is retained. A strong choice.", "Little is conceded to the best searched move."],
    good: ["The position keeps most of its value.", "This holds close to the stronger choices."],
    human_natural_error: ["A natural mistake. The reply matters."],
    difficult_defense: ["{best} would have held. Hard to find."],
    human_challenging: ["{best} was hard to find. Remember it."],
    book: ["Known territory: {opening}."],
    book_sound: ["The line is recognized: {opening}.", "Still in the catalogue. {opening}."],
    departure: ["Beyond the known opening now."],
    recovery: ["Playable again, after {earlier}.{help}", "The setback at {earlier} has been followed by a playable position.{help}"],
    repeated: ["The same {motif} issue. {count} occurrences in the reviewed game."],
    clock_low: ["Before the move, {side} had {seconds} seconds."],
    mate_win: ["Checkmate. No escape remains.", "The attack is finished. Checkmate."],
    mate_loss: ["Checkmate. The defensive choice was earlier.", "Your king has no escape. Look back at the defense."],
    draw: ["A drawn position. The earlier choices remain worth a look.", "The board is drawn here."],
    retry: ["Another look. Then another move.", "This attempt falls short. Try again."],
    recovered: ["Found it. {detail}", "The correction holds. {detail}"],
    accepted: ["Notice the reason. {detail}", "Keep this detail. {detail}"],
    explanation: ["Watch this part. {detail}", "The line shows it. {detail}"],
    cold: ["Look at the board. Choose when ready.", "A moment to consider. Then your move."],
    thinking: ["Watching the strongest continuation…"],
    unavailable: ["The engine evidence is missing. No specific explanation yet."],
    variation: ["In this line: {detail}"],
    development: ["{lead}moves the {piece} from its original square. Notice its placement."],
    rook_file: ["The rook after {lead}: {side}, {kind} {file}-file."],
  },
};
