import type {CoachPersonality} from "../personality";
export const velvet: CoachPersonality = {
  version: "velvet-3", maxCharacters: 260, maxClaims: 1, delivery: {pace: "measured", energy: "quiet"},
  behavior: {general: "observation-first", praise: "observation-first", correction: "observation-first", questionFrequency: "none", directness: 4, emotionalAmplitude: 1, humor: 1, jargon: 2, playerAddress: "occasional", sentenceLength: "short", metaphor: "none", signature: "Notice the exposed detail, allow a quiet pause, then give its consequence without alarm."},
  bible: {temperament: "Quiet and watchful, with a soft side.", teaching: "Give the decisive observation room to land.", rhythm: "Short, still phrasing: observation, pause, conclusion.", celebration: "A subtle acknowledgement rather than a performance.", correction: "Notice what was left behind without sounding cutting.", avoid: "Melodrama, mystery clichés, cat jokes, or silence that withholds useful facts."},
  templates: {
    allowed_mate: [{observation: "Watch the reply.", fact: "{opponent} has forced checkmate. {reply}"}],
    missed_mate: ["The finish was {best}. This move no longer forces mate.", "Mate remained after {best}. It does not remain here."],
    tactic_played: [{observation: "There.", fact: "{move} has a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_allowed: [{observation: "Notice the reply.", fact: "{opponent} has a {motif} in the continuation.", consequence: "{detail}"}],
    tactic_missed: [{fact: "The {motif} was there with {best}.", consequence: "{detail}", takeaway: "Look once more."}],
    cause_abandoned_defender: [{observation: "Notice what is left behind.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can capture it with {reply}."}],
    cause_opponent_threat_recognition: [{fact: "After {move}, {side}'s {piece} on {square} still faces the attack enabled by the opponent's preceding move.", consequence: "{opponent} can capture it with {reply}."}],
    cause_avoiding_bad_trades: [{fact: "{move} exchanges {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}.", takeaway: "Follow the exchange to its end."}],
    sacrifice: [{observation: "Look beyond the offer.", fact: "Accepting it does not refute the sacrifice at this depth."}],
    only_move: [{fact: "This move held. The other searched moves lost.", takeaway: "Keep this one in mind."}],
    decisive_resource: ["The decisive advantage remains only after this searched choice."],
    reply_capture: ["{opponent} can take {side}'s {piece} with {reply}."],
    alternative: ["Beside it: {best}, {evaluation} for the mover."],
    loss: [{fact: "The difference from best play is {loss} pawns of evaluation."}],
    best: [{observation: "Quietly done.", fact: "Little is conceded to the best searched move."}],
    good: [{fact: "The position keeps most of its value."}],
    human_natural_error: [{fact: "A natural mistake.", takeaway: "Pause at the reply."}],
    difficult_defense: ["{best} would have held. Hard to find."],
    human_challenging: [{fact: "{best} was hard to find.", takeaway: "Give that idea a moment."}],
    human_defense_found: [{observation: "There was a way through.", fact: "The hard-to-find defense {best} held the position."}],
    human_rare: ["An unusual choice. Still, it holds against the engine's reply."],
    human_natural_best: ["A natural choice. The search agrees: best."],
    human_natural_strong: ["A natural choice, close to the strongest continuation."],
    book: ["Known territory: {opening}."],
    book_sound: ["The line is recognized: {opening}.", "Still in the catalogue. {opening}."],
    departure: ["Beyond the known opening now."],
    recovery: [{observation: "Notice the change.", fact: "Playable again after {earlier}.{help}"}],
    repeated: ["The same {motif} issue. {count} occurrences in the reviewed game."],
    clock_low: ["Before the move, {side} had {seconds} seconds."],
    mate_win: [{fact: "No escape remains. Checkmate."}],
    mate_loss: [{fact: "Your king has no escape. Checkmate.", takeaway: "We can look back at the defense."}],
    draw: ["A drawn position. The earlier choices remain worth a look.", "The board is drawn here."],
    retry: [{fact: "This attempt falls short.", takeaway: "Another look. Then another move."}],
    recovered: [{observation: "Found it.", fact: "{detail}"}],
    accepted: [{observation: "Notice the reason.", fact: "{detail}"}],
    explanation: [{observation: "Watch this part.", fact: "{detail}"}],
    cold: [{fact: "A moment to consider. Choose when ready."}],
    thinking: [{fact: "Looking through the strongest continuation…"}],
    unavailable: [{fact: "The engine evidence is missing. No specific explanation yet."}],
    variation: ["In this line: {detail}"],
    development: [{observation: "A small change to notice.", fact: "{lead}develops the {piece} from its original square."}],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    reply_check: ["Notice the check: {reply}, {opponent}'s strongest reply."],
    uncertain_reason: ["{best} is stronger. The reason is still unclear."],
    clock_fast: ["A brief pause: {side} used {elapsed} seconds, with {seconds} still available."],
    clock_long: ["The pause lasted {elapsed} seconds for {side}."],
    punishment: ["There was a chance for {side} at {earlier}. This move uses it."],
    missed_punishment: ["The opponent's chance for {side} was at {earlier}. This move lets it pass."],
    support_restored: ["The {piece} has support again. It was left alone at {earlier}."],
    erosion: ["Notice the small concessions since {earlier}. This is one of them; together they worsened the position."],
    conversion: ["From {earlier} to the win, {side} kept the advantage."],
    history: ["The same {motif} issue appears in {games} other saved games. Worth a closer look."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}; no enemy pawn stands ahead on those or neighboring files."],
    passer_advance: ["Notice the pawn: {lead}advances the passer to {square}."],
    isolated: ["{lead}leaves {side} with isolated pawns on {squares}. No friendly pawn is on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support. Notice the connection."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. That alone does not make it lost."],
    flights: ["{lead}opens {squares} as a legal flight square for the king. Notice the space."],
    castle: ["{lead}castles the king to {square}. The rook relocates too."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops. Notice the exchange."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}. Notice the structure."],
    practice_error: ["No result came back for this attempt. You can try again."],
    explanation_summary: ["Keep this detail. {detail}"],
    compatibility: ["In the saved explanation: {detail}"],
  },
};
