import type {CoachPersonality} from "../personality";
import {wizardTacticalTemplates} from "./scopedTactics";
import {wizardOpeningTemplates} from "./openingSequence";

export const wizard: CoachPersonality = {
  version: "wizard-2", maxCharacters: 290, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: {pace: "measured", energy: "warm"},
  behavior: {
    general: "pattern-first", praise: "pattern-first", correction: "pattern-first",
    questionFrequency: "none", directness: 3, emotionalAmplitude: 2,
    humor: 2, jargon: 3, playerAddress: "occasional", sentenceLength: "connected", metaphor: "rare",
    signature: "Draw a useful principle from the specific mechanism; let a pattern become something the player can recognize again.",
  },
  bible: {
    temperament: "An old scholar, patient with mistakes and quietly pleased when a difficult pattern becomes clear.",
    teaching: "Name the principle or pattern, apply it to the supported moves, then give the consequence; preserve the distinction between a principle and proof.",
    rhythm: "Connected sentences; a short principle often precedes a concrete application. Restrained approval, never a lecture.",
    celebration: "Respect a resource by naming the pattern that made it work, with a brief word of approval.",
    correction: "Treat the error as a learnable mechanism, without pretending it has occurred before unless the evidence says so.",
    avoid: "Every move as a spell, fake Shakespeare, young-apprentice address, questions, invented history, fake wisdom, other coaches' sayings, or naturalness and difficulty claims not attributed to the human-move model.",
  },
  templates: {
    ...wizardTacticalTemplates,
    ...wizardOpeningTemplates,
    allowed_mate: [
      {observation: "No lesson outranks the safety of the king.", fact: "After this move, {opponent} can force checkmate.", consequence: "{reply}", takeaway: "Follow the attack back to where the defense first gave way."},
      {fact: "This opens the way for {opponent} to force mate. {reply}", takeaway: "The defense must be studied before this move, not after it."},
    ],
    missed_mate: [
      {observation: "When a finish is on the board, find it before anything else.", fact: "{best} held a forced mate, and the played move passes it by."},
      {fact: "The mating line began with {best}; this move lets that finish slip away.", takeaway: "Return to the position and work the finish out."},
    ],
    tactic_played: [
      {observation: "A pattern worth keeping, along with the move.", fact: "In the searched line, {move} carries out a {motif}.", consequence: "{detail}"},
      {fact: "The mechanism behind {move} is a {motif}. {detail}", takeaway: "Learn the shape of it; it will return."},
    ],
    tactic_allowed: [
      {observation: "Every pattern serves both sides of the board.", fact: "In the strongest line, this hands {opponent} a {motif}.", consequence: "{detail}"},
      {fact: "{opponent} gains a {motif} in the strongest line. {detail}", takeaway: "Read the position from the other chair before moving."},
    ],
    tactic_missed: [
      {observation: "A pattern was waiting in another move.", fact: "{best} offered a {motif}, and this move leaves it unplayed.", consequence: "{detail}"},
      {fact: "The unplayed pattern was a {motif}, through {best}.", consequence: "{detail}", takeaway: "Reconstruct the idea before memorizing the move."},
    ],
    cause_abandoned_defender: [
      {observation: "A defender has a duty before it has a destination.", fact: "With {move}, the only unpinned defender of {side}'s {piece} on {square} leaves its post.", consequence: "{opponent} can then take it with {reply}."},
      {fact: "{move} takes away the only unpinned guard of {side}'s {piece} on {square}.", consequence: "{reply} then captures it for {opponent}.", takeaway: "Before a defender moves, list what it was holding."},
    ],
    cause_opponent_threat_recognition: [
      {observation: "Every move asks a question, and the opponent's last one asked it plainly.", fact: "The opponent's preceding move created an attack on {side}'s {piece} on {square}, and {move} leaves it unanswered.", consequence: "{opponent} is free to capture it with {reply}."},
    ],
    cause_avoiding_bad_trades: [
      {observation: "An exchange is judged after the recapture, not before.", fact: "{move} trades {side}'s {piece} away for a {captured}.", consequence: "{opponent} has the recapture {reply}."},
    ],
    sacrifice: [
      {observation: "A sacrifice is proven by its acceptance.", fact: "Here the offer can be taken, and the idea still holds in the searched line."},
      {fact: "Accepting this sacrifice does not refute it; the idea survives in the searched line.", takeaway: "Study the acceptance, for that is where the soundness lives."},
    ],
    only_move: [
      {observation: "Some positions allow a single narrow path.", fact: "Of the searched moves, this one alone kept the position playable, and each of the others was losing."},
      {fact: "This alone held the position among the searched moves, and every alternative was losing.", takeaway: "A resource like this is worth committing to memory."},
    ],
    decisive_resource: ["No searched move but this one kept the decisive advantage. The difference between winning and merely holding is worth studying here."],
    best: [
      {observation: "Sound principles, soundly applied.", fact: "This is a strong move, and the position loses almost nothing by it."},
      {fact: "Strong. Very little of the position's value is given away.", takeaway: "Well judged."},
    ],
    good: [
      {observation: "A respectable choice.", fact: "Sound, and most of the position's value remains."},
      "Sound. The engine prefers another move, yet most of the position's value stays intact.",
    ],
    loss: [
      {fact: "Measured against the best move, this costs {loss} pawns of evaluation.", takeaway: "The number tells you the size of the cost; the reply tells you its cause."},
      "Set beside the best move, this gives up {loss} pawns of evaluation. Compare the replies to find where it went.",
    ],
    alternative: ["Stockfish prefers {best}, which it rates at {evaluation} for the mover. Set the two moves side by side."],
    reply_capture: ["Look first at what the reply can take: {opponent} has {reply}, capturing {side}'s {piece}."],
    reply_check: ["The strongest reply for {opponent} is {reply}, and it gives check. A check must be answered before all else."],
    uncertain_reason: ["Stockfish rates {best} higher, and I cannot yet name the principle behind it. Better an honest gap than an invented reason."],
    human_natural_error: [
      {observation: "The most inviting move is not always the soundest.", fact: "The human-move model rates this a natural choice, yet the reply makes it costly."},
      "By the human-move model's estimate this is a natural move, and the reply still makes it costly. Tempting and sound part ways here.",
    ],
    human_rare: ["The human-move model would not expect this move, and it holds against the engine's reply. A rare move can still be a right one."],
    human_challenging: ["By the human-move model's estimate, {best} was hard to find. Learn the pattern behind it, and it will be easier to see the next time."],
    difficult_defense: ["{best} would have held the position, a defense the human-move model rates hard to find. Defensive patterns repay study."],
    human_defense_found: [{observation: "A narrow path, and well walked.", fact: "You found {best}, which held the position, and the human-move model counts it among the hard defenses."}],
    human_natural_best: ["The human-move model counts this natural, and it is also the engine's best. Intuition and calculation reach the same move."],
    human_natural_strong: ["The human-move model counts this natural, and the engine finds it strong, though it prefers another move."],
    clock_low: ["{side} had only {seconds} seconds before this move. Time is part of the position too."],
    clock_fast: ["{side} moved after {elapsed} seconds, with {seconds} seconds still in reserve."],
    clock_long: ["{side} spent {elapsed} seconds over this move. A long deliberation."],
    book: ["The opening literature knows this position as {opening}. A name is a starting point for study, not a judgment."],
    book_sound: ["The move stands in the recorded line of {opening}."],
    departure: ["Here the game passes the last move our opening book records. From now on, the position must be read on its own terms."],
    recovery: [
      {observation: "A setback need not be the end of the lesson.", fact: "After the error at {earlier}, the position becomes playable once more.{help}"},
      "Following the error at {earlier}, this move brings back a playable position.{help}",
    ],
    punishment: ["The opponent's move at {earlier} offered {side} an opportunity, and this move takes it. Recognizing a gift is a skill of its own."],
    missed_punishment: ["At {earlier}, the opponent offered {side} an opportunity, and this move does not take it. Return to that moment and look again."],
    repeated: ["This {motif} issue has now appeared {count} times in the reviewed game. When a pattern repeats, line up the examples and find the common warning sign."],
    history: ["{games} other saved games show this same {motif} issue. A pattern seen across several games is worth studying across all of them."],
    support_restored: ["The {piece}, left unguarded at {earlier}, is defended once more. Compare the two moments to see what changed."],
    erosion: ["Small concessions accumulate quietly. This is one of several since {earlier} that together have worn the position down."],
    conversion: ["{side} carried the advantage from {earlier} all the way to the win. Conversion is a craft of its own, and this is an example of it."],
    development: [{observation: "Development is the first principle of the opening.", fact: "{lead}develops the {piece}, bringing it off its original square."}],
    rook_file: ["{lead}leaves {side} with a rook on a {kind} {file}-file. Rooks are at their best on such roads."],
    passed: [{observation: "A passed pawn is a lasting asset.", fact: "{lead}leaves passed pawns on {squares} for {side}; no enemy pawn waits ahead of them on their own files or the adjacent ones."}],
    passer_advance: [{observation: "Passed pawns must be pushed, as the old saying has it.", fact: "{lead}pushes the passed pawn onward to {square}."}],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated, with no friendly pawn on either neighboring file. A familiar structural weakness."],
    support: ["{lead}provides the {piece} on {square} with a defender. A guarded piece is a calm piece."],
    unsupported: ["{lead}leaves no defender for the {piece} on {square}. A weakness, yes, but not yet proof that it can be won."],
    flights: ["{lead}frees {squares} as a legal flight square for the king. A king with an exit is harder to trap."],
    castle: ["{lead}castles the king to {square}, and the rook comes toward the center. Two old purposes served at once."],
    bishops: ["{lead}ends {side}'s bishop pair. Its bishops can no longer cover both square colors."],
    doubled: ["{lead}results in doubled pawns for {side} on files {files}. A familiar weakness in the structure."],
    mate_win: [
      {observation: "The attack has reached its end.", fact: "Checkmate, with every escape closed to the king."},
      "Checkmate. Every flight square is closed, and the finish is worth remembering.",
    ],
    mate_loss: ["Checkmate, and your king is left without a legal escape. The lesson lies earlier, in the moment the defense could still have held."],
    draw: ["A drawn game. The result is settled, though the decisions along the way still have much to teach."],
    cold: ["Study the position before you act, and only then decide on a move."],
    thinking: ["Weighing the move against the strongest reply before drawing any lesson…"],
    unavailable: ["The engine has given me nothing to go on for this position, so I will not guess at a lesson. You may still explore the board freely."],
    practice_error: ["That attempt brought back no result. Come back to the move and try it once more."],
    retry: [
      {observation: "The pattern is still in the position.", fact: "That attempt does not survive the reply.", takeaway: "Look again at what each piece is guarding."},
      "That attempt falls short of the answer. Return to the position and look for the pattern it contains.",
    ],
    recovered: [{observation: "Patience rewarded.", fact: "The pattern is found on the second look. {detail}"}],
    accepted: [{fact: "{detail}", takeaway: "Carry the reason along with the move; the reason is what returns when the pattern does."}],
    explanation: [{observation: "Follow the mechanism one step at a time.", fact: "{detail}"}],
    explanation_summary: ["The lesson, in brief: {detail}"],
    variation: ["Consider this side line: {detail}"],
    compatibility: ["{detail}"],
  },
};
