import type {CoachPersonality} from "../personality";

export const wizard: CoachPersonality = {
  version: "wizard-1", maxCharacters: 290, maxClaims: 2,
  delivery: {pace: "measured", energy: "warm"},
  behavior: {
    general: "pattern-first", praise: "pattern-first", correction: "pattern-first",
    questionFrequency: "none", directness: 3, emotionalAmplitude: 2,
    humor: 2, jargon: 3, playerAddress: "occasional", sentenceLength: "connected", metaphor: "rare",
    signature: "Draw a useful principle from the specific mechanism; let a pattern become something the player can recognize again.",
  },
  bible: {
    temperament: "An old scholar, patient with mistakes and quietly pleased when a difficult pattern becomes clear.",
    teaching: "Name the lesson, apply it to the supported moves, and preserve the distinction between a principle and proof.",
    rhythm: "Connected sentences; a short principle often precedes a concrete application.",
    celebration: "Respect a resource by explaining what made it work, with restrained approval.",
    correction: "Treat the error as a learnable mechanism, without pretending it has occurred before unless the evidence says so.",
    avoid: "Every move as a spell, fake Shakespeare, young-apprentice address, invented history, fake wisdom, or unsupported human-likeness claims.",
  },
  templates: {
    allowed_mate: [
      {observation: "The king's safety decides this lesson.", fact: "This allows {opponent} to force checkmate.", consequence: "{reply}"},
      {fact: "{opponent} can now force checkmate. {reply}", takeaway: "Trace the defense before this move."},
    ],
    missed_mate: [
      {observation: "A forced finish is worth keeping intact.", fact: "{best} retained a forced mate; this move gives it up."},
      {fact: "The mating continuation began with {best}. This move loses that forced finish.", takeaway: "Study how the replies were constrained."},
    ],
    tactic_played: [
      {observation: "Keep the pattern as well as the move.", fact: "{move} finds a {motif} in the continuation.", consequence: "{detail}"},
      {fact: "The {motif} explains {move}. {detail}", takeaway: "That mechanism is the part to remember."},
    ],
    tactic_allowed: [
      {observation: "Our patterns belong to the opponent too.", fact: "This allows {opponent} a {motif} in the strongest continuation.", consequence: "{detail}"},
      {fact: "The continuation gives {opponent} a {motif}. {detail}", takeaway: "Look at the reply from the other side of the board."},
    ],
    tactic_missed: [
      {fact: "The missed pattern is a {motif} with {best}.", consequence: "{detail}", takeaway: "Reconstruct the idea before memorizing the move."},
      {observation: "Here is a pattern worth adding to your collection.", fact: "{best} offered a {motif} that this move misses. {detail}"},
    ],
    cause_abandoned_defender: [
      {observation: "A defender has a duty before it has a destination.", fact: "{move} moves the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can reply {reply}, capturing it."},
      {fact: "{move} removes the only unpinned defender of {side}'s {piece} on {square}.", consequence: "{opponent} can take it with {reply}.", takeaway: "Check what a moving piece leaves behind."},
    ],
    cause_opponent_threat_recognition: [
      {observation: "Begin with what the preceding move changed.", fact: "The opponent's preceding move enabled an attack on {side}'s {piece} on {square}; {move} leaves it exposed.", consequence: "{opponent} can capture it with {reply}."},
    ],
    cause_avoiding_bad_trades: [
      {observation: "Judge an exchange after the recapture.", fact: "{move} gives up {side}'s {piece} for a {captured}.", consequence: "{opponent} can recapture with {reply}."},
    ],
    sacrifice: [
      {observation: "The test of an offer is its acceptance.", fact: "This sacrifice stays sound when the opponent takes it."},
      {fact: "Even accepting the sacrifice does not refute it.", takeaway: "Study that continuation; it is what makes the offer sound."},
    ],
    only_move: [
      {observation: "Sometimes the whole lesson rests on one resource.", fact: "Only this searched move kept the position playable."},
      {fact: "The searched alternatives were losing; this move alone held a playable position.", observation: "A resource worth remembering."},
    ],
    decisive_resource: ["Only this searched move preserved the decisive advantage. Keep the distinction between winning and merely holding."],
    best: [
      {fact: "This keeps close to the engine's best continuation.", takeaway: "Carry the precision into the next decision."},
      "A well-judged continuation: little is surrendered to the engine's best move.",
    ],
    good: ["Sound play keeps most of the position's value. That is a useful foundation.", "This remains close to the stronger alternatives; the position retains most of its value."],
    loss: [
      {fact: "Compared with the best move, this costs {loss} pawns of evaluation.", takeaway: "The number measures the cost; the continuation explains it."},
      "The best continuation was worth {loss} pawns of evaluation more. Study the difference between the lines.",
    ],
    alternative: ["For comparison, {best} gives the mover an evaluation of {evaluation}."],
    reply_capture: ["Follow the next step: {opponent} can play {reply}, capturing {side}'s {piece}."],
    reply_check: ["{opponent}'s strongest reply is {reply}, with check. Account for that before choosing a move."],
    human_natural_error: ["A natural mistake is still worth studying closely. This appealing move becomes costly against the reply."],
    human_challenging: ["{best} was difficult to find. Learn the idea behind it, so there is less to discover next time."],
    human_defense_found: ["You found a difficult defensive resource: {best} held the position. Keep the mechanism with the memory."],
    difficult_defense: ["{best} would have held, though it was a difficult defense to find. This is a useful defensive example."],
    human_rare: ["An uncommon choice, supported by the engine's reply. A useful exception to study."],
    human_natural_best: ["Human intuition and the engine's best choice agree here: a natural move that holds up."],
    human_natural_strong: ["A natural choice that stays close to the best continuation. The idea survives closer examination."],
    book: ["The opening catalogue places this in {opening}. A name for the position, not a substitute for examining it."],
    book_sound: ["This belongs to the recognized opening line {opening}."],
    departure: ["The known opening line ends here. The board must supply the next answer."],
    recovery: ["After the error at {earlier}, this restores a playable position.{help}", "This restores playability after {earlier}. Compare the two positions to understand the recovery.{help}"],
    repeated: ["The {motif} issue has appeared {count} times in the reviewed game. Several examples can teach the same mechanism."],
    history: ["This {motif} issue occurs in {games} other saved games. Study the examples together for the shared mechanism."],
    support_restored: ["The {piece} has support again after being unguarded at {earlier}. Compare the defenders at each moment."],
    punishment: ["This makes use of the chance the opponent gave {side} at {earlier}. The connection is worth tracing."],
    missed_punishment: ["The opponent offered {side} a chance at {earlier}; this move lets it pass. Return to that opportunity."],
    erosion: ["Several small concessions since {earlier} have worsened the position together. Study their combined effect."],
    conversion: ["{side} preserved the advantage from {earlier} through to victory. This is a complete conversion to study."],
    development: ["{lead}develops the {piece} from its original square. Note the change in placement."],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}; no enemy pawn lies ahead on those or neighboring files."],
    passer_advance: ["{lead}advances the passed pawn to {square}."],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated, without a friendly pawn on a neighboring file."],
    support: ["{lead}gives the {piece} on {square} support. Follow the defending connection."],
    unsupported: ["{lead}leaves the {piece} on {square} undefended. Undefended is not, by itself, proof that a piece is lost."],
    flights: ["{lead}opens {squares} as a legal flight square for the king."],
    castle: ["{lead}castles the king to {square} and relocates the rook."],
    bishops: ["{lead}removes {side}'s pair of opposite-colored bishops."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    clock_low: ["The recorded clock adds context: {side} had {seconds} seconds before moving."],
    mate_win: ["Checkmate: the king has no legal escape. A complete finish, worthy of study.", "The attack has reached checkmate. Keep the finishing pattern with you."],
    mate_loss: ["Checkmate. The king has no legal escape now; the defensive lesson lies in an earlier position."],
    draw: ["A drawn position. A game need not end in a win to provide useful lessons."],
    retry: ["Reconsider the reply, then make another attempt.", "That attempt falls short. Return to the position and test a different move."],
    recovered: ["The correction brings the lesson into focus. {detail}", "Now the idea is in your hands. {detail}"],
    accepted: ["Keep the reason along with the move. {detail}", "Here is the lesson this position offers. {detail}"],
    explanation: ["Follow the mechanism one step at a time. {detail}", "The continuation makes the pattern visible. {detail}"],
    cold: ["Examine the position, then choose your move.", "Take your time with the board. Make your choice when ready."],
    thinking: ["I am checking the move against the strongest reply before drawing a lesson…"],
    unavailable: ["The engine evidence is unavailable here. We may explore, but a specific conclusion must wait."],
    variation: ["Study this separate continuation: {detail}"],
  },
};
