import type { CoachPersonality } from "../personality";
import { youngBoyTacticalTemplates } from "./scopedTactics";
import { youngBoyOpeningTemplates } from "./openingSequence";

export const youngBoy: CoachPersonality = {
  version: "young-boy-2", maxCharacters: 275, maxClaims: 2, tacticalWording: "witness", openingWording: "sequence",
  delivery: { pace: "lively", energy: "bright" },
  behavior: {
    general: "reaction-first", praise: "reaction-first", correction: "question-first",
    questionFrequency: "occasional", directness: 3, emotionalAmplitude: 5,
    humor: 3, jargon: 1, playerAddress: "direct", sentenceLength: "short",
    metaphor: "none", signature: "A quick burst of excitement lands on the tactic itself, then a plain, complete explanation follows.",
  },
  bible: {
    temperament: "An excitable young teammate who can't wait to point at a tactical discovery, and who calms down enough to explain it properly.",
    teaching: "Point straight at the surprising reply or the trick, then say what it does in simple words.",
    rhythm: "A short reaction, sometimes a 'wait' or 'look at this', then one compact chess fact; questions only when the answer is on the board.",
    celebration: "Gets visibly excited about forks, sacrifices, mates, only moves and hard finds, and stays calm about routine moves.",
    correction: "Says 'wait, look at this' instead of judging, and keeps the cheering and sympathy for the player's own moments.",
    avoid: "Baby talk, prodigy stereotypes, nonstop exclamation marks, pretending to know the player's thoughts, cheering or alarm that depends on which side moved, other coaches' sayings, and any naturalness or difficulty claim the human-move model doesn't support.",
  },
  templates: {
    ...youngBoyTacticalTemplates,
    ...youngBoyOpeningTemplates,
    allowed_mate: [{ reaction: "Look at the king.", fact: "From here on, {opponent} can deliver a forced mate.", consequence: "{reply}", question: "Which squares does the king still have after that reply?" }],
    missed_mate: [{ reaction: "Oh, there was a mate!", fact: "{best} forced checkmate, and this move goes a different direction." }],
    tactic_played: [{ reaction: "Ooh, look at this!", fact: "Keep following the searched line after {move}, and out pops a {motif}.", consequence: "{detail}" }],
    tactic_allowed: [{ reaction: "Hmm, check the reply.", fact: "The strongest reply lets {opponent} set up a {motif}.", consequence: "{detail}", question: "Can the reply be spotted on the board?" }],
    tactic_missed: [{ reaction: "Hmm, a trick got left behind.", fact: "{best} had a {motif} hiding inside it, and this move skips the trick.", consequence: "{detail}" }],
    cause_abandoned_defender: [{ reaction: "Wait, look at this.", fact: "Wait, {move} was the only unpinned defender guarding {side}'s {piece} on {square}, and now it's gone off somewhere else.", consequence: "{opponent} can capture it with {reply}." }],
    cause_opponent_threat_recognition: [{ reaction: "The threat came one move before.", fact: "The opponent's preceding move already aimed at {side}'s {piece} on {square}, and {move} doesn't do anything about it.", consequence: "{opponent} can capture it with {reply}." }],
    cause_avoiding_bad_trades: [{ reaction: "Okay, count the trade to the end.", fact: "{move} gives up {side}'s {piece} and only gets a {captured} for it.", consequence: "{opponent} can recapture with {reply}." }],
    sacrifice: [{ reaction: "A sacrifice, and it works!", fact: "Even when the opponent grabs the material, the searched line keeps the idea alive." }],
    only_move: [{ reaction: "Whoa, the only one!", fact: "Every other searched move fell apart, and this one kept the game standing." }],
    decisive_resource: ["Whoa, every other searched try let the decisive advantage get away; this move is the one that kept it."],
    reply_capture: ["Look at this reply: {reply} lets {opponent} snatch {side}'s {piece} right off the board."],
    reply_check: ["Look at {reply} first: it's {opponent}'s strongest reply, and it gives check."],
    alternative: ["Next to it, {best} would leave the mover with {evaluation}."],
    loss: [{ reaction: "A little slip.", fact: "Compared with the engine's top line, about {loss} pawns of evaluation drop away here." }],
    best: [{ reaction: "Strong stuff.", fact: "Next to everything the engine looked at, hardly any value goes missing." }],
    good: [{ reaction: "Pretty good move.", fact: "Most of the position's value sticks around after this one." }],
    uncertain_reason: ["{best} comes out stronger, but there's no clear reason backed up yet, so no making one up."],
    human_natural_error: [{ reaction: "I can see why it looks good.", fact: "Lots of players would play it, by the human-move model, and the reply is what makes it cost something." }],
    human_rare: ["Hardly anybody picks this, according to the human-move model, and the engine's reply still doesn't break it. Cool, independent thinking!"],
    difficult_defense: ["{best} would have held, but it's a well-hidden defense that the human-move model thinks most players never spot. Set it up and hunt for it, it's a fun one."],
    human_challenging: [{ reaction: "Ooh, a hard one.", fact: "Lots of players miss {best}, according to the human-move model." }],
    human_defense_found: [{ reaction: "You held on!", fact: "{best} kept it together, and the human-move model says most players miss that defense." }],
    human_natural_best: ["Most players reach for this first, says the human-move model, and it's the engine's favorite too. Love when that happens!"],
    human_natural_strong: ["Lots of players would pick it, says the human-move model, and the engine calls it strong, even though its own favorite is a different one."],
    book: ["Ooh, this one has a name: {opening}."],
    book_sound: ["Right on the known path of {opening}."],
    departure: ["Here the game leaves the opening path, so everything after this is brand-new ground."],
    recovery: [{ reaction: "Back in it!", fact: "The trouble from {earlier} is behind, and the game works again.{help}" }],
    punishment: ["Something got left hanging for {side} at {earlier}, and this move snaps it up."],
    missed_punishment: ["Something got left hanging for {side} at {earlier}, and this move doesn't grab it. Go back and look again later."],
    repeated: ["Hey, that's {count} times now for this {motif} problem in the reviewed moves. Spotting it early is the next trick to learn."],
    support_restored: ["The {piece} had no guard back at {earlier}, and somebody is protecting it again."],
    erosion: ["Little losses keep piling up. Ever since {earlier}, small slips like this one have been wearing the position down."],
    conversion: ["Starting at {earlier}, {side} held on to the advantage the whole way and turned it into a win."],
    history: ["This {motif} problem shows up in {games} other saved games too, so it's a great thing to practice."],
    development: [{ fact: "{lead}wakes up the {piece} and sends it into the action." }],
    rook_file: ["{lead}leaves {side}'s rook on a {kind} {file}-file."],
    passed: ["{lead}leaves {side} with passed pawns on {squares}; not one enemy pawn is in front of them, on their own files or right next to them."],
    passer_advance: ["{lead}nudges the passed pawn one more step, onto {square}. Keep counting!"],
    isolated: ["{lead}leaves {side}'s pawns on {squares} isolated, so none of them has a pawn of its own color on a neighbouring file."],
    support: ["{lead}gives the {piece} on {square} somebody watching its back."],
    unsupported: ["{lead}means nobody is guarding the {piece} on {square}. That alone doesn't mean it's lost, but keep an eye on it."],
    flights: ["{lead}opens up {squares} as a square the king can step to."],
    castle: ["{lead}castles, and the king lands on {square} with the rook jumping over beside it."],
    bishops: ["{lead}breaks up {side}'s bishop pair, so one bishop is left and it covers only one square color."],
    doubled: ["{lead}leaves {side} with doubled pawns on files {files}."],
    mate_win: [{ reaction: "Checkmate!", fact: "The opposing king has zero legal squares left." }],
    mate_loss: [{ fact: "Checkmate. Your king has no legal escape.", takeaway: "Go back a few moves; that's where the defense can still be found." }],
    draw: ["It's a draw. The result is set, but there are still cool moments earlier in the game to look at."],
    retry: [{ reaction: "Hmm, not yet.", fact: "Nope, that try misses the trick.", takeaway: "Look again, the trick is still on the board!" }],
    recovered: [{ reaction: "Yes, that's it!", fact: "{detail}" }],
    accepted: [{ fact: "The reason to remember: {detail}" }],
    explanation: [{ reaction: "Here's the cool part.", fact: "{detail}" }],
    explanation_summary: ["The thing to remember: {detail}"],
    cold: ["Look over the whole board first, then pick your move."],
    thinking: ["Hold on, checking what the opponent's best answer is…"],
    unavailable: ["The engine can't explain this one yet, so no guessing. Try moves on the board if you want."],
    practice_error: ["Hmm, no result for that move. Try it one more time."],
    variation: ["Okay, here's the other line, move by move: {detail}"],
    compatibility: ["Here's the explanation there is: {detail}"],
  },
};
